export const BETA_FEATURE_FLAGS = [
  { flag_key: 'beta.enabled', name: 'IA Conect Beta', description: 'Libera a entrada para a experiência Beta isolada.', is_enabled: true, is_private: false },
  { flag_key: 'beta.execution.enabled', name: 'Beta · Execução', description: 'Kill switch central para novas execuções do Beta.', is_enabled: true, is_private: true },
  { flag_key: 'beta.auto_router.enabled', name: 'Beta · AUTO Router', description: 'Libera seleção automática de modelo elegível no Beta.', is_enabled: true, is_private: true },
  { flag_key: 'beta.image_editor', name: 'Beta · Editor de imagem', description: 'Libera o editor generativo de imagem do Beta.', is_enabled: true, is_private: false },
  { flag_key: 'beta.video', name: 'Beta · Vídeo', description: 'Libera a experiência unificada de vídeo do Beta.', is_enabled: true, is_private: false },
  { flag_key: 'beta.video_editor', name: 'Beta · Editor de vídeo', description: 'Libera edição e extensão generativa de vídeo.', is_enabled: true, is_private: false },
  { flag_key: 'beta.audio', name: 'Beta · Áudio', description: 'Libera o módulo multimodal de áudio.', is_enabled: true, is_private: false },
  { flag_key: 'beta.audio.voice_clone', name: 'Beta · Clonagem de voz', description: 'Libera clonagem de voz autorizada.', is_enabled: true, is_private: false },
  { flag_key: 'beta.audio.music', name: 'Beta · Música', description: 'Libera geração de música.', is_enabled: true, is_private: false },
  { flag_key: 'beta.audio.sfx', name: 'Beta · Efeitos sonoros', description: 'Libera geração de efeitos sonoros.', is_enabled: true, is_private: false },
  { flag_key: 'beta.audio.transcription', name: 'Beta · Transcrição', description: 'Libera transcrição e recursos derivados.', is_enabled: true, is_private: false },
  { flag_key: 'beta.audio.dubbing', name: 'Beta · Dublagem', description: 'Libera pipeline de tradução e dublagem.', is_enabled: true, is_private: false },
  { flag_key: 'beta.three_d', name: 'Beta · 3D', description: 'Libera geração e visualização 3D.', is_enabled: true, is_private: false },
  { flag_key: 'beta.flows', name: 'Beta · Fluxos', description: 'Libera o editor visual de Fluxos.', is_enabled: true, is_private: false },
  { flag_key: 'beta.flow_runtime', name: 'Beta · Flow Runtime', description: 'Libera execução de Fluxos pelo runtime DAG.', is_enabled: true, is_private: false },
  { flag_key: 'beta.flow_runtime.execution', name: 'Beta · Flow Runtime Execution', description: 'Kill switch de novas execuções do Flow Runtime.', is_enabled: true, is_private: true },
  { flag_key: 'beta.flow_economics', name: 'Beta · Flow Economics', description: 'Libera orçamento, limites e métricas econômicas dos Fluxos.', is_enabled: true, is_private: false },
  { flag_key: 'beta.flow_economics.budget_guard', name: 'Beta · Flow Budget Guard', description: 'Kill switch da proteção de orçamento por Flow.', is_enabled: true, is_private: true },
  { flag_key: 'beta.templates', name: 'Beta · Templates', description: 'Libera galeria e templates de Fluxos.', is_enabled: true, is_private: false },
  { flag_key: 'beta.flow_apps', name: 'Beta · Workflow Apps', description: 'Libera Apps construídos a partir de Fluxos.', is_enabled: false, is_private: false },
  { flag_key: 'beta.batch', name: 'Beta · Batch', description: 'Libera execução em lote e fan-out controlado.', is_enabled: false, is_private: false },
  { flag_key: 'beta.context', name: 'Beta · Contexto', description: 'Libera contextos reutilizáveis e versionados.', is_enabled: false, is_private: false },
  { flag_key: 'beta.copilot', name: 'Beta · Copilot', description: 'Libera assistência contextual com confirmação explícita antes de mudanças.', is_enabled: false, is_private: false },
  { flag_key: 'beta.brand_kit', name: 'Beta · Brand Kit', description: 'Libera contexto de marca reutilizável.', is_enabled: false, is_private: false },
  { flag_key: 'beta.sharing', name: 'Beta · Compartilhamento', description: 'Libera compartilhamento controlado de recursos Beta.', is_enabled: false, is_private: false },
  { flag_key: 'beta.analytics', name: 'Beta · Analytics', description: 'Libera métricas agregadas do workspace e compartilhamentos.', is_enabled: false, is_private: false },
] as const;
