import React,{useEffect,useMemo,useState}from'react';
import{ArrowRight,Images,Sparkles,Video,Wallet,WandSparkles}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';import{formatCentsToBRL}from'../../config/constants.js';import{generationClient}from'../../services/generationClient.js';import{assetService}from'../../services/assetService.js';import{Asset,Generation}from'../../types/index.js';import{ModelShowcase,ShowcaseItem}from'../workspace/ModelShowcase.js';
interface DashboardViewProps{onNavigate:(view:string)=>void;}
const starterIdeas=[
 {title:'UGC de produto',subtitle:'Gancho forte, demonstração e CTA em formato vertical.',mode:'create-video'},
 {title:'Personagem consistente',subtitle:'Construa uma identidade e leve o mesmo rosto para várias cenas.',mode:'create-image'},
 {title:'Comercial cinematográfico',subtitle:'Produto premium, luz controlada e movimento de câmera.',mode:'create-video'},
 {title:'Imagem para vídeo',subtitle:'Parta de uma imagem e transforme em movimento sem refazer o conceito.',mode:'create-video'},
];
export const DashboardView:React.FC<DashboardViewProps>=({onNavigate})=>{const{profile,wallet}=useAuth();const[recent,setRecent]=useState<Generation[]>([]),[assets,setAssets]=useState<Asset[]>([]);useEffect(()=>{generationClient.list(8).then(setRecent).catch(()=>setRecent([]));assetService.listAssets().then(r=>setAssets(r.slice(0,8))).catch(()=>setAssets([]))},[]);const completed=useMemo(()=>recent.filter(g=>g.status==='SUCCEEDED'),[recent]);const tryModel=(item:ShowcaseItem)=>{sessionStorage.setItem('ia-connect:last-showcase-model',item.modelId);onNavigate(item.mode==='IMAGE'?'create-image':'create-video')};return <div className="space-y-8 pb-12">
<section className="pt-2 sm:pt-4"><div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3"><div><p className="text-[10px] font-semibold text-zinc-500">Olá, {profile?.display_name||'criador'}</p><h1 className="mt-1 text-2xl sm:text-[32px] leading-tight font-black tracking-[-0.04em] text-white">Abra um modelo. Veja o resultado. Crie o seu.</h1><p className="mt-2 text-xs sm:text-sm text-zinc-500">A home agora funciona como uma vitrine viva de modelos, referências e ideias prontas para entrar em produção.</p></div><button onClick={()=>onNavigate('wallet')} className="self-start sm:self-auto inline-flex items-center gap-2 h-9 px-3 rounded-xl border border-white/[0.07] bg-white/[0.025] text-[10px] text-zinc-500 hover:text-white"><Wallet className="w-3.5 h-3.5"/>{formatCentsToBRL(wallet?.available_balance_cents||0)}</button></div>
<div className="mt-6 grid lg:grid-cols-2 gap-3"><button onClick={()=>onNavigate('create-image')} className="group min-h-[170px] rounded-[22px] border border-white/[0.08] bg-[radial-gradient(circle_at_78%_30%,rgba(168,85,247,.24),transparent_28%),#11141a] p-5 text-left hover:border-violet-400/20"><Sparkles className="w-4 h-4 text-violet-300"/><h2 className="mt-8 text-lg font-black text-white">Image Studio</h2><p className="mt-1 text-[11px] text-zinc-500">Crie, edite e reutilize personagens, produtos e estilos.</p><span className="mt-4 inline-flex gap-1.5 text-[10px] font-bold text-violet-200">Gerar imagem <ArrowRight className="w-3 h-3"/></span></button><button onClick={()=>onNavigate('create-video')} className="group min-h-[170px] rounded-[22px] border border-white/[0.08] bg-[radial-gradient(circle_at_78%_30%,rgba(16,185,129,.23),transparent_28%),#101519] p-5 text-left hover:border-emerald-400/20"><WandSparkles className="w-4 h-4 text-emerald-300"/><h2 className="mt-8 text-lg font-black text-white">Video Studio</h2><p className="mt-1 text-[11px] text-zinc-500">Compare modelos, anime referências e produza takes completos.</p><span className="mt-4 inline-flex gap-1.5 text-[10px] font-bold text-emerald-200">Gerar vídeo <ArrowRight className="w-3 h-3"/></span></button></div></section>
<ModelShowcase compact onTry={tryModel} title="Modelos em destaque" subtitle="Assista a demonstrações públicas selecionadas e entre no gerador certo sem precisar pesquisar fora da plataforma."/>
<section><div className="flex items-center justify-between"><div><h2 className="text-sm font-black text-white">Prompts que você vai poder adaptar</h2><p className="mt-0.5 text-[10px] text-zinc-600">Estrutura preparada para virar uma biblioteca de templates: abrir, trocar personagem/produto e gerar.</p></div><button onClick={()=>onNavigate('library')} className="hidden sm:inline-flex items-center gap-1.5 text-[10px] text-zinc-500"><Images className="w-3.5 h-3.5"/>Biblioteca</button></div><div className="mt-3 grid sm:grid-cols-2 xl:grid-cols-4 gap-3">{starterIdeas.map(i=><button key={i.title} onClick={()=>onNavigate(i.mode)} className="min-h-[130px] rounded-2xl border border-white/[0.07] bg-[#0f1218] p-4 text-left hover:border-white/[0.14]"><span className="text-[8px] uppercase tracking-[.16em] font-black text-cyan-300">Template</span><h3 className="mt-6 text-xs font-black text-white">{i.title}</h3><p className="mt-1 text-[9px] leading-relaxed text-zinc-600">{i.subtitle}</p></button>)}</div></section>
{completed.length>0&&<section><div className="flex items-center justify-between"><div><h2 className="text-sm font-black text-white">Suas criações recentes</h2><p className="mt-0.5 text-[10px] text-zinc-600">Continue de onde parou.</p></div><button onClick={()=>onNavigate('history')} className="text-[10px] text-zinc-500">Ver todas</button></div><div className="mt-3 grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-3">{completed.slice(0,4).map(g=><button key={g.generation_id} onClick={()=>onNavigate('history')} className="text-left"><div className="aspect-[4/3] rounded-2xl overflow-hidden border border-white/[0.07] bg-[#0d1015]">{g.result_url?(g.mode==='TEXT_TO_IMAGE'||g.mode==='IMAGE_TO_IMAGE'?<img src={g.result_url} alt="" className="w-full h-full object-cover"/>:<video src={g.result_url} muted preload="metadata" className="w-full h-full object-cover"/>):<div className="w-full h-full grid place-items-center"><Sparkles className="w-5 h-5 text-zinc-700"/></div>}</div><p className="mt-2 text-[10px] text-zinc-300 truncate">{g.original_prompt||'Criação'}</p></button>)}</div></section>}
{assets.length>0&&<section className="rounded-2xl border border-white/[0.06] bg-white/[0.018] p-4"><div className="flex items-center justify-between"><div><h2 className="text-xs font-black text-white">Da sua Biblioteca</h2><p className="mt-0.5 text-[9px] text-zinc-600">Assets prontos para reutilizar.</p></div><button onClick={()=>onNavigate('library')} className="text-[9px] text-zinc-500">Abrir Biblioteca</button></div><div className="mt-3 flex gap-2 overflow-x-auto">{assets.map(a=><button key={a.asset_id} onClick={()=>onNavigate('library')} className="w-20 h-20 shrink-0 rounded-xl overflow-hidden border border-white/[0.06] bg-[#0b0e13]">{a.type==='IMAGE'&&a.public_url?<img src={a.thumbnail_url||a.public_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center"><Video className="w-4 h-4 text-zinc-700"/></div>}</button>)}</div></section>}
</div>};