import React,{useEffect,useMemo,useState}from'react';
import{ArrowRight,Image as ImageIcon,Sparkles,Video}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{generationClient}from'../../services/generationClient.js';
import{Generation}from'../../types/index.js';
import{ModelShowcase,ShowcaseItem}from'../workspace/ModelShowcase.js';
interface DashboardViewProps{onNavigate:(view:string)=>void;}
function ratio(value?:string){const m=String(value||'').match(/(\d+(?:\.\d+)?):(\d+(?:\.\d+)?)/);return m?`${m[1]} / ${m[2]}`:'4 / 3'}
export const DashboardView:React.FC<DashboardViewProps>=({onNavigate})=>{const{profile}=useAuth();const[recent,setRecent]=useState<Generation[]>([]);useEffect(()=>{generationClient.list(10).then(setRecent).catch(()=>setRecent([]))},[]);const completed=useMemo(()=>recent.filter(g=>g.status==='SUCCEEDED'&&g.result_url),[recent]);const tryModel=(item:ShowcaseItem)=>{sessionStorage.setItem('ia-connect:last-showcase-model',item.modelId);onNavigate(item.mode==='IMAGE'?'create-image':'create-video')};return <div className="space-y-7 pb-10">
<section className="relative overflow-hidden rounded-[24px] border border-sky-300/[0.11] bg-[#07121d] px-5 py-6 sm:px-7 sm:py-7"><div className="absolute inset-0 bg-[radial-gradient(circle_at_82%_16%,rgba(25,184,255,.12),transparent_30%)]"/><div className="relative z-10 max-w-3xl"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">Bem-vindo de volta</p><h1 className="mt-3 text-3xl sm:text-4xl xl:text-[44px] font-black tracking-[-.05em] leading-[.98] text-white">Olá, {profile?.display_name||'criador'} 👋<br/><span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-300 to-blue-400">O que você vai criar hoje?</span></h1><p className="mt-3 max-w-xl text-xs sm:text-sm text-zinc-400">Crie imagens e vídeos com modelos de última geração em um fluxo simples e direto.</p></div></section>
<section className="grid md:grid-cols-2 gap-3"><button onClick={()=>onNavigate('create-image')} className="group relative overflow-hidden min-h-[138px] rounded-2xl border border-sky-300/[0.12] bg-[radial-gradient(circle_at_82%_30%,rgba(25,184,255,.15),transparent_30%),#08131e] p-5 text-left hover:border-sky-300/[0.28]"><ImageIcon className="w-5 h-5 text-sky-300"/><h2 className="mt-6 text-lg font-black">Criar imagem</h2><p className="mt-1 text-[10px] text-zinc-500">Estilos, referências, personagens, produtos e muito mais.</p><span className="absolute right-4 bottom-4 w-9 h-9 rounded-full border border-sky-300/[0.2] bg-sky-300/[0.07] grid place-items-center text-sky-300"><ArrowRight className="w-4 h-4"/></span></button><button onClick={()=>onNavigate('create-video')} className="group relative overflow-hidden min-h-[138px] rounded-2xl border border-blue-300/[0.12] bg-[radial-gradient(circle_at_82%_30%,rgba(92,124,255,.18),transparent_30%),#08131e] p-5 text-left hover:border-blue-300/[0.28]"><Video className="w-5 h-5 text-blue-300"/><h2 className="mt-6 text-lg font-black">Criar vídeo</h2><p className="mt-1 text-[10px] text-zinc-500">Dê movimento às suas ideias com modelos de última geração.</p><span className="absolute right-4 bottom-4 w-9 h-9 rounded-full border border-blue-300/[0.2] bg-blue-300/[0.07] grid place-items-center text-blue-300"><ArrowRight className="w-4 h-4"/></span></button></section>
<ModelShowcase compact onTry={tryModel} title="Modelos em destaque" subtitle="Escolha um modelo, veja o resultado em movimento e comece a criar."/>
<section><div className="flex items-end justify-between gap-4"><div><h2 className="text-lg font-black text-white">Suas criações recentes</h2><p className="mt-1 text-[10px] text-zinc-500">Continue de onde parou.</p></div><button onClick={()=>onNavigate('history')} className="text-[9px] font-bold text-sky-300 inline-flex items-center gap-1">Ver biblioteca<ArrowRight className="w-3 h-3"/></button></div>{completed.length>0?<div className="mt-4 grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-3 items-start">{completed.slice(0,5).map(g=><button key={g.generation_id} onClick={()=>onNavigate('history')} className="text-left group min-w-0"><div className="rounded-2xl overflow-hidden border border-sky-300/[0.09] bg-black group-hover:border-sky-300/[0.22]" style={{aspectRatio:ratio(g.aspect_ratio)}}>{g.mode==='TEXT_TO_IMAGE'||g.mode==='IMAGE_TO_IMAGE'?<img src={g.result_url!} alt="" className="w-full h-full object-contain"/>:<video src={g.result_url!} muted playsInline preload="metadata" className="w-full h-full object-contain"/>}</div><p className="mt-2 text-[9px] font-semibold text-zinc-300 truncate">{g.original_prompt||'Criação'}</p><p className="mt-0.5 text-[8px] text-zinc-600">{g.mode==='TEXT_TO_IMAGE'||g.mode==='IMAGE_TO_IMAGE'?'Imagem':'Vídeo'} · {g.aspect_ratio||'formato original'}</p></button>)}</div>:<div className="mt-4 rounded-2xl border border-dashed border-sky-300/[0.12] bg-sky-300/[0.02] p-8 text-center"><Sparkles className="w-5 h-5 mx-auto text-sky-300/50"/><p className="mt-2 text-[10px] text-zinc-500">Suas próximas criações vão aparecer aqui.</p></div>}</section>
</div>};