import React,{useEffect,useMemo,useRef,useState}from'react';
import{Box,FolderKanban,Layers3,Plus,Search,Sparkles,Trash2,UserRound,X,UploadCloud,Image as ImageIcon,Check,Camera,ScanFace,PersonStanding}from'lucide-react';
import{assetService}from'../../services/assetService.js';
import{creativeEntityService,CreativeEntity,CreativeEntityAssetRole,CreativeEntityKind}from'../../services/creativeEntityService.js';
import{Asset}from'../../types/index.js';

const meta:Record<CreativeEntityKind,{title:string;singular:string;description:string;icon:any;helper:string;placeholder:string}>={
 CHARACTER:{title:'Personagens',singular:'Personagem',description:'Avatares reutilizáveis com identidade visual consistente.',icon:UserRound,helper:'Use uma referência clara de rosto e outra de corpo. O sistema sabe qual imagem deve preservar em cada função.',placeholder:'Ex.: 32 anos, barba curta, cabelo escuro, expressão confiante. Preservar identidade facial, proporções e roupa-base.'},
 PRODUCT:{title:'Produtos',singular:'Produto',description:'Produtos prontos para reutilizar em imagens, CGI e vídeos comerciais.',icon:Box,helper:'Uma única imagem forte é suficiente. Prefira um mockup limpo mostrando vários ângulos do mesmo produto.',placeholder:'Ex.: tênis preto fosco, sola branca. Preservar logo, textura, materiais e proporções.'},
 STYLE:{title:'Estilos',singular:'Estilo',description:'Direções visuais reutilizáveis para manter o mesmo acabamento entre gerações.',icon:Layers3,helper:'Use uma única imagem que represente claramente o estilo desejado.',placeholder:'Ex.: crochê artesanal, realista cinematográfico, editorial premium, 3D clay, anime.'},
 PROJECT:{title:'Projetos',singular:'Projeto',description:'Agrupe referências e organize trabalhos em andamento.',icon:FolderKanban,helper:'Agrupe os assets principais do trabalho para acessá-los rapidamente.',placeholder:'Contexto, objetivo e regras principais deste projeto.'}
};

type SlotKey='FACE'|'BODY'|'PRIMARY';
const slotCopy:Record<SlotKey,{title:string;subtitle:string;icon:any}>={
 FACE:{title:'Imagem de rosto',subtitle:'Rosto bem visível, frontal ou 3/4, sem obstruções.',icon:ScanFace},
 BODY:{title:'Imagem de corpo',subtitle:'Corpo inteiro ou 3/4, proporções e roupa bem visíveis.',icon:PersonStanding},
 PRIMARY:{title:'Imagem principal',subtitle:'A referência única que representa esta entidade.',icon:ImageIcon}
};

export const EntityLibraryView:React.FC<{kind:CreativeEntityKind;embedded?:boolean;projectId?:string|null}>=({kind,embedded=false,projectId})=>{
 const info=meta[kind],Icon=info.icon;
 const[items,setItems]=useState<CreativeEntity[]>([]),[assets,setAssets]=useState<Asset[]>([]),[queryText,setQueryText]=useState(''),[open,setOpen]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false),[activeSlot,setActiveSlot]=useState<SlotKey|null>(null),[slotIds,setSlotIds]=useState<Partial<Record<SlotKey,string>>>({}),[projectAssetIds,setProjectAssetIds]=useState<string[]>([]);
 const fileInputRef=useRef<HTMLInputElement|null>(null);
 const refresh=async()=>setItems(await creativeEntityService.list(kind,kind==='PROJECT'?undefined:projectId));
 useEffect(()=>{refresh().catch(()=>setItems([]));assetService.listAssets().then(setAssets).catch(()=>setAssets([]))},[kind,projectId]);
 const visible=useMemo(()=>{const q=queryText.trim().toLowerCase();return q?items.filter(i=>`${i.name} ${i.description}`.toLowerCase().includes(q)):items},[items,queryText]);
 const imageAssets=assets.filter(a=>a.type==='IMAGE');
 const assetById=(id?:string)=>imageAssets.find(a=>a.asset_id===id)||null;
 const reset=()=>{setOpen(false);setName('');setDescription('');setSlotIds({});setProjectAssetIds([]);setActiveSlot(null)};
 const selectSlot=(slot:SlotKey,id:string)=>{setSlotIds(p=>({...p,[slot]:id}));setActiveSlot(null)};
 const uploadIntoSlot=async(file?:File)=>{if(!activeSlot||!file||!file.type.startsWith('image/'))return;setUploading(true);try{const asset=await assetService.uploadAsset({file,category:kind==='PRODUCT'?'PRODUCT':kind==='CHARACTER'?'CHARACTER':'GENERIC'} as any);setAssets(p=>[asset,...p.filter(x=>x.asset_id!==asset.asset_id)]);selectSlot(activeSlot,asset.asset_id)}finally{setUploading(false)}};
 const save=async()=>{if(!name.trim())return;let assetRoles:Partial<Record<CreativeEntityAssetRole,string>>={};let assetIds:string[]=[];let cover:Asset|null=null;if(kind==='CHARACTER'){const face=assetById(slotIds.FACE),body=assetById(slotIds.BODY);if(!face||!body)return;assetRoles={FACE:face.asset_id,BODY:body.asset_id};assetIds=[face.asset_id,body.asset_id];cover=face}else if(kind==='PRODUCT'||kind==='STYLE'){const primary=assetById(slotIds.PRIMARY);if(!primary)return;assetRoles={PRIMARY:primary.asset_id};assetIds=[primary.asset_id];cover=primary}else{assetIds=projectAssetIds;cover=assetById(projectAssetIds[0])}setSaving(true);try{await creativeEntityService.save({kind,name:name.trim(),description:description.trim(),project_id:kind==='PROJECT'?null:(projectId||null),cover_asset_id:cover?.asset_id||null,cover_url:cover?.thumbnail_url||cover?.public_url||null,asset_ids:Array.from(new Set(assetIds)),asset_roles:assetRoles});reset();await refresh()}finally{setSaving(false)}};
 const canSave=Boolean(name.trim())&&(kind==='CHARACTER'?Boolean(slotIds.FACE&&slotIds.BODY):kind==='PRODUCT'||kind==='STYLE'?Boolean(slotIds.PRIMARY):true);
 const toggleProject=(id:string)=>setProjectAssetIds(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id]);

 const Slot=({slot}: {slot:SlotKey})=>{const copy=slotCopy[slot],SIcon=copy.icon,asset=assetById(slotIds[slot]);return <button type="button" onClick={()=>setActiveSlot(slot)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files?.[0];if(!file)return;setActiveSlot(slot);setTimeout(()=>void uploadIntoSlot(file),0)}} className={`relative min-h-[176px] rounded-2xl overflow-hidden border transition-all text-left group ${asset?'border-white/[0.10] bg-[#0b0e13] hover:border-cyan-300/30':'border-dashed border-white/[0.10] bg-[#0b0e13]/70 hover:border-cyan-300/35 hover:bg-cyan-300/[0.025]'}`}>{asset?<><img src={asset.thumbnail_url||asset.public_url} alt="" className="absolute inset-0 w-full h-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/10 to-black/10"/><div className="absolute inset-x-0 bottom-0 p-3"><div className="flex items-center justify-between gap-2"><div><p className="text-[10px] font-black text-white">{copy.title}</p><p className="mt-0.5 text-[8px] text-zinc-400 truncate max-w-[180px]">{asset.name}</p></div><span className="px-2 py-1 rounded-lg bg-black/55 border border-white/10 text-[8px] text-zinc-300">Alterar</span></div></div></>:<div className="absolute inset-0 grid place-items-center p-5"><div className="text-center"><div className="w-11 h-11 mx-auto rounded-2xl border border-white/[0.08] bg-white/[0.035] grid place-items-center"><SIcon className="w-5 h-5 text-zinc-500"/></div><p className="mt-3 text-[11px] font-black text-zinc-200">{copy.title}</p><p className="mt-1 text-[8px] leading-relaxed text-zinc-600 max-w-[210px]">{copy.subtitle}</p><p className="mt-3 text-[8px] font-semibold text-cyan-300">Clique ou arraste uma imagem</p></div></div>}</button>};

 return <div className="space-y-4 pb-8"><section className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div>{!embedded&&<div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-300"><Icon className="w-4 h-4"/> Biblioteca criativa</div>}<h2 className={`${embedded?'text-lg':'mt-2 text-2xl'} font-black tracking-[-0.03em] text-white`}>{info.title}</h2><p className="mt-1 text-[11px] text-zinc-500 max-w-2xl">{info.description}</p></div><button onClick={()=>setOpen(true)} className="h-9 px-3.5 rounded-xl bg-gradient-to-r from-cyan-300 to-emerald-300 text-[#061015] text-[10px] font-black flex items-center gap-2"><Plus className="w-3.5 h-3.5"/> Novo {info.singular.toLowerCase()}</button></section><div className="relative max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"/><input value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder={`Buscar ${info.title.toLowerCase()}...`} className="w-full h-10 pl-10 pr-3 rounded-xl bg-[#11151c] border border-white/[0.07] text-xs text-zinc-200 outline-none focus:border-cyan-300/25"/></div>
 {visible.length?<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-3">{visible.map(item=><article key={item.entity_id} className="group rounded-xl overflow-hidden border border-white/[0.07] bg-[#11151c] hover:border-cyan-300/20 transition-colors"><div className="aspect-square bg-[#0b0e13] relative overflow-hidden">{item.cover_url?<img src={item.cover_url} className="w-full h-full object-cover group-hover:scale-[1.02] transition-transform" alt=""/>:<div className="w-full h-full grid place-items-center"><Icon className="w-7 h-7 text-zinc-800"/></div>}<span className="absolute left-2 top-2 px-1.5 py-0.5 rounded-md border border-white/10 bg-black/55 backdrop-blur text-[7px] font-bold uppercase tracking-wider text-zinc-300">{info.singular}</span></div><div className="p-2.5"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="text-[11px] font-bold text-white truncate">{item.name}</h3><p className="mt-1 text-[9px] leading-relaxed text-zinc-600 line-clamp-2">{item.description||'Sem descrição.'}</p></div><button onClick={async()=>{if(kind==='PROJECT')await creativeEntityService.archive(item.entity_id);else await creativeEntityService.remove(item.entity_id);await refresh()}} className="p-1.5 rounded-lg text-zinc-700 hover:text-rose-400 hover:bg-rose-500/10"><Trash2 className="w-3 h-3"/></button></div><div className="mt-2 flex items-center gap-1.5 text-[8px] text-zinc-700"><Sparkles className="w-3 h-3 text-cyan-300"/>{kind==='CHARACTER'?'rosto + corpo':`${item.asset_ids.length} referência(s)`}</div></div></article>)}</div>:<div className="min-h-[280px] rounded-2xl border border-dashed border-white/[0.07] bg-[#11151c]/50 grid place-items-center"><div className="text-center"><div className="w-12 h-12 mx-auto rounded-2xl bg-white/[0.035] border border-white/[0.06] grid place-items-center"><Icon className="w-5 h-5 text-zinc-700"/></div><p className="mt-3 text-sm font-semibold text-zinc-300">Nenhum {info.singular.toLowerCase()} ainda</p><p className="mt-1 text-[10px] text-zinc-600">Crie o primeiro e reaproveite referências em novos trabalhos.</p></div></div>}

 {open&&<div className="fixed inset-0 z-[80] bg-black/75 backdrop-blur-sm grid place-items-center p-4"><div className="w-full max-w-2xl max-h-[90vh] overflow-hidden rounded-2xl border border-white/[0.08] bg-[#11151c] shadow-2xl flex flex-col"><div className="px-4 py-3 border-b border-white/[0.06] flex items-center justify-between"><div><h2 className="text-sm font-bold text-white">Criar {info.singular.toLowerCase()}</h2><p className="text-[9px] text-zinc-600">{info.helper}</p></div><button onClick={reset} className="p-1.5 rounded-lg text-zinc-600 hover:text-white"><X className="w-4 h-4"/></button></div><div className="p-4 overflow-y-auto space-y-4"><label><span className="text-[9px] font-semibold text-zinc-400">Nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder={kind==='CHARACTER'?'Ex.: Sofia':kind==='PRODUCT'?'Ex.: Carbon X':kind==='STYLE'?'Ex.: Crochê editorial':'Nome'} className="mt-1 w-full h-10 px-3 rounded-xl bg-[#0b0e13] border border-white/[0.07] text-xs text-white outline-none focus:border-cyan-300/30"/></label>
 {kind==='CHARACTER'&&<><div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><Slot slot="FACE"/><Slot slot="BODY"/></div><div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[0.035] px-3 py-2.5"><p className="text-[9px] font-black text-cyan-300">Por que separar?</p><p className="mt-1 text-[9px] leading-relaxed text-zinc-500">A referência de rosto preserva identidade facial. A de corpo preserva proporções, roupa e silhueta. Isso evita misturar funções e torna o uso do personagem mais previsível.</p></div></>}
 {(kind==='PRODUCT'||kind==='STYLE')&&<><Slot slot="PRIMARY"/><div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[0.035] px-3 py-2.5"><p className="text-[9px] font-black text-cyan-300">{kind==='PRODUCT'?'Imagem recomendada':'Referência recomendada'}</p><p className="mt-1 text-[9px] leading-relaxed text-zinc-500">{kind==='PRODUCT'?'Use um mockup limpo com o produto em vários ângulos na mesma imagem, fundo neutro e detalhes legíveis. Assim uma única referência carrega mais informação sem complicar o fluxo.':'Escolha uma imagem que represente o acabamento final desejado: realista, crochê, clay, anime, editorial, CGI etc.'}</p></div></>}
 {kind==='PROJECT'&&<div><p className="text-[10px] font-semibold text-zinc-300 mb-2">Assets do projeto</p><div className="grid grid-cols-5 sm:grid-cols-7 gap-2 max-h-56 overflow-y-auto">{imageAssets.slice(0,80).map(asset=>{const on=projectAssetIds.includes(asset.asset_id);return <button key={asset.asset_id} onClick={()=>toggleProject(asset.asset_id)} className={`relative aspect-square rounded-lg overflow-hidden border-2 ${on?'border-cyan-300':'border-white/[0.06]'}`}><img src={asset.thumbnail_url||asset.public_url} alt="" className="w-full h-full object-cover"/>{on&&<span className="absolute top-1 right-1 w-4 h-4 rounded-full bg-cyan-300 text-[#071015] grid place-items-center"><Check className="w-2.5 h-2.5"/></span>}</button>})}</div></div>}
 <label><span className="text-[9px] font-semibold text-zinc-400">Descrição e regras</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={info.placeholder} className="mt-1 w-full min-h-20 p-3 rounded-xl bg-[#0b0e13] border border-white/[0.07] text-xs text-white outline-none resize-none focus:border-cyan-300/30"/></label></div><div className="px-4 py-3 border-t border-white/[0.06] flex items-center justify-between"><p className="text-[8px] text-zinc-700">{kind==='CHARACTER'?'2 referências específicas':kind==='PRODUCT'||kind==='STYLE'?'1 referência principal':`${projectAssetIds.length} assets`}</p><div className="flex gap-2"><button onClick={reset} className="h-9 px-3 rounded-xl text-[10px] font-semibold text-zinc-500 hover:text-white">Cancelar</button><button disabled={!canSave||saving} onClick={save} className="h-9 px-4 rounded-xl bg-white text-black text-[10px] font-bold disabled:opacity-40">{saving?'Salvando...':`Criar ${info.singular.toLowerCase()}`}</button></div></div></div></div>}

 {activeSlot&&<div className="fixed inset-0 z-[95] bg-black/80 backdrop-blur-sm grid place-items-center p-4"><div className="w-full max-w-xl max-h-[82vh] rounded-2xl border border-white/[0.08] bg-[#11151c] shadow-2xl flex flex-col overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.06] flex items-center justify-between"><div><h3 className="text-sm font-bold text-white">{slotCopy[activeSlot].title}</h3><p className="text-[9px] text-zinc-600">Escolha uma imagem já salva ou envie uma nova agora.</p></div><button onClick={()=>setActiveSlot(null)} className="p-1.5 rounded-lg text-zinc-600 hover:text-white"><X className="w-4 h-4"/></button></div><div className="p-4 overflow-y-auto"><button onClick={()=>fileInputRef.current?.click()} disabled={uploading} className="w-full h-12 rounded-xl border border-dashed border-cyan-300/25 bg-cyan-300/[0.035] text-cyan-200 flex items-center justify-center gap-2 text-[10px] font-bold hover:bg-cyan-300/[0.06]"><UploadCloud className="w-4 h-4"/>{uploading?'Enviando...':'Fazer upload de uma imagem'}</button><input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={e=>{const f=e.target.files?.[0];void uploadIntoSlot(f);e.currentTarget.value=''}}/><div className="flex items-center gap-3 my-4"><div className="h-px flex-1 bg-white/[0.06]"/><span className="text-[8px] uppercase tracking-wider text-zinc-700">ou escolha da biblioteca</span><div className="h-px flex-1 bg-white/[0.06]"/></div>{imageAssets.length?<div className="grid grid-cols-4 sm:grid-cols-6 gap-2">{imageAssets.slice(0,90).map(asset=><button key={asset.asset_id} onClick={()=>selectSlot(activeSlot,asset.asset_id)} className="group relative aspect-square rounded-xl overflow-hidden border border-white/[0.07] hover:border-cyan-300/40"><img src={asset.thumbnail_url||asset.public_url} alt="" className="w-full h-full object-cover group-hover:scale-[1.03] transition-transform"/></button>)}</div>:<div className="py-12 text-center"><Camera className="w-6 h-6 mx-auto text-zinc-800"/><p className="mt-2 text-[10px] text-zinc-600">Nenhuma imagem salva ainda.</p></div>}</div></div></div>}
 </div>
};
