import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{AlertCircle,ChevronDown,Image as ImageIcon,Layers3,Plus,Sparkles,UploadCloud,X}from'lucide-react';
import{Asset,Generation,GenerationRequestDraft,ModelRegistryItem,PricingEntry,WorkspaceReference}from'../../types/index.js';
import{workspaceService}from'../../services/workspaceService.js';import{assetService}from'../../services/assetService.js';import{generationClient}from'../../services/generationClient.js';import{getModelCapabilities}from'../../services/modelCapabilities.js';import{DEFAULT_PRESERVATION_RULES}from'../../config/constants.js';import{STUDIO_FALLBACK_MODELS,STUDIO_FALLBACK_PRICING}from'../../config/studioCatalog.js';import{useAuth}from'../../context/AuthContext.js';import{PromptComposer}from'../workspace/PromptComposer.js';import{AssetPickerContentView,AssetPickerModal}from'../workspace/AssetPickerModal.js';import{CompactModelPicker}from'../workspace/CompactModelPicker.js';import{CreationGallery}from'../workspace/CreationGallery.js';

interface Props{onUseImageForVideo?: (asset:Asset)=>void;initialEditAsset?:Asset|null;}
type SelectionMode='AUTO'|'MANUAL';const terminal=(s:string)=>['SUCCEEDED','FAILED','CANCELLED','REFUNDED'].includes(s);const creditText=(v?:number|null)=>v==null?'Créditos indisponíveis':`${Math.max(0,Number(v||0)).toLocaleString('pt-BR')} créditos`;const FALLBACK_IMAGE_MODELS=STUDIO_FALLBACK_MODELS.filter(m=>m.category==='IMAGE'&&m.status!=='INACTIVE');const resolutionRank=(v:string)=>({'1K':1,'1.5K':1.5,'2K':2,'4K':4}[v.toUpperCase()]||0);
function localAlias(refs:WorkspaceReference[]){const used=new Set(refs.map(r=>r.alias_snapshot.toLowerCase()));let i=1;while(used.has(`img${i}`))i++;return`img${i}`}
function referenceFor(asset:Asset,refs:WorkspaceReference[],alias?:string):WorkspaceReference{const d=DEFAULT_PRESERVATION_RULES.GENERIC;return{asset_id:asset.asset_id,alias_snapshot:alias||localAlias(refs),role:'GENERAL',priority:'HIGH',preservation_rules:d.preserve,flexible_rules:d.flexible,asset}}
function ratioFromAsset(asset:Asset){if(!asset.width||!asset.height)return'1:1';const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a,d=gcd(asset.width,asset.height);return`${Math.round(asset.width/d)}:${Math.round(asset.height/d)}`}

export const ImageCreateView:React.FC<Props>=({onUseImageForVideo,initialEditAsset})=>{
 const{wallet,refreshWallet}=useAuth();
 const[models,setModels]=useState<ModelRegistryItem[]>(FALLBACK_IMAGE_MODELS),[pricing,setPricing]=useState<PricingEntry[]>(STUDIO_FALLBACK_PRICING),[assets,setAssets]=useState<Asset[]>([]),[favoriteModelIds,setFavoriteModelIds]=useState<string[]>([]),[recentModelIds,setRecentModelIds]=useState<string[]>([]),[selectionMode,setSelectionMode]=useState<SelectionMode>('AUTO'),[manualModelId,setManualModelId]=useState(FALLBACK_IMAGE_MODELS[0]?.model_id||''),[prompt,setPrompt]=useState(''),[references,setReferences]=useState<WorkspaceReference[]>([]),[aspectRatio,setAspectRatio]=useState('1:1'),[resolution,setResolution]=useState('1K'),[numberOfOutputs,setNumberOfOutputs]=useState(1),[seed,setSeed]=useState<number|''>(''),[showAdvanced,setShowAdvanced]=useState(false),[pickerOpen,setPickerOpen]=useState(false),[pickerView,setPickerView]=useState<AssetPickerContentView>('ASSETS'),[generating,setGenerating]=useState(false),[generation,setGeneration]=useState<Generation|null>(null),[error,setError]=useState(''),[livePricesByModelId,setLivePricesByModelId]=useState<Record<string,number|null>>({}),[priceLoadingModelIds,setPriceLoadingModelIds]=useState<string[]>([]),[dragging,setDragging]=useState(false),[uploadBusy,setUploadBusy]=useState(false);
 const pollRef=useRef<any>(null),quoteSeq=useRef(0),quoteCache=useRef(new Map<string,{price:number;providerId:string|null}>());
 useEffect(()=>{let mounted=true;Promise.all([workspaceService.listModels().catch(()=>[]),workspaceService.listPricing().catch(()=>[]),assetService.listAssets().catch(()=>[]),workspaceService.getUserPreferences().catch(()=>({favorite_model_ids:[],recent_model_ids:[]}as any))]).then(([mr,pr,ar,prefs])=>{if(!mounted)return;const imageModels=mr.filter(m=>m.category==='IMAGE'&&m.status!=='INACTIVE');if(imageModels.length){setModels(imageModels);setManualModelId(c=>imageModels.some(m=>m.model_id===c)?c:imageModels[0].model_id)}if(pr.length)setPricing(pr);setAssets(ar||[]);setFavoriteModelIds(prefs.favorite_model_ids||[]);setRecentModelIds(prefs.recent_model_ids||[])});return()=>{mounted=false;if(pollRef.current)clearTimeout(pollRef.current)}},[]);
 const editImage=useCallback((asset:Asset)=>{setError('');setSelectionMode('AUTO');setPrompt('');setReferences([referenceFor(asset,[])]);setAspectRatio(ratioFromAsset(asset));setNumberOfOutputs(1);window.scrollTo({top:0,behavior:'smooth'})},[]);
 useEffect(()=>{if(initialEditAsset?.type==='IMAGE')editImage(initialEditAsset)},[initialEditAsset?.asset_id,editImage]);
 const mode=references.length?'IMAGE_TO_IMAGE':'TEXT_TO_IMAGE';
 const baseCompatibleModels=useMemo(()=>models.filter(model=>{const caps=getModelCapabilities(model);return model.supported_modes.includes(mode)&&model.supported_aspect_ratios.includes(aspectRatio)&&(!references.length||(caps.supports_image_reference&&references.length<=caps.max_reference_images))}),[models,mode,aspectRatio,references.length]);
 const manualModel=models.find(m=>m.model_id===manualModelId)||models[0]||null;
 const availableResolutions=useMemo(()=>{const values=selectionMode==='MANUAL'&&manualModel?manualModel.supported_resolutions:Array.from(new Set(baseCompatibleModels.flatMap(m=>m.supported_resolutions||[])));return[...values].sort((a,b)=>resolutionRank(a)-resolutionRank(b))},[selectionMode,manualModel,baseCompatibleModels]);
 useEffect(()=>{if(availableResolutions.length&&!availableResolutions.includes(resolution))setResolution(availableResolutions.includes('1K')?'1K':availableResolutions[0])},[availableResolutions,resolution]);
 const compatibleModels=useMemo(()=>baseCompatibleModels.filter(m=>m.supported_resolutions.includes(resolution)),[baseCompatibleModels,resolution]);
 const autoModel=useMemo(()=>[...compatibleModels].sort((a,b)=>(livePricesByModelId[a.model_id]??Number.MAX_SAFE_INTEGER)-(livePricesByModelId[b.model_id]??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name))[0]||null,[compatibleModels,livePricesByModelId]);
 const activeModel=selectionMode==='AUTO'?autoModel:manualModel,activeCaps=activeModel?getModelCapabilities(activeModel):null,selectedCompatible=Boolean(activeModel&&compatibleModels.some(m=>m.model_id===activeModel.model_id)),canAttach=selectionMode==='AUTO'?models.some(m=>getModelCapabilities(m).supports_image_reference):Boolean(activeCaps?.supports_image_reference),maxReferences=selectionMode==='AUTO'?Math.max(0,...models.map(m=>getModelCapabilities(m).max_reference_images)):activeCaps?.max_reference_images||0,estimatedPrice=activeModel&&Object.prototype.hasOwnProperty.call(livePricesByModelId,activeModel.model_id)?livePricesByModelId[activeModel.model_id]:null,quoteLoading=Boolean(activeModel&&priceLoadingModelIds.includes(activeModel.model_id)),unitPrice=estimatedPrice==null?null:Math.ceil(estimatedPrice/Math.max(1,numberOfOutputs)),balance=(wallet as any)?.available_credits??wallet?.available_balance_cents??0,hasBalance=estimatedPrice!=null&&balance>=estimatedPrice;
 const quoteModel=async(model:ModelRegistryItem)=>{const preview=await workspaceService.validateAndPreview({model_id:model.model_id,mode,prompt:prompt.trim()||'pricing preview',references,settings:{duration_seconds:1,resolution,aspect_ratio:aspectRatio,number_of_outputs:numberOfOutputs,seed:typeof seed==='number'?seed:null}});const price=(preview.request_draft as any).retail_credit_price??preview.request_draft.estimated_cost_cents;if(price==null)throw new Error('Cotação indisponível.');return{price,providerId:String((preview.request_draft as any).provider_id||'')||null}};
 useEffect(()=>{const seq=++quoteSeq.current,compatibleIds=new Set(compatibleModels.map(m=>m.model_id)),baseline:Record<string,number|null>={};models.forEach(m=>baseline[m.model_id]=compatibleIds.has(m.model_id)?(livePricesByModelId[m.model_id]??null):null);setLivePricesByModelId(baseline);setPriceLoadingModelIds(compatibleModels.map(m=>m.model_id));const timer=window.setTimeout(async()=>{const next={...baseline};await Promise.all(compatibleModels.map(async model=>{const key=`${model.model_id}|${mode}|${resolution}|${aspectRatio}|${numberOfOutputs}|${references.length}|${typeof seed==='number'?seed:''}`,cached=quoteCache.current.get(key);if(cached){next[model.model_id]=cached.price;return}try{const q=await quoteModel(model);quoteCache.current.set(key,q);next[model.model_id]=q.price}catch{next[model.model_id]=null}}));if(seq!==quoteSeq.current)return;setLivePricesByModelId(next);setPriceLoadingModelIds([])},220);return()=>window.clearTimeout(timer)},[models,compatibleModels,mode,resolution,aspectRatio,numberOfOutputs,references.length,typeof seed==='number'?seed:'']);
 const selectModel=async(model:ModelRegistryItem)=>{setSelectionMode('MANUAL');setManualModelId(model.model_id);const p=await workspaceService.trackRecentModel(model.model_id,mode).catch(()=>null);if(p)setRecentModelIds(p.recent_model_ids||[])};const toggleFavorite=async(id:string)=>{const p=await workspaceService.toggleFavoriteModel(id).catch(()=>null);if(p)setFavoriteModelIds(p.favorite_model_ids||[])};
 const addReference=(asset:Asset)=>setReferences(prev=>prev.some(r=>r.asset_id===asset.asset_id)||prev.length>=maxReferences?prev:[...prev,referenceFor(asset,prev)]);const removeReference=(id:string)=>setReferences(prev=>prev.filter(r=>r.asset_id!==id));const openPicker=(view:AssetPickerContentView='ASSETS')=>{setPickerView(view);setPickerOpen(true)};
 const quickUpload=useCallback(async(files:File[])=>{const images=files.filter(f=>f.type.startsWith('image/'));if(!images.length)return;setUploadBusy(true);try{for(const file of images){const asset=await assetService.uploadAsset({file,category:'GENERIC'});setAssets(prev=>[asset,...prev.filter(x=>x.asset_id!==asset.asset_id)]);setReferences(prev=>prev.some(r=>r.asset_id===asset.asset_id)||prev.length>=maxReferences?prev:[...prev,referenceFor(asset,prev)])}}catch(e:any){setError(e?.message||'Não foi possível enviar a imagem.')}finally{setUploadBusy(false)}},[maxReferences]);
 useEffect(()=>{const onPaste=(e:ClipboardEvent)=>{const files=Array.from(e.clipboardData?.files||[]).filter(f=>f.type.startsWith('image/'));if(files.length)void quickUpload(files)};window.addEventListener('paste',onPaste);return()=>window.removeEventListener('paste',onPaste)},[quickUpload]);
 const restoreGeneration=(saved:Generation)=>{setError('');setSelectionMode('MANUAL');setManualModelId(saved.model_id);setPrompt(saved.original_prompt||'');setAspectRatio(saved.aspect_ratio||'1:1');setResolution(saved.resolution||'1K');setNumberOfOutputs(saved.number_of_outputs||1);setSeed(saved.seed??'');const restored:WorkspaceReference[]=[];(saved.references||[]).forEach((snapshot,index)=>{const asset=assets.find(a=>a.asset_id===snapshot.asset_id);if(asset)restored.push(referenceFor(asset,restored,snapshot.alias||`img${index+1}`))});setReferences(restored);window.scrollTo({top:0,behavior:'smooth'})};
 const refreshAssets=async()=>{const rows=await assetService.listAssets().catch(()=>[]);if(rows.length)setAssets(rows)};
 const poll=(id:string)=>{pollRef.current=setTimeout(async()=>{try{const next=await generationClient.get(id);setGeneration(next);window.dispatchEvent(new CustomEvent('generation:updated',{detail:next}));if(next.status==='SUCCEEDED'){await Promise.all([refreshAssets(),refreshWallet()]);setGenerating(false);return}if(terminal(next.status)){setGenerating(false);if(next.status==='FAILED')setError(next.error_message||'A geração falhou.');return}poll(id)}catch(e:any){setGenerating(false);setError(e?.message||'Falha ao consultar a geração.')}},2200)};
 const generate=async()=>{setError('');if(!prompt.trim())return setError('Descreva a imagem que deseja criar.');if(!activeModel||!selectedCompatible)return setError('Escolha uma IA compatível ou use Auto para encontrar uma rota válida.');if(quoteLoading||estimatedPrice==null)return setError('Aguarde a cotação antes de gerar.');if(!hasBalance)return setError('Créditos insuficientes para esta geração.');try{setPriceLoadingModelIds(prev=>Array.from(new Set([...prev,activeModel.model_id])));const fresh=await quoteModel(activeModel);setPriceLoadingModelIds(prev=>prev.filter(id=>id!==activeModel.model_id));let authorizedPrice=estimatedPrice;if(fresh.price<estimatedPrice){authorizedPrice=fresh.price;setLivePricesByModelId(prev=>({...prev,[activeModel.model_id]:fresh.price}))}else if(fresh.price>estimatedPrice)return setError(`A cotação subiu de ${creditText(estimatedPrice)} para ${creditText(fresh.price)}. Nada foi cobrado. Aguarde a atualização do preço.`);setGenerating(true);const draft={request_id:`img_req_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,user_id:'',model_id:activeModel.model_id,model_name:activeModel.name,mode,prompt:prompt.trim(),compiled_prompt:prompt.trim(),prompt_compiler_version:'image-workspace-credits-v2',references,settings:{duration_seconds:1,resolution,aspect_ratio:aspectRatio,number_of_outputs:numberOfOutputs,seed:typeof seed==='number'?seed:null},estimated_cost_cents:authorizedPrice,customer_balance_available_cents:balance,retail_credit_price:authorizedPrice,authorized_credit_price:authorizedPrice,credit_balance_available:balance,created_at:new Date().toISOString()}as unknown as GenerationRequestDraft;const started=await generationClient.create(draft);setGeneration(started);window.dispatchEvent(new CustomEvent('generation:updated',{detail:started}));if(terminal(started.status)){setGenerating(false);if(started.status==='SUCCEEDED')await Promise.all([refreshAssets(),refreshWallet()]);else setError(started.error_message||'A geração não pôde ser concluída.')}else poll(started.generation_id)}catch(e:any){setGenerating(false);setError(e?.message||'Não foi possível iniciar a geração.')}};
 const useForVideo=async(asset:Asset)=>{try{const d=DEFAULT_PRESERVATION_RULES.GENERIC;await workspaceService.saveDraft({model_id:'AUTO',mode:'IMAGE_TO_VIDEO',prompt:'',references:[{asset_id:asset.asset_id,alias_snapshot:'img1',role:'START_FRAME',priority:'HIGH',preservation_rules:d.preserve,flexible_rules:d.flexible,asset}],settings:{duration_seconds:5,resolution:'720p',aspect_ratio:ratioFromAsset(asset),number_of_outputs:1}});onUseImageForVideo?.(asset)}catch(e:any){setError(e?.message||'Não foi possível preparar esta imagem para vídeo.')}};

 return <div className="flex h-full min-h-0 bg-[#0b0e13]">
  <aside className="w-full md:w-[344px] xl:w-[356px] h-full shrink-0 bg-[#090c11] border-r border-white/[0.06] flex flex-col">
   <div className="flex-1 overflow-y-auto p-3 space-y-2.5">
    <CompactModelPicker models={models} pricing={pricing} selectionMode={selectionMode} selectedModelId={manualModelId} autoResolvedModel={autoModel} onSelectAuto={()=>setSelectionMode('AUTO')} onSelectModel={selectModel} favoriteModelIds={favoriteModelIds} recentModelIds={recentModelIds} onToggleFavorite={toggleFavorite} currentResolution={resolution} currentDuration={1} currentOutputs={numberOfOutputs} livePricesByModelId={livePricesByModelId} priceLoadingModelIds={priceLoadingModelIds}/>
    <section onDragEnter={e=>{e.preventDefault();setDragging(true)}} onDragOver={e=>e.preventDefault()} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);void quickUpload(Array.from(e.dataTransfer.files||[]))}} className={`rounded-xl border p-2.5 transition-colors ${dragging?'border-cyan-300/55 bg-cyan-300/[0.07]':'border-white/[0.065] bg-white/[0.025]'}`}>
      <div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold text-zinc-300">Referências</p><p className="text-[8px] text-zinc-700">Cole, arraste ou escolha uma imagem</p></div><button disabled={!canAttach||references.length>=maxReferences} onClick={()=>openPicker('ASSETS')} className="w-7 h-7 rounded-lg border border-white/[0.07] bg-white/[0.035] grid place-items-center text-zinc-400 disabled:opacity-30"><Plus className="w-3.5 h-3.5"/></button></div>
      {references.length>0?<div className="mt-2 flex gap-1.5 overflow-x-auto">{references.map(ref=><div key={ref.asset_id} className="relative w-14 h-14 shrink-0 rounded-lg overflow-hidden border border-white/[0.08]">{ref.asset?.public_url?<img src={ref.asset.thumbnail_url||ref.asset.public_url} className="w-full h-full object-cover" alt=""/>:<ImageIcon className="absolute inset-0 m-auto w-4 h-4 text-zinc-700"/>}<button onClick={()=>removeReference(ref.asset_id)} className="absolute top-0.5 right-0.5 w-4 h-4 rounded bg-black/70 grid place-items-center"><X className="w-2.5 h-2.5"/></button><span className="absolute left-1 bottom-1 px-1 py-0.5 rounded text-[7px] font-mono bg-black/70 text-white">@{ref.alias_snapshot}</span></div>)}</div>:<div className="mt-2 h-10 rounded-lg border border-dashed border-white/[0.08] flex items-center justify-center gap-1.5 text-[8px] text-zinc-700"><UploadCloud className="w-3.5 h-3.5"/>{uploadBusy?'Enviando...':'Arraste uma imagem aqui'}</div>}
    </section>
    <PromptComposer prompt={prompt} onChangePrompt={setPrompt} negativePrompt="" onChangeNegativePrompt={()=>{}} onOpenImproveModal={()=>{}} references={references} onRequestAddMedia={openPicker} supportsNegativePrompt={false} maxChars={activeCaps?.max_prompt_length||10000}/>
    <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><p className="text-[9px] font-semibold text-zinc-400 mb-2">Proporção</p><div className="flex flex-wrap gap-1.5">{(activeModel?.supported_aspect_ratios?.length?activeModel.supported_aspect_ratios:['1:1','16:9','9:16','4:3','3:4']).map(r=><button key={r} onClick={()=>setAspectRatio(r)} className={`px-2.5 py-1.5 rounded-lg border text-[9px] font-semibold ${aspectRatio===r?'border-cyan-300/35 bg-cyan-300/10 text-cyan-200':'border-white/[0.06] text-zinc-500'}`}>{r}</button>)}</div></section>
    <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><div className="flex items-center justify-between mb-2"><div><p className="text-[9px] font-semibold text-zinc-400">Qualidade</p><p className="text-[7px] text-zinc-700">Opções disponíveis para {activeModel?.name||'a IA selecionada'}</p></div><span className="text-[9px] font-black text-cyan-300">{resolution}</span></div><div className={`grid gap-1.5 ${availableResolutions.length>=4?'grid-cols-4':availableResolutions.length===3?'grid-cols-3':availableResolutions.length===2?'grid-cols-2':'grid-cols-1'}`}>{availableResolutions.map(v=><button key={v} onClick={()=>setResolution(v)} className={`h-8 rounded-lg border text-[9px] font-bold ${resolution===v?'border-cyan-300/40 bg-cyan-300/10 text-cyan-200':'border-white/[0.06] text-zinc-600'}`}>{v}</button>)}</div>{unitPrice!=null&&<p className="mt-2 text-[7px] text-zinc-700">{creditText(unitPrice)} por imagem · preço atual</p>}</section>
    <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><div className="flex items-center justify-between mb-2"><div className="flex items-center gap-1.5"><Layers3 className="w-3.5 h-3.5 text-zinc-600"/><p className="text-[9px] font-semibold text-zinc-400">Quantidade</p></div><span className="text-[8px] text-zinc-700">gera de uma vez</span></div><div className="grid grid-cols-4 gap-1.5">{[1,2,3,4].map(n=><button key={n} onClick={()=>setNumberOfOutputs(n)} className={`h-8 rounded-lg border text-[10px] font-black ${numberOfOutputs===n?'border-cyan-300/35 bg-cyan-300/10 text-cyan-200':'border-white/[0.06] text-zinc-600'}`}>{n}</button>)}</div></section>
    <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] overflow-hidden"><button onClick={()=>setShowAdvanced(v=>!v)} className="w-full h-10 px-3 flex items-center text-[10px] font-semibold text-zinc-400">Configurações avançadas <ChevronDown className={`ml-auto w-3.5 h-3.5 transition-transform ${showAdvanced?'rotate-180':''}`}/></button>{showAdvanced&&<div className="px-3 pb-3"><label className="text-[8px] text-zinc-600">Seed<input type="number" value={seed} onChange={e=>setSeed(e.target.value===''?'':Number(e.target.value))} placeholder="Aleatório" className="mt-1 w-full h-8 px-2 rounded-lg bg-[#0b0e13] border border-white/[0.06] text-[9px] text-zinc-300 outline-none"/></label></div>}</section>
    {error&&<div className="rounded-xl border border-rose-400/15 bg-rose-500/[0.06] px-3 py-2 text-[9px] text-rose-300 flex gap-2"><AlertCircle className="w-3.5 h-3.5 shrink-0"/>{error}</div>}
   </div>
   <div className="p-3 border-t border-white/[0.06] bg-[#080b0f]"><div className="mb-2 flex items-center justify-between"><div><p className="text-[8px] text-zinc-700">Preço final · {numberOfOutputs} imagem(ns) · {resolution}</p><p className="text-[11px] font-bold text-white">{quoteLoading?'Calculando...':creditText(estimatedPrice)}</p></div><div className="text-right"><p className="text-[8px] text-zinc-700">Saldo</p><p className="text-[10px] font-semibold text-zinc-400">{creditText(balance)}</p></div></div><button onClick={generate} disabled={generating||quoteLoading||!prompt.trim()||!activeModel||!selectedCompatible||estimatedPrice==null||!hasBalance} className="w-full h-11 rounded-xl bg-gradient-to-r from-cyan-300 via-emerald-300 to-cyan-300 text-[#071015] text-[11px] font-black flex items-center justify-center gap-2 disabled:opacity-35 disabled:grayscale"><Sparkles className="w-4 h-4"/>{generating?'Gerando...':`Gerar ${numberOfOutputs>1?`${numberOfOutputs} imagens`:'imagem'}${estimatedPrice!=null?` • ${estimatedPrice.toLocaleString('pt-BR')} créditos`:''}`}</button></div>
  </aside>
  <CreationGallery defaultFilter="IMAGE" title="Minhas criações" subtitle="Imagens, vídeos e histórico do seu studio." liveGeneration={generation} onRestoreGeneration={restoreGeneration} onUseImageAsReference={addReference} onEditImage={editImage} onCreateVideoFromImage={useForVideo}/>
  <AssetPickerModal isOpen={pickerOpen} onClose={()=>setPickerOpen(false)} availableAssets={assets} onSelectAsset={addReference} onAssetUploaded={asset=>setAssets(prev=>[asset,...prev.filter(i=>i.asset_id!==asset.asset_id)])} attachedAssetIds={references.map(r=>r.asset_id)} title="Adicionar referência à imagem" subtitle="Escolha mídia, personagem, produto ou estilo sem repetir etapas." defaultTab="LIBRARY" defaultContentView={pickerView} allowedTypes={['IMAGE']}/>
 </div>;
};