import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{Brush,CheckCircle2,Eraser,Expand,Image as ImageIcon,Layers,LoaderCircle,RefreshCw,RemoveFormatting,Scaling,Sparkles,Upload,WandSparkles}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{assetService}from'../../services/assetService.js';
import{apiRequest,ApiError}from'../../services/apiClient.js';
import{editorClient,EditorCapability,EditorJobView}from'../../services/editorClient.js';
import{Asset}from'../../types/index.js';
import{CreationGallery}from'../workspace/CreationGallery.js';

type Tool=Extract<EditorCapability,'image-edit'|'inpaint-mask'|'background-remove-replace'|'outpaint'|'upscale'|'variations'>;
const TOOLS:Array<{id:Tool;label:string;description:string;icon:React.ComponentType<{className?:string}>}>=[
 {id:'image-edit',label:'Editar',description:'Altere a imagem com instruções.',icon:WandSparkles},
 {id:'inpaint-mask',label:'Inpaint',description:'Edite somente a área pintada.',icon:Brush},
 {id:'background-remove-replace',label:'Fundo',description:'Remova ou substitua o fundo.',icon:RemoveFormatting},
 {id:'outpaint',label:'Expandir',description:'Amplie a cena para outro formato.',icon:Expand},
 {id:'upscale',label:'Upscale',description:'Aumente a resolução preservando o conteúdo.',icon:Scaling},
 {id:'variations',label:'Variações',description:'Crie uma nova versão fiel ao original.',icon:Layers},
];
const promptRequired=(tool:Tool)=>['image-edit','inpaint-mask','outpaint'].includes(tool);
const errorText=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir esta operação.';
const status=(job:EditorJobView|null)=>job?.status==='SUCCEEDED'?'Concluído':job?.status==='FAILED'?'Falhou':job?.status==='RUNNING'?'Processando':job?.status==='QUEUED'?'Na fila':job?.status==='QUOTED'?'Preço calculado':'Preparando';

export const ImageEditorView:React.FC=()=>{
 const{wallet,refreshWallet}=useAuth();
 const[tool,setTool]=useState<Tool>('image-edit'),[models,setModels]=useState<any[]>([]),[images,setImages]=useState<Asset[]>([]),[sourceId,setSourceId]=useState(''),[prompt,setPrompt]=useState(''),[resolution,setResolution]=useState('2K'),[aspectRatio,setAspectRatio]=useState('1:1'),[backgroundMode,setBackgroundMode]=useState<'TRANSPARENT'|'REPLACE'>('TRANSPARENT'),[variationStrength,setVariationStrength]=useState(.35),[brushSize,setBrushSize]=useState(46),[maskDirty,setMaskDirty]=useState(false),[job,setJob]=useState<EditorJobView|null>(null),[result,setResult]=useState<Asset|null>(null),[busy,setBusy]=useState('load'),[error,setError]=useState(''),[pollCount,setPollCount]=useState(0);
 const maskRef=useRef<HTMLCanvasElement|null>(null),drawing=useRef(false);
 const load=useCallback(async()=>{setBusy(current=>current||'load');setError('');try{const[catalog,assets]=await Promise.all([editorClient.catalog(),assetService.listAssets({type:'IMAGE'})]);setModels(catalog.filter(model=>model.capabilities.some((cap:any)=>TOOLS.some(tool=>tool.id===cap.id))));setImages(assets);setSourceId(current=>current||assets[0]?.asset_id||'');}catch(err){setError(errorText(err));}finally{setBusy(current=>current==='load'?'':current);}},[]);
 useEffect(()=>{void load();},[load]);
 const source=images.find(asset=>asset.asset_id===sourceId)||null;
 const eligible=useMemo(()=>models.filter(model=>model.capabilities.some((cap:any)=>cap.id===tool)),[models,tool]);
 const model=eligible.find(model=>model.model_id==='AUTO')||eligible[0]||null;
 const invalidate=()=>{setJob(null);setResult(null);setPollCount(0);setError('');};
 useEffect(()=>{invalidate();},[tool,sourceId]);
 useEffect(()=>{if(!job||!['QUEUED','RUNNING'].includes(job.status)||pollCount>=150)return;const timer=window.setTimeout(async()=>{try{setJob(await editorClient.get(job.job_id));setPollCount(v=>v+1);}catch(err){setError(errorText(err));setPollCount(150);}},Math.min(6500,1800+pollCount*120));return()=>window.clearTimeout(timer);},[job,pollCount]);
 useEffect(()=>{if(job?.status!=='SUCCEEDED')return;void refreshWallet();const id=job.result_asset_ids?.[0];if(id)void editorClient.asset(id).then(setResult).catch(()=>setResult(null));window.dispatchEvent(new CustomEvent('creations:updated',{detail:{kind:'IMAGE',asset_ids:job.result_asset_ids||[]}}));},[job?.status,job?.result_asset_ids,refreshWallet]);
 const clearMask=useCallback(()=>{const canvas=maskRef.current,ctx=canvas?.getContext('2d');if(!canvas||!ctx)return;ctx.fillStyle='#000';ctx.fillRect(0,0,canvas.width,canvas.height);setMaskDirty(false);},[]);
 useEffect(()=>{if(tool==='inpaint-mask')requestAnimationFrame(clearMask);},[tool,sourceId,clearMask]);
 const point=(event:React.PointerEvent<HTMLCanvasElement>)=>{const canvas=event.currentTarget,rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height};};
 const begin=(event:React.PointerEvent<HTMLCanvasElement>)=>{drawing.current=true;event.currentTarget.setPointerCapture(event.pointerId);const p=point(event),ctx=event.currentTarget.getContext('2d');ctx?.beginPath();ctx?.moveTo(p.x,p.y);};
 const move=(event:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const p=point(event),ctx=event.currentTarget.getContext('2d');if(!ctx)return;ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#fff';ctx.lineWidth=brushSize*event.currentTarget.width/700;ctx.lineTo(p.x,p.y);ctx.stroke();setMaskDirty(true);};
 const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy('upload');try{const asset=await assetService.uploadAsset({file,name:file.name});setImages(rows=>[asset,...rows.filter(row=>row.asset_id!==asset.asset_id)]);setSourceId(asset.asset_id);invalidate();}catch(err){setError(errorText(err));}finally{setBusy('');}};
 const uploadMask=async()=>{const canvas=maskRef.current;if(!canvas||!maskDirty)throw new Error('Pinte a área que deseja alterar.');const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(value=>value?resolve(value):reject(new Error('Não foi possível gerar a máscara.')),'image/png'));const file=new File([blob],`mask-${Date.now()}.png`,{type:'image/png'});const asset=await assetService.uploadAsset({file,name:'Máscara de inpaint'});await apiRequest(`/api/assets/${encodeURIComponent(asset.asset_id)}`,{method:'PATCH',body:JSON.stringify({media_metadata:{editor_mask:true}})});return asset;};
 const buildRequest=async()=>{if(!source)throw new Error('Selecione uma imagem.');if(!model)throw new Error('Nenhum modelo elegível está disponível.');if(promptRequired(tool)&&!prompt.trim())throw new Error('Descreva a edição desejada.');if(tool==='background-remove-replace'&&backgroundMode==='REPLACE'&&!prompt.trim())throw new Error('Descreva o novo fundo.');const references:any[]=[{asset_id:source.asset_id,slot_type:'GENERAL',role:'SOURCE'}];if(tool==='inpaint-mask'){const mask=await uploadMask();references.push({asset_id:mask.asset_id,slot_type:'GENERAL',role:'MASK'});}const operation:Record<Tool,string>={'image-edit':'EDIT','inpaint-mask':'INPAINT','background-remove-replace':backgroundMode==='TRANSPARENT'?'BACKGROUND_REMOVE':'BACKGROUND_REPLACE','outpaint':'OUTPAINT','upscale':'UPSCALE','variations':'VARIATIONS'};const controls:any={resolution,output_format:'png',number_of_outputs:1,editor_operation:operation[tool],background_mode:tool==='background-remove-replace'?backgroundMode:undefined,variation_strength:tool==='variations'?variationStrength:undefined};if(tool==='image-edit'||tool==='outpaint')controls.aspect_ratio=aspectRatio;return{capability_id:tool,model_id:model.model_id,prompt:prompt.trim(),references,controls};};
 const quote=async()=>{setBusy('quote');setError('');try{const created=await editorClient.create(await buildRequest());setJob(await editorClient.quote(created.job_id));setPollCount(0);}catch(err){setError(errorText(err));}finally{setBusy('');}};
 const execute=async()=>{if(!job)return;setBusy('execute');setError('');try{setJob(await editorClient.queue(job.job_id));setPollCount(0);}catch(err){setError(errorText(err));}finally{setBusy('');}};
 const price=job?.quote?.credit_price??null,balance=wallet?.available_credits??0,insufficient=price!=null&&balance<price;
 return <div className="flex h-full min-h-0 flex-col xl:flex-row bg-[#080c12]">
  <section className="w-full xl:w-[46%] min-h-0 overflow-y-auto border-b xl:border-b-0 xl:border-r border-white/[0.06] p-4 sm:p-5 lg:p-6 space-y-4">
   <header><span className="text-[9px] font-bold uppercase tracking-[.18em] text-cyan-300">Editor de imagem</span><h1 className="mt-1 text-xl font-bold text-white">Edite sem destruir o original.</h1><p className="mt-1 text-[11px] text-zinc-500">Cada edição cria um novo asset derivado e preserva a origem.</p></header>
   <div className="grid grid-cols-2 lg:grid-cols-3 gap-2">{TOOLS.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTool(item.id)} className={`rounded-xl border p-3 text-left ${tool===item.id?'border-cyan-300/25 bg-cyan-300/[0.08]':'border-white/[0.07] bg-white/[0.025]'}`}><Icon className="w-4 h-4 text-cyan-200"/><strong className="mt-2 block text-[10px] text-zinc-200">{item.label}</strong><small className="block mt-1 text-[8px] leading-relaxed text-zinc-600">{item.description}</small></button>})}</div>
   <div className="flex gap-2"><select value={sourceId} onChange={e=>setSourceId(e.target.value)} className="flex-1 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-[10px] text-zinc-300"><option value="">Selecione da Biblioteca</option>{images.map(asset=><option key={asset.asset_id} value={asset.asset_id}>{asset.name}</option>)}</select><label className="h-10 px-3 rounded-xl border border-white/[0.08] flex items-center gap-2 text-[10px] text-zinc-300 cursor-pointer"><Upload className="w-3.5 h-3.5"/>{busy==='upload'?'Enviando':'Upload'}<input className="hidden" type="file" accept="image/*" onChange={upload}/></label></div>
   <div className="relative min-h-[280px] rounded-2xl border border-white/[0.07] bg-black/30 overflow-hidden grid place-items-center">{source?.public_url?<img src={source.public_url} alt={source.name} className="max-h-[460px] max-w-full object-contain"/>:<div className="text-zinc-700 text-center"><ImageIcon className="w-8 h-8 mx-auto"/><span className="text-[9px]">Selecione uma imagem</span></div>}{tool==='inpaint-mask'&&source&&<canvas ref={maskRef} width={1024} height={1024} className="absolute inset-0 w-full h-full opacity-45 touch-none" onPointerDown={begin} onPointerMove={move} onPointerUp={()=>drawing.current=false} onPointerCancel={()=>drawing.current=false}/>}</div>
   {tool==='inpaint-mask'&&<div className="flex items-center gap-3"><label className="flex-1 text-[9px] text-zinc-500">Pincel <input className="w-full" type="range" min={12} max={140} value={brushSize} onChange={e=>setBrushSize(Number(e.target.value))}/></label><button onClick={clearMask} className="text-[9px] text-zinc-400 flex gap-1"><Eraser className="w-3 h-3"/>Limpar</button></div>}
   {['image-edit','inpaint-mask','background-remove-replace','outpaint','variations'].includes(tool)&&<textarea rows={4} value={prompt} onChange={e=>{setPrompt(e.target.value);invalidate();}} placeholder="Descreva a edição desejada…" className="w-full rounded-xl bg-white/[0.035] border border-white/[0.07] p-3 text-[11px] text-zinc-200 outline-none"/>}
   <div className="grid sm:grid-cols-2 gap-2">{tool==='background-remove-replace'&&<label className="text-[9px] text-zinc-500">Fundo<select value={backgroundMode} onChange={e=>{setBackgroundMode(e.target.value as any);invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300"><option value="TRANSPARENT">Remover / transparente</option><option value="REPLACE">Substituir</option></select></label>}{tool==='outpaint'&&<label className="text-[9px] text-zinc-500">Formato final<select value={aspectRatio} onChange={e=>{setAspectRatio(e.target.value);invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300">{['1:1','16:9','9:16','4:3','3:4','21:9'].map(v=><option key={v}>{v}</option>)}</select></label>}<label className="text-[9px] text-zinc-500">Resolução<select value={resolution} onChange={e=>{setResolution(e.target.value);invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300">{['1K','2K','4K'].map(v=><option key={v}>{v}</option>)}</select></label>{tool==='variations'&&<label className="text-[9px] text-zinc-500">Força · {Math.round(variationStrength*100)}%<input className="mt-2 w-full" type="range" min={.1} max={.9} step={.05} value={variationStrength} onChange={e=>{setVariationStrength(Number(e.target.value));invalidate();}}/></label>}</div>
   {error&&<div className="rounded-xl border border-rose-400/15 bg-rose-400/[0.05] p-3 text-[10px] text-rose-300">{error}</div>}
   <div className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between"><div><span className="text-[8px] uppercase tracking-wider text-zinc-600">Créditos</span><strong className="block text-[12px] text-white">{price==null?'Calcule antes de executar':`${price.toLocaleString('pt-BR')} créditos`}</strong>{price!=null&&<small className="text-[8px] text-zinc-600">Saldo: {balance.toLocaleString('pt-BR')}</small>}</div>{!job?.quote?<button onClick={()=>void quote()} disabled={Boolean(busy)||!model||!source} className="ia-button-primary h-10 px-4 text-[10px] font-bold flex items-center gap-2 justify-center">{busy==='quote'?<LoaderCircle className="w-4 h-4 animate-spin"/>:<Sparkles className="w-4 h-4"/>}Calcular créditos</button>:['DRAFT','QUOTED'].includes(job.status)?<div className="flex gap-2"><button onClick={()=>void quote()} className="h-10 px-3 rounded-xl border border-white/[0.08] text-[9px] text-zinc-400"><RefreshCw className="w-3.5 h-3.5"/></button><button onClick={()=>void execute()} disabled={Boolean(busy)||insufficient} className="ia-button-primary h-10 px-4 text-[10px] font-bold flex items-center gap-2">{busy==='execute'?<LoaderCircle className="w-4 h-4 animate-spin"/>:<WandSparkles className="w-4 h-4"/>}Aplicar edição</button></div>:<button disabled className="h-10 px-4 rounded-xl border border-white/[0.08] text-[9px] text-zinc-500">{status(job)}</button>}</div>
   {job?.status==='SUCCEEDED'&&result?.public_url&&<section className="grid grid-cols-2 gap-3"><div><span className="text-[8px] text-zinc-600">Original</span><img src={source?.public_url||''} className="mt-1 rounded-xl w-full aspect-square object-cover"/></div><div><span className="text-[8px] text-zinc-600">Resultado</span><img src={result.public_url} className="mt-1 rounded-xl w-full aspect-square object-cover"/></div></section>}
  </section>
  <section className="flex-1 min-h-[420px] xl:min-h-0"><CreationGallery defaultFilter="IMAGE" title="Minhas criações" subtitle="Histórico universal do IA Connect. Edições aparecem junto das demais imagens."/></section>
 </div>;
};
export default ImageEditorView;
