import React, { useEffect, useMemo, useRef, useState } from 'react';
import { AlertCircle, Check, ChevronDown, Download, ExternalLink, Image as ImageIcon, Loader2, Plus, RefreshCw, Sparkles, Video, WandSparkles, X } from 'lucide-react';
import { Asset, ModelRegistryItem, PricingEntry, WorkspaceReference, Generation, GenerationRequestDraft } from '../../types/index.js';
import { workspaceService } from '../../services/workspaceService.js';
import { assetService } from '../../services/assetService.js';
import { generationClient } from '../../services/generationClient.js';
import { getModelCapabilities } from '../../services/modelCapabilities.js';
import { DEFAULT_PRESERVATION_RULES } from '../../config/constants.js';
import { useAuth } from '../../context/AuthContext.js';
import { PromptComposer } from '../workspace/PromptComposer.js';
import { AssetPickerModal } from '../workspace/AssetPickerModal.js';

interface Props { onUseImageForVideo?: (asset: Asset) => void; }
type SelectionMode = 'AUTO' | 'MANUAL';
const terminal = (status: string) => ['SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED'].includes(status);
const money = (cents?: number | null) => cents == null ? 'Preço indisponível' : new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(cents/100);

function localAlias(refs: WorkspaceReference[]) { const used=new Set(refs.map(r=>r.alias_snapshot.toLowerCase())); let i=1; while(used.has(`img${i}`))i++; return `img${i}`; }
function referenceFor(asset: Asset, refs: WorkspaceReference[]): WorkspaceReference { const d=DEFAULT_PRESERVATION_RULES.GENERIC; return {asset_id:asset.asset_id,alias_snapshot:localAlias(refs),role:'GENERAL',priority:'HIGH',preservation_rules:d.preserve,flexible_rules:d.flexible,asset}; }

export const ImageCreateView: React.FC<Props> = ({ onUseImageForVideo }) => {
  const { wallet, refreshWallet } = useAuth();
  const [loading,setLoading]=useState(true); const [models,setModels]=useState<ModelRegistryItem[]>([]); const [pricing,setPricing]=useState<PricingEntry[]>([]); const [assets,setAssets]=useState<Asset[]>([]);
  const [selectionMode,setSelectionMode]=useState<SelectionMode>('AUTO'); const [manualModelId,setManualModelId]=useState(''); const [prompt,setPrompt]=useState(''); const [references,setReferences]=useState<WorkspaceReference[]>([]);
  const [aspectRatio,setAspectRatio]=useState('1:1'); const [seed,setSeed]=useState<number|''>(''); const [showAdvanced,setShowAdvanced]=useState(false); const [pickerOpen,setPickerOpen]=useState(false);
  const [generating,setGenerating]=useState(false); const [generation,setGeneration]=useState<Generation|null>(null); const [resultAssets,setResultAssets]=useState<Asset[]>([]); const [error,setError]=useState(''); const pollRef=useRef<any>(null);

  useEffect(()=>{let mounted=true;(async()=>{try{setLoading(true);const [modelRows,priceRows,assetRows]=await Promise.all([workspaceService.listModels(),workspaceService.listPricing(),assetService.listAssets()]);if(!mounted)return;const imageModels=modelRows.filter(m=>m.category==='IMAGE'&&m.status!=='INACTIVE');setModels(imageModels);setPricing(priceRows||[]);setAssets(assetRows||[]);setManualModelId(imageModels[0]?.model_id||'');}catch(err:any){if(mounted)setError(err?.message||'Não foi possível preparar o gerador de imagens.');}finally{if(mounted)setLoading(false);}})();return()=>{mounted=false;if(pollRef.current)clearTimeout(pollRef.current);};},[]);

  const mode=references.length?'IMAGE_TO_IMAGE':'TEXT_TO_IMAGE';
  const compatibleModels=useMemo(()=>models.filter(model=>{if(!model.supported_modes.includes(mode))return false;if(!model.supported_aspect_ratios.includes(aspectRatio))return false;if(references.length){const c=getModelCapabilities(model);if(!c.supports_image_reference||references.length>c.max_reference_images)return false;}return true;}),[models,mode,aspectRatio,references.length]);
  const priceFor=(modelId:string)=>{const rows=pricing.filter(r=>r.active&&r.model_id===modelId&&(!r.resolution||r.resolution==='1K'||r.resolution==='ANY'));return rows.length?Math.min(...rows.map(r=>r.customer_price_cents)):null;};
  const autoModel=useMemo(()=>[...compatibleModels].sort((a,b)=>(priceFor(a.model_id)??Number.MAX_SAFE_INTEGER)-(priceFor(b.model_id)??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name))[0]||null,[compatibleModels,pricing]);
  const manualModel=models.find(m=>m.model_id===manualModelId)||null; const activeModel=selectionMode==='AUTO'?autoModel:manualModel; const activeCaps=activeModel?getModelCapabilities(activeModel):null;
  const selectedCompatible=Boolean(activeModel&&compatibleModels.some(m=>m.model_id===activeModel.model_id)); const estimatedPrice=activeModel?priceFor(activeModel.model_id):null; const balance=wallet?.available_balance_cents||0; const hasBalance=estimatedPrice==null||balance>=estimatedPrice;
  const canAttach=selectionMode==='AUTO'?models.some(m=>getModelCapabilities(m).supports_image_reference):Boolean(activeCaps?.supports_image_reference); const maxReferences=selectionMode==='AUTO'?Math.max(0,...models.map(m=>getModelCapabilities(m).max_reference_images)):activeCaps?.max_reference_images||0;

  const addReference=(asset:Asset)=>setReferences(prev=>prev.some(r=>r.asset_id===asset.asset_id)||prev.length>=maxReferences?prev:[...prev,referenceFor(asset,prev)]);
  const removeReference=(assetId:string)=>{const ref=references.find(r=>r.asset_id===assetId);setReferences(prev=>prev.filter(r=>r.asset_id!==assetId));if(ref?.alias_snapshot){const escaped=ref.alias_snapshot.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');setPrompt(v=>v.replace(new RegExp(`@${escaped}\\b\\s*`,'g'),'').replace(/[ \t]{2,}/g,' '));}};
  const refreshGeneratedAssets=async(id:string)=>{const rows=await assetService.listAssets();setAssets(rows);const generated=rows.filter(a=>(a as any).source_generation_id===id);setResultAssets(generated);return generated;};
  const poll=(id:string)=>{pollRef.current=setTimeout(async()=>{try{const next=await generationClient.get(id);setGeneration(next);if(next.status==='SUCCEEDED'){await refreshGeneratedAssets(next.generation_id);await refreshWallet();setGenerating(false);return;}if(terminal(next.status)){setGenerating(false);if(next.status==='FAILED')setError(next.error_message||'A geração falhou.');return;}poll(id);}catch(err:any){setGenerating(false);setError(err?.message||'Falha ao consultar a geração.');}},2500);};

  const generate=async()=>{setError('');setResultAssets([]);if(!prompt.trim())return setError('Descreva a imagem que deseja criar.');if(!activeModel||!selectedCompatible)return setError('Escolha uma IA compatível ou use Auto para encontrar uma rota válida.');if(estimatedPrice==null)return setError('Este modelo ainda não possui preço configurado para geração.');if(!hasBalance)return setError('Saldo insuficiente para esta geração.');const now=Date.now();const draft={request_id:`img_req_${now}_${Math.random().toString(36).slice(2,7)}`,user_id:'',model_id:activeModel.model_id,model_name:activeModel.name,mode,prompt:prompt.trim(),compiled_prompt:prompt.trim(),prompt_compiler_version:'image-workspace-1.0',references,settings:{duration_seconds:1,resolution:'1K',aspect_ratio:aspectRatio,number_of_outputs:1,seed:typeof seed==='number'?seed:null},estimated_cost_cents:estimatedPrice,customer_balance_available_cents:balance,balance_after_generation_cents:balance-estimatedPrice,has_sufficient_funds:hasBalance,created_at:new Date().toISOString()} as unknown as GenerationRequestDraft;try{setGenerating(true);const started=await generationClient.create(draft);setGeneration(started);if(terminal(started.status)){setGenerating(false);if(started.status==='SUCCEEDED')await refreshGeneratedAssets(started.generation_id);else setError(started.error_message||'A geração não pôde ser concluída.');}else poll(started.generation_id);}catch(err:any){setGenerating(false);setError(err?.message||'Não foi possível iniciar a geração.');}};

  const useForVideo=async(asset:Asset)=>{try{const d=DEFAULT_PRESERVATION_RULES.GENERIC;await workspaceService.saveDraft({model_id:'AUTO',mode:'IMAGE_TO_VIDEO',prompt:'',references:[{asset_id:asset.asset_id,alias_snapshot:'img1',role:'START_FRAME',priority:'HIGH',preservation_rules:d.preserve,flexible_rules:d.flexible,asset}],settings:{duration_seconds:5,resolution:'720p',aspect_ratio:aspectRatio,number_of_outputs:1}});onUseImageForVideo?.(asset);}catch(err:any){setError(err?.message||'Não foi possível preparar esta imagem para vídeo.');}};

  if(loading)return <div className="flex-1 h-full grid place-items-center bg-[#0b0e13]"><div className="flex items-center gap-2 text-[10px] text-zinc-600"><Loader2 className="w-4 h-4 animate-spin text-violet-400"/> Preparando gerador de imagens...</div></div>;

  return <div className="flex h-full min-h-0 bg-[#0b0e13]">
    <aside className="w-full md:w-[344px] xl:w-[356px] h-full shrink-0 bg-[#090c11] border-r border-white/[0.06] flex flex-col">
      <div className="flex-1 overflow-y-auto p-3 space-y-2.5">
        <section className="rounded-2xl border border-white/[0.07] bg-[#10141b] p-3"><div className="flex items-center gap-2 mb-2"><WandSparkles className="w-3.5 h-3.5 text-violet-300"/><span className="text-[9px] uppercase tracking-[0.16em] font-bold text-zinc-600">Modelo de IA</span></div><div className="grid grid-cols-[74px_1fr] gap-2"><button onClick={()=>setSelectionMode('AUTO')} className={`rounded-xl border px-2 py-2 text-[10px] font-bold flex items-center justify-center gap-1 ${selectionMode==='AUTO'?'border-violet-400/35 bg-violet-400/12 text-violet-200':'border-white/[0.065] text-zinc-500'}`}><Sparkles className="w-3 h-3"/> Auto</button><select value={selectionMode==='MANUAL'?manualModelId:''} onChange={(e)=>{setSelectionMode('MANUAL');setManualModelId(e.target.value);}} className="h-9 rounded-xl bg-[#0b0e13] border border-white/[0.07] px-2.5 text-[10px] font-semibold text-zinc-200 outline-none"><option value="">Escolher IA</option>{models.map(m=><option key={m.model_id} value={m.model_id}>{m.name}</option>)}</select></div><p className="mt-2 text-[8px] text-zinc-650 truncate">{activeModel?`${activeModel.name} · ${activeModel.best_for||'imagem premium'}`:'Auto encontra uma rota compatível'}</p></section>

        <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold text-zinc-300">Referências</p><p className="text-[8px] text-zinc-700">Upload rápido ou Biblioteca</p></div><button disabled={!canAttach||references.length>=maxReferences} onClick={()=>setPickerOpen(true)} className="w-7 h-7 rounded-lg border border-white/[0.07] bg-white/[0.035] grid place-items-center text-zinc-400 disabled:opacity-30"><Plus className="w-3.5 h-3.5"/></button></div>{references.length>0&&<div className="mt-2 flex gap-1.5 overflow-x-auto">{references.map(ref=>{const selected=prompt.includes(`@${ref.alias_snapshot}`);return <div key={ref.asset_id} className={`relative w-14 h-14 shrink-0 rounded-lg overflow-hidden border-2 ${selected?'border-violet-400 ring-2 ring-violet-400/10':'border-white/[0.07]'}`}>{ref.asset?.public_url?<img src={ref.asset.thumbnail_url||ref.asset.public_url} className="w-full h-full object-cover" alt=""/>:<ImageIcon className="absolute inset-0 m-auto w-4 h-4 text-zinc-700"/>}<button onClick={()=>removeReference(ref.asset_id)} className="absolute top-0.5 right-0.5 w-4 h-4 rounded bg-black/70 grid place-items-center"><X className="w-2.5 h-2.5"/></button><span className="absolute left-1 bottom-1 px-1 py-0.5 rounded bg-black/70 text-[7px] font-mono text-white">@{ref.alias_snapshot}</span></div>;})}</div>}</section>

        <PromptComposer prompt={prompt} onChangePrompt={setPrompt} negativePrompt="" onChangeNegativePrompt={()=>{}} onOpenImproveModal={()=>{}} references={references} onRequestAddMedia={()=>setPickerOpen(true)} supportsNegativePrompt={false} maxChars={activeCaps?.max_prompt_length||10000}/>

        <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><p className="text-[9px] font-semibold text-zinc-400 mb-2">Proporção</p><div className="flex flex-wrap gap-1.5">{['1:1','16:9','9:16','4:3','3:4'].map(r=><button key={r} onClick={()=>setAspectRatio(r)} className={`px-2.5 py-1.5 rounded-lg border text-[9px] font-semibold ${aspectRatio===r?'border-violet-400/40 bg-violet-400/15 text-violet-200':'border-white/[0.06] text-zinc-500'}`}>{r}</button>)}</div></section>
        <section className="rounded-xl border border-white/[0.065] bg-white/[0.025] overflow-hidden"><button onClick={()=>setShowAdvanced(v=>!v)} className="w-full h-10 px-3 flex items-center text-[10px] font-semibold text-zinc-400">Configurações avançadas <ChevronDown className={`ml-auto w-3.5 h-3.5 transition-transform ${showAdvanced?'rotate-180':''}`}/></button>{showAdvanced&&<div className="px-3 pb-3"><label className="text-[8px] text-zinc-600">Seed<input type="number" value={seed} onChange={(e)=>setSeed(e.target.value===''?'':Number(e.target.value))} placeholder="Aleatório" className="mt-1 w-full h-8 px-2 rounded-lg bg-[#0b0e13] border border-white/[0.06] text-[9px] text-zinc-300 outline-none"/></label></div>}</section>
        {!selectedCompatible&&activeModel&&<div className="rounded-xl border border-amber-400/15 bg-amber-500/[0.06] px-3 py-2 text-[9px] text-amber-300">{activeModel.name} não atende a combinação atual. Remova referências ou use Auto.</div>}
        {error&&<div className="rounded-xl border border-rose-400/15 bg-rose-500/[0.06] px-3 py-2 text-[9px] text-rose-300 flex gap-2"><AlertCircle className="w-3.5 h-3.5 shrink-0"/>{error}</div>}
      </div>
      <div className="p-3 border-t border-white/[0.06] bg-[#080b0f]"><div className="mb-2 flex items-center justify-between"><div><p className="text-[8px] text-zinc-700">Estimativa</p><p className="text-[11px] font-bold text-white">{money(estimatedPrice)}</p></div><div className="text-right"><p className="text-[8px] text-zinc-700">Saldo</p><p className={`text-[10px] font-semibold ${hasBalance?'text-zinc-400':'text-rose-400'}`}>{money(balance)}</p></div></div><button onClick={generate} disabled={generating||!prompt.trim()||!activeModel||!selectedCompatible||estimatedPrice==null||!hasBalance} className="w-full h-11 rounded-xl bg-gradient-to-r from-violet-500 via-fuchsia-500 to-cyan-400 text-white text-[11px] font-black flex items-center justify-center gap-2 disabled:opacity-35 disabled:grayscale"><Sparkles className="w-4 h-4"/>{generating?'Gerando...':'Gerar imagem'}</button></div>
    </aside>

    <main className="flex-1 min-w-0 h-full overflow-y-auto bg-[#0b0e13]">
      <div className="px-5 lg:px-6 pt-5 pb-3 border-b border-white/[0.055]"><div className="flex items-center justify-between"><div><h2 className="text-[20px] font-bold tracking-tight text-white">Minhas imagens</h2><p className="mt-0.5 text-[10px] text-zinc-600">Resultados são salvos automaticamente na Biblioteca de Assets.</p></div>{generation&&!terminal(generation.status)&&<span className="inline-flex items-center gap-1.5 text-[10px] text-zinc-500"><RefreshCw className="w-3 h-3 animate-spin"/>{generation.status}</span>}</div></div>
      {!generation&&!resultAssets.length?<div className="h-[calc(100%-78px)] min-h-[420px] flex flex-col items-center justify-center text-center px-6"><div className="w-14 h-14 rounded-2xl bg-white/[0.035] border border-white/[0.06] grid place-items-center"><ImageIcon className="w-6 h-6 text-zinc-700"/></div><h3 className="mt-4 text-sm font-semibold text-zinc-300">Sua próxima imagem aparece aqui</h3><p className="mt-1 text-[10px] text-zinc-600 max-w-md">Crie do zero ou use referências. Em Auto, o sistema escolhe uma rota compatível.</p></div>:null}
      {generating&&!resultAssets.length&&<div className="h-[calc(100%-78px)] min-h-[420px] grid place-items-center"><div className="text-center"><Loader2 className="w-6 h-6 animate-spin text-violet-400 mx-auto"/><h3 className="mt-3 text-sm font-semibold text-zinc-300">Criando sua imagem</h3><p className="mt-1 text-[10px] text-zinc-600">O resultado será salvo em Assets quando terminar.</p></div></div>}
      {generation?.status==='FAILED'&&<div className="m-5 rounded-xl border border-rose-400/15 bg-rose-500/[0.06] p-4 text-rose-300"><p className="text-xs font-semibold">A geração falhou</p><p className="text-[10px] mt-1">{generation.error_message||'Tente novamente ou escolha outra IA.'}</p></div>}
      {resultAssets.length>0&&<div className="p-5 lg:p-6 grid grid-cols-1 xl:grid-cols-2 2xl:grid-cols-3 gap-4">{resultAssets.map(asset=><article key={asset.asset_id} className="group rounded-2xl overflow-hidden border border-white/[0.07] bg-[#11151c]"><div className="relative aspect-square bg-[#0b0e13] flex items-center justify-center"><img src={asset.public_url} alt={asset.name} className="w-full h-full object-contain"/><span className="absolute left-3 top-3 inline-flex items-center gap-1 px-2 py-1 rounded-full bg-violet-500/90 text-white text-[8px] font-bold"><Check className="w-2.5 h-2.5"/> GERADO</span><div className="absolute inset-x-3 bottom-3 opacity-0 translate-y-2 group-hover:opacity-100 group-hover:translate-y-0 transition-all flex justify-center"><div className="rounded-xl bg-black/80 backdrop-blur border border-white/10 p-1 flex gap-1"><button onClick={()=>addReference(asset)} title="Usar como referência" className="w-9 h-9 rounded-lg hover:bg-white/10 grid place-items-center text-zinc-300"><ImageIcon className="w-4 h-4"/></button><button onClick={()=>useForVideo(asset)} title="Criar vídeo" className="w-9 h-9 rounded-lg hover:bg-white/10 grid place-items-center text-zinc-300"><Video className="w-4 h-4"/></button><a href={asset.public_url} target="_blank" rel="noreferrer" title="Abrir" className="w-9 h-9 rounded-lg hover:bg-white/10 grid place-items-center text-zinc-300"><ExternalLink className="w-4 h-4"/></a><a href={asset.public_url} download title="Baixar" className="w-9 h-9 rounded-lg hover:bg-white/10 grid place-items-center text-zinc-300"><Download className="w-4 h-4"/></a></div></div></div><div className="p-3"><p className="text-[11px] font-semibold text-zinc-200 truncate">{asset.name}</p><p className="mt-0.5 text-[8px] font-mono text-zinc-700">@{asset.alias}</p></div></article>)}</div>}
    </main>

    <AssetPickerModal isOpen={pickerOpen} onClose={()=>setPickerOpen(false)} availableAssets={assets} onSelectAsset={addReference} onAssetUploaded={(asset)=>setAssets(prev=>[asset,...prev])} attachedAssetIds={references.map(r=>r.asset_id)} title="Adicionar referência à imagem" subtitle="Envie agora ou reutilize uma imagem da sua Biblioteca de Assets." defaultTab="LIBRARY" allowedTypes={['IMAGE']}/>
  </div>;
};
