import React,{useState}from'react';
import{ArrowRight,BookOpen,Image as ImageIcon,Layers3,Sparkles,Video,Wallet,Zap}from'lucide-react';
import{BrandMark}from'../common/BrandMark.js';
import{ModelShowcase,ShowcaseItem}from'../workspace/ModelShowcase.js';
interface Props{onLogin:()=>void;onStart:()=>void;}
const media=(key:string)=>`https://hzjyhhenajbjxkwkmzdg.supabase.co/functions/v1/showcase-media?key=${key}`;
type GalleryItem={key:string;label:string;ratio:number};
const galleryRows:GalleryItem[][]=[
 [{key:'product',label:'Produto & publicidade',ratio:5/4},{key:'character',label:'Personagens realistas',ratio:4/5},{key:'cgi',label:'CGI surreal',ratio:16/9},{key:'architecture',label:'Arquitetura & interiores',ratio:16/9}],
 [{key:'fashion',label:'Fashion & editorial',ratio:4/5},{key:'toy',label:'3D & estilizado',ratio:1},{key:'anime',label:'Anime & ilustração',ratio:16/9},{key:'scifi',label:'Concept art & sci-fi',ratio:16/9}],
];
const HeroMedia:React.FC=()=>{const[failed,setFailed]=useState(false);return <>{!failed?<video src="/media/showcase/hero.mp4" autoPlay muted loop playsInline preload="metadata" disablePictureInPicture onError={()=>setFailed(true)} className="absolute inset-0 h-full w-full object-cover"/>:<iframe title="Demonstração IA Connect" className="absolute inset-0 h-full w-full scale-[1.13] pointer-events-none" src="https://www.youtube-nocookie.com/embed/KUyRq7szZsM?autoplay=1&mute=1&controls=0&loop=1&playlist=KUyRq7szZsM&playsinline=1&rel=0&modestbranding=1&iv_load_policy=3&disablekb=1" allow="autoplay; encrypted-media" referrerPolicy="strict-origin-when-cross-origin"/>}<div className="absolute inset-0 pointer-events-none bg-gradient-to-r from-[#050a10]/48 via-transparent to-transparent"/></>};
const GalleryCard:React.FC<{item:GalleryItem}>=({item})=><figure className="group relative min-w-0 overflow-hidden rounded-xl sm:rounded-2xl border border-sky-300/[0.09] bg-[#08131e]" style={{aspectRatio:item.ratio}}><img src={media(item.key)} alt={item.label} loading="lazy" className="absolute inset-0 h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.025]"/><figcaption className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/80 via-black/25 to-transparent px-3 pb-2.5 pt-10"><p className="text-[8px] sm:text-[9px] font-black">{item.label}</p></figcaption></figure>;
export const LandingPageView:React.FC<Props>=({onLogin,onStart})=>{const startFromModel=(item:ShowcaseItem)=>{if(item.availableInStudio)sessionStorage.setItem('ia-connect:last-showcase-model',item.modelId);onStart()};return <div className="min-h-screen bg-[#050a10] text-white overflow-x-hidden">
<header className="fixed inset-x-0 top-0 z-50 border-b border-sky-300/[0.08] bg-[#050a10]/88 backdrop-blur-xl"><div className="mx-auto max-w-7xl h-16 px-5 sm:px-8 flex items-center justify-between"><BrandMark/><nav className="hidden md:flex items-center gap-6 text-[10px] font-semibold text-zinc-500"><a href="#models" className="hover:text-sky-200">Modelos</a><a href="#gallery" className="hover:text-sky-200">Explorar</a><a href="#how" className="hover:text-sky-200">Como funciona</a></nav><div className="flex items-center gap-2"><button onClick={onLogin} className="h-9 px-4 rounded-xl text-xs font-semibold text-zinc-400 hover:text-white">Entrar</button><button onClick={onStart} className="ia-primary h-9 px-4 rounded-xl text-xs font-black">Começar agora</button></div></div></header>
<main><section className="relative pt-28 sm:pt-32 pb-12 px-5 overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_15%,rgba(25,184,255,.16),transparent_28%),radial-gradient(circle_at_78%_22%,rgba(82,119,255,.16),transparent_32%)]"/><div className="relative mx-auto max-w-7xl grid lg:grid-cols-[.92fr,1.08fr] gap-8 lg:gap-12 items-center"><div><p className="text-[9px] font-black uppercase tracking-[.22em] text-sky-300">Da ideia à realidade</p><h1 className="mt-4 text-4xl sm:text-6xl lg:text-[68px] font-black tracking-[-.055em] leading-[.96]">Crie sem limites<br/>com o <span className="text-transparent bg-clip-text bg-gradient-to-r from-sky-300 via-cyan-300 to-blue-400">poder da IA.</span></h1><p className="mt-5 max-w-xl text-sm sm:text-base leading-relaxed text-zinc-400">Imagens e vídeos com modelos de última geração. Veja o preço antes de gerar, pague pelo que usar e mantenha tudo organizado em um único fluxo.</p><div className="mt-7 flex flex-wrap gap-3"><button onClick={onStart} className="ia-primary h-12 px-6 rounded-xl text-sm font-black inline-flex items-center gap-2">Começar agora<ArrowRight className="w-4 h-4"/></button><button onClick={()=>document.getElementById('models')?.scrollIntoView({behavior:'smooth'})} className="h-12 px-6 rounded-xl border border-sky-300/[0.13] bg-sky-300/[0.03] text-sm font-bold text-zinc-300 hover:bg-sky-300/[0.07]">Ver modelos</button></div><div className="mt-8 grid grid-cols-2 sm:grid-cols-4 gap-2">{[[ImageIcon,'Imagem + vídeo'],[Layers3,'Vários modelos'],[Wallet,'Preço antes'],[Zap,'Pague pelo uso']].map(([Icon,label]:any)=><div key={label} className="rounded-xl border border-sky-300/[0.08] bg-[#08131e]/70 px-3 py-3"><Icon className="w-4 h-4 text-sky-300"/><p className="mt-2 text-[9px] font-bold text-zinc-300">{label}</p></div>)}</div></div><div className="relative aspect-video lg:aspect-[16/11] max-h-[480px] rounded-[28px] overflow-hidden border border-sky-300/[0.12] bg-[#08131e] shadow-[0_35px_120px_rgba(0,0,0,.42)]"><HeroMedia/></div></div></section>
<section id="models" className="py-14 px-5 border-t border-sky-300/[0.06]"><div className="mx-auto max-w-7xl"><ModelShowcase onTry={startFromModel} title="Tecnologia de ponta para grandes ideias" subtitle="Vídeos em loop contínuo para comparar estética, movimento e capacidade sem sair da página."/></div></section>
<section id="gallery" className="py-14 bg-[#06101a]/55 border-y border-sky-300/[0.06] overflow-hidden"><div className="mx-auto max-w-7xl px-5"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">Da realidade à imaginação</p><h2 className="mt-2 text-3xl sm:text-4xl font-black tracking-[-.04em]">Veja o que é possível criar</h2><p className="mt-2 text-sm text-zinc-500">Cada criação mantém seu enquadramento original. Juntas, elas formam um mosaico de possibilidades.</p></div><div className="mt-7 w-full px-2 sm:px-4 lg:px-5 space-y-2 sm:space-y-3"><div className="grid grid-cols-2 gap-2 sm:gap-3 lg:hidden">{galleryRows.flat().map(item=><GalleryCard key={item.key} item={item}/>)}</div>{galleryRows.map((row,rowIndex)=><div key={rowIndex} className="hidden lg:grid gap-3" style={{gridTemplateColumns:row.map(item=>`${item.ratio}fr`).join(' ')}}>{row.map(item=><GalleryCard key={item.key} item={item}/>)}</div>)}</div></section>
<section className="py-14 px-5"><div className="mx-auto max-w-7xl"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">Tudo em um só lugar</p><h2 className="mt-2 text-3xl sm:text-4xl font-black tracking-[-.04em]">Ferramentas poderosas para criar sem limites</h2><div className="mt-6 grid md:grid-cols-4 gap-3">{[[ImageIcon,'Gerador de imagens','Crie, edite e reutilize referências.'],[Video,'Gerador de vídeos','Transforme ideias e imagens em movimento.'],[BookOpen,'Biblioteca','Organize personagens, produtos, estilos e assets.'],[Sparkles,'Fluxo contínuo','Regenere, baixe e leve uma criação para o próximo passo.']].map(([Icon,title,text]:any)=><div key={title} className="rounded-2xl border border-sky-300/[0.1] bg-[#08131e] p-5"><Icon className="w-5 h-5 text-sky-300"/><h3 className="mt-5 text-sm font-black">{title}</h3><p className="mt-2 text-[10px] leading-relaxed text-zinc-500">{text}</p></div>)}</div></div></section>
<section id="how" className="py-14 px-5 border-y border-sky-300/[0.06] bg-[#06101a]/50"><div className="mx-auto max-w-7xl"><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">Como funciona</p><h2 className="mt-2 text-3xl font-black tracking-[-.04em]">Simples. Rápido. Sem complicação.</h2><div className="mt-7 grid md:grid-cols-3 gap-4">{[['1','Escolha o modelo','Compare capacidade e veja o preço antes de gerar.'],['2','Coloque saldo','Adicione créditos à conta quando precisar.'],['3','Crie e baixe','Gere, salve, reutilize e baixe sua criação.']].map(([n,t,d])=><div key={n} className="flex gap-4"><span className="w-9 h-9 shrink-0 rounded-full border border-sky-300/30 bg-sky-300/[0.08] grid place-items-center text-sm font-black text-sky-300">{n}</span><div><h3 className="text-xs font-black">{t}</h3><p className="mt-1 text-[10px] leading-relaxed text-zinc-500">{d}</p></div></div>)}</div></div></section>
<section className="py-14 px-5"><div className="mx-auto max-w-6xl rounded-[28px] border border-sky-300/[0.14] bg-[radial-gradient(circle_at_14%_30%,rgba(25,184,255,.16),transparent_34%),#08131e] px-6 py-10 sm:px-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6"><div><p className="text-[9px] font-black uppercase tracking-[.2em] text-sky-300">Mais liberdade</p><h2 className="mt-2 text-3xl font-black">Você no controle.</h2><p className="mt-2 max-w-2xl text-sm text-zinc-500">Sem mensalidade por modelo. Você adiciona saldo, sabe o custo antes da geração e usa seus créditos no seu ritmo.</p></div><button onClick={onStart} className="ia-primary h-11 px-5 rounded-xl text-xs font-black whitespace-nowrap">Começar agora</button></div></section></main>
<footer className="border-t border-sky-300/[0.07] py-8 px-5"><div className="mx-auto max-w-7xl flex flex-col sm:flex-row items-center justify-between gap-4"><BrandMark/><p className="text-[9px] text-zinc-700">IA Connect · Creative AI Studio</p></div></footer></div>};
