import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Clock3,Disc3,FileAudio,Hash}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{musicGenerationClient,MusicJob,MusicModel}from'../../services/musicGenerationClient.js';
import{Asset}from'../../types/index.js';
import{CreationGallery}from'../workspace/CreationGallery.js';
import{StableGeneratorModelPicker}from'../workspace/StableGeneratorModelPicker.js';
import{GeneratorDiscreteSlider,GeneratorFooter,GeneratorOptionGrid,GeneratorPanel,GeneratorScroll,GeneratorSettingRow,GeneratorToggle}from'../workspace/GeneratorControls.js';
import{PromptComposer}from'../workspace/PromptComposer.js';
import{MobileStudioLayout}from'../workspace/MobileStudioLayout.js';

const PREFERRED_DURATIONS=[15,30,60,90,120,180,240],FALLBACK_DURATIONS=[30,60,120];
const terminal=(status?:string)=>['SUCCEEDED','FAILED','CANCELLED'].includes(String(status||''));
const message=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir esta operação.';
type OpenCard='duration'|'format'|'seed'|null;

export const MusicCreateView:React.FC=()=>{
 const{wallet,refreshWallet}=useAuth();
 const[models,setModels]=useState<MusicModel[]>([]),[selectedModelId,setSelectedModelId]=useState(''),[prompt,setPrompt]=useState(''),[duration,setDuration]=useState(60),[format,setFormat]=useState('mp3'),[instrumental,setInstrumental]=useState(true),[seed,setSeed]=useState<number|''>(''),[openCard,setOpenCard]=useState<OpenCard>(null),[mobileActiveCount,setMobileActiveCount]=useState(0);
 const[job,setJob]=useState<MusicJob|null>(null),[currentAsset,setCurrentAsset]=useState<Asset|null>(null),[busy,setBusy]=useState('load'),[error,setError]=useState(''),[pollCount,setPollCount]=useState(0);
 const loadCurrentAsset=useCallback(async(assetId?:string)=>{if(!assetId)return setCurrentAsset(null);const rows=await assetService.listAssets({type:'AUDIO',origin:'GENERATED'}).catch(()=>[]);setCurrentAsset(rows.find(asset=>asset.asset_id===assetId)||null)},[]);
 const load=useCallback(async()=>{setBusy(current=>current||'load');setError('');try{const available=(await musicGenerationClient.catalog()).filter(model=>model.capabilities.some(capability=>capability.id==='music'));setModels(available);const fallback=available.find(model=>model.providers?.length)?.model_id||'';setSelectedModelId(current=>available.some(model=>model.model_id===current)?current:fallback)}catch(err){setError(message(err))}finally{setBusy(current=>current==='load'?'':current)}},[]);
 useEffect(()=>{void load()},[load]);
 const model=useMemo(()=>models.find(item=>item.model_id===selectedModelId)||null,[models,selectedModelId]);
 const capability=useMemo(()=>model?.capabilities.find(item=>item.id==='music')||null,[model]);
 const autoModels=useMemo(()=>models.filter(item=>item.model_id!=='AUTO'&&item.providers?.length),[models]);
 const autoCapabilities=useMemo(()=>autoModels.map(item=>item.capabilities.find(cap=>cap.id==='music')).filter(Boolean) as NonNullable<MusicModel['capabilities'][number]>[],[autoModels]);
 const routeReady=Boolean(model?.providers?.length);
 const durations=useMemo(()=>{let values:number[]=[];if(selectedModelId==='AUTO'&&autoCapabilities.length){const sets:Set<number>[]=autoCapabilities.map(cap=>new Set<number>((cap.supported_durations||[]).map(value=>Number(value)).filter(value=>Number.isFinite(value))));values=[...sets[0]].filter(value=>sets.every(set=>set.has(value)));}else values=((capability?.supported_durations?.length?capability.supported_durations:model?.supported_durations)||[]).map(value=>Number(value));const clean=Array.from(new Set<number>(values.filter(value=>Number.isFinite(value)&&value>0))).sort((a,b)=>a-b);if(!clean.length)return FALLBACK_DURATIONS;const allowed=new Set<number>(clean),preferred=PREFERRED_DURATIONS.filter(value=>allowed.has(value));return preferred.length?preferred:Array.from(new Set<number>([clean[0],clean[Math.floor((clean.length-1)/2)],clean[clean.length-1]]))},[selectedModelId,autoCapabilities,capability,model]);
 const supportsSeed=selectedModelId==='AUTO'?autoCapabilities.length>0&&autoCapabilities.every(cap=>cap.controls?.includes('seed')):Boolean(capability?.controls?.includes('seed'));
 const supportsFormat=selectedModelId==='AUTO'?autoCapabilities.length>0&&autoCapabilities.every(cap=>cap.controls?.includes('output_format')):Boolean(capability?.controls?.includes('output_format'));
 useEffect(()=>{if(!durations.includes(duration))setDuration(durations.includes(60)?60:durations[0])},[durations,duration]);
 const invalidate=()=>{setJob(null);setCurrentAsset(null);setPollCount(0);setError('')};
 useEffect(()=>{if(!job||terminal(job.status)||!['QUEUED','RUNNING'].includes(job.status)||pollCount>=160)return;const timer=window.setTimeout(async()=>{try{setJob(await musicGenerationClient.get(job.job_id));setPollCount(value=>value+1)}catch(err){setError(message(err));setPollCount(160)}},Math.min(6500,1800+pollCount*120));return()=>window.clearTimeout(timer)},[job,pollCount]);
 useEffect(()=>{if(job?.status!=='SUCCEEDED')return;void refreshWallet();const assetId=job.result_asset_ids?.[0];void loadCurrentAsset(assetId);const timer=window.setTimeout(()=>void loadCurrentAsset(assetId),900);window.dispatchEvent(new CustomEvent('creations:updated',{detail:{kind:'MUSIC',asset_ids:job.result_asset_ids||[]}}));return()=>window.clearTimeout(timer)},[job?.status,job?.result_asset_ids,loadCurrentAsset,refreshWallet]);
 const quote=async()=>{if(!prompt.trim())return setError('Descreva a música que deseja criar.');if(!routeReady)return setError('Nenhum modelo com rota e preço verificados está disponível agora.');setBusy('quote');setError('');setJob(null);setCurrentAsset(null);try{const created=await musicGenerationClient.create({model_id:selectedModelId,prompt:prompt.trim(),controls:{duration_seconds:duration,instrumental,output_format:supportsFormat?format:undefined,seed:supportsSeed?(seed===''?null:seed):undefined}});setJob(await musicGenerationClient.quote(created.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const generate=async()=>{if(!job)return;setBusy('generate');setError('');try{setJob(await musicGenerationClient.queue(job.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const balance=wallet?.available_credits??0,price=job?.quote?.credit_price??null,insufficient=price!=null&&balance<price;
 const status=job?.status==='SUCCEEDED'?'Concluído':job?.status==='FAILED'?'Falhou':job?.status==='RUNNING'?'Processando':job?.status==='QUEUED'?'Na fila':job?.status==='QUOTED'?'Preço calculado':'Preparando';
 const footer=!job?.quote?{label:'Calcular créditos',disabled:Boolean(busy)||!prompt.trim()||!routeReady,onClick:quote,secondary:undefined as string|undefined,onSecondary:undefined as(()=>void)|undefined}:{label:['DRAFT','QUOTED'].includes(job.status)?'Gerar música':status,disabled:Boolean(busy)||insufficient||!['DRAFT','QUOTED'].includes(job.status),onClick:generate,secondary:['DRAFT','QUOTED'].includes(job.status)?'Atualizar':undefined,onSecondary:['DRAFT','QUOTED'].includes(job.status)?quote:undefined};
 const creator=<GeneratorPanel ariaLabel="Gerador de música"><GeneratorScroll>
  <StableGeneratorModelPicker models={models.filter(item=>item.model_id!=='AUTO'||Boolean(item.providers?.length)).map(item=>({model_id:item.model_id,name:item.name,description:'Modelo de música',supported_durations:item.supported_durations||[]}))} selectedModelId={selectedModelId} loading={busy==='load'} onSelect={modelId=>{setSelectedModelId(modelId);invalidate()}}/>
  {!busy&&models.length===0&&<section className="ia-stable-current"><strong>Nenhum modelo disponível.</strong><p>As IAs serão exibidas quando uma Route estiver pronta.</p></section>}
  <PromptComposer prompt={prompt} onChangePrompt={value=>{setPrompt(value);invalidate()}} negativePrompt="" onChangeNegativePrompt={()=>{}} onOpenImproveModal={()=>{}} references={[]} onRequestAddMedia={()=>{}} supportsNegativePrompt={false} supportsReferences={false} maxChars={4000} label="Descrição da música" placeholder="Ex.: trilha cinematográfica emocional, piano suave, cordas crescendo, sem vocais…" showImproveButton={false}/>
  <div className="space-y-1.5">
   <GeneratorSettingRow icon={Clock3} label="Duração" value={`${duration}s`} open={openCard==='duration'} onToggle={()=>setOpenCard(openCard==='duration'?null:'duration')} semantic="duration"><GeneratorDiscreteSlider values={durations} value={duration} onChange={value=>{setDuration(value);invalidate()}} suffix="s" subtitle="duração da música"/></GeneratorSettingRow>
   {supportsFormat&&<GeneratorSettingRow icon={FileAudio} label="Formato" value={format.toUpperCase()} open={openCard==='format'} onToggle={()=>setOpenCard(openCard==='format'?null:'format')} semantic="resolution"><GeneratorOptionGrid values={[{value:'mp3',label:'MP3'},{value:'wav',label:'WAV'}]} current={format} onSelect={value=>{setFormat(value);invalidate()}}/></GeneratorSettingRow>}
   {supportsSeed&&<GeneratorSettingRow icon={Hash} label="Seed" value={seed===''?'Automática':String(seed)} open={openCard==='seed'} onToggle={()=>setOpenCard(openCard==='seed'?null:'seed')}><div className="rounded-lg border border-white/[0.06] bg-black/15 p-2"><input type="number" min="0" value={seed} onChange={event=>{setSeed(event.target.value===''?'':Number(event.target.value));invalidate()}} placeholder="Automática" className="w-full bg-transparent text-[10px] text-white outline-none placeholder:text-zinc-700"/></div></GeneratorSettingRow>}
  </div>
  <GeneratorToggle checked={instrumental} onChange={value=>{setInstrumental(value);invalidate()}} label="Instrumental" description={instrumental?'Gerar sem vocais.':'Permitir vocais quando o modelo suportar.'}/>
  {job&&<section className="ia-stable-current"><div className="flex items-center justify-between"><div><span className="text-[8px] text-zinc-600">Resultado atual</span><strong className="block text-[10px] text-white">{status}</strong></div><Disc3 className={`w-4 h-4 text-cyan-300 ${['QUEUED','RUNNING'].includes(job.status)?'is-spin-slow':''}`}/></div>{job.quote&&<p>Modelo executado: <strong>{job.quote.selected_model_id}</strong> · {job.quote.routing_mode==='AUTO'?'roteamento AUTO':'modelo específico'}.</p>}{job.status==='SUCCEEDED'&&currentAsset?.public_url&&<audio controls preload="metadata" src={currentAsset.public_url} className="mt-2 w-full h-9"/>}{job.status==='FAILED'&&<p>{job.error_message||'A música não pôde ser gerada.'}</p>}</section>}
 </GeneratorScroll><GeneratorFooter error={error} price={price} balance={balance} hasBalance={!insufficient} primaryLabel={footer.label} onPrimary={()=>void footer.onClick()} primaryDisabled={footer.disabled} primaryBusy={busy==='quote'||busy==='generate'} secondaryLabel={footer.secondary} onSecondary={footer.onSecondary?()=>void footer.onSecondary?.():undefined} secondaryDisabled={Boolean(busy)}/></GeneratorPanel>;
 return <MobileStudioLayout activeCount={mobileActiveCount} creator={creator} gallery={<CreationGallery defaultFilter="MUSIC" title="Minhas criações" subtitle="Todo o histórico de criações do seu studio." onActiveCountChange={setMobileActiveCount}/>}/>;
};
export default MusicCreateView;
