import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Disc3,LoaderCircle,RefreshCw,Sparkles,WandSparkles}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{musicGenerationClient,MusicJob,MusicModel}from'../../services/musicGenerationClient.js';
import{Asset}from'../../types/index.js';
import{CreationGallery}from'../workspace/CreationGallery.js';
import{StableGeneratorModelPicker}from'../workspace/StableGeneratorModelPicker.js';
import'../../styles/stable-generator-shell.css';

const PREFERRED_DURATIONS=[15,30,60,90,120,180,240],FALLBACK_DURATIONS=[30,60,120];
const terminal=(status?:string)=>['SUCCEEDED','FAILED','CANCELLED'].includes(String(status||''));
const message=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir esta operação.';

export const MusicCreateView:React.FC=()=>{
 const{wallet,refreshWallet}=useAuth();
 const[models,setModels]=useState<MusicModel[]>([]),[selectedModelId,setSelectedModelId]=useState('AUTO'),[prompt,setPrompt]=useState(''),[duration,setDuration]=useState(60),[format,setFormat]=useState('mp3'),[instrumental,setInstrumental]=useState(true),[seed,setSeed]=useState<number|''>('');
 const[job,setJob]=useState<MusicJob|null>(null),[currentAsset,setCurrentAsset]=useState<Asset|null>(null),[busy,setBusy]=useState('load'),[error,setError]=useState(''),[pollCount,setPollCount]=useState(0);
 const loadCurrentAsset=useCallback(async(assetId?:string)=>{if(!assetId)return setCurrentAsset(null);const rows=await assetService.listAssets({type:'AUDIO',origin:'GENERATED'}).catch(()=>[]);setCurrentAsset(rows.find(asset=>asset.asset_id===assetId)||null)},[]);
 const load=useCallback(async()=>{setBusy(current=>current||'load');setError('');try{const available=(await musicGenerationClient.catalog()).filter(model=>model.capabilities.some(capability=>capability.id==='music'));setModels(available);setSelectedModelId(current=>current==='AUTO'||available.some(model=>model.model_id===current)?current:'AUTO')}catch(err){setError(message(err))}finally{setBusy(current=>current==='load'?'':current)}},[]);
 useEffect(()=>{void load()},[load]);
 const model=useMemo(()=>selectedModelId==='AUTO'?null:models.find(item=>item.model_id===selectedModelId)||null,[models,selectedModelId]);
 const capability=useMemo(()=>model?.capabilities.find(item=>item.id==='music')||null,[model]);
 const routeReady=selectedModelId==='AUTO'?models.some(item=>item.providers?.length):Boolean(model?.providers?.length);
 const durations=useMemo(()=>{const values:number[]=(capability?.supported_durations?.length?capability.supported_durations:model?.supported_durations)||[];const clean=Array.from(new Set<number>(values.map(Number).filter(value=>Number.isFinite(value)&&value>0))).sort((a,b)=>a-b);if(!clean.length)return FALLBACK_DURATIONS;const allowed=new Set(clean),preferred=PREFERRED_DURATIONS.filter(value=>allowed.has(value));return preferred.length?preferred:Array.from(new Set([clean[0],clean[Math.floor((clean.length-1)/2)],clean[clean.length-1]]))},[capability,model]);
 const supportsSeed=Boolean(capability?.controls?.includes('seed'));
 useEffect(()=>{if(!durations.includes(duration))setDuration(durations.includes(60)?60:durations[0])},[durations,duration]);
 const invalidate=()=>{setJob(null);setCurrentAsset(null);setPollCount(0);setError('')};
 useEffect(()=>{if(!job||terminal(job.status)||!['QUEUED','RUNNING'].includes(job.status)||pollCount>=160)return;const timer=window.setTimeout(async()=>{try{setJob(await musicGenerationClient.get(job.job_id));setPollCount(value=>value+1)}catch(err){setError(message(err));setPollCount(160)}},Math.min(6500,1800+pollCount*120));return()=>window.clearTimeout(timer)},[job,pollCount]);
 useEffect(()=>{if(job?.status!=='SUCCEEDED')return;void refreshWallet();const assetId=job.result_asset_ids?.[0];void loadCurrentAsset(assetId);const timer=window.setTimeout(()=>void loadCurrentAsset(assetId),900);window.dispatchEvent(new CustomEvent('creations:updated',{detail:{kind:'MUSIC',asset_ids:job.result_asset_ids||[]}}));return()=>window.clearTimeout(timer)},[job?.status,job?.result_asset_ids,loadCurrentAsset,refreshWallet]);
 const quote=async()=>{if(!prompt.trim())return setError('Descreva a música que deseja criar.');if(!routeReady)return setError('Nenhum modelo com rota e preço verificados está disponível agora.');setBusy('quote');setError('');setJob(null);setCurrentAsset(null);try{const created=await musicGenerationClient.create({model_id:selectedModelId,prompt:prompt.trim(),controls:{duration_seconds:duration,instrumental,output_format:format,seed:supportsSeed?(seed===''?null:seed):undefined}});setJob(await musicGenerationClient.quote(created.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const generate=async()=>{if(!job)return;setBusy('generate');setError('');try{setJob(await musicGenerationClient.queue(job.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const balance=wallet?.available_credits??0,price=job?.quote?.credit_price??null,insufficient=price!=null&&balance<price;
 const status=job?.status==='SUCCEEDED'?'Concluído':job?.status==='FAILED'?'Falhou':job?.status==='RUNNING'?'Processando':job?.status==='QUEUED'?'Na fila':job?.status==='QUOTED'?'Preço calculado':'Preparando';
 return <div className="ia-stable-generator-studio">
  <aside className="ia-stable-generator-panel" aria-label="Gerador de música"><div className="ia-stable-generator-scroll">
   <StableGeneratorModelPicker models={models.map(item=>({model_id:item.model_id,name:item.name,description:'Modelo de música'}))} selectedModelId={selectedModelId} loading={busy==='load'} onSelect={modelId=>{setSelectedModelId(modelId);invalidate()}} accentClass="from-violet-500/35 via-indigo-500/15 to-fuchsia-500/20"/>
   <section className="ia-stable-generator-field"><div className="ia-stable-generator-labelrow"><label htmlFor="music-prompt">Descrição da música</label><span>{prompt.length.toLocaleString('pt-BR')} caracteres</span></div><textarea id="music-prompt" className="ia-stable-generator-textarea" rows={9} value={prompt} maxLength={4000} onChange={event=>{setPrompt(event.target.value);invalidate()}} placeholder="Ex.: trilha cinematográfica emocional, piano suave, cordas crescendo, sem vocais…"/></section>
   <div className="ia-stable-generator-settings"><label className="ia-stable-setting"><span>Duração</span><select value={duration} onChange={event=>{setDuration(Number(event.target.value));invalidate()}}>{durations.map(value=><option key={value} value={value}>{value}s</option>)}</select></label><label className="ia-stable-setting"><span>Formato</span><select value={format} onChange={event=>{setFormat(event.target.value);invalidate()}}><option value="mp3">MP3</option><option value="wav">WAV</option></select></label>{supportsSeed&&<label className="ia-stable-setting"><span>Seed</span><input type="number" min="0" value={seed} onChange={event=>{setSeed(event.target.value===''?'':Number(event.target.value));invalidate()}} placeholder="Automática"/></label>}</div>
   <label className="ia-stable-toggle"><input type="checkbox" checked={instrumental} onChange={event=>{setInstrumental(event.target.checked);invalidate()}}/><span><strong>Instrumental</strong><small>{instrumental?'Gerar sem vocais.':'Permitir vocais quando o modelo suportar.'}</small></span></label>
   {job&&<section className="ia-stable-current"><div className="flex items-center justify-between"><div><span className="text-[8px] text-zinc-600">Resultado atual</span><strong className="block text-[10px] text-white">{status}</strong></div><Disc3 className={`w-4 h-4 text-violet-300 ${['QUEUED','RUNNING'].includes(job.status)?'is-spin-slow':''}`}/></div>{job.quote&&<p>Modelo executado: <strong>{job.quote.selected_model_id}</strong> · {job.quote.routing_mode==='AUTO'?'roteamento AUTO':'modelo específico'}.</p>}{job.status==='SUCCEEDED'&&currentAsset?.public_url&&<audio controls preload="metadata" src={currentAsset.public_url} className="mt-2 w-full h-9"/>}{job.status==='FAILED'&&<p>{job.error_message||'A música não pôde ser gerada.'}</p>}</section>}
  </div><div className="ia-stable-generator-actionbar">{error&&<div className="ia-stable-error mb-2" role="status">{error}</div>}<div className="ia-stable-price-row"><div><span>Preço</span><strong>{price==null?'Preço indisponível':`${price.toLocaleString('pt-BR')} créditos`}</strong></div><div className="ia-stable-balance"><span>Saldo</span><strong>{balance.toLocaleString('pt-BR')} créditos</strong></div></div>{!job?.quote?<button className="ia-stable-generator-primary" disabled={Boolean(busy)||!prompt.trim()||!routeReady} onClick={()=>void quote()}>{busy==='quote'?<LoaderCircle className="is-spin"/>:<Sparkles/>}Calcular créditos</button>:['DRAFT','QUOTED'].includes(job.status)?<div className="ia-stable-generator-actions"><button className="ia-stable-generator-secondary" disabled={Boolean(busy)} onClick={()=>void quote()}><RefreshCw/>Atualizar</button><button className="ia-stable-generator-primary" disabled={Boolean(busy)||insufficient} onClick={()=>void generate()}>{busy==='generate'?<LoaderCircle className="is-spin"/>:<WandSparkles/>}Gerar música</button></div>:<button className="ia-stable-generator-primary" disabled>{['QUEUED','RUNNING'].includes(job.status)&&<LoaderCircle className="is-spin"/>}{status}</button>}</div></aside>
  <main className="ia-stable-generator-main"><CreationGallery defaultFilter="MUSIC" title="Minhas criações" subtitle="Imagens, vídeos, voz e música no mesmo histórico universal."/></main>
 </div>;
};
export default MusicCreateView;
