import React,{useEffect,useMemo,useRef,useState}from'react';
import{Box,Check,Image as ImageIcon,Layers3,Plus,Search,Trash2,UploadCloud,X}from'lucide-react';
import{assetService}from'../../services/assetService.js';
import{creativeEntityService,CreativeEntity}from'../../services/creativeEntityService.js';
import{Asset}from'../../types/index.js';

type Kind='PRODUCT'|'STYLE';
const config={
 PRODUCT:{title:'Produtos',singular:'produto',icon:Box,description:'Salve uma única referência central para reutilizar o produto em imagens e vídeos.',helper:'Use preferencialmente um mockup limpo com vários ângulos do mesmo produto na própria imagem.',placeholder:'Ex.: tênis preto fosco com sola branca. Preservar logo, materiais, cores e proporções.'},
 STYLE:{title:'Estilos',singular:'estilo',icon:Layers3,description:'Salve uma única imagem que represente claramente a linguagem visual desejada.',helper:'Escolha uma referência que deixe evidente o acabamento: realista, crochê, clay, editorial, anime, CGI etc.',placeholder:'Ex.: crochê artesanal com fibras aparentes, iluminação suave e acabamento premium.'}
} as const;

export const SingleImageEntityLibraryView:React.FC<{kind:Kind;embedded?:boolean;projectId?:string|null}>=({kind,embedded=false,projectId})=>{
 const info=config[kind],Icon=info.icon;
 const[items,setItems]=useState<CreativeEntity[]>([]),[assets,setAssets]=useState<Asset[]>([]),[queryText,setQueryText]=useState(''),[open,setOpen]=useState(false),[pickerOpen,setPickerOpen]=useState(false),[name,setName]=useState(''),[description,setDescription]=useState(''),[assetId,setAssetId]=useState(''),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const fileRef=useRef<HTMLInputElement|null>(null);
 const refresh=async()=>setItems(await creativeEntityService.list(kind,projectId));
 useEffect(()=>{refresh().catch(()=>setItems([]));assetService.listAssets().then(setAssets).catch(()=>setAssets([]))},[kind,projectId]);
 const images=assets.filter(a=>a.type==='IMAGE'),selected=images.find(a=>a.asset_id===assetId)||null;
 const visible=useMemo(()=>{const q=queryText.trim().toLowerCase();return q?items.filter(i=>`${i.name} ${i.description}`.toLowerCase().includes(q)):items},[items,queryText]);
 const reset=()=>{setOpen(false);setPickerOpen(false);setName('');setDescription('');setAssetId('')};
 const upload=async(file?:File)=>{if(!file||!file.type.startsWith('image/'))return;setUploading(true);try{const asset=await assetService.uploadAsset({file,category:kind==='PRODUCT'?'PRODUCT':'GENERIC'} as any);setAssets(p=>[asset,...p.filter(x=>x.asset_id!==asset.asset_id)]);setAssetId(asset.asset_id);setPickerOpen(false)}finally{setUploading(false)}};
 const save=async()=>{if(!name.trim()||!selected)return;setSaving(true);try{await creativeEntityService.save({kind,name:name.trim(),description:description.trim(),project_id:projectId||null,cover_asset_id:selected.asset_id,cover_url:selected.thumbnail_url||selected.public_url,asset_ids:[selected.asset_id],asset_roles:{PRIMARY:selected.asset_id}});reset();await refresh()}finally{setSaving(false)}};
 return <div className="space-y-4 pb-8">
  <section className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div>{!embedded&&<div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-cyan-300"><Icon className="w-4 h-4"/> Biblioteca criativa</div>}<h2 className={`${embedded?'text-lg':'mt-2 text-2xl'} font-black tracking-[-0.03em] text-white`}>{info.title}</h2><p className="mt-1 text-[11px] text-zinc-500 max-w-2xl">{info.description}</p></div><button onClick={()=>setOpen(true)} className="h-9 px-3.5 rounded-xl bg-gradient-to-r from-cyan-300 to-emerald-300 text-[#061015] text-[10px] font-black flex items-center gap-2"><Plus className="w-3.5 h-3.5"/> Novo {info.singular}</button></section>
  <div className="relative max-w-md"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"/><input value={queryText} onChange={e=>setQueryText(e.target.value)} placeholder={`Buscar ${info.title.toLowerCase()}...`} className="w-full h-10 pl-10 pr-3 rounded-xl bg-[#11151c] border border-white/[0.07] text-xs text-zinc-200 outline-none focus:border-cyan-300/25"/></div>
  {visible.length?<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5 gap-3">{visible.map(item=><article key={item.entity_id} className="group rounded-xl overflow-hidden border border-white/[0.07] bg-[#11151c]"><div className="aspect-square bg-[#0b0e13] relative overflow-hidden">{item.cover_url?<img src={item.cover_url} alt="" className="w-full h-full object-cover"/>:<div className="w-full h-full grid place-items-center"><Icon className="w-7 h-7 text-zinc-800"/></div>}</div><div className="p-2.5 flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="text-[11px] font-bold text-white truncate">{item.name}</h3><p className="mt-1 text-[9px] text-zinc-600 line-clamp-2">{item.description||'Sem descrição.'}</p></div><button onClick={async()=>{await creativeEntityService.remove(item.entity_id);await refresh()}} className="p-1.5 rounded-lg text-zinc-700 hover:text-rose-400"><Trash2 className="w-3 h-3"/></button></div></article>)}</div>:<div className="min-h-[260px] rounded-2xl border border-dashed border-white/[0.07] bg-[#11151c]/50 grid place-items-center"><div className="text-center"><Icon className="w-6 h-6 mx-auto text-zinc-700"/><p className="mt-3 text-sm font-semibold text-zinc-300">Nenhum {info.singular} ainda</p></div></div>}

  {open&&<div className="fixed inset-0 z-[80] bg-black/75 backdrop-blur-sm grid place-items-center p-4"><div className="w-full max-w-xl rounded-2xl border border-white/[0.08] bg-[#11151c] shadow-2xl overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.06] flex items-center justify-between"><div><h2 className="text-sm font-bold text-white">Criar {info.singular}</h2><p className="text-[9px] text-zinc-600">{info.helper}</p></div><button onClick={reset} className="p-1.5 text-zinc-600 hover:text-white"><X className="w-4 h-4"/></button></div><div className="p-4 space-y-4"><label><span className="text-[9px] font-semibold text-zinc-400">Nome</span><input value={name} onChange={e=>setName(e.target.value)} placeholder={kind==='PRODUCT'?'Ex.: Carbon X':'Ex.: Crochê editorial'} className="mt-1 w-full h-10 px-3 rounded-xl bg-[#0b0e13] border border-white/[0.07] text-xs text-white outline-none focus:border-cyan-300/30"/></label>
    <div><div className="flex items-center justify-between mb-2"><div><p className="text-[10px] font-black text-zinc-200">Imagem do {info.singular}</p><p className="text-[8px] text-zinc-600">Apenas uma imagem. Clique no quadro ou arraste o arquivo diretamente.</p></div><span className="text-[8px] text-cyan-300 font-semibold">Obrigatória</span></div><button type="button" onClick={()=>setPickerOpen(true)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void upload(e.dataTransfer.files?.[0])}} className={`relative w-full min-h-[230px] rounded-2xl overflow-hidden border ${selected?'border-white/[0.10] bg-[#0b0e13]':'border-dashed border-cyan-300/20 bg-[#0b0e13]/70 hover:bg-cyan-300/[0.025]'}`}>{selected?<><img src={selected.thumbnail_url||selected.public_url} alt="" className="absolute inset-0 w-full h-full object-contain bg-black/30"/><div className="absolute inset-x-0 bottom-0 p-3 bg-gradient-to-t from-black/90 to-transparent flex items-end justify-between"><div className="text-left"><p className="text-[10px] font-bold text-white">{selected.name}</p><p className="text-[8px] text-zinc-500">Imagem principal selecionada</p></div><span className="px-2 py-1 rounded-lg bg-black/60 border border-white/10 text-[8px] text-zinc-300">Alterar</span></div></>:<div className="absolute inset-0 grid place-items-center"><div className="text-center"><div className="w-12 h-12 mx-auto rounded-2xl border border-white/[0.08] bg-white/[0.035] grid place-items-center"><UploadCloud className="w-5 h-5 text-cyan-300"/></div><p className="mt-3 text-[11px] font-black text-white">Adicionar imagem</p><p className="mt-1 text-[9px] text-zinc-600">Da biblioteca ou novo upload</p><p className="mt-3 text-[8px] text-cyan-300">Clique ou arraste aqui</p></div></div>}</button></div>
    <div className="rounded-xl border border-cyan-300/10 bg-cyan-300/[0.035] px-3 py-2.5"><p className="text-[9px] font-black text-cyan-300">{kind==='PRODUCT'?'Como preparar a melhor referência':'Como escolher a melhor referência'}</p><p className="mt-1 text-[9px] leading-relaxed text-zinc-500">{info.helper}</p></div>
    <label><span className="text-[9px] font-semibold text-zinc-400">Descrição e regras</span><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder={info.placeholder} className="mt-1 w-full min-h-24 p-3 rounded-xl bg-[#0b0e13] border border-white/[0.07] text-xs text-white outline-none resize-none focus:border-cyan-300/30"/></label></div><div className="px-4 py-3 border-t border-white/[0.06] flex justify-end gap-2"><button onClick={reset} className="h-9 px-3 rounded-xl text-[10px] font-semibold text-zinc-500">Cancelar</button><button disabled={!name.trim()||!selected||saving} onClick={save} className="h-9 px-4 rounded-xl bg-white text-black text-[10px] font-bold disabled:opacity-35">{saving?'Salvando...':`Criar ${info.singular}`}</button></div></div></div>}

  {pickerOpen&&<div className="fixed inset-0 z-[90] bg-black/80 backdrop-blur grid place-items-center p-4"><div className="w-full max-w-2xl max-h-[80vh] rounded-2xl border border-white/[0.08] bg-[#11151c] overflow-hidden flex flex-col"><div className="p-4 border-b border-white/[0.06] flex items-center justify-between"><div><h3 className="text-sm font-black text-white">Escolher imagem</h3><p className="text-[9px] text-zinc-600">Use uma imagem já existente ou envie uma nova.</p></div><button onClick={()=>setPickerOpen(false)} className="p-1.5 text-zinc-600"><X className="w-4 h-4"/></button></div><div className="p-4 overflow-y-auto"><button disabled={uploading} onClick={()=>fileRef.current?.click()} className="w-full h-11 rounded-xl border border-dashed border-cyan-300/25 bg-cyan-300/[0.04] text-[10px] font-bold text-cyan-200 flex items-center justify-center gap-2"><UploadCloud className="w-4 h-4"/>{uploading?'Enviando...':'Fazer novo upload'}</button><input ref={fileRef} type="file" accept="image/*" hidden onChange={e=>{const f=e.target.files?.[0];e.currentTarget.value='';void upload(f)}}/><div className="mt-4 grid grid-cols-4 sm:grid-cols-6 gap-2">{images.map(a=><button key={a.asset_id} onClick={()=>{setAssetId(a.asset_id);setPickerOpen(false)}} className={`relative aspect-square rounded-xl overflow-hidden border-2 ${assetId===a.asset_id?'border-cyan-300':'border-white/[0.06]'}`}><img src={a.thumbnail_url||a.public_url} alt="" className="w-full h-full object-cover"/>{assetId===a.asset_id&&<span className="absolute top-1 right-1 w-5 h-5 rounded-full bg-cyan-300 text-black grid place-items-center"><Check className="w-3 h-3"/></span>}</button>)}</div></div></div></div>}
 </div>;
};