import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{Box,ChevronDown,CirclePlus,Database,GitBranch,Image as ImageIcon,Layers3,LoaderCircle,Maximize2,Minus,MousePointer2,Music2,Network,Play,Plus,RefreshCw,RotateCcw,Save,Search,Square,Trash2,Type,Video,Volume2,X,ZoomIn,ZoomOut}from'lucide-react';
import type{BetaCapability,BetaCapabilityMediaType,BetaCapabilityModel}from'../../beta/capabilityClient.js';
import type{FlowEdge,FlowNode,FlowRecord}from'../../beta/flowClient.js';
import type{FlowRunView}from'../../beta/flowRuntimeClient.js';
import{spacesClient,SpaceAsset}from'../../services/spacesClient.js';
import{ApiError}from'../../services/apiClient.js';

const WORLD_W=4200,WORLD_H=2600,NODE_W=224,NODE_H=142;
const mediaLabels:Record<string,string>={TEXT:'Texto',IMAGE:'Imagem',VIDEO:'Vídeo',AUDIO:'Áudio',MODEL_3D:'3D',MASK:'Máscara',STRUCTURED_DATA:'Dados'};
const capabilityLabels:Record<string,string>={
 'text-to-image':'Gerar imagem','image-to-image':'Imagem → imagem','image-edit':'Editar imagem','inpaint-mask':'Inpaint','background-remove-replace':'Remover / trocar fundo','outpaint':'Expandir imagem','upscale':'Upscale','variations':'Variações',
 'text-to-video':'Gerar vídeo','image-to-video':'Imagem → vídeo','first-frame':'Frame inicial','last-frame':'Inicial + final','video-extend':'Estender vídeo','video-edit':'Editar vídeo',
 'text-to-speech':'Gerar voz','music':'Gerar música','text-to-3d':'Texto → 3D','image-to-3d':'Imagem → 3D','multi-image-to-3d':'Multiimagem → 3D',
};
const id=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const errorText=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir a operação.';
const capLabel=(value:string)=>capabilityLabels[value]||value.split('-').map(p=>p.charAt(0).toUpperCase()+p.slice(1)).join(' ');
function categoryFor(cap:string){if(cap.includes('3d'))return'3D';if(cap.includes('video')||cap.includes('frame'))return'Vídeo';if(cap.includes('speech')||cap.includes('music')||cap.includes('audio')||cap.includes('voice'))return'Áudio';if(cap.includes('image')||['inpaint-mask','background-remove-replace','outpaint','upscale','variations'].includes(cap))return'Imagem';return'Utilidades';}
function capFor(models:BetaCapabilityModel[],node:FlowNode):BetaCapability|null{if(node.kind!=='TOOL'||!node.capability_id)return null;const model=models.find(m=>m.model_id===node.model_id)||models.find(m=>m.capabilities.some(c=>c.id===node.capability_id));return model?.capabilities.find(c=>c.id===node.capability_id)||null;}
function outputs(models:BetaCapabilityModel[],assets:SpaceAsset[],node:FlowNode):BetaCapabilityMediaType[]{if(node.kind==='INPUT')return node.media_type?[node.media_type]:[];if(node.kind==='ASSET'){const a=assets.find(x=>x.asset_id===node.asset_id);return a?[a.type as BetaCapabilityMediaType]:node.media_type?[node.media_type]:[];}if(node.kind==='TOOL')return capFor(models,node)?.outputs||[];return[];}
function inputs(models:BetaCapabilityModel[],node:FlowNode):BetaCapabilityMediaType[]{if(node.kind==='OUTPUT')return node.media_type?[node.media_type]:[];if(node.kind==='TOOL')return capFor(models,node)?.inputs||[];return[];}
function nodeIcon(node:FlowNode){const cap=node.capability_id||'';if(node.kind==='INPUT')return Type;if(node.kind==='OUTPUT')return Square;if(node.kind==='ASSET')return Database;const cat=categoryFor(cap);return cat==='Vídeo'?Video:cat==='Áudio'?Music2:cat==='3D'?Layers3:ImageIcon;}
function pathFor(a:FlowNode,b:FlowNode){const x1=a.x+NODE_W,y1=a.y+NODE_H/2,x2=b.x,y2=b.y+NODE_H/2,c=Math.max(70,Math.abs(x2-x1)*.45);return`M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`;}

export const SpacesView:React.FC=()=>{
 const[flows,setFlows]=useState<FlowRecord[]>([]),[current,setCurrent]=useState<FlowRecord|null>(null);
 const[name,setName]=useState('Novo Space'),[description,setDescription]=useState(''),[nodes,setNodes]=useState<FlowNode[]>([]),[edges,setEdges]=useState<FlowEdge[]>([]);
 const[models,setModels]=useState<BetaCapabilityModel[]>([]),[assets,setAssets]=useState<SpaceAsset[]>([]);
 const[selectedId,setSelectedId]=useState<string|null>(null),[linkFrom,setLinkFrom]=useState<string|null>(null),[dirty,setDirty]=useState(false);
 const[busy,setBusy]=useState(''),[error,setError]=useState(''),[run,setRun]=useState<FlowRunView|null>(null),[runInputs,setRunInputs]=useState<Record<string,string>>({});
 const[zoom,setZoom]=useState(.9),[pan,setPan]=useState({x:80,y:60}),[palette,setPalette]=useState<{x:number;y:number;worldX:number;worldY:number}|null>(null),[query,setQuery]=useState('');
 const canvasRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<{id:string;dx:number;dy:number}|null>(null),panRef=useRef<{x:number;y:number;ox:number;oy:number}|null>(null);

 const load=useCallback(async()=>{setBusy('load');setError('');try{const[flowRows,cat,assetRows]=await Promise.all([spacesClient.list(),spacesClient.catalog(),spacesClient.assets()]);setFlows(flowRows);setModels(cat.models||[]);setAssets(assetRows);}catch(e){setError(errorText(e));}finally{setBusy('');}},[]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{if(!run||run.status!=='RUNNING')return;const timer=window.setTimeout(async()=>{try{const next=await spacesClient.advance(run.run_id);setRun(next);if(next.status==='SUCCEEDED'){setAssets(await spacesClient.assets());window.dispatchEvent(new CustomEvent('creations:updated'));}}catch(e){setError(errorText(e));}},2200);return()=>window.clearTimeout(timer)},[run]);

 const selected=nodes.find(n=>n.node_id===selectedId)||null;
 const allCaps=useMemo(()=>Array.from(new Set(models.flatMap(m=>m.capabilities.map(c=>c.id)))).sort(),[models]);
 const paletteItems=useMemo(()=>allCaps.filter(c=>capLabel(c).toLowerCase().includes(query.toLowerCase())||categoryFor(c).toLowerCase().includes(query.toLowerCase())),[allCaps,query]);
 const nodeRunMap=useMemo(()=>new Map((run?.node_runs||[]).map(n=>[n.node_id,n])),[run]);
 const assetMap=useMemo(()=>new Map(assets.map(a=>[a.asset_id,a])),[assets]);

 const applyFlow=(flow:FlowRecord|null)=>{setCurrent(flow);setName(flow?.name||'Novo Space');setDescription(flow?.description||'');setNodes(flow?.graph.nodes||[]);setEdges(flow?.graph.edges||[]);setSelectedId(null);setLinkFrom(null);setDirty(false);setRun(null);setRunInputs({});setError('');setPan({x:80,y:60});setZoom(.9)};
 const openFlow=async(flowId:string)=>{if(!flowId){applyFlow(null);return;}setBusy('open');try{applyFlow(await spacesClient.get(flowId));}catch(e){setError(errorText(e));}finally{setBusy('')}};
 const touch=()=>setDirty(true);
 const addNodeAt=(base:Omit<FlowNode,'node_id'|'x'|'y'>,x:number,y:number)=>{const next:{node_id:string;x:number;y:number}&Omit<FlowNode,'node_id'|'x'|'y'>={...base,node_id:id('node'),x:Math.max(0,Math.min(WORLD_W-NODE_W,x)),y:Math.max(0,Math.min(WORLD_H-NODE_H,y))};setNodes(rows=>[...rows,next]);setSelectedId(next.node_id);touch();setPalette(null);setQuery('')};
 const addTool=(capabilityId:string,x:number,y:number)=>{const eligible=models.filter(m=>m.capabilities.some(c=>c.id===capabilityId));const model=eligible.find(m=>m.model_id==='AUTO')||eligible[0];if(!model)return;addNodeAt({kind:'TOOL',label:capLabel(capabilityId),capability_id:capabilityId,model_id:model.model_id,prompt:'',controls:{}},x,y)};
 const addPrimitive=(kind:'INPUT'|'OUTPUT'|'ASSET',media:BetaCapabilityMediaType,x:number,y:number)=>addNodeAt(kind==='ASSET'?{kind,label:'Asset da Library',media_type:media,asset_id:null}:{kind,label:kind==='INPUT'?`Entrada · ${mediaLabels[media]}`:`Saída · ${mediaLabels[media]}`,media_type:media},x,y);
 const patchSelected=(patch:Partial<FlowNode>)=>{if(!selectedId)return;setNodes(rows=>rows.map(n=>n.node_id===selectedId?{...n,...patch}:n));touch()};
 const removeNode=(nodeId:string)=>{setNodes(rows=>rows.filter(n=>n.node_id!==nodeId));setEdges(rows=>rows.filter(e=>e.from_node_id!==nodeId&&e.to_node_id!==nodeId));if(selectedId===nodeId)setSelectedId(null);if(linkFrom===nodeId)setLinkFrom(null);touch()};
 const connectTo=(targetId:string)=>{if(!linkFrom||linkFrom===targetId){setLinkFrom(null);return;}const a=nodes.find(n=>n.node_id===linkFrom),b=nodes.find(n=>n.node_id===targetId);if(!a||!b)return;const common=outputs(models,assets,a).filter(t=>inputs(models,b).includes(t));if(!common.length){setError('Esses nós não possuem um tipo de mídia compatível.');setLinkFrom(null);return;}if(!edges.some(e=>e.from_node_id===a.node_id&&e.to_node_id===b.node_id&&e.media_type===common[0]))setEdges(rows=>[...rows,{edge_id:id('edge'),from_node_id:a.node_id,to_node_id:b.node_id,media_type:common[0]}]);setLinkFrom(null);touch()};

 const saveSpace=async()=>{setBusy('save');setError('');try{const payload={name:name.trim()||'Novo Space',description,project_id:current?.project_id||null,graph:{nodes,edges}};const saved=current?await spacesClient.save(current.flow_id,{...payload,expected_revision:current.revision}):await spacesClient.create(payload);setCurrent(saved);setFlows(rows=>[saved,...rows.filter(f=>f.flow_id!==saved.flow_id)]);setDirty(false);return saved;}catch(e){setError(errorText(e));return null;}finally{setBusy('')}};
 const runtimePayload=()=>{const payload:Record<string,any>={};for(const n of nodes.filter(n=>n.kind==='INPUT')){const raw=String(runInputs[n.node_id]||'').trim();if(n.media_type==='TEXT')payload[n.node_id]={text:raw};else if(n.media_type==='STRUCTURED_DATA'){payload[n.node_id]={structured:JSON.parse(raw||'{}')}}else payload[n.node_id]={asset_id:raw};}return payload};
 const runSpace=async()=>{setBusy('run');setError('');try{let flow=current;if(!flow||dirty)flow=await saveSpace();if(!flow)return;setRun(await spacesClient.start(flow.flow_id,runtimePayload()));}catch(e){setError(errorText(e));}finally{setBusy('')}};
 const deleteSpace=async()=>{if(!current)return;setBusy('delete');try{await spacesClient.remove(current.flow_id);setFlows(rows=>rows.filter(f=>f.flow_id!==current.flow_id));applyFlow(null);}catch(e){setError(errorText(e));}finally{setBusy('')}};

 const canvasPoint=(clientX:number,clientY:number)=>{const r=canvasRef.current?.getBoundingClientRect();return r?{x:(clientX-r.left-pan.x)/zoom,y:(clientY-r.top-pan.y)/zoom}:{x:300,y:200}};
 const onCanvasContext=(e:React.MouseEvent)=>{e.preventDefault();const p=canvasPoint(e.clientX,e.clientY);const r=canvasRef.current?.getBoundingClientRect();if(!r)return;setPalette({x:e.clientX-r.left,y:e.clientY-r.top,worldX:p.x,worldY:p.y});setQuery('')};
 const onCanvasPointerDown=(e:React.PointerEvent)=>{if(e.button!==0||e.target!==e.currentTarget)return;setSelectedId(null);setPalette(null);panRef.current={x:e.clientX,y:e.clientY,ox:pan.x,oy:pan.y};e.currentTarget.setPointerCapture(e.pointerId)};
 const onCanvasPointerMove=(e:React.PointerEvent)=>{if(dragRef.current){const p=canvasPoint(e.clientX,e.clientY);setNodes(rows=>rows.map(n=>n.node_id===dragRef.current?.id?{...n,x:Math.max(0,Math.min(WORLD_W-NODE_W,p.x-dragRef.current!.dx)),y:Math.max(0,Math.min(WORLD_H-NODE_H,p.y-dragRef.current!.dy))}:n));touch();return;}if(panRef.current)setPan({x:panRef.current.ox+e.clientX-panRef.current.x,y:panRef.current.oy+e.clientY-panRef.current.y})};
 const onCanvasPointerUp=()=>{dragRef.current=null;panRef.current=null};
 const onWheel=(e:React.WheelEvent)=>{e.preventDefault();const next=Math.max(.35,Math.min(1.6,zoom*(e.deltaY>0?.9:1.1)));if(next===zoom)return;const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const mx=e.clientX-r.left,my=e.clientY-r.top,wx=(mx-pan.x)/zoom,wy=(my-pan.y)/zoom;setPan({x:mx-wx*next,y:my-wy*next});setZoom(next)};
 const fit=()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r||!nodes.length){setZoom(.9);setPan({x:80,y:60});return;}const minX=Math.min(...nodes.map(n=>n.x)),minY=Math.min(...nodes.map(n=>n.y)),maxX=Math.max(...nodes.map(n=>n.x+NODE_W)),maxY=Math.max(...nodes.map(n=>n.y+NODE_H));const z=Math.max(.35,Math.min(1.15,Math.min((r.width-120)/(maxX-minX),(r.height-120)/(maxY-minY))));setZoom(z);setPan({x:(r.width-(minX+maxX)*z)/2,y:(r.height-(minY+maxY)*z)/2})};

 const renderPreview=(node:FlowNode)=>{const nr=nodeRunMap.get(node.node_id);const resultId=nr?.output_asset_ids?.[0];const asset=resultId?assetMap.get(resultId):node.kind==='ASSET'&&node.asset_id?assetMap.get(node.asset_id):null;if(!asset?.public_url)return null;if(asset.type==='IMAGE')return <img src={asset.public_url} alt="" className="h-14 w-full rounded-lg object-cover"/>;if(asset.type==='VIDEO')return <video src={asset.public_url} muted preload="metadata" className="h-14 w-full rounded-lg object-cover"/>;if(asset.type==='AUDIO')return <div className="flex h-14 items-center gap-2 rounded-lg bg-white/[0.04] px-3 text-sky-300"><Volume2 className="h-4 w-4"/><span className="text-[10px]">Áudio pronto</span></div>;if(asset.type==='MODEL_3D')return <div className="flex h-14 items-center gap-2 rounded-lg bg-white/[0.04] px-3 text-violet-300"><Layers3 className="h-4 w-4"/><span className="text-[10px]">Modelo 3D</span></div>;return null};

 return <div className="flex h-full min-h-0 flex-col bg-[#050a10] text-zinc-100">
  <header className="flex h-14 shrink-0 items-center gap-2 border-b border-white/[0.07] bg-[#07111b]/95 px-3 backdrop-blur-xl">
   <div className="flex min-w-0 items-center gap-2"><div className="grid h-8 w-8 place-items-center rounded-xl border border-sky-300/15 bg-sky-400/[0.08] text-sky-300"><Network className="h-4 w-4"/></div><div className="hidden sm:block"><strong className="block text-[12px]">Spaces</strong><span className="block text-[9px] text-zinc-500">Canvas de automação</span></div></div>
   <select value={current?.flow_id||''} onChange={e=>void openFlow(e.target.value)} className="ml-2 max-w-[220px] rounded-lg border border-white/10 bg-[#0a1622] px-2 py-1.5 text-[10px]"><option value="">Novo Space</option>{flows.map(f=><option key={f.flow_id} value={f.flow_id}>{f.name} · r{f.revision}</option>)}</select>
   <input value={name} onChange={e=>{setName(e.target.value);touch()}} className="min-w-0 flex-1 bg-transparent px-2 text-[12px] font-semibold outline-none" aria-label="Nome do Space"/>
   <button onClick={()=>applyFlow(null)} className="rounded-lg border border-white/10 p-2 text-zinc-400 hover:text-white" title="Novo"><Plus className="h-4 w-4"/></button>
   <button onClick={()=>void saveSpace()} disabled={Boolean(busy)} className="hidden items-center gap-1.5 rounded-lg border border-white/10 px-3 py-2 text-[10px] font-semibold text-zinc-300 hover:bg-white/[0.04] sm:flex">{busy==='save'?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:<Save className="h-3.5 w-3.5"/>}Salvar</button>
   <button onClick={()=>void runSpace()} disabled={Boolean(busy)||nodes.length===0} className="flex items-center gap-1.5 rounded-lg bg-sky-400 px-3 py-2 text-[10px] font-extrabold text-[#03111c] hover:bg-sky-300 disabled:opacity-50">{busy==='run'?<LoaderCircle className="h-3.5 w-3.5 animate-spin"/>:<Play className="h-3.5 w-3.5"/>}Executar</button>
  </header>
  {error&&<div className="shrink-0 border-b border-rose-400/10 bg-rose-500/[0.08] px-4 py-2 text-[10px] text-rose-200">{error}</div>}
  <div className="relative flex min-h-0 flex-1 overflow-hidden">
   <div ref={canvasRef} onContextMenu={onCanvasContext} onPointerDown={onCanvasPointerDown} onPointerMove={onCanvasPointerMove} onPointerUp={onCanvasPointerUp} onPointerCancel={onCanvasPointerUp} onWheel={onWheel} className="relative min-w-0 flex-1 touch-none overflow-hidden bg-[#050a10]" style={{backgroundImage:'radial-gradient(rgba(125,211,252,.14) 1px, transparent 1px)',backgroundSize:`${24*zoom}px ${24*zoom}px`,backgroundPosition:`${pan.x}px ${pan.y}px`}}>
    <div className="pointer-events-none absolute left-4 top-4 z-20 flex items-center gap-1 rounded-xl border border-white/[0.07] bg-[#08131e]/90 p-1 shadow-xl backdrop-blur-xl">
     <button className="pointer-events-auto p-2 text-zinc-400 hover:text-white" onClick={()=>setZoom(z=>Math.min(1.6,z*1.15))}><ZoomIn className="h-3.5 w-3.5"/></button><span className="w-10 text-center text-[9px] text-zinc-500">{Math.round(zoom*100)}%</span><button className="pointer-events-auto p-2 text-zinc-400 hover:text-white" onClick={()=>setZoom(z=>Math.max(.35,z/1.15))}><ZoomOut className="h-3.5 w-3.5"/></button><button className="pointer-events-auto p-2 text-zinc-400 hover:text-white" onClick={fit}><Maximize2 className="h-3.5 w-3.5"/></button>
    </div>
    <button onClick={()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const p=canvasPoint(r.left+r.width/2,r.top+r.height/2);setPalette({x:r.width/2-150,y:80,worldX:p.x,worldY:p.y})}} className="absolute bottom-5 left-5 z-30 flex items-center gap-2 rounded-xl border border-sky-300/15 bg-[#0a1722]/95 px-3 py-2 text-[10px] font-bold text-sky-200 shadow-2xl"><CirclePlus className="h-4 w-4"/>Adicionar nó</button>
    <div className="absolute origin-top-left" style={{width:WORLD_W,height:WORLD_H,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
     <svg className="pointer-events-none absolute inset-0 overflow-visible" width={WORLD_W} height={WORLD_H}>{edges.map(edge=>{const a=nodes.find(n=>n.node_id===edge.from_node_id),b=nodes.find(n=>n.node_id===edge.to_node_id);if(!a||!b)return null;return <g key={edge.edge_id}><path d={pathFor(a,b)} fill="none" stroke="rgba(56,189,248,.55)" strokeWidth={2}/><circle cx={b.x} cy={b.y+NODE_H/2} r={4} fill="#38bdf8"/></g>})}</svg>
     {nodes.map(node=>{const Icon=nodeIcon(node),nr=nodeRunMap.get(node.node_id),selectedNow=node.node_id===selectedId,status=nr?.status;return <div key={node.node_id} onPointerDown={e=>{e.stopPropagation();setSelectedId(node.node_id);const p=canvasPoint(e.clientX,e.clientY);dragRef.current={id:node.node_id,dx:p.x-node.x,dy:p.y-node.y};(e.currentTarget as HTMLDivElement).setPointerCapture(e.pointerId)}} onPointerUp={e=>{e.stopPropagation();dragRef.current=null}} className={`absolute rounded-2xl border bg-[#0a1621]/96 shadow-2xl ${selectedNow?'border-sky-300/60 ring-1 ring-sky-300/20':'border-white/[0.09]'}`} style={{left:node.x,top:node.y,width:NODE_W,minHeight:NODE_H}}>
       <button onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();connectTo(node.node_id)}} className={`absolute -left-2 top-1/2 z-10 h-4 w-4 -translate-y-1/2 rounded-full border-2 border-[#07111b] ${linkFrom?'bg-sky-400':'bg-zinc-600'}`} title="Entrada"/>
       <button onPointerDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();setLinkFrom(node.node_id)}} className={`absolute -right-2 top-1/2 z-10 h-4 w-4 -translate-y-1/2 rounded-full border-2 border-[#07111b] ${linkFrom===node.node_id?'bg-amber-300':'bg-sky-400'}`} title="Saída"/>
       <div className="flex items-start gap-2 border-b border-white/[0.06] p-3"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-xl bg-white/[0.045] text-sky-300"><Icon className="h-4 w-4"/></div><div className="min-w-0 flex-1"><strong className="block truncate text-[10px]">{node.label}</strong><span className="block truncate text-[8px] uppercase tracking-[.08em] text-zinc-600">{node.kind==='TOOL'?categoryFor(node.capability_id||''):node.kind}</span></div>{status&&<span className={`mt-1 h-2 w-2 rounded-full ${status==='SUCCEEDED'?'bg-emerald-400':status==='FAILED'?'bg-rose-400':status==='RUNNING'?'animate-pulse bg-sky-300':'bg-zinc-600'}`}/>}</div>
       <div className="p-2.5">{renderPreview(node)||<div className="flex h-14 items-center justify-center rounded-xl border border-dashed border-white/[0.07] bg-black/10 text-[9px] text-zinc-600">{node.kind==='TOOL'?(node.prompt||'Configure no painel lateral'):mediaLabels[node.media_type||'TEXT']||'Nó'}</div>}</div>
      </div>})}
    </div>
    {palette&&<div className="absolute z-50 w-[310px] overflow-hidden rounded-2xl border border-white/10 bg-[#091520]/98 shadow-2xl backdrop-blur-xl" style={{left:Math.min(palette.x,(canvasRef.current?.clientWidth||800)-326),top:Math.min(palette.y,(canvasRef.current?.clientHeight||600)-470)}} onPointerDown={e=>e.stopPropagation()}>
      <div className="flex items-center gap-2 border-b border-white/[0.07] p-3"><Search className="h-4 w-4 text-zinc-500"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ferramenta..." className="min-w-0 flex-1 bg-transparent text-[11px] outline-none"/><button onClick={()=>setPalette(null)}><X className="h-4 w-4 text-zinc-500"/></button></div>
      <div className="max-h-[390px] overflow-y-auto p-2">
       {!query&&<><p className="px-2 pb-1 pt-1 text-[8px] font-bold uppercase tracking-[.14em] text-zinc-600">Entradas e Assets</p><div className="grid grid-cols-2 gap-1">{(['TEXT','IMAGE','VIDEO','AUDIO','MODEL_3D'] as BetaCapabilityMediaType[]).map(m=><button key={'in'+m} onClick={()=>addPrimitive('INPUT',m,palette.worldX,palette.worldY)} className="rounded-xl px-2 py-2 text-left text-[9px] text-zinc-300 hover:bg-white/[0.05]">Entrada · {mediaLabels[m]}</button>)}<button onClick={()=>addPrimitive('ASSET','IMAGE',palette.worldX,palette.worldY)} className="rounded-xl px-2 py-2 text-left text-[9px] text-zinc-300 hover:bg-white/[0.05]">Asset da Library</button></div></>}
       {['Imagem','Vídeo','Áudio','3D','Utilidades'].map(cat=>{const rows=paletteItems.filter(c=>categoryFor(c)===cat);if(!rows.length)return null;return <div key={cat}><p className="px-2 pb-1 pt-3 text-[8px] font-bold uppercase tracking-[.14em] text-zinc-600">{cat}</p>{rows.map(c=><button key={c} onClick={()=>addTool(c,palette.worldX,palette.worldY)} className="flex w-full items-center justify-between rounded-xl px-2 py-2 text-left hover:bg-white/[0.05]"><span className="text-[10px] text-zinc-200">{capLabel(c)}</span><Plus className="h-3.5 w-3.5 text-zinc-600"/></button>)}</div>})}
       {!query&&<><p className="px-2 pb-1 pt-3 text-[8px] font-bold uppercase tracking-[.14em] text-zinc-600">Saídas</p><div className="grid grid-cols-2 gap-1">{(['IMAGE','VIDEO','AUDIO','MODEL_3D','TEXT'] as BetaCapabilityMediaType[]).map(m=><button key={'out'+m} onClick={()=>addPrimitive('OUTPUT',m,palette.worldX,palette.worldY)} className="rounded-xl px-2 py-2 text-left text-[9px] text-zinc-300 hover:bg-white/[0.05]">Saída · {mediaLabels[m]}</button>)}</div></>}
      </div>
    </div>}
    <div className="absolute bottom-5 right-5 z-20 h-28 w-44 overflow-hidden rounded-xl border border-white/[0.08] bg-[#07111b]/90 p-2 shadow-xl"><div className="relative h-full w-full bg-[radial-gradient(rgba(125,211,252,.12)_1px,transparent_1px)] [background-size:10px_10px]">{nodes.map(n=><button key={n.node_id} onClick={()=>setSelectedId(n.node_id)} className={`absolute h-2 w-3 rounded-sm ${n.node_id===selectedId?'bg-sky-300':'bg-zinc-500'}`} style={{left:`${Math.min(96,Math.max(0,n.x/WORLD_W*100))}%`,top:`${Math.min(92,Math.max(0,n.y/WORLD_H*100))}%`}}/>)}</div></div>
   </div>
   <aside className="hidden w-[310px] shrink-0 overflow-y-auto border-l border-white/[0.07] bg-[#07111b] lg:block">
    {selected?<div className="p-4"><div className="mb-4 flex items-start justify-between"><div><span className="text-[8px] font-bold uppercase tracking-[.14em] text-sky-400">Inspector</span><h2 className="mt-1 text-[13px] font-bold">{selected.label}</h2></div><button onClick={()=>removeNode(selected.node_id)} className="rounded-lg p-2 text-zinc-600 hover:bg-rose-500/10 hover:text-rose-300"><Trash2 className="h-4 w-4"/></button></div>
      <label className="mb-3 block"><span className="mb-1 block text-[9px] text-zinc-500">Nome do nó</span><input value={selected.label} onChange={e=>patchSelected({label:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px] outline-none focus:border-sky-300/40"/></label>
      {selected.kind==='TOOL'&&<><label className="mb-3 block"><span className="mb-1 block text-[9px] text-zinc-500">Modelo</span><select value={selected.model_id||''} onChange={e=>patchSelected({model_id:e.target.value})} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]">{models.filter(m=>m.capabilities.some(c=>c.id===selected.capability_id)).map(m=><option key={m.model_id} value={m.model_id}>{m.name}</option>)}</select></label><label className="mb-3 block"><span className="mb-1 block text-[9px] text-zinc-500">Prompt / instrução</span><textarea rows={5} value={selected.prompt||''} onChange={e=>patchSelected({prompt:e.target.value})} className="w-full resize-none rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px] outline-none focus:border-sky-300/40" placeholder="Descreva o que este nó deve fazer..."/></label>{(()=>{const cap=capFor(models,selected);if(!cap)return null;return <div className="space-y-3">{cap.controls.includes('duration')&&cap.supported_durations?.length?<label className="block"><span className="mb-1 block text-[9px] text-zinc-500">Duração</span><select value={String(selected.controls?.duration_seconds||cap.supported_durations[0])} onChange={e=>patchSelected({controls:{...(selected.controls||{}),duration_seconds:Number(e.target.value)}})} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]">{cap.supported_durations.map(v=><option key={v} value={v}>{v}s</option>)}</select></label>:null}{cap.controls.includes('resolution')&&cap.supported_resolutions?.length?<label className="block"><span className="mb-1 block text-[9px] text-zinc-500">Resolução</span><select value={String(selected.controls?.resolution||cap.supported_resolutions[0])} onChange={e=>patchSelected({controls:{...(selected.controls||{}),resolution:e.target.value}})} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]">{cap.supported_resolutions.map(v=><option key={v}>{v}</option>)}</select></label>:null}{cap.controls.includes('aspect_ratio')&&cap.supported_aspect_ratios?.length?<label className="block"><span className="mb-1 block text-[9px] text-zinc-500">Formato</span><select value={String(selected.controls?.aspect_ratio||cap.supported_aspect_ratios[0])} onChange={e=>patchSelected({controls:{...(selected.controls||{}),aspect_ratio:e.target.value}})} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]">{cap.supported_aspect_ratios.map(v=><option key={v}>{v}</option>)}</select></label>:null}</div>})()}</>}
      {selected.kind==='ASSET'&&<label className="mb-3 block"><span className="mb-1 block text-[9px] text-zinc-500">Asset da Library</span><select value={selected.asset_id||''} onChange={e=>{const a=assetMap.get(e.target.value);patchSelected({asset_id:e.target.value,media_type:a?.type as BetaCapabilityMediaType,label:a?.name||selected.label})}} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]"><option value="">Selecione...</option>{assets.map(a=><option key={a.asset_id} value={a.asset_id}>{a.name}</option>)}</select></label>}
      {selected.kind==='INPUT'&&<><label className="mb-3 block"><span className="mb-1 block text-[9px] text-zinc-500">Tipo</span><select value={selected.media_type||'TEXT'} onChange={e=>patchSelected({media_type:e.target.value as BetaCapabilityMediaType})} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]">{Object.keys(mediaLabels).map(m=><option key={m} value={m}>{mediaLabels[m]}</option>)}</select></label>{selected.media_type==='TEXT'?<label className="block"><span className="mb-1 block text-[9px] text-zinc-500">Valor para a próxima execução</span><textarea rows={4} value={runInputs[selected.node_id]||''} onChange={e=>setRunInputs(v=>({...v,[selected.node_id]:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]"/></label>:<label className="block"><span className="mb-1 block text-[9px] text-zinc-500">Asset de entrada</span><select value={runInputs[selected.node_id]||''} onChange={e=>setRunInputs(v=>({...v,[selected.node_id]:e.target.value}))} className="w-full rounded-xl border border-white/10 bg-[#0b1824] px-3 py-2 text-[10px]"><option value="">Selecione...</option>{assets.filter(a=>selected.media_type==='MASK'?a.type==='IMAGE':a.type===selected.media_type).map(a=><option key={a.asset_id} value={a.asset_id}>{a.name}</option>)}</select></label>}</>}
      <div className="mt-5 rounded-xl border border-white/[0.07] bg-white/[0.02] p-3"><span className="text-[8px] uppercase tracking-[.12em] text-zinc-600">Conexões</span><div className="mt-2 flex items-center gap-2 text-[9px] text-zinc-400"><GitBranch className="h-3.5 w-3.5"/>{edges.filter(e=>e.from_node_id===selected.node_id||e.to_node_id===selected.node_id).length} ligação(ões)</div>{linkFrom===selected.node_id&&<p className="mt-2 text-[9px] text-amber-300">Selecione a entrada do próximo nó.</p>}</div>
     </div>:<div className="grid h-full place-items-center p-8 text-center"><div><MousePointer2 className="mx-auto h-6 w-6 text-zinc-700"/><p className="mt-3 text-[10px] text-zinc-600">Selecione um nó para configurar.</p><p className="mt-1 text-[9px] text-zinc-700">Clique com o botão direito no canvas para adicionar ferramentas.</p></div></div>}
    {run&&<div className="border-t border-white/[0.07] p-4"><div className="flex items-center justify-between"><div><span className="text-[8px] uppercase tracking-[.12em] text-zinc-600">Execução</span><strong className="mt-1 block text-[10px]">{run.status}</strong></div>{run.status==='FAILED'&&<button onClick={async()=>setRun(await spacesClient.retry(run.run_id))} className="p-2 text-zinc-400"><RotateCcw className="h-4 w-4"/></button>}</div><p className="mt-2 text-[9px] text-zinc-500">{run.authorized_credits_total.toLocaleString('pt-BR')} créditos autorizados</p></div>}
   </aside>
  </div>
 </div>;
};
