import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Box,Boxes,CheckCircle2,Download,Image as ImageIcon,LoaderCircle,RefreshCw,Sparkles,Upload,WandSparkles}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{threeDGenerationClient,ThreeDCapability,ThreeDJob,ThreeDModel}from'../../services/threeDGenerationClient.js';
import{Asset}from'../../types/index.js';
import{CreationGallery}from'../workspace/CreationGallery.js';
import{StableGeneratorModelPicker}from'../workspace/StableGeneratorModelPicker.js';
import{StableModel3DPreview}from'../workspace/StableModel3DPreview.js';
import'../../styles/stable-generator-shell.css';

type Tool=ThreeDCapability;
const TOOLS:Array<{id:Tool;label:string;description:string;icon:React.ComponentType<{className?:string}>}>=[{id:'text-to-3d',label:'Texto → 3D',description:'Crie por descrição.',icon:Box},{id:'image-to-3d',label:'Imagem → 3D',description:'Use uma imagem.',icon:ImageIcon},{id:'multi-image-to-3d',label:'Multiimagem → 3D',description:'Combine 2–4 vistas.',icon:Boxes}];
const terminal=(status?:string)=>['SUCCEEDED','FAILED','CANCELLED'].includes(String(status||''));
const message=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir esta operação.';

export const ThreeDCreateView:React.FC=()=>{
 const{wallet,refreshWallet}=useAuth();
 const[tool,setTool]=useState<Tool>('text-to-3d'),[models,setModels]=useState<ThreeDModel[]>([]),[selectedModelId,setSelectedModelId]=useState('AUTO'),[images,setImages]=useState<Asset[]>([]),[selectedIds,setSelectedIds]=useState<string[]>([]),[prompt,setPrompt]=useState('');
 const[meshMode,setMeshMode]=useState<'TEXTURED'|'LOW_POLY'|'GEOMETRY'>('TEXTURED'),[pbr,setPbr]=useState(false),[targetFaces,setTargetFaces]=useState(500000),[topology,setTopology]=useState<'TRIANGLE'|'QUAD'>('TRIANGLE');
 const[job,setJob]=useState<ThreeDJob|null>(null),[result,setResult]=useState<Asset|null>(null),[busy,setBusy]=useState('load'),[error,setError]=useState(''),[pollCount,setPollCount]=useState(0);
 const load=useCallback(async()=>{setBusy(current=>current||'load');setError('');try{const[catalog,assetRows]=await Promise.all([threeDGenerationClient.catalog(),assetService.listAssets({type:'IMAGE'})]);setModels(catalog);setImages(assetRows);setSelectedModelId(current=>current==='AUTO'||catalog.some(model=>model.model_id===current)?current:'AUTO')}catch(err){setError(message(err))}finally{setBusy(current=>current==='load'?'':current)}},[]);
 useEffect(()=>{void load()},[load]);
 const availableModels=useMemo(()=>models.filter(model=>model.capabilities.some(cap=>cap.id===tool)),[models,tool]);
 const model=useMemo(()=>selectedModelId==='AUTO'?null:availableModels.find(item=>item.model_id===selectedModelId)||null,[availableModels,selectedModelId]);
 const routeReady=selectedModelId==='AUTO'?availableModels.some(item=>(item.providers||[]).some(provider=>provider.capability_ids.includes(tool))):Boolean(model?.providers?.some(provider=>provider.capability_ids.includes(tool)));
 const invalidate=()=>{setJob(null);setResult(null);setPollCount(0);setError('')};
 useEffect(()=>{if(selectedModelId!=='AUTO'&&!availableModels.some(item=>item.model_id===selectedModelId))setSelectedModelId('AUTO');setSelectedIds([]);invalidate()},[tool]);
 useEffect(()=>{if(!job||terminal(job.status)||!['QUEUED','RUNNING'].includes(job.status)||pollCount>=180)return;const timer=window.setTimeout(async()=>{try{setJob(await threeDGenerationClient.get(job.job_id));setPollCount(value=>value+1)}catch(err){setError(message(err));setPollCount(180)}},Math.min(7000,2000+pollCount*100));return()=>window.clearTimeout(timer)},[job,pollCount]);
 useEffect(()=>{if(job?.status!=='SUCCEEDED')return;void refreshWallet();const assetId=job.result_asset_ids?.[0];if(assetId)void threeDGenerationClient.asset(assetId).then(setResult).catch(()=>setResult(null));window.dispatchEvent(new CustomEvent('creations:updated',{detail:{kind:'THREE_D',asset_ids:job.result_asset_ids||[]}}))},[job?.status,job?.result_asset_ids,refreshWallet]);
 const toggleImage=(id:string)=>{invalidate();if(tool==='image-to-3d'){setSelectedIds([id]);return}setSelectedIds(current=>current.includes(id)?current.filter(value=>value!==id):current.length<4?[...current,id]:current)};
 const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const files:File[]=event.target.files?Array.from(event.target.files as FileList):[];event.target.value='';if(!files.length)return;setBusy('upload');setError('');try{const next:Asset[]=[];for(const file of files.slice(0,tool==='multi-image-to-3d'?4:1))next.push(await assetService.uploadAsset({file,name:file.name}));setImages(current=>[...next,...current.filter(row=>!next.some(item=>item.asset_id===row.asset_id))]);setSelectedIds(current=>tool==='image-to-3d'?[next[0].asset_id]:Array.from(new Set([...current,...next.map(item=>item.asset_id)])).slice(0,4));invalidate()}catch(err){setError(message(err))}finally{setBusy('')}};
 const buildRequest=()=>{if(!routeReady)throw new Error('Nenhum modelo com rota e preço verificados está disponível para esta modalidade.');if(tool==='text-to-3d'&&!prompt.trim())throw new Error('Descreva o objeto que deseja criar.');if(tool==='image-to-3d'&&selectedIds.length!==1)throw new Error('Selecione uma imagem de referência.');if(tool==='multi-image-to-3d'&&(selectedIds.length<2||selectedIds.length>4))throw new Error('Selecione de 2 a 4 imagens do mesmo objeto.');return{capability_id:tool,model_id:selectedModelId,prompt:prompt.trim(),references:selectedIds.map(asset_id=>({asset_id,slot_type:'GENERAL' as const})),controls:{output_format:'glb',mesh_mode:meshMode,pbr:meshMode==='GEOMETRY'?false:pbr,target_faces:targetFaces,topology}}};
 const quote=async()=>{setBusy('quote');setError('');setJob(null);setResult(null);try{const created=await threeDGenerationClient.create(buildRequest());setJob(await threeDGenerationClient.quote(created.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const generate=async()=>{if(!job)return;setBusy('generate');setError('');try{setJob(await threeDGenerationClient.queue(job.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const balance=wallet?.available_credits??0,price=job?.quote?.credit_price??null,insufficient=price!=null&&balance<price;
 const status=job?.status==='SUCCEEDED'?'Concluído':job?.status==='FAILED'?'Falhou':job?.status==='CANCELLED'?'Cancelado':job?.status==='RUNNING'?'Processando':job?.status==='QUEUED'?'Na fila':job?.status==='QUOTED'?'Preço calculado':'Preparando';
 return <div className="ia-stable-generator-studio">
  <aside className="ia-stable-generator-panel" aria-label="Gerador 3D"><div className="ia-stable-generator-scroll">
   <StableGeneratorModelPicker models={availableModels.map(item=>({model_id:item.model_id,name:item.name,description:'Modelo 3D'}))} selectedModelId={selectedModelId} loading={busy==='load'} onSelect={modelId=>{setSelectedModelId(modelId);invalidate()}} accentClass="from-emerald-500/28 via-cyan-500/12 to-violet-500/18"/>
   <div className="ia-stable-toolgrid">{TOOLS.map(item=>{const Icon=item.icon;return <button type="button" key={item.id} className={tool===item.id?'is-selected':''} onClick={()=>setTool(item.id)}><Icon/><strong>{item.label}</strong><small>{item.description}</small></button>})}</div>
   {tool==='text-to-3d'?<section className="ia-stable-generator-field"><div className="ia-stable-generator-labelrow"><label htmlFor="three-d-prompt">Descrição do objeto</label><span>{prompt.length.toLocaleString('pt-BR')} caracteres</span></div><textarea id="three-d-prompt" className="ia-stable-generator-textarea" rows={6} value={prompt} maxLength={4000} onChange={event=>{setPrompt(event.target.value);invalidate()}} placeholder="Ex.: cadeira lounge escultural em nogueira, almofada de couro caramelo…"/></section>:<section className="ia-stable-generator-field"><div className="ia-stable-generator-labelrow"><span>{tool==='image-to-3d'?'Imagem de referência':'Vistas do mesmo objeto'}</span><label className="ia-stable-generator-secondary cursor-pointer"><Upload className="w-3 h-3"/>{busy==='upload'?'Enviando…':'Upload'}<input type="file" className="hidden" accept="image/*" multiple={tool==='multi-image-to-3d'} disabled={busy==='upload'} onChange={upload}/></label></div><div className="grid grid-cols-4 gap-1.5">{images.slice(0,12).map(asset=><button type="button" key={asset.asset_id} className={`relative aspect-square overflow-hidden rounded-lg border ${selectedIds.includes(asset.asset_id)?'border-emerald-300':'border-white/[0.07]'}`} onClick={()=>toggleImage(asset.asset_id)}><img src={asset.thumbnail_url||asset.public_url||''} alt={asset.name} className="w-full h-full object-cover"/>{selectedIds.includes(asset.asset_id)&&<span className="absolute right-1 bottom-1 rounded bg-emerald-300 text-black text-[7px] font-black px-1">{selectedIds.indexOf(asset.asset_id)+1}</span>}</button>)}</div></section>}
   <div className="ia-stable-generator-settings"><label className="ia-stable-setting"><span>Tipo de malha</span><select value={meshMode} onChange={event=>{setMeshMode(event.target.value as any);invalidate()}}><option value="TEXTURED">Texturizada</option><option value="LOW_POLY">Low poly</option><option value="GEOMETRY">Somente geometria</option></select></label><label className="ia-stable-setting"><span>Topologia</span><select value={topology} onChange={event=>{setTopology(event.target.value as any);invalidate()}}><option value="TRIANGLE">Triângulos</option><option value="QUAD">Quads</option></select></label><label className="ia-stable-setting is-stack"><span>Faces alvo · {targetFaces.toLocaleString('pt-BR')}</span><input type="range" min={40000} max={1500000} step={20000} value={targetFaces} onChange={event=>{setTargetFaces(Number(event.target.value));invalidate()}}/></label></div>
   <label className="ia-stable-toggle"><input type="checkbox" checked={pbr} disabled={meshMode==='GEOMETRY'} onChange={event=>{setPbr(event.target.checked);invalidate()}}/><span><strong>Materiais PBR</strong><small>Gera materiais físicos quando suportado.</small></span></label>
   {job&&<section className="ia-stable-current"><div className="flex items-center justify-between"><div><span className="text-[8px] text-zinc-600">Resultado atual</span><strong className="block text-[10px] text-white">{status}</strong></div>{job.status==='SUCCEEDED'?<CheckCircle2 className="w-4 h-4 text-emerald-300"/>:<Box className="w-4 h-4 text-emerald-300"/>}</div>{job.quote&&<p>Modelo executado: <strong>{job.quote.selected_model_id}</strong> · {job.quote.routing_mode==='AUTO'?'roteamento AUTO':'modelo específico'}.</p>}{job.status==='FAILED'&&<p>{job.error_message||'A geração 3D não pôde ser concluída.'}</p>}{job.status==='SUCCEEDED'&&result?.public_url&&<><StableModel3DPreview url={result.public_url} label={result.name}/><a className="mt-2 ia-stable-generator-secondary" href={result.public_url} target="_blank" rel="noreferrer"><Download/>Abrir GLB</a></>}</section>}
  </div><div className="ia-stable-generator-actionbar">{error&&<div className="ia-stable-error mb-2" role="status">{error}</div>}<div className="ia-stable-price-row"><div><span>Preço</span><strong>{price==null?'Preço indisponível':`${price.toLocaleString('pt-BR')} créditos`}</strong></div><div className="ia-stable-balance"><span>Saldo</span><strong>{balance.toLocaleString('pt-BR')} créditos</strong></div></div>{!job?.quote?<button className="ia-stable-generator-primary" disabled={Boolean(busy)||!routeReady} onClick={()=>void quote()}>{busy==='quote'?<LoaderCircle className="is-spin"/>:<Sparkles/>}Calcular créditos</button>:['DRAFT','QUOTED'].includes(job.status)?<div className="ia-stable-generator-actions"><button className="ia-stable-generator-secondary" disabled={Boolean(busy)} onClick={()=>void quote()}><RefreshCw/>Atualizar</button><button className="ia-stable-generator-primary" disabled={Boolean(busy)||insufficient} onClick={()=>void generate()}>{busy==='generate'?<LoaderCircle className="is-spin"/>:<WandSparkles/>}Gerar 3D</button></div>:<button className="ia-stable-generator-primary" disabled>{['QUEUED','RUNNING'].includes(job.status)&&<LoaderCircle className="is-spin"/>}{status}</button>}</div></aside>
  <main className="ia-stable-generator-main"><CreationGallery defaultFilter="THREE_D" title="Minhas criações" subtitle="O mesmo histórico universal de Imagem, Vídeo, Voz, Música e 3D."/></main>
 </div>;
};
export default ThreeDCreateView;
