import React,{useCallback,useEffect,useMemo,useState}from'react';
import{Box,Boxes,CheckCircle2,Download,Grid3X3,Image as ImageIcon,Layers3,Upload}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{threeDGenerationClient,ThreeDCapability,ThreeDJob,ThreeDModel}from'../../services/threeDGenerationClient.js';
import{Asset}from'../../types/index.js';
import{CreationGallery}from'../workspace/CreationGallery.js';
import{StableGeneratorModelPicker}from'../workspace/StableGeneratorModelPicker.js';
import{StableModel3DPreview}from'../workspace/StableModel3DPreview.js';
import{GeneratorField,GeneratorFooter,GeneratorOptionGrid,GeneratorPanel,GeneratorRangeSlider,GeneratorScroll,GeneratorSettingRow,GeneratorToggle}from'../workspace/GeneratorControls.js';
import{PromptComposer}from'../workspace/PromptComposer.js';
import{MobileStudioLayout}from'../workspace/MobileStudioLayout.js';

type Tool=ThreeDCapability;
type OpenCard='mesh'|'topology'|'faces'|null;
const TOOLS:Array<{id:Tool;label:string;description:string;icon:React.ComponentType<{className?:string}>}>=[{id:'text-to-3d',label:'Texto → 3D',description:'Crie por descrição.',icon:Box},{id:'image-to-3d',label:'Imagem → 3D',description:'Use uma imagem.',icon:ImageIcon},{id:'multi-image-to-3d',label:'Multiimagem → 3D',description:'Combine 2–4 vistas.',icon:Boxes}];
const terminal=(status?:string)=>['SUCCEEDED','FAILED','CANCELLED'].includes(String(status||''));
const message=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir esta operação.';

export const ThreeDCreateView:React.FC=()=>{
 const{wallet,refreshWallet}=useAuth();
 const[tool,setTool]=useState<Tool>('text-to-3d'),[models,setModels]=useState<ThreeDModel[]>([]),[selectedModelId,setSelectedModelId]=useState('AUTO'),[images,setImages]=useState<Asset[]>([]),[selectedIds,setSelectedIds]=useState<string[]>([]),[prompt,setPrompt]=useState(''),[openCard,setOpenCard]=useState<OpenCard>(null),[mobileActiveCount,setMobileActiveCount]=useState(0);
 const[meshMode,setMeshMode]=useState<'TEXTURED'|'LOW_POLY'|'GEOMETRY'>('TEXTURED'),[pbr,setPbr]=useState(false),[targetFaces,setTargetFaces]=useState(500000),[topology,setTopology]=useState<'TRIANGLE'|'QUAD'>('TRIANGLE');
 const[job,setJob]=useState<ThreeDJob|null>(null),[result,setResult]=useState<Asset|null>(null),[busy,setBusy]=useState('load'),[error,setError]=useState(''),[pollCount,setPollCount]=useState(0);
 const load=useCallback(async()=>{setBusy(current=>current||'load');setError('');try{const[catalog,assetRows]=await Promise.all([threeDGenerationClient.catalog(),assetService.listAssets({type:'IMAGE'})]);setModels(catalog);setImages(assetRows);const fallback=catalog.find(model=>model.model_id==='AUTO'&&model.providers?.length)?.model_id||catalog.find(model=>model.model_id!=='AUTO'&&model.providers?.length)?.model_id||catalog.find(model=>model.model_id!=='AUTO')?.model_id||'';setSelectedModelId(current=>current==='AUTO'?fallback:(catalog.some(model=>model.model_id===current)?current:fallback))}catch(err){setError(message(err))}finally{setBusy(current=>current==='load'?'':current)}},[]);
 useEffect(()=>{void load()},[load]);
 const availableModels=useMemo(()=>models.filter(model=>model.capabilities.some(cap=>cap.id===tool)),[models,tool]);
 const model=useMemo(()=>selectedModelId==='AUTO'?null:availableModels.find(item=>item.model_id===selectedModelId)||null,[availableModels,selectedModelId]);
 const routeReady=selectedModelId==='AUTO'?Boolean(availableModels.find(item=>item.model_id==='AUTO')?.providers?.some(provider=>provider.capability_ids.includes(tool))):Boolean(model?.providers?.some(provider=>provider.capability_ids.includes(tool)));
 const invalidate=()=>{setJob(null);setResult(null);setPollCount(0);setError('')};
 useEffect(()=>{if(selectedModelId!=='AUTO'&&!availableModels.some(item=>item.model_id===selectedModelId)){const fallback=availableModels.find(item=>item.model_id==='AUTO'&&item.providers?.some(provider=>provider.capability_ids.includes(tool)))?.model_id||availableModels.find(item=>item.model_id!=='AUTO'&&item.providers?.some(provider=>provider.capability_ids.includes(tool)))?.model_id||availableModels.find(item=>item.model_id!=='AUTO')?.model_id||'';setSelectedModelId(fallback);}else if(selectedModelId==='AUTO'&&!availableModels.find(item=>item.model_id==='AUTO')?.providers?.some(provider=>provider.capability_ids.includes(tool))){setSelectedModelId(availableModels.find(item=>item.model_id!=='AUTO'&&item.providers?.some(provider=>provider.capability_ids.includes(tool)))?.model_id||availableModels.find(item=>item.model_id!=='AUTO')?.model_id||'');}setSelectedIds([]);invalidate()},[tool]);
 useEffect(()=>{if(!job||terminal(job.status)||!['QUEUED','RUNNING'].includes(job.status)||pollCount>=180)return;const timer=window.setTimeout(async()=>{try{setJob(await threeDGenerationClient.get(job.job_id));setPollCount(value=>value+1)}catch(err){setError(message(err));setPollCount(180)}},Math.min(7000,2000+pollCount*100));return()=>window.clearTimeout(timer)},[job,pollCount]);
 useEffect(()=>{if(job?.status!=='SUCCEEDED')return;void refreshWallet();const assetId=job.result_asset_ids?.[0];if(assetId)void threeDGenerationClient.asset(assetId).then(setResult).catch(()=>setResult(null));window.dispatchEvent(new CustomEvent('creations:updated',{detail:{kind:'THREE_D',asset_ids:job.result_asset_ids||[]}}))},[job?.status,job?.result_asset_ids,refreshWallet]);
 const toggleImage=(id:string)=>{invalidate();if(tool==='image-to-3d'){setSelectedIds([id]);return}setSelectedIds(current=>current.includes(id)?current.filter(value=>value!==id):current.length<4?[...current,id]:current)};
 const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const files:File[]=event.target.files?Array.from(event.target.files as FileList):[];event.target.value='';if(!files.length)return;setBusy('upload');setError('');try{const next:Asset[]=[];for(const file of files.slice(0,tool==='multi-image-to-3d'?4:1))next.push(await assetService.uploadAsset({file,name:file.name}));setImages(current=>[...next,...current.filter(row=>!next.some(item=>item.asset_id===row.asset_id))]);setSelectedIds(current=>tool==='image-to-3d'?[next[0].asset_id]:Array.from(new Set([...current,...next.map(item=>item.asset_id)])).slice(0,4));invalidate()}catch(err){setError(message(err))}finally{setBusy('')}};
 const buildRequest=()=>{if(!routeReady)throw new Error('Nenhum modelo com rota e preço verificados está disponível para esta modalidade.');if(tool==='text-to-3d'&&!prompt.trim())throw new Error('Descreva o objeto que deseja criar.');if(tool==='image-to-3d'&&selectedIds.length!==1)throw new Error('Selecione uma imagem de referência.');if(tool==='multi-image-to-3d'&&(selectedIds.length<2||selectedIds.length>4))throw new Error('Selecione de 2 a 4 imagens do mesmo objeto.');return{capability_id:tool,model_id:selectedModelId,prompt:prompt.trim(),references:selectedIds.map(asset_id=>({asset_id,slot_type:'GENERAL' as const})),controls:{output_format:'glb',mesh_mode:meshMode,pbr:meshMode==='GEOMETRY'?false:pbr,target_faces:targetFaces,topology}}};
 const quote=async()=>{setBusy('quote');setError('');setJob(null);setResult(null);try{const created=await threeDGenerationClient.create(buildRequest());setJob(await threeDGenerationClient.quote(created.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const generate=async()=>{if(!job)return;setBusy('generate');setError('');try{setJob(await threeDGenerationClient.queue(job.job_id));setPollCount(0)}catch(err){setError(message(err))}finally{setBusy('')}};
 const balance=wallet?.available_credits??0,price=job?.quote?.credit_price??null,insufficient=price!=null&&balance<price;
 const status=job?.status==='SUCCEEDED'?'Concluído':job?.status==='FAILED'?'Falhou':job?.status==='CANCELLED'?'Cancelado':job?.status==='RUNNING'?'Processando':job?.status==='QUEUED'?'Na fila':job?.status==='QUOTED'?'Preço calculado':'Preparando';
 const meshLabel=meshMode==='TEXTURED'?'Texturizada':meshMode==='LOW_POLY'?'Low poly':'Somente geometria',topologyLabel=topology==='TRIANGLE'?'Triângulos':'Quads';
 const requestReady=routeReady&&(tool!=='text-to-3d'||Boolean(prompt.trim()))&&(tool!=='image-to-3d'||selectedIds.length===1)&&(tool!=='multi-image-to-3d'||(selectedIds.length>=2&&selectedIds.length<=4));
 const footer=!job?.quote?{label:'Calcular créditos',disabled:Boolean(busy)||!requestReady,onClick:quote,secondary:undefined as string|undefined,onSecondary:undefined as(()=>void)|undefined}:{label:['DRAFT','QUOTED'].includes(job.status)?'Gerar 3D':status,disabled:Boolean(busy)||insufficient||!['DRAFT','QUOTED'].includes(job.status),onClick:generate,secondary:['DRAFT','QUOTED'].includes(job.status)?'Atualizar':undefined,onSecondary:['DRAFT','QUOTED'].includes(job.status)?quote:undefined};
 const creator=<GeneratorPanel ariaLabel="Gerador 3D"><GeneratorScroll>
  <StableGeneratorModelPicker models={availableModels.map(item=>({model_id:item.model_id,name:item.name,description:'Modelo 3D'}))} selectedModelId={selectedModelId} loading={busy==='load'} onSelect={modelId=>{setSelectedModelId(modelId);invalidate()}}/>
  <div className="grid grid-cols-3 gap-1.5">{TOOLS.map(item=>{const Icon=item.icon;const selected=tool===item.id;return <button type="button" key={item.id} onClick={()=>setTool(item.id)} className={`min-w-0 rounded-xl border p-2.5 text-left transition-colors ${selected?'border-cyan-300/30 bg-cyan-300/[0.08] text-cyan-100':'border-white/[0.065] bg-white/[0.025] text-zinc-500 hover:text-zinc-200'}`}><Icon className="w-3.5 h-3.5"/><strong className="block mt-1.5 text-[9px] text-white">{item.label}</strong><small className="block mt-0.5 text-[7px] leading-tight text-zinc-700">{item.description}</small></button>})}</div>
  {tool==='text-to-3d'?<PromptComposer prompt={prompt} onChangePrompt={value=>{setPrompt(value);invalidate()}} negativePrompt="" onChangeNegativePrompt={()=>{}} onOpenImproveModal={()=>{}} references={[]} onRequestAddMedia={()=>{}} supportsNegativePrompt={false} supportsReferences={false} maxChars={4000} label="Descrição do objeto" placeholder="Ex.: cadeira lounge escultural em nogueira, almofada de couro caramelo…" showImproveButton={false}/>:<GeneratorField label={tool==='image-to-3d'?'Imagem de referência':'Vistas do mesmo objeto'}><div className="flex justify-end mb-2"><label className="h-8 rounded-lg border border-white/[0.07] bg-white/[0.035] px-2.5 flex items-center gap-1.5 text-[9px] font-semibold text-zinc-300 cursor-pointer"><Upload className="w-3 h-3"/>{busy==='upload'?'Enviando…':'Upload'}<input type="file" className="hidden" accept="image/*" multiple={tool==='multi-image-to-3d'} disabled={busy==='upload'} onChange={upload}/></label></div><div className="grid grid-cols-4 gap-1.5">{images.slice(0,12).map(asset=><button type="button" key={asset.asset_id} className={`relative aspect-square overflow-hidden rounded-lg border ${selectedIds.includes(asset.asset_id)?'border-cyan-300':'border-white/[0.07]'}`} onClick={()=>toggleImage(asset.asset_id)}><img src={asset.thumbnail_url||asset.public_url||''} alt={asset.name} className="w-full h-full object-cover"/>{selectedIds.includes(asset.asset_id)&&<span className="absolute right-1 bottom-1 rounded bg-cyan-300 text-black text-[7px] font-black px-1">{selectedIds.indexOf(asset.asset_id)+1}</span>}</button>)}</div></GeneratorField>}
  <div className="space-y-1.5">
   <GeneratorSettingRow icon={Layers3} label="Tipo de malha" value={meshLabel} open={openCard==='mesh'} onToggle={()=>setOpenCard(openCard==='mesh'?null:'mesh')}><GeneratorOptionGrid values={[{value:'TEXTURED',label:'Texturizada'},{value:'LOW_POLY',label:'Low poly'},{value:'GEOMETRY',label:'Somente geometria'}]} current={meshMode} onSelect={value=>{setMeshMode(value as any);invalidate()}}/></GeneratorSettingRow>
   <GeneratorSettingRow icon={Grid3X3} label="Topologia" value={topologyLabel} open={openCard==='topology'} onToggle={()=>setOpenCard(openCard==='topology'?null:'topology')} semantic="ratio"><GeneratorOptionGrid values={[{value:'TRIANGLE',label:'Triângulos'},{value:'QUAD',label:'Quads'}]} current={topology} onSelect={value=>{setTopology(value as any);invalidate()}}/></GeneratorSettingRow>
   <GeneratorSettingRow icon={Boxes} label="Faces alvo" value={targetFaces.toLocaleString('pt-BR')} open={openCard==='faces'} onToggle={()=>setOpenCard(openCard==='faces'?null:'faces')} semantic="outputs"><GeneratorRangeSlider min={40000} max={1500000} step={20000} value={targetFaces} onChange={value=>{setTargetFaces(value);invalidate()}} headline={targetFaces.toLocaleString('pt-BR')} subtitle="densidade aproximada da malha"/></GeneratorSettingRow>
  </div>
  <GeneratorToggle checked={pbr} disabled={meshMode==='GEOMETRY'} onChange={value=>{setPbr(value);invalidate()}} label="Materiais PBR" description="Gera materiais físicos quando suportado."/>
  {job&&<section className="ia-stable-current"><div className="flex items-center justify-between"><div><span className="text-[8px] text-zinc-600">Resultado atual</span><strong className="block text-[10px] text-white">{status}</strong></div>{job.status==='SUCCEEDED'?<CheckCircle2 className="w-4 h-4 text-cyan-300"/>:<Box className="w-4 h-4 text-cyan-300"/>}</div>{job.quote&&<p>Modelo executado: <strong>{job.quote.selected_model_id}</strong> · {job.quote.routing_mode==='AUTO'?'roteamento AUTO':'modelo específico'}.</p>}{job.status==='FAILED'&&<p>{job.error_message||'A geração 3D não pôde ser concluída.'}</p>}{job.status==='SUCCEEDED'&&result?.public_url&&<><StableModel3DPreview url={result.public_url} label={result.name}/><a className="mt-2 h-9 rounded-lg border border-white/[0.07] bg-white/[0.035] px-3 flex items-center justify-center gap-2 text-[9px] font-semibold text-zinc-300" href={result.public_url} target="_blank" rel="noreferrer"><Download className="w-3 h-3"/>Abrir GLB</a></>}</section>}
 </GeneratorScroll><GeneratorFooter error={error} price={price} balance={balance} hasBalance={!insufficient} primaryLabel={footer.label} onPrimary={()=>void footer.onClick()} primaryDisabled={footer.disabled} primaryBusy={busy==='quote'||busy==='generate'} secondaryLabel={footer.secondary} onSecondary={footer.onSecondary?()=>void footer.onSecondary?.():undefined} secondaryDisabled={Boolean(busy)}/></GeneratorPanel>;
 return <MobileStudioLayout activeCount={mobileActiveCount} creator={creator} gallery={<CreationGallery defaultFilter="THREE_D" title="Minhas criações" subtitle="Todo o histórico de criações do seu studio." onActiveCountChange={setMobileActiveCount}/>}/>;
};
export default ThreeDCreateView;
