import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{Asset,Generation,GenerationRequestDraft,ModelRegistryItem,PricingEntry,WorkspaceReference}from'../../types/index.js';
import{workspaceService}from'../../services/workspaceService.js';
import{assetService}from'../../services/assetService.js';
import{generationClient}from'../../services/generationClient.js';
import{getModelCapabilities}from'../../services/modelCapabilities.js';
import{DEFAULT_PRESERVATION_RULES}from'../../config/constants.js';
import{STUDIO_FALLBACK_MODELS,STUDIO_FALLBACK_PRICING}from'../../config/studioCatalog.js';
import{useAuth}from'../../context/AuthContext.js';
import{AssetPickerContentView,AssetPickerModal}from'../workspace/AssetPickerModal.js';
import{CreationGallery}from'../workspace/CreationGallery.js';
import{UnifiedImageCreatorPanel}from'../workspace/UnifiedImageCreatorPanel.js';

interface Props{onUseImageForVideo?:(asset:Asset)=>void;initialEditAsset?:Asset|null;}
type SelectionMode='AUTO'|'MANUAL';
const terminal=(s:string)=>['SUCCEEDED','FAILED','CANCELLED','REFUNDED'].includes(s);
const FALLBACK_IMAGE_MODELS=STUDIO_FALLBACK_MODELS.filter(m=>m.category==='IMAGE'&&m.status!=='INACTIVE');
const resolutionRank=(v:string)=>({'1K':1,'1.5K':1.5,'2K':2,'4K':4}[v.toUpperCase()]||0);
function localAlias(refs:WorkspaceReference[]){const used=new Set(refs.map(r=>r.alias_snapshot.toLowerCase()));let i=1;while(used.has(`img${i}`))i++;return`img${i}`;}
function referenceFor(asset:Asset,refs:WorkspaceReference[],alias?:string):WorkspaceReference{const d=DEFAULT_PRESERVATION_RULES.GENERIC;return{asset_id:asset.asset_id,alias_snapshot:alias||localAlias(refs),role:'GENERAL',priority:'HIGH',preservation_rules:d.preserve,flexible_rules:d.flexible,asset};}
function ratioFromAsset(asset:Asset){if(!asset.width||!asset.height)return'1:1';const gcd=(a:number,b:number):number=>b?gcd(b,a%b):a,d=gcd(asset.width,asset.height);return`${Math.round(asset.width/d)}:${Math.round(asset.height/d)}`;}

export const UnifiedImageCreateView:React.FC<Props>=({onUseImageForVideo,initialEditAsset})=>{
 const{wallet,refreshWallet}=useAuth();
 const[models,setModels]=useState<ModelRegistryItem[]>(FALLBACK_IMAGE_MODELS),[pricing,setPricing]=useState<PricingEntry[]>(STUDIO_FALLBACK_PRICING),[assets,setAssets]=useState<Asset[]>([]),[favoriteModelIds,setFavoriteModelIds]=useState<string[]>([]),[recentModelIds,setRecentModelIds]=useState<string[]>([]),[selectionMode,setSelectionMode]=useState<SelectionMode>('AUTO'),[manualModelId,setManualModelId]=useState(FALLBACK_IMAGE_MODELS[0]?.model_id||''),[prompt,setPrompt]=useState(''),[references,setReferences]=useState<WorkspaceReference[]>([]),[aspectRatio,setAspectRatio]=useState('1:1'),[resolution,setResolution]=useState('1K'),[numberOfOutputs,setNumberOfOutputs]=useState(1),[seed,setSeed]=useState<number|''>(''),[showAdvanced,setShowAdvanced]=useState(false),[pickerOpen,setPickerOpen]=useState(false),[pickerView,setPickerView]=useState<AssetPickerContentView>('ASSETS'),[generating,setGenerating]=useState(false),[generation,setGeneration]=useState<Generation|null>(null),[error,setError]=useState(''),[unitPricesByModelId,setUnitPricesByModelId]=useState<Record<string,number|null>>({}),[priceLoadingModelIds,setPriceLoadingModelIds]=useState<string[]>([]),[uploadBusy,setUploadBusy]=useState(false);
 const pollRef=useRef<any>(null),quoteSeq=useRef(0),quoteCache=useRef(new Map<string,number>());
 useEffect(()=>{let mounted=true;Promise.all([workspaceService.listModels().catch(()=>[]),workspaceService.listPricing().catch(()=>[]),assetService.listAssets().catch(()=>[]),workspaceService.getUserPreferences().catch(()=>({favorite_model_ids:[],recent_model_ids:[]}as any))]).then(([mr,pr,ar,prefs])=>{if(!mounted)return;const imageModels=mr.filter(m=>m.category==='IMAGE'&&m.status!=='INACTIVE');if(imageModels.length){setModels(imageModels);setManualModelId(c=>imageModels.some(m=>m.model_id===c)?c:imageModels[0].model_id);}if(pr.length)setPricing(pr);setAssets(ar||[]);setFavoriteModelIds(prefs.favorite_model_ids||[]);setRecentModelIds(prefs.recent_model_ids||[]);});return()=>{mounted=false;if(pollRef.current)clearTimeout(pollRef.current);};},[]);
 const editImage=useCallback((asset:Asset)=>{setError('');setSelectionMode('AUTO');setPrompt('');setReferences([referenceFor(asset,[])]);setAspectRatio(ratioFromAsset(asset));setNumberOfOutputs(1);window.scrollTo({top:0,behavior:'smooth'});},[]);
 useEffect(()=>{if(initialEditAsset?.type==='IMAGE')editImage(initialEditAsset);},[initialEditAsset?.asset_id,editImage]);
 const mode=references.length?'IMAGE_TO_IMAGE':'TEXT_TO_IMAGE';
 const baseCompatibleModels=useMemo(()=>models.filter(model=>{const caps=getModelCapabilities(model);return model.supported_modes.includes(mode)&&model.supported_aspect_ratios.includes(aspectRatio)&&(!references.length||(caps.supports_image_reference&&references.length<=caps.max_reference_images));}),[models,mode,aspectRatio,references.length]);
 const manualModel=models.find(m=>m.model_id===manualModelId)||models[0]||null;
 const availableResolutions=useMemo(()=>{const values=selectionMode==='MANUAL'&&manualModel?manualModel.supported_resolutions:Array.from(new Set(baseCompatibleModels.flatMap(m=>m.supported_resolutions||[])));return[...values].sort((a,b)=>resolutionRank(a)-resolutionRank(b));},[selectionMode,manualModel,baseCompatibleModels]);
 useEffect(()=>{if(availableResolutions.length&&!availableResolutions.includes(resolution))setResolution(availableResolutions.includes('1K')?'1K':availableResolutions[0]);},[availableResolutions,resolution]);
 const compatibleModels=useMemo(()=>baseCompatibleModels.filter(m=>m.supported_resolutions.includes(resolution)),[baseCompatibleModels,resolution]);
 const livePricesByModelId=useMemo(()=>{const out:Record<string,number|null>={};models.forEach(m=>{const unit=unitPricesByModelId[m.model_id];out[m.model_id]=unit==null?null:unit*Math.max(1,numberOfOutputs);});return out;},[models,unitPricesByModelId,numberOfOutputs]);
 const autoModel=useMemo(()=>[...compatibleModels].sort((a,b)=>(livePricesByModelId[a.model_id]??Number.MAX_SAFE_INTEGER)-(livePricesByModelId[b.model_id]??Number.MAX_SAFE_INTEGER)||a.name.localeCompare(b.name))[0]||null,[compatibleModels,livePricesByModelId]);
 const activeModel=selectionMode==='AUTO'?autoModel:manualModel;
 const activeCaps=activeModel?getModelCapabilities(activeModel):null;
 const selectedCompatible=Boolean(activeModel&&compatibleModels.some(m=>m.model_id===activeModel.model_id));
 const maxReferences=selectionMode==='AUTO'?Math.max(0,...models.map(m=>getModelCapabilities(m).max_reference_images)):activeCaps?.max_reference_images||0;
 const unitPrice=activeModel?unitPricesByModelId[activeModel.model_id]??null:null,estimatedPrice=unitPrice==null?null:unitPrice*Math.max(1,numberOfOutputs),quoteLoading=Boolean(activeModel&&priceLoadingModelIds.includes(activeModel.model_id)),balance=(wallet as any)?.available_credits??wallet?.available_balance_cents??0,hasBalance=estimatedPrice!=null&&balance>=estimatedPrice;
 const quoteUnitPrice=async(model:ModelRegistryItem)=>{const preview=await generationClient.quote({model_id:model.model_id,mode,prompt:prompt.trim()||'pricing preview',references,settings:{duration_seconds:1,resolution,aspect_ratio:aspectRatio,number_of_outputs:1,seed:typeof seed==='number'?seed:null}});const d:any=preview.request_draft,unit=Number(d.unit_credit_price??d.retail_credit_price??d.estimated_cost_cents);if(!Number.isFinite(unit)||unit<=0)throw new Error('Preço unitário indisponível.');return unit;};
 useEffect(()=>{const seq=++quoteSeq.current,compatibleIds=new Set(compatibleModels.map(m=>m.model_id)),baseline:Record<string,number|null>={},missing:ModelRegistryItem[]=[];models.forEach(m=>{if(!compatibleIds.has(m.model_id)){baseline[m.model_id]=null;return;}const key=`${m.model_id}|${mode}|${resolution}|${aspectRatio}|${references.length}`,cached=quoteCache.current.get(key);if(cached!=null)baseline[m.model_id]=cached;else{baseline[m.model_id]=unitPricesByModelId[m.model_id]??null;missing.push(m);}});setUnitPricesByModelId(baseline);setPriceLoadingModelIds(missing.map(m=>m.model_id));if(!missing.length)return;const timer=window.setTimeout(async()=>{const next={...baseline};await Promise.all(missing.map(async model=>{const key=`${model.model_id}|${mode}|${resolution}|${aspectRatio}|${references.length}`;try{const unit=await quoteUnitPrice(model);quoteCache.current.set(key,unit);next[model.model_id]=unit;}catch{next[model.model_id]=null;}}));if(seq!==quoteSeq.current)return;setUnitPricesByModelId(next);setPriceLoadingModelIds([]);},120);return()=>window.clearTimeout(timer);},[models,compatibleModels,mode,resolution,aspectRatio,references.length]);
 const selectModel=async(model:ModelRegistryItem)=>{setSelectionMode('MANUAL');setManualModelId(model.model_id);const p=await workspaceService.trackRecentModel(model.model_id,mode).catch(()=>null);if(p)setRecentModelIds(p.recent_model_ids||[]);};
 const toggleFavorite=async(id:string)=>{const p=await workspaceService.toggleFavoriteModel(id).catch(()=>null);if(p)setFavoriteModelIds(p.favorite_model_ids||[]);};
 const addReference=(asset:Asset)=>setReferences(prev=>prev.some(r=>r.asset_id===asset.asset_id)||prev.length>=maxReferences?prev:[...prev,referenceFor(asset,prev)]);
 const removeReference=(id:string)=>setReferences(prev=>prev.filter(r=>r.asset_id!==id));
 const openPicker=(view:AssetPickerContentView='ASSETS')=>{setPickerView(view);setPickerOpen(true);};
 const quickUpload=useCallback(async(files:File[])=>{const images=files.filter(f=>f.type.startsWith('image/'));if(!images.length)return;setUploadBusy(true);try{for(const file of images){const asset=await assetService.uploadAsset({file,category:'GENERIC'});setAssets(prev=>[asset,...prev.filter(x=>x.asset_id!==asset.asset_id)]);setReferences(prev=>prev.some(r=>r.asset_id===asset.asset_id||prev.length>=maxReferences)?prev:[...prev,referenceFor(asset,prev)]);}}catch(e:any){setError(e?.message||'Não foi possível enviar a imagem.');}finally{setUploadBusy(false);}},[maxReferences]);
 useEffect(()=>{const onPaste=(e:ClipboardEvent)=>{const files=Array.from(e.clipboardData?.files||[]).filter(f=>f.type.startsWith('image/'));if(files.length)void quickUpload(files);};window.addEventListener('paste',onPaste);return()=>window.removeEventListener('paste',onPaste);},[quickUpload]);
 const restoreGeneration=(saved:Generation)=>{setError('');setSelectionMode('MANUAL');setManualModelId(saved.model_id);setPrompt(saved.original_prompt||'');setAspectRatio(saved.aspect_ratio||'1:1');setResolution(saved.resolution||'1K');setNumberOfOutputs(saved.number_of_outputs||1);setSeed(saved.seed??'');const restored:WorkspaceReference[]=[];(saved.references||[]).forEach((snapshot,index)=>{const asset=assets.find(a=>a.asset_id===snapshot.asset_id);if(asset)restored.push(referenceFor(asset,restored,snapshot.alias||`img${index+1}`));});setReferences(restored);window.scrollTo({top:0,behavior:'smooth'});};
 const refreshAssets=async()=>{const rows=await assetService.listAssets().catch(()=>[]);if(rows.length)setAssets(rows);};
 const poll=(id:string)=>{pollRef.current=setTimeout(async()=>{try{const next=await generationClient.get(id);setGeneration(next);window.dispatchEvent(new CustomEvent('generation:updated',{detail:next}));if(next.status==='SUCCEEDED'){await Promise.all([refreshAssets(),refreshWallet()]);setGenerating(false);return;}if(terminal(next.status)){setGenerating(false);if(next.status==='FAILED')setError(next.error_message||'A geração falhou.');return;}poll(id);}catch(e:any){setGenerating(false);setError(e?.message||'Falha ao consultar a geração.');}},2200);};
 const generate=async()=>{setError('');if(!prompt.trim())return setError('Descreva a imagem que deseja criar.');if(!activeModel||!selectedCompatible)return setError('Escolha uma IA compatível ou use Auto para encontrar uma rota válida.');if(quoteLoading||estimatedPrice==null)return setError('Aguarde o preço da configuração antes de gerar.');if(!hasBalance)return setError('Créditos insuficientes para esta geração.');try{setGenerating(true);const preview=await generationClient.quote({model_id:activeModel.model_id,mode,prompt:prompt.trim(),references,settings:{duration_seconds:1,resolution,aspect_ratio:aspectRatio,number_of_outputs:numberOfOutputs,seed:typeof seed==='number'?seed:null}}),draft:any=preview.request_draft,current=Number(draft.retail_credit_price??draft.estimated_cost_cents);if(current!==estimatedPrice){setGenerating(false);return setError(`O preço fixo foi atualizado. Nenhum crédito foi cobrado.`);}const started=await generationClient.create(draft as GenerationRequestDraft);setGeneration(started);window.dispatchEvent(new CustomEvent('generation:updated',{detail:started}));if(terminal(started.status)){setGenerating(false);if(started.status==='SUCCEEDED')await Promise.all([refreshAssets(),refreshWallet()]);else setError(started.error_message||'A geração não pôde ser concluída.');}else poll(started.generation_id);}catch(e:any){setGenerating(false);setError(e?.message||'Não foi possível iniciar a geração.');}};
 const useForVideo=async(asset:Asset)=>{try{const d=DEFAULT_PRESERVATION_RULES.GENERIC;await workspaceService.saveDraft({model_id:'AUTO',mode:'IMAGE_TO_VIDEO',prompt:'',references:[{asset_id:asset.asset_id,alias_snapshot:'img1',role:'START_FRAME',priority:'HIGH',preservation_rules:d.preserve,flexible_rules:d.flexible,asset}],settings:{duration_seconds:5,resolution:'720p',aspect_ratio:ratioFromAsset(asset),number_of_outputs:1}});onUseImageForVideo?.(asset);}catch(e:any){setError(e?.message||'Não foi possível preparar esta imagem para vídeo.');}};
 return <div className="flex h-full min-h-0 bg-[#0b0e13]">
  <UnifiedImageCreatorPanel models={models} pricing={pricing} selectionMode={selectionMode} selectedModelId={manualModelId} autoResolvedModel={autoModel} onSelectAuto={()=>setSelectionMode('AUTO')} onSelectModel={selectModel} favoriteModelIds={favoriteModelIds} recentModelIds={recentModelIds} onToggleFavorite={toggleFavorite} references={references} onOpenPicker={()=>openPicker('ASSETS')} onRemoveReference={removeReference} onQuickUpload={quickUpload} uploadBusy={uploadBusy} prompt={prompt} onChangePrompt={setPrompt} aspectRatio={aspectRatio} onChangeAspectRatio={setAspectRatio} resolution={resolution} onChangeResolution={setResolution} numberOfOutputs={numberOfOutputs} onChangeNumberOfOutputs={setNumberOfOutputs} availableResolutions={availableResolutions} activeModel={activeModel} showAdvanced={showAdvanced} onToggleAdvanced={()=>setShowAdvanced(v=>!v)} seed={seed} onChangeSeed={setSeed} totalPrice={estimatedPrice} unitPrice={unitPrice} balance={balance} hasBalance={hasBalance} generating={generating} priceLoading={quoteLoading} onGenerate={generate} error={error} livePricesByModelId={livePricesByModelId} priceLoadingModelIds={priceLoadingModelIds}/>
  <CreationGallery defaultFilter="IMAGE" title="Minhas criações" subtitle="Imagens, vídeos e histórico do seu studio." liveGeneration={generation} onRestoreGeneration={restoreGeneration} onUseImageAsReference={addReference} onEditImage={editImage} onCreateVideoFromImage={useForVideo}/>
  <AssetPickerModal isOpen={pickerOpen} onClose={()=>setPickerOpen(false)} availableAssets={assets} onSelectAsset={addReference} onAssetUploaded={asset=>setAssets(prev=>[asset,...prev.filter(i=>i.asset_id!==asset.asset_id)])} attachedAssetIds={references.map(r=>r.asset_id)} title="Adicionar referência à imagem" subtitle="Escolha mídia, personagem, produto ou estilo sem repetir etapas." defaultTab="LIBRARY" defaultContentView={pickerView} allowedTypes={['IMAGE']}/>
 </div>;
};
