import React,{useCallback,useEffect,useMemo,useState}from'react';
import{CheckCircle2,LoaderCircle,RefreshCw,Sparkles,Upload,Video,VideoIcon,WandSparkles}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{editorClient,EditorCapability,EditorJobView}from'../../services/editorClient.js';
import{Asset}from'../../types/index.js';
import{CreationGallery}from'../workspace/CreationGallery.js';

type Tool=Extract<EditorCapability,'video-extend'|'video-edit'>;
const TOOLS:Array<{id:Tool;label:string;description:string;icon:React.ComponentType<{className?:string}>}>=[
 {id:'video-extend',label:'Estender vídeo',description:'Continue um vídeo preservando a continuidade.',icon:VideoIcon},
 {id:'video-edit',label:'Editar vídeo',description:'Transforme o vídeo a partir de instruções.',icon:WandSparkles},
];
const errorText=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir esta operação.';
const status=(job:EditorJobView|null)=>job?.status==='SUCCEEDED'?'Concluído':job?.status==='FAILED'?'Falhou':job?.status==='RUNNING'?'Processando':job?.status==='QUEUED'?'Na fila':job?.status==='QUOTED'?'Preço calculado':'Preparando';

export const VideoEditorView:React.FC=()=>{
 const{wallet,refreshWallet}=useAuth();
 const[tool,setTool]=useState<Tool>('video-edit'),[models,setModels]=useState<any[]>([]),[videos,setVideos]=useState<Asset[]>([]),[sourceVideoId,setSourceVideoId]=useState(''),[modelId,setModelId]=useState('AUTO'),[prompt,setPrompt]=useState(''),[duration,setDuration]=useState(5),[resolution,setResolution]=useState('720p'),[aspectRatio,setAspectRatio]=useState('16:9'),[audioEnabled,setAudioEnabled]=useState(true),[job,setJob]=useState<EditorJobView|null>(null),[result,setResult]=useState<Asset|null>(null),[busy,setBusy]=useState('load'),[error,setError]=useState(''),[pollCount,setPollCount]=useState(0);
 const load=useCallback(async()=>{setBusy(current=>current||'load');setError('');try{const[catalog,assets]=await Promise.all([editorClient.catalog(),assetService.listAssets({type:'VIDEO'})]);setModels(catalog.filter(model=>model.capabilities.some((cap:any)=>TOOLS.some(tool=>tool.id===cap.id))));setVideos(assets);setSourceVideoId(current=>current||assets[0]?.asset_id||'');}catch(err){setError(errorText(err));}finally{setBusy(current=>current==='load'?'':current);}},[]);
 useEffect(()=>{void load();},[load]);
 const eligibleModels=useMemo(()=>models.filter(model=>model.capabilities.some((cap:any)=>cap.id===tool)),[models,tool]);
 useEffect(()=>{if(!eligibleModels.some(model=>model.model_id===modelId))setModelId(eligibleModels.find(model=>model.model_id==='AUTO')?.model_id||eligibleModels[0]?.model_id||'');},[eligibleModels,modelId]);
 const model=eligibleModels.find(item=>item.model_id===modelId)||eligibleModels.find(item=>item.model_id==='AUTO')||eligibleModels[0]||null;
 const capability=model?.capabilities.find((cap:any)=>cap.id===tool)||null;
 const controls=new Set<string>(capability?.controls||[]),durationOptions=capability?.supported_durations?.length?capability.supported_durations:[5],resolutionOptions=capability?.supported_resolutions?.length?capability.supported_resolutions:['720p'],ratioOptions=capability?.supported_aspect_ratios?.length?capability.supported_aspect_ratios:['16:9'];
 const source=videos.find(asset=>asset.asset_id===sourceVideoId)||null;
 const invalidate=()=>{setJob(null);setResult(null);setPollCount(0);setError('');};
 useEffect(()=>{invalidate();},[tool,modelId,sourceVideoId]);
 useEffect(()=>{if(controls.has('duration')&&!durationOptions.includes(duration))setDuration(durationOptions[0]||5);if(controls.has('resolution')&&!resolutionOptions.includes(resolution))setResolution(resolutionOptions[0]||'720p');if(controls.has('aspect_ratio')&&!ratioOptions.includes(aspectRatio))setAspectRatio(ratioOptions[0]||'16:9');},[capability?.id]);
 useEffect(()=>{if(!job||!['QUEUED','RUNNING'].includes(job.status)||pollCount>=180)return;const timer=window.setTimeout(async()=>{try{setJob(await editorClient.get(job.job_id));setPollCount(v=>v+1);}catch(err){setError(errorText(err));setPollCount(180);}},Math.min(7000,1800+pollCount*110));return()=>window.clearTimeout(timer);},[job,pollCount]);
 useEffect(()=>{if(job?.status!=='SUCCEEDED')return;void refreshWallet();const id=job.result_asset_ids?.[0];if(id)void editorClient.asset(id).then(setResult).catch(()=>setResult(null));window.dispatchEvent(new CustomEvent('creations:updated',{detail:{kind:'VIDEO',asset_ids:job.result_asset_ids||[]}}));},[job?.status,job?.result_asset_ids,refreshWallet]);
 const upload=async(event:React.ChangeEvent<HTMLInputElement>)=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy('upload');try{const asset=await assetService.uploadAsset({file,name:file.name});setVideos(rows=>[asset,...rows.filter(row=>row.asset_id!==asset.asset_id)]);setSourceVideoId(asset.asset_id);invalidate();}catch(err){setError(errorText(err));}finally{setBusy('');}};
 const buildRequest=()=>{if(!source)throw new Error('Selecione um vídeo de origem.');if(!model)throw new Error('Nenhum modelo elegível está disponível.');if(tool==='video-edit'&&!prompt.trim())throw new Error('Descreva a edição desejada.');const requestControls:any={output_format:'mp4',audio_enabled:audioEnabled,number_of_outputs:1};if(controls.has('duration'))requestControls.duration_seconds=duration;if(controls.has('resolution'))requestControls.resolution=resolution;if(controls.has('aspect_ratio'))requestControls.aspect_ratio=aspectRatio;return{capability_id:tool,model_id:model.model_id,prompt:prompt.trim(),references:[{asset_id:source.asset_id,slot_type:'GENERAL',role:'SOURCE'}],controls:requestControls};};
 const quote=async()=>{setBusy('quote');setError('');try{const created=await editorClient.create(buildRequest());setJob(await editorClient.quote(created.job_id));setPollCount(0);}catch(err){setError(errorText(err));}finally{setBusy('');}};
 const execute=async()=>{if(!job)return;setBusy('execute');setError('');try{setJob(await editorClient.queue(job.job_id));setPollCount(0);}catch(err){setError(errorText(err));}finally{setBusy('');}};
 const price=job?.quote?.credit_price??null,balance=wallet?.available_credits??0,insufficient=price!=null&&balance<price;
 return <div className="flex h-full min-h-0 flex-col xl:flex-row bg-[#080c12]">
  <section className="w-full xl:w-[46%] min-h-0 overflow-y-auto border-b xl:border-b-0 xl:border-r border-white/[0.06] p-4 sm:p-5 lg:p-6 space-y-4">
   <header><span className="text-[9px] font-bold uppercase tracking-[.18em] text-cyan-300">Editor de vídeo</span><h1 className="mt-1 text-xl font-bold text-white">Estenda ou transforme seus vídeos.</h1><p className="mt-1 text-[11px] text-zinc-500">O original é preservado. Cada execução cria um novo asset na Biblioteca.</p></header>
   <div className="grid grid-cols-2 gap-2">{TOOLS.map(item=>{const Icon=item.icon;return <button key={item.id} onClick={()=>setTool(item.id)} className={`rounded-xl border p-3 text-left ${tool===item.id?'border-cyan-300/25 bg-cyan-300/[0.08]':'border-white/[0.07] bg-white/[0.025]'}`}><Icon className="w-4 h-4 text-cyan-200"/><strong className="mt-2 block text-[10px] text-zinc-200">{item.label}</strong><small className="block mt-1 text-[8px] leading-relaxed text-zinc-600">{item.description}</small></button>})}</div>
   <div className="grid gap-2 sm:grid-cols-[1fr_auto]"><select value={sourceVideoId} onChange={e=>setSourceVideoId(e.target.value)} className="h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-[10px] text-zinc-300"><option value="">Selecione da Biblioteca</option>{videos.map(asset=><option key={asset.asset_id} value={asset.asset_id}>{asset.name}</option>)}</select><label className="h-10 px-3 rounded-xl border border-white/[0.08] flex items-center gap-2 text-[10px] text-zinc-300 cursor-pointer"><Upload className="w-3.5 h-3.5"/>{busy==='upload'?'Enviando':'Upload'}<input className="hidden" type="file" accept="video/*" onChange={upload}/></label></div>
   <div className="min-h-[260px] rounded-2xl border border-white/[0.07] bg-black/30 overflow-hidden grid place-items-center">{source?.public_url?<video src={source.public_url} controls preload="metadata" className="w-full max-h-[420px]"/>:<div className="text-zinc-700 text-center"><Video className="w-8 h-8 mx-auto"/><span className="text-[9px]">Selecione um vídeo</span></div>}</div>
   <label className="block text-[9px] text-zinc-500">IA / modelo<select value={model?.model_id||''} onChange={e=>{setModelId(e.target.value);invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300">{eligibleModels.map(item=><option key={item.model_id} value={item.model_id}>{item.model_id==='AUTO'?'AUTO · Melhor modelo disponível':item.name}</option>)}</select></label>
   <textarea rows={5} value={prompt} onChange={e=>{setPrompt(e.target.value);invalidate();}} placeholder={tool==='video-extend'?'Opcional: descreva como o vídeo deve continuar…':'Ex.: transforme a cena em um pôr do sol cinematográfico, preservando o personagem…'} className="w-full rounded-xl bg-white/[0.035] border border-white/[0.07] p-3 text-[11px] text-zinc-200 outline-none"/>
   <div className="grid sm:grid-cols-2 gap-2">{controls.has('duration')&&<label className="text-[9px] text-zinc-500">Duração<select value={duration} onChange={e=>{setDuration(Number(e.target.value));invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300">{durationOptions.map((value:number)=><option key={value} value={value}>{value}s</option>)}</select></label>}{controls.has('resolution')&&<label className="text-[9px] text-zinc-500">Resolução<select value={resolution} onChange={e=>{setResolution(e.target.value);invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300">{resolutionOptions.map((value:string)=><option key={value}>{value}</option>)}</select></label>}{controls.has('aspect_ratio')&&<label className="text-[9px] text-zinc-500">Formato<select value={aspectRatio} onChange={e=>{setAspectRatio(e.target.value);invalidate();}} className="mt-1 w-full h-10 rounded-xl bg-white/[0.035] border border-white/[0.07] px-3 text-zinc-300">{ratioOptions.map((value:string)=><option key={value}>{value}</option>)}</select></label>}<label className="flex items-center gap-2 text-[9px] text-zinc-400 mt-5"><input type="checkbox" checked={audioEnabled} onChange={e=>{setAudioEnabled(e.target.checked);invalidate();}}/>Preservar/gerar áudio quando suportado</label></div>
   {error&&<div className="rounded-xl border border-rose-400/15 bg-rose-400/[0.05] p-3 text-[10px] text-rose-300">{error}</div>}
   <div className="rounded-2xl border border-white/[0.07] bg-white/[0.025] p-4 flex flex-col sm:flex-row gap-3 sm:items-center sm:justify-between"><div><span className="text-[8px] uppercase tracking-wider text-zinc-600">Créditos</span><strong className="block text-[12px] text-white">{price==null?'Calcule antes de executar':`${price.toLocaleString('pt-BR')} créditos`}</strong>{price!=null&&<small className="text-[8px] text-zinc-600">Saldo: {balance.toLocaleString('pt-BR')}</small>}</div>{!job?.quote?<button onClick={()=>void quote()} disabled={Boolean(busy)||!model||!source} className="ia-button-primary h-10 px-4 text-[10px] font-bold flex items-center gap-2 justify-center">{busy==='quote'?<LoaderCircle className="w-4 h-4 animate-spin"/>:<Sparkles className="w-4 h-4"/>}Calcular créditos</button>:['DRAFT','QUOTED'].includes(job.status)?<div className="flex gap-2"><button onClick={()=>void quote()} className="h-10 px-3 rounded-xl border border-white/[0.08] text-[9px] text-zinc-400"><RefreshCw className="w-3.5 h-3.5"/></button><button onClick={()=>void execute()} disabled={Boolean(busy)||insufficient} className="ia-button-primary h-10 px-4 text-[10px] font-bold flex items-center gap-2">{busy==='execute'?<LoaderCircle className="w-4 h-4 animate-spin"/>:<WandSparkles className="w-4 h-4"/>}Executar</button></div>:<button disabled className="h-10 px-4 rounded-xl border border-white/[0.08] text-[9px] text-zinc-500">{status(job)}</button>}</div>
   {job?.status==='SUCCEEDED'&&result?.public_url&&<section className="rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.03] p-3"><div className="mb-2 flex items-center gap-2 text-[10px] text-emerald-300"><CheckCircle2 className="w-4 h-4"/>Resultado concluído</div><video src={result.public_url} controls preload="metadata" className="w-full rounded-xl"/></section>}
  </section>
  <section className="flex-1 min-h-[420px] xl:min-h-0"><CreationGallery defaultFilter="VIDEO" title="Minhas criações" subtitle="Histórico universal do IA Connect. Vídeos editados e estendidos aparecem aqui."/></section>
 </div>;
};
export default VideoEditorView;
