import React,{useEffect,useRef,useState}from'react';
import{Wallet,RotateCcw,FileText,Plus,Copy,CheckCircle2,X,Loader2,QrCode,Gift,Tag,ShieldCheck,Clock3,ArrowRight,ExternalLink}from'lucide-react';
import{useAuth}from'../../context/AuthContext.js';import{creditService}from'../../services/creditService.js';import{paymentClient,CouponQuote}from'../../services/paymentClient.js';import{PaymentRecord}from'../../types/index.js';import{CreditTransaction,PackVersion}from'../../types/credits.js';import{formatCentsToBRL}from'../../config/constants.js';
const terminal=(s:string)=>['CONFIRMED','FAILED','EXPIRED'].includes(s),credits=(v:number)=>`${Math.max(0,Number(v||0)).toLocaleString('pt-BR')} créditos`;const bonusPct=(p:PackVersion)=>p.base_credits>0?Math.round((p.bonus_credits/p.base_credits)*100):0;
const unitPerThousand=(p:PackVersion)=>Math.round((p.price_brl_cents/Math.max(1,p.total_credits))*1000);
const packPresentation=(id:string)=>({
 starter:{name:'Essencial',description:'Para testar o studio e fazer gerações pontuais.'},
 casual:{name:'Creator',description:'Para quem já produz conteúdo com frequência.'},
 popular:{name:'Pro',description:'Equilíbrio entre volume e custo por geração.'},
 professional:{name:'Studio',description:'Para produção recorrente e projetos maiores.'},
 power:{name:'Scale',description:'Maior volume e melhor eficiência por crédito.'},
}as Record<string,{name:string;description:string}>)[id]||{name:'Créditos',description:'Créditos para usar em qualquer modelo disponível.'};
export const WalletView:React.FC=()=>{const{wallet,refreshWallet}=useAuth(),[transactions,setTransactions]=useState<CreditTransaction[]>([]),[packs,setPacks]=useState<PackVersion[]>([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[rechargeOpen,setRechargeOpen]=useState(false),[redeemOpen,setRedeemOpen]=useState(false),[redeemCode,setRedeemCode]=useState(''),[redeemLoading,setRedeemLoading]=useState(false),[redeemMessage,setRedeemMessage]=useState(''),[selectedPack,setSelectedPack]=useState<PackVersion|null>(null),[creating,setCreating]=useState(false),[payment,setPayment]=useState<PaymentRecord|null>(null),[error,setError]=useState(''),[copied,setCopied]=useState(false),[nowMs,setNowMs]=useState(Date.now()),[couponCode,setCouponCode]=useState(''),[couponQuote,setCouponQuote]=useState<CouponQuote|null>(null),[couponLoading,setCouponLoading]=useState(false),[couponNotice,setCouponNotice]=useState(''),pollRef=useRef<any>(null);
 const load=async()=>{setLoading(true);try{const[t,p]=await Promise.all([creditService.listTransactions(50),creditService.listPacks()]);setTransactions(t.transactions);setPacks(p);if(!selectedPack&&p.length)setSelectedPack(p.find(x=>x.badge)||p[p.length-1]||p[0]);}finally{setLoading(false)}};useEffect(()=>{load().catch(console.error);return()=>{if(pollRef.current)clearTimeout(pollRef.current)}},[]);useEffect(()=>{if(!payment||terminal(payment.status))return;setNowMs(Date.now());const timer=window.setInterval(()=>setNowMs(Date.now()),1000);return()=>window.clearInterval(timer)},[payment?.payment_id,payment?.status]);const refresh=async()=>{setRefreshing(true);await Promise.all([refreshWallet(),load()]);setRefreshing(false)};const close=()=>{if(pollRef.current)clearTimeout(pollRef.current);setRechargeOpen(false);setPayment(null);setError('');setCopied(false);setCouponCode('');setCouponQuote(null);setCouponNotice('')};const poll=(id:string)=>{pollRef.current=setTimeout(async()=>{try{const p=await paymentClient.get(id);setPayment(p);if(p.status==='CONFIRMED'){await refresh();return}if(!terminal(p.status))poll(id)}catch{}},2500)};
 const choosePack=(pack:PackVersion)=>{setSelectedPack(pack);setCouponQuote(null);setCouponNotice('');setError('')};const applyCoupon=async()=>{if(!selectedPack||!couponCode.trim())return;setCouponLoading(true);setError('');setCouponNotice('');try{const inspected=await creditService.inspectCoupon(couponCode.trim(),selectedPack);if(inspected.redemption_mode==='DIRECT_CREDIT'){const result=await creditService.redeemCoupon(couponCode.trim());await refresh();setCouponCode('');setCouponQuote(null);setCouponNotice(`${Number(result.credits||0).toLocaleString('pt-BR')} créditos de presente foram adicionados à sua conta.`);return}setCouponQuote(inspected as CouponQuote)}catch(e:any){setCouponQuote(null);setError(e?.message||'Cupom inválido.')}finally{setCouponLoading(false)}};const removeCoupon=()=>{setCouponCode('');setCouponQuote(null);setCouponNotice('');setError('')};
 const smartRedeem=async()=>{if(!redeemCode.trim())return;setRedeemLoading(true);setRedeemMessage('');setError('');try{const inspected=await creditService.inspectCoupon(redeemCode.trim());if(inspected.redemption_mode==='CHECKOUT'){setRedeemOpen(false);setRechargeOpen(true);setCouponCode(redeemCode.trim().toUpperCase());setCouponQuote(null);setCouponNotice('Este código é aplicado durante uma compra. Escolha o pack e clique em Aplicar.');setRedeemCode('');return}const result=await creditService.redeemCoupon(redeemCode.trim());await refresh();setRedeemMessage(`${Number(result.credits||0).toLocaleString('pt-BR')} créditos adicionados com sucesso.`);setRedeemCode('')}catch(e:any){setRedeemMessage(e?.message||'Não foi possível resgatar este código.')}finally{setRedeemLoading(false)}};
 const createPix=async()=>{if(!selectedPack)return;setCreating(true);setError('');try{const p=await paymentClient.purchasePack(selectedPack.pack_id,selectedPack.version,couponQuote?.coupon?.code);setPayment(p);if(!terminal(p.status))poll(p.payment_id);else if(p.status==='CONFIRMED')await refresh()}catch(e:any){setError(e?.message||'Não foi possível criar o Pix.')}finally{setCreating(false)}};const copyPix=async()=>{if(!payment?.pix_code)return;await navigator.clipboard.writeText(payment.pix_code);setCopied(true);setTimeout(()=>setCopied(false),1800)};const positive=(t:string)=>['PURCHASE_ISSUE','PROMO_ISSUE','ADMIN_CREDIT','CREATOR_REWARD','MIGRATION_ISSUE','GENERATION_RELEASE'].includes(t);
 const checkoutCredits=selectedPack?selectedPack.total_credits+(couponQuote?.bonus_credits||0):0,checkoutAmount=selectedPack?(couponQuote?.final_amount_cents??selectedPack.price_brl_cents):0;
 const baselineUnit=packs.length?unitPerThousand(packs[0]):0,bestUnit=packs.length?Math.min(...packs.map(unitPerThousand)):0;
 const remainingSeconds=payment?.expires_at?Math.max(0,Math.floor((Date.parse(payment.expires_at)-nowMs)/1000)):0,remainingText=`${String(Math.floor(remainingSeconds/60)).padStart(2,'0')}:${String(remainingSeconds%60).padStart(2,'0')}`;
 return <div className="space-y-5 text-zinc-100"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><h1 className="text-xl font-bold text-white">Créditos</h1><p className="text-xs text-zinc-500 mt-1">Uma carteira para usar qualquer modelo disponível no IA Connect.</p></div><div className="flex flex-wrap gap-2"><button onClick={refresh} disabled={refreshing} className="h-9 px-3 rounded-xl border border-white/[0.08] bg-white/[0.035] text-[11px] text-zinc-300 flex items-center gap-2"><RotateCcw className={`w-3.5 h-3.5 ${refreshing?'animate-spin':''}`}/>Atualizar</button><button onClick={()=>{setRedeemMessage('');setRedeemOpen(true)}} className="h-9 px-3 rounded-xl border border-white/[0.08] bg-white/[0.035] text-[11px] text-zinc-200 flex items-center gap-2"><Tag className="w-3.5 h-3.5"/>Resgatar código</button><button onClick={()=>setRechargeOpen(true)} className="ia-primary h-9 px-4 rounded-xl text-[11px] font-bold flex items-center gap-2"><Plus className="w-3.5 h-3.5"/>Adicionar créditos</button></div></div>
 <div className="grid sm:grid-cols-3 gap-3"><div className="sm:col-span-2 p-5 rounded-2xl border border-sky-400/15 bg-gradient-to-br from-sky-400/[0.10] to-blue-500/[0.025]"><div className="flex items-center gap-2 text-zinc-400 text-[10px] uppercase tracking-wider"><Wallet className="w-4 h-4 text-sky-300"/>Disponível</div><div className="text-3xl font-black mt-3 tabular-nums text-white">{credits(wallet?.available_credits??0)}</div><p className="text-[10px] text-zinc-500 mt-2">Preço das gerações é mostrado em créditos antes do clique.</p></div><div className="p-5 rounded-2xl border border-white/[0.07] bg-[#08131e]"><p className="text-[10px] text-zinc-500 uppercase tracking-wider">Reservado</p><p className="text-xl font-bold mt-3 tabular-nums">{credits(wallet?.reserved_credits??0)}</p><p className="text-[10px] text-zinc-600 mt-2">Gerações em processamento.</p></div></div>
 <div className="rounded-2xl border border-white/[0.07] bg-[#08131e] overflow-hidden"><div className="px-5 py-4 border-b border-white/[0.06]"><h2 className="text-sm font-semibold">Movimentações</h2><p className="text-[10px] text-zinc-600 mt-0.5">Ledger de créditos</p></div>{loading?<div className="py-12 text-center text-xs text-zinc-600">Carregando...</div>:transactions.length===0?<div className="py-12 flex flex-col items-center text-zinc-600"><FileText className="w-5 h-5 mb-2"/><span className="text-xs">Nenhuma movimentação ainda.</span></div>:<div className="overflow-x-auto"><table className="w-full text-[11px]"><thead className="text-zinc-600 border-b border-white/[0.05]"><tr><th className="text-left font-medium px-5 py-3">Data</th><th className="text-left font-medium px-3 py-3">Tipo</th><th className="text-right font-medium px-5 py-3">Créditos</th></tr></thead><tbody className="divide-y divide-white/[0.045]">{transactions.map(tx=><tr key={tx.transaction_id}><td className="px-5 py-3 text-zinc-500 whitespace-nowrap">{new Date(tx.created_at).toLocaleString('pt-BR')}</td><td className="px-3 py-3 text-zinc-300">{tx.type.replaceAll('_',' ')}</td><td className={`px-5 py-3 text-right font-semibold tabular-nums ${positive(tx.type)?'text-sky-300':'text-zinc-200'}`}>{positive(tx.type)?'+':'-'} {Math.abs(tx.amount_credits).toLocaleString('pt-BR')}</td></tr>)}</tbody></table></div>}</div>
 {redeemOpen&&<div className="fixed inset-0 z-[125] bg-black/80 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#08131e] p-5"><div className="flex items-center justify-between"><div><h2 className="text-sm font-bold text-white">Resgatar código</h2><p className="text-[10px] text-zinc-500 mt-1">O IA Connect identifica automaticamente se o código concede créditos ou pertence a uma compra.</p></div><button onClick={()=>setRedeemOpen(false)} className="p-2 text-zinc-600 hover:text-white"><X className="w-4 h-4"/></button></div><div className="mt-4 flex gap-2"><input autoFocus value={redeemCode} onChange={e=>setRedeemCode(e.target.value.toUpperCase())} placeholder="Digite seu código" className="flex-1 h-10 px-3 rounded-xl bg-white/[0.035] border border-white/[0.08] text-xs text-white uppercase outline-none focus:border-sky-300/40"/><button onClick={smartRedeem} disabled={redeemLoading||!redeemCode.trim()} className="ia-primary h-10 px-4 rounded-xl text-[10px] font-black disabled:opacity-40">{redeemLoading?<Loader2 className="w-4 h-4 animate-spin"/>:'Resgatar'}</button></div>{redeemMessage&&<div className="mt-3 p-3 rounded-xl border border-white/[0.07] bg-white/[0.03] text-[10px] text-zinc-300">{redeemMessage}</div>}</div></div>}
 {rechargeOpen&&<div className="fixed inset-0 z-[120] bg-black/80 backdrop-blur-md flex items-center justify-center p-3 sm:p-5">
  <div className="w-full max-w-5xl max-h-[92vh] overflow-y-auto rounded-[24px] border border-white/[0.09] bg-[#07111b] shadow-[0_32px_100px_rgba(0,0,0,.65)]">
   <div className="sticky top-0 z-10 px-5 sm:px-6 py-4 border-b border-white/[0.06] bg-[#07111b]/95 backdrop-blur-xl flex items-start justify-between gap-4">
    <div>
     <div className="flex items-center gap-2"><div className="w-8 h-8 rounded-xl bg-sky-300/10 border border-sky-300/15 grid place-items-center"><Wallet className="w-4 h-4 text-sky-300"/></div><div><h2 className="text-[15px] font-black text-white">Comprar créditos</h2><p className="text-[10px] text-zinc-500 mt-0.5">Checkout seguro via Pix · confirmação automática</p></div></div>
     <div className="mt-3 flex items-center gap-2 text-[8px] font-bold uppercase tracking-[0.13em]">
      <span className={`px-2.5 py-1 rounded-full border ${!payment?'border-sky-300/25 bg-sky-300/10 text-sky-200':'border-emerald-300/20 bg-emerald-300/[0.07] text-emerald-300'}`}>1 · Plano</span>
      <span className="h-px w-5 bg-white/10"/>
      <span className={`px-2.5 py-1 rounded-full border ${payment&&payment.status!=='CONFIRMED'?'border-sky-300/25 bg-sky-300/10 text-sky-200':payment?.status==='CONFIRMED'?'border-emerald-300/20 bg-emerald-300/[0.07] text-emerald-300':'border-white/[0.06] text-zinc-700'}`}>2 · Pix</span>
      <span className="h-px w-5 bg-white/10"/>
      <span className={`px-2.5 py-1 rounded-full border ${payment?.status==='CONFIRMED'?'border-emerald-300/20 bg-emerald-300/[0.07] text-emerald-300':'border-white/[0.06] text-zinc-700'}`}>3 · Confirmação</span>
     </div>
    </div>
    <button onClick={close} aria-label="Fechar checkout" className="w-9 h-9 rounded-xl border border-white/[0.07] bg-white/[0.025] grid place-items-center text-zinc-500 hover:text-white hover:bg-white/[0.05]"><X className="w-4 h-4"/></button>
   </div>

   <div className="p-4 sm:p-6">
    {!payment?<div className="grid lg:grid-cols-[1.45fr_.8fr] gap-5">
     <div>
      <div className="mb-3"><h3 className="text-[13px] font-bold text-white">Escolha o volume de créditos</h3><p className="mt-1 text-[10px] text-zinc-600">Todos os créditos funcionam em qualquer IA disponível no studio. Packs maiores reduzem o custo efetivo por crédito.</p></div>
      <div className="grid sm:grid-cols-2 gap-3">
       {packs.map(pack=>{const selected=selectedPack?.pack_id===pack.pack_id&&selectedPack?.version===pack.version,pct=bonusPct(pack),unit=unitPerThousand(pack),saving=baselineUnit>0?Math.max(0,Math.round((1-unit/baselineUnit)*100)):0,meta=packPresentation(pack.pack_id),best=unit===bestUnit&&packs.length>1;return <button key={`${pack.pack_id}-${pack.version}`} onClick={()=>choosePack(pack)} className={`group relative min-h-[168px] p-4 rounded-2xl border text-left transition-all ${selected?'border-sky-300/55 bg-gradient-to-br from-sky-300/[0.12] to-blue-500/[0.035] shadow-[0_0_0_1px_rgba(125,211,252,.08),0_16px_40px_rgba(0,0,0,.22)]':'border-white/[0.07] bg-white/[0.022] hover:border-white/[0.14] hover:bg-white/[0.035]'}`}>
        <div className="flex items-start justify-between gap-3"><div><p className="text-[9px] font-bold uppercase tracking-[0.14em] text-zinc-500">{meta.name}</p><p className="mt-1.5 text-[20px] leading-none font-black text-white tabular-nums">{pack.total_credits.toLocaleString('pt-BR')}</p><p className="mt-1 text-[9px] text-zinc-600">créditos</p></div>{selected?<CheckCircle2 className="w-5 h-5 text-sky-300"/>:(pack.badge||best)?<span className={`px-2 py-1 rounded-full text-[7px] font-black uppercase tracking-wider ${pack.badge?'bg-sky-300 text-[#03121c]':'border border-emerald-300/20 bg-emerald-300/[0.07] text-emerald-300'}`}>{pack.badge||'Melhor custo'}</span>:null}</div>
        <p className="mt-3 text-[9px] leading-relaxed text-zinc-500">{meta.description}</p>
        <div className="mt-4 pt-3 border-t border-white/[0.06] flex items-end justify-between gap-3"><div><p className="text-[8px] text-zinc-700">Pagamento</p><p className="mt-0.5 text-[13px] font-black text-white">{formatCentsToBRL(pack.price_brl_cents)}</p></div><div className="text-right"><p className="text-[8px] text-zinc-700">por 1.000 cr.</p><p className="mt-0.5 text-[9px] font-bold text-zinc-400">{formatCentsToBRL(unit)}</p></div></div>
        {(pack.bonus_credits>0||saving>0)&&<div className="mt-2 flex flex-wrap gap-1.5">{pack.bonus_credits>0&&<span className="inline-flex items-center gap-1 rounded-md border border-emerald-300/15 bg-emerald-300/[0.05] px-2 py-1 text-[8px] font-bold text-emerald-300"><Gift className="w-3 h-3"/>+{pack.bonus_credits.toLocaleString('pt-BR')} bônus · +{pct}%</span>}{saving>0&&<span className="rounded-md border border-white/[0.06] bg-white/[0.025] px-2 py-1 text-[8px] font-semibold text-zinc-500">economia efetiva ~{saving}%</span>}</div>}
       </button>})}
      </div>
     </div>

     <aside className="lg:sticky lg:top-[108px] h-fit rounded-2xl border border-white/[0.08] bg-[#0a1622] overflow-hidden">
      <div className="p-4 border-b border-white/[0.06]"><p className="text-[9px] font-bold uppercase tracking-[0.13em] text-zinc-600">Resumo da compra</p>{selectedPack?<><div className="mt-3 flex items-start justify-between gap-3"><div><p className="text-[11px] font-bold text-white">{packPresentation(selectedPack.pack_id).name}</p><p className="mt-0.5 text-[9px] text-zinc-600">{selectedPack.total_credits.toLocaleString('pt-BR')} créditos do pack</p></div><p className="text-[12px] font-black text-white">{formatCentsToBRL(selectedPack.price_brl_cents)}</p></div></>:<p className="mt-3 text-[10px] text-zinc-600">Selecione um pack para continuar.</p>}</div>
      {selectedPack&&<div className="p-4 space-y-4">
       <div>
        <p className="text-[9px] font-semibold text-zinc-400 mb-2 flex items-center gap-1.5"><Tag className="w-3 h-3"/>Cupom</p>
        <div className="flex gap-2"><input value={couponCode} onChange={e=>{setCouponCode(e.target.value.toUpperCase());if(couponQuote)setCouponQuote(null);setCouponNotice('')}} disabled={Boolean(couponQuote)} placeholder="CÓDIGO" className="flex-1 min-w-0 h-10 px-3 rounded-xl border border-white/[0.08] bg-black/20 text-[10px] text-white uppercase outline-none focus:border-sky-300/35"/><button onClick={couponQuote?removeCoupon:applyCoupon} disabled={couponLoading||(!couponQuote&&!couponCode.trim())} className="h-10 px-3 rounded-xl border border-white/[0.08] bg-white/[0.04] text-[9px] font-bold text-zinc-200 disabled:opacity-40">{couponLoading?<Loader2 className="w-3.5 h-3.5 animate-spin"/>:couponQuote?'Remover':'Aplicar'}</button></div>
        {couponQuote&&<div className="mt-2 rounded-xl border border-emerald-300/15 bg-emerald-300/[0.055] px-3 py-2"><p className="text-[9px] font-bold text-emerald-200">Cupom {couponQuote.coupon.code} aplicado</p>{couponQuote.bonus_credits>0&&<p className="text-[8px] text-emerald-300 mt-1">+{couponQuote.bonus_credits.toLocaleString('pt-BR')} créditos extras</p>}{couponQuote.discount_cents>0&&<p className="text-[8px] text-emerald-300 mt-0.5">− {formatCentsToBRL(couponQuote.discount_cents)} no pagamento</p>}</div>}
        {couponNotice&&<div className="mt-2 rounded-xl border border-sky-300/15 bg-sky-300/[0.05] px-3 py-2 text-[8px] text-sky-200">{couponNotice}</div>}
       </div>
       <div className="space-y-2 text-[10px]"><div className="flex justify-between text-zinc-500"><span>Créditos</span><span className="text-zinc-300">{selectedPack.total_credits.toLocaleString('pt-BR')}</span></div>{couponQuote?.bonus_credits?<div className="flex justify-between text-emerald-300"><span>Bônus do cupom</span><span>+{couponQuote.bonus_credits.toLocaleString('pt-BR')}</span></div>:null}{couponQuote?.discount_cents?<div className="flex justify-between text-emerald-300"><span>Desconto</span><span>− {formatCentsToBRL(couponQuote.discount_cents)}</span></div>:null}<div className="pt-3 mt-1 border-t border-white/[0.07] flex items-end justify-between"><div><p className="text-[8px] text-zinc-600">Você recebe</p><p className="mt-0.5 text-[15px] font-black text-white">{checkoutCredits.toLocaleString('pt-BR')} cr.</p></div><div className="text-right"><p className="text-[8px] text-zinc-600">Total no Pix</p><p className="mt-0.5 text-[18px] font-black text-white">{formatCentsToBRL(checkoutAmount)}</p></div></div></div>
       <button onClick={createPix} disabled={creating||!selectedPack} className="ia-primary w-full h-12 rounded-xl font-black text-[11px] flex items-center justify-center gap-2 disabled:opacity-40">{creating?<Loader2 className="w-4 h-4 animate-spin"/>:<><QrCode className="w-4 h-4"/>Continuar para o Pix<ArrowRight className="w-3.5 h-3.5"/></>}</button>
       <div className="rounded-xl border border-white/[0.06] bg-black/15 p-3 flex items-start gap-2.5"><ShieldCheck className="w-4 h-4 shrink-0 text-emerald-300"/><div><p className="text-[9px] font-bold text-zinc-300">Pagamento seguro</p><p className="mt-0.5 text-[8px] leading-relaxed text-zinc-600">O pagamento é processado pelo Mercado Pago. Os créditos são liberados automaticamente após a confirmação.</p></div></div>
      </div>}
     </aside>
    </div>:payment.status==='CONFIRMED'?<div className="max-w-lg mx-auto py-10 text-center">
     <div className="w-16 h-16 mx-auto rounded-2xl border border-emerald-300/20 bg-emerald-300/[0.08] grid place-items-center"><CheckCircle2 className="w-8 h-8 text-emerald-300"/></div>
     <h3 className="mt-5 text-[20px] font-black text-white">Pagamento confirmado</h3>
     <p className="mt-2 text-[11px] leading-relaxed text-zinc-500">Os créditos já foram emitidos para sua conta e estão disponíveis para novas gerações.</p>
     <div className="mt-5 rounded-2xl border border-white/[0.07] bg-white/[0.02] p-4 flex items-center justify-between"><div className="text-left"><p className="text-[8px] uppercase tracking-wider text-zinc-600">Valor pago</p><p className="mt-1 text-[14px] font-black text-white">{formatCentsToBRL(payment.amount_cents)}</p></div><div className="text-right"><p className="text-[8px] uppercase tracking-wider text-zinc-600">Status</p><p className="mt-1 text-[10px] font-bold text-emerald-300">Créditos liberados</p></div></div>
     <button onClick={close} className="mt-5 ia-primary h-11 px-7 rounded-xl text-[11px] font-black">Voltar ao studio</button>
    </div>:payment.status==='FAILED'||payment.status==='EXPIRED'?<div className="max-w-lg mx-auto py-10 text-center">
     <div className="w-14 h-14 mx-auto rounded-2xl border border-rose-300/15 bg-rose-400/[0.06] grid place-items-center"><Clock3 className="w-6 h-6 text-rose-300"/></div>
     <h3 className="mt-4 text-[17px] font-black text-white">{payment.status==='EXPIRED'?'Pix expirado':'Pagamento não concluído'}</h3>
     <p className="mt-2 text-[10px] text-zinc-500">{payment.status==='EXPIRED'?'Esse código Pix não pode mais ser usado. Gere um novo para continuar.':'O gateway não confirmou este pagamento. Você pode tentar novamente sem alterar seu saldo.'}</p>
     <button onClick={()=>{setPayment(null);setError('');setCopied(false)}} className="mt-5 h-11 px-5 rounded-xl border border-white/[0.09] bg-white/[0.04] text-[10px] font-bold text-white">Gerar novo Pix</button>
    </div>:<div className="grid lg:grid-cols-[.85fr_1.15fr] gap-5 items-start">
     <section className="rounded-2xl border border-white/[0.08] bg-white/[0.02] p-5 text-center">
      <div className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full border border-amber-300/15 bg-amber-300/[0.06] text-[8px] font-bold text-amber-200"><span className="w-1.5 h-1.5 rounded-full bg-amber-300 animate-pulse"/>Aguardando pagamento</div>
      <h3 className="mt-3 text-[18px] font-black text-white">{formatCentsToBRL(payment.amount_cents)}</h3>
      <p className="mt-1 text-[9px] text-zinc-600">Escaneie o QR Code com o app do seu banco.</p>
      {payment.pix_qr_code_base64?<div className="mt-4 w-fit mx-auto p-3 rounded-2xl bg-white shadow-[0_18px_50px_rgba(0,0,0,.28)]"><img src={`data:image/png;base64,${payment.pix_qr_code_base64}`} className="w-52 h-52" alt="QR Code Pix"/></div>:<div className="mt-4 w-52 h-52 mx-auto rounded-2xl border border-dashed border-white/[0.08] grid place-items-center text-[9px] text-zinc-600">QR Code indisponível</div>}
      <div className="mt-4 inline-flex items-center gap-2 text-[9px] text-zinc-500"><Clock3 className="w-3.5 h-3.5"/><span>Expira em</span><strong className={`font-mono tabular-nums ${remainingSeconds<300?'text-amber-300':'text-zinc-300'}`}>{remainingText}</strong></div>
     </section>

     <section className="rounded-2xl border border-white/[0.08] bg-[#0a1622] overflow-hidden">
      <div className="p-5 border-b border-white/[0.06]"><p className="text-[9px] uppercase tracking-[0.13em] font-bold text-zinc-600">Pix copia e cola</p><p className="mt-1 text-[10px] text-zinc-500">Prefere pagar pelo computador? Copie o código e cole na área Pix do seu banco.</p></div>
      <div className="p-5 space-y-4">
       <div className="rounded-xl border border-white/[0.07] bg-black/20 p-3"><p className="max-h-20 overflow-y-auto break-all font-mono text-[9px] leading-relaxed text-zinc-400">{payment.pix_code||'Código Pix indisponível.'}</p></div>
       <button onClick={copyPix} disabled={!payment.pix_code} className={`w-full h-11 rounded-xl border text-[10px] font-black flex items-center justify-center gap-2 transition-all disabled:opacity-35 ${copied?'border-emerald-300/25 bg-emerald-300/[0.08] text-emerald-200':'border-sky-300/20 bg-sky-300/[0.08] text-sky-100 hover:bg-sky-300/[0.12]'}`}><Copy className="w-3.5 h-3.5"/>{copied?'Código copiado':'Copiar código Pix'}</button>
       {payment.checkout_url&&<a href={payment.checkout_url} target="_blank" rel="noreferrer" className="w-full h-10 rounded-xl border border-white/[0.07] bg-white/[0.025] text-[9px] font-semibold text-zinc-300 flex items-center justify-center gap-2 hover:bg-white/[0.05]">Abrir página de pagamento <ExternalLink className="w-3.5 h-3.5"/></a>}
       <div className="grid sm:grid-cols-2 gap-2"><div className="rounded-xl border border-white/[0.06] bg-black/15 p-3"><p className="text-[8px] text-zinc-600">Forma de pagamento</p><p className="mt-1 text-[10px] font-bold text-white">Pix</p></div><div className="rounded-xl border border-white/[0.06] bg-black/15 p-3"><p className="text-[8px] text-zinc-600">Processamento</p><p className="mt-1 text-[10px] font-bold text-white">Mercado Pago</p></div></div>
       <div className="rounded-xl border border-emerald-300/10 bg-emerald-300/[0.04] p-3 flex gap-2.5"><ShieldCheck className="w-4 h-4 shrink-0 text-emerald-300"/><div><p className="text-[9px] font-bold text-zinc-300">Confirmação automática</p><p className="mt-0.5 text-[8px] leading-relaxed text-zinc-600">Assim que o gateway confirmar o Pix, os créditos são adicionados automaticamente. Não é necessário enviar comprovante.</p></div></div>
      </div>
     </section>
    </div>}
    {error&&<div className="mt-4 p-3 rounded-xl bg-rose-500/[0.08] border border-rose-400/10 text-[10px] text-rose-300">{error}</div>}
   </div>
  </div>
 </div>}</div>;
};
