import React, { useEffect, useRef, useState } from 'react';
import { Wallet, RotateCcw, FileText, Plus, Copy, CheckCircle2, X, Loader2, QrCode } from 'lucide-react';
import { useAuth } from '../../context/AuthContext.js';
import { walletService } from '../../services/walletService.js';
import { paymentClient } from '../../services/paymentClient.js';
import { WalletTransaction, PaymentRecord } from '../../types/index.js';
import { formatCentsToBRL } from '../../config/constants.js';

const presets=[2000,5000,10000,20000];
const terminal=(status:string)=>['CONFIRMED','FAILED','EXPIRED'].includes(status);

export const WalletView:React.FC=()=>{
 const {wallet,refreshWallet}=useAuth(); const [transactions,setTransactions]=useState<WalletTransaction[]>([]); const [loading,setLoading]=useState(true); const [refreshing,setRefreshing]=useState(false);
 const [rechargeOpen,setRechargeOpen]=useState(false); const [amount,setAmount]=useState('50'); const [creating,setCreating]=useState(false); const [payment,setPayment]=useState<PaymentRecord|null>(null); const [error,setError]=useState(''); const [copied,setCopied]=useState(false); const pollRef=useRef<any>(null);
 const loadLedger=async()=>{try{setLoading(true);const r=await walletService.listTransactions(50,0);setTransactions(r.transactions);}finally{setLoading(false);}};
 useEffect(()=>{loadLedger().catch(console.error);return()=>{if(pollRef.current)clearTimeout(pollRef.current);};},[]);
 const refresh=async()=>{setRefreshing(true);await Promise.all([refreshWallet(),loadLedger()]);setRefreshing(false);};
 const closeRecharge=()=>{if(pollRef.current)clearTimeout(pollRef.current);setRechargeOpen(false);setPayment(null);setError('');setCopied(false);};
 const poll=(id:string)=>{pollRef.current=setTimeout(async()=>{try{const p=await paymentClient.get(id);setPayment(p);if(p.status==='CONFIRMED'){await refresh();return;}if(!terminal(p.status))poll(id);}catch{}},2500);};
 const createPix=async()=>{const cents=Math.round(Number(amount.replace(',','.'))*100);if(!Number.isFinite(cents)||cents<500){setError('A recarga mínima é R$ 5,00.');return;}setCreating(true);setError('');try{const p=await paymentClient.createPix(cents);setPayment(p);if(!terminal(p.status))poll(p.payment_id);else if(p.status==='CONFIRMED')await refresh();}catch(e:any){setError(e?.message||'Não foi possível criar o Pix.');}finally{setCreating(false);}};
 const copyPix=async()=>{if(!payment?.pix_code)return;await navigator.clipboard.writeText(payment.pix_code);setCopied(true);setTimeout(()=>setCopied(false),1800);};
 const credit=(t:string)=>['DEPOSIT','ADMIN_CREDIT','PROMOTIONAL_CREDIT','REFUND'].includes(t);
 return <div className="space-y-5 text-zinc-100">
  <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><h1 className="text-xl font-bold text-white">Carteira</h1><p className="text-xs text-zinc-500 mt-1">Créditos para suas gerações e histórico de movimentações.</p></div><div className="flex gap-2"><button onClick={refresh} disabled={refreshing} className="h-9 px-3 rounded-xl border border-white/[0.08] bg-white/[0.035] text-[11px] text-zinc-300 hover:bg-white/[0.06] flex items-center gap-2"><RotateCcw className={`w-3.5 h-3.5 ${refreshing?'animate-spin':''}`}/>Atualizar</button><button onClick={()=>setRechargeOpen(true)} className="h-9 px-4 rounded-xl bg-gradient-to-r from-emerald-400 to-cyan-400 text-[#06100d] text-[11px] font-bold flex items-center gap-2"><Plus className="w-3.5 h-3.5"/>Adicionar saldo</button></div></div>
  <div className="grid sm:grid-cols-3 gap-3"><div className="sm:col-span-2 p-5 rounded-2xl border border-emerald-400/15 bg-gradient-to-br from-emerald-400/[0.08] to-cyan-400/[0.025]"><div className="flex items-center gap-2 text-zinc-400 text-[10px] uppercase tracking-wider"><Wallet className="w-4 h-4 text-emerald-300"/>Saldo disponível</div><div className="text-3xl font-black mt-3 tabular-nums text-white">{formatCentsToBRL(wallet?.available_balance_cents||0)}</div><p className="text-[10px] text-zinc-500 mt-2">Disponível imediatamente para novas gerações.</p></div><div className="p-5 rounded-2xl border border-white/[0.07] bg-[#11151c]"><p className="text-[10px] text-zinc-500 uppercase tracking-wider">Reservado</p><p className="text-xl font-bold mt-3 tabular-nums">{formatCentsToBRL(wallet?.reserved_balance_cents||0)}</p><p className="text-[10px] text-zinc-600 mt-2">Jobs em processamento.</p></div></div>
  <div className="rounded-2xl border border-white/[0.07] bg-[#11151c] overflow-hidden"><div className="px-5 py-4 border-b border-white/[0.06]"><h2 className="text-sm font-semibold">Movimentações</h2><p className="text-[10px] text-zinc-600 mt-0.5">Ledger da sua carteira</p></div>{loading?<div className="py-12 text-center text-xs text-zinc-600">Carregando...</div>:transactions.length===0?<div className="py-12 flex flex-col items-center text-zinc-600"><FileText className="w-5 h-5 mb-2"/><span className="text-xs">Nenhuma movimentação ainda.</span></div>:<div className="overflow-x-auto"><table className="w-full text-[11px]"><thead className="text-zinc-600 border-b border-white/[0.05]"><tr><th className="text-left font-medium px-5 py-3">Data</th><th className="text-left font-medium px-3 py-3">Descrição</th><th className="text-right font-medium px-5 py-3">Valor</th></tr></thead><tbody className="divide-y divide-white/[0.045]">{transactions.map(tx=><tr key={tx.transaction_id}><td className="px-5 py-3 text-zinc-500 whitespace-nowrap">{new Date(tx.created_at).toLocaleString('pt-BR')}</td><td className="px-3 py-3 text-zinc-300">{tx.description||tx.type}</td><td className={`px-5 py-3 text-right font-semibold tabular-nums ${credit(tx.type)?'text-emerald-300':'text-zinc-200'}`}>{credit(tx.type)?'+':'-'} {formatCentsToBRL(tx.amount_cents)}</td></tr>)}</tbody></table></div>}</div>
  {rechargeOpen&&<div className="fixed inset-0 z-[120] bg-black/75 backdrop-blur-sm flex items-center justify-center p-4"><div className="w-full max-w-md rounded-2xl border border-white/[0.09] bg-[#11151c] shadow-2xl overflow-hidden"><div className="px-5 py-4 border-b border-white/[0.06] flex justify-between items-center"><div><h2 className="text-sm font-semibold">Adicionar saldo</h2><p className="text-[10px] text-zinc-600 mt-0.5">Pagamento seguro via Pix</p></div><button onClick={closeRecharge} className="p-2 text-zinc-600 hover:text-white"><X className="w-4 h-4"/></button></div><div className="p-5 space-y-4">
   {!payment?<><div className="grid grid-cols-4 gap-2">{presets.map(c=><button key={c} onClick={()=>setAmount(String(c/100))} className="py-2 rounded-xl border border-white/[0.07] bg-white/[0.025] hover:border-emerald-400/30 text-[10px] font-semibold">{formatCentsToBRL(c)}</button>)}</div><label className="block"><span className="text-[10px] text-zinc-500">Outro valor</span><div className="mt-1.5 flex items-center rounded-xl border border-white/[0.08] bg-[#0b0e13] px-3"><span className="text-xs text-zinc-500">R$</span><input value={amount} onChange={e=>setAmount(e.target.value.replace(/[^0-9,.]/g,''))} className="w-full bg-transparent outline-none p-3 text-sm text-white"/></div></label><button onClick={createPix} disabled={creating} className="w-full h-11 rounded-xl bg-gradient-to-r from-emerald-400 to-cyan-400 text-[#06100d] font-bold text-xs flex items-center justify-center gap-2">{creating?<Loader2 className="w-4 h-4 animate-spin"/>:<QrCode className="w-4 h-4"/>}Gerar Pix</button></>:payment.status==='CONFIRMED'?<div className="py-8 text-center"><CheckCircle2 className="w-10 h-10 text-emerald-400 mx-auto"/><h3 className="font-bold mt-3">Pagamento confirmado</h3><p className="text-xs text-zinc-500 mt-1">{formatCentsToBRL(payment.amount_cents)} já foi adicionado ao seu saldo.</p><button onClick={closeRecharge} className="mt-5 px-5 py-2.5 rounded-xl bg-white text-black text-xs font-bold">Concluir</button></div>:<div className="text-center space-y-3"><p className="text-xs text-zinc-400">Pague {formatCentsToBRL(payment.amount_cents)} pelo Pix abaixo.</p>{payment.pix_qr_code_base64&&<img src={`data:image/png;base64,${payment.pix_qr_code_base64}`} className="w-48 h-48 bg-white p-2 rounded-xl mx-auto" alt="QR Code Pix"/>}<button onClick={copyPix} className="w-full h-10 rounded-xl border border-white/[0.08] bg-white/[0.035] text-xs font-semibold flex items-center justify-center gap-2"><Copy className="w-3.5 h-3.5"/>{copied?'Código copiado':'Copiar Pix copia e cola'}</button><p className="text-[10px] text-zinc-600">Aguardando confirmação automática do pagamento...</p></div>}
   {error&&<div className="p-3 rounded-xl bg-rose-500/[0.08] border border-rose-400/10 text-[10px] text-rose-300">{error}</div>}
  </div></div></div>}
 </div>;
};
