import crypto from 'crypto';
import {catalogRepository} from '../../repositories/catalogRepository.js';
import {creditWalletService} from '../../services/creditWalletService.js';
import {betaFlowRepository} from '../flows/flowRepository.js';
import {betaFlowService} from '../flows/flowService.js';
import {betaFlowEconomicRuntimeService} from '../flows/flowEconomicRuntimeService.js';
import {betaTemplateService} from '../templates/templateService.js';
import {workflowAppService} from '../apps/workflowAppService.js';
import {BatchCondition,BatchItem,BatchRecord,BatchSourceType} from './batchTypes.js';
import {batchRepository} from './batchRepository.js';

const now=()=>new Date().toISOString(),clean=(v:any,n:number)=>String(v??'').trim().slice(0,n);
function fail(code:string,message:string):never{throw Object.assign(new Error(message),{code});}
async function assertEnabled(){const [beta,batch,exec]=await Promise.all([catalogRepository.getFeatureFlag('beta.enabled'),catalogRepository.getFeatureFlag('beta.batch'),catalogRepository.getFeatureFlag('beta.execution.enabled')]);if(!beta?.is_enabled||!batch?.is_enabled)fail('BATCH_DISABLED','Batch está temporariamente indisponível.');if(!exec?.is_enabled)fail('BETA_EXECUTION_DISABLED','Novas execuções Beta estão temporariamente pausadas.');}
function sourceType(v:any):BatchSourceType{const value=String(v||'FLOW').toUpperCase();if(!['FLOW','APP','TEMPLATE'].includes(value))fail('BATCH_SOURCE_INVALID','Fonte de Batch inválida.');return value as BatchSourceType;}
function concurrency(v:any){const admin=Math.max(1,Math.min(10,Number(process.env.BETA_BATCH_MAX_CONCURRENCY||3)||3));const requested=Math.max(1,Math.floor(Number(v)||1));return Math.min(requested,admin);}
function credits(v:any,label:string){const n=Math.floor(Number(v));if(!Number.isFinite(n)||n<1||n>1_000_000)fail('BATCH_ECONOMIC_LIMIT_INVALID',`${label} inválido.`);return n;}
function pathValue(obj:any,path:string){return clean(path,160).split('.').filter(Boolean).reduce((v,key)=>v==null?undefined:v[key],obj);}
function conditionPass(input:any,condition:BatchCondition|null){if(!condition)return true;const actual=pathValue(input,condition.path),expected=condition.value;switch(condition.op){case'exists':return actual!==undefined&&actual!==null;case'equals':return actual===expected;case'not_equals':return actual!==expected;case'contains':return Array.isArray(actual)?actual.includes(expected):String(actual??'').includes(String(expected??''));case'gt':return Number(actual)>Number(expected);case'gte':return Number(actual)>=Number(expected);case'lt':return Number(actual)<Number(expected);case'lte':return Number(actual)<=Number(expected);case'boolean':return Boolean(actual)===Boolean(expected);default:return false;}}
function interpolate(value:any,vars:Record<string,any>):any{if(typeof value==='string')return value.replace(/\{\{\s*([\w.-]+)\s*\}\}/g,(_,key)=>String(pathValue(vars,key)??''));if(Array.isArray(value))return value.map(v=>interpolate(v,vars));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,interpolate(v,vars)]));return value;}
function expand(rawItems:any[],fanOutPath:string|null){const result:any[]=[];for(const item of rawItems){if(!fanOutPath){result.push(item);continue;}const list=pathValue(item,fanOutPath);if(!Array.isArray(list)){result.push(item);continue;}if(list.length>50)fail('BATCH_FAN_OUT_LIMIT','Fan-out excede 50 itens por entrada.');for(const value of list)result.push({...item,__fan_out_value:value});}if(result.length>500)fail('BATCH_ITEM_LIMIT','Batch excede o limite de 500 execuções.');return result;}
async function snapshot(userId:string,type:BatchSourceType,id:string){let graph:any,name='',revision=1;if(type==='FLOW'){const flow=await betaFlowService.get(userId,id);graph=flow.graph;name=flow.name;revision=flow.revision;}else if(type==='APP'){const app:any=await workflowAppService.get(userId,id);const flow=await betaFlowService.get(userId,app.runtime_flow_id);graph=flow.graph;name=app.name;revision=app.revision;}else{const template:any=await betaTemplateService.get(userId,id);graph=template.graph;name=template.name;revision=template.source_flow_revision||1;}const runtime=await betaFlowRepository.create(userId,{name:`Batch Runtime · ${name}`,description:'Snapshot interno de Batch',project_id:null,status:'DRAFT',graph,system_kind:'BATCH',source_app_id:null});return{runtime_flow_id:runtime.flow_id,source_revision:revision};}
function counts(row:BatchRecord){const succeeded=row.items.filter(x=>x.status==='SUCCEEDED').length,failed=row.items.filter(x=>x.status==='FAILED').length,skipped=row.items.filter(x=>x.status==='SKIPPED').length,cancelled=row.items.filter(x=>x.status==='CANCELLED').length,done=succeeded+failed+skipped+cancelled;return{succeeded,failed,skipped,cancelled,progress:row.item_count?Math.round(done/row.item_count*100):100};}
function finalize(row:BatchRecord):BatchRecord{const c=counts(row),active=row.items.some(x=>x.status==='RUNNING'||x.status==='PENDING');if(active)return{...row,...c};const status:BatchRecord['status']=row.status==='CANCELLED'?'CANCELLED':c.failed&&c.succeeded?'PARTIAL':c.failed?'FAILED':'SUCCEEDED';return{...row,...c,status,completed_at:now()};}
function publicRow(row:BatchRecord){return row;}

export const batchService={
 async list(userId:string){return batchRepository.list(userId);},
 async get(userId:string,batchId:string){const row=await batchRepository.get(batchId,userId);if(!row)fail('BATCH_NOT_FOUND','Batch não encontrado.');return row;},
 async create(userId:string,input:any,idempotencyKey:string){await assertEnabled();if(!idempotencyKey)fail('IDEMPOTENCY_KEY_REQUIRED','Idempotency-Key obrigatório.');const type=sourceType(input?.source_type),sourceId=clean(input?.source_id,140);if(!sourceId)fail('BATCH_SOURCE_REQUIRED','Selecione um Flow, App ou Template.');const raw=Array.isArray(input?.items)?input.items:[];if(!raw.length||raw.length>500)fail('BATCH_ITEM_LIMIT','Envie entre 1 e 500 itens.');const fan=clean(input?.fan_out_path,160)||null,expanded=expand(raw,fan),perItem=credits(input?.max_credits_per_item,'Limite por item'),estimated=expanded.length*perItem,maxTotal=credits(input?.max_total_credits??estimated,'Limite total');if(estimated>maxTotal)fail('BATCH_RUNAWAY_SPEND','A exposição máxima estimada excede o limite total configurado.');const variables=input?.variables&&typeof input.variables==='object'&&!Array.isArray(input.variables)?input.variables:{};const condition=input?.condition&&typeof input.condition==='object'?input.condition as BatchCondition:null;const snap=await snapshot(userId,type,sourceId),timestamp=now();const items:BatchItem[]=expanded.map((item,index)=>({item_id:`bi_${index}_${crypto.randomBytes(4).toString('hex')}`,index,status:conditionPass(item,condition)?'PENDING':'SKIPPED',input:interpolate(item,{...variables,item}),flow_run_id:null,error_code:null,error_message:null,created_at:timestamp,updated_at:timestamp}));return publicRow(await batchRepository.createIdempotent(userId,idempotencyKey,{user_id:userId,source_type:type,source_id:sourceId,runtime_flow_id:snap.runtime_flow_id,source_revision:snap.source_revision,status:'DRAFT',item_count:items.length,progress:0,succeeded:0,failed:0,skipped:items.filter(x=>x.status==='SKIPPED').length,cancelled:0,concurrency:concurrency(input?.concurrency),max_credits_per_item:perItem,max_total_credits:maxTotal,estimated_max_credits:estimated,variables,condition,fan_out_path:fan,items}));},
 async confirm(userId:string,batchId:string){await assertEnabled();const row=await this.get(userId,batchId);if(row.status!=='DRAFT')return row;const simulation=await creditWalletService.simulateReserve(userId,row.max_total_credits);if(!simulation.has_sufficient_credits)fail('BATCH_INSUFFICIENT_CREDITS',`Faltam ${simulation.missing_credits} créditos para autorizar a exposição máxima do Batch.`);return batchRepository.save({...row,status:'READY'});},
 async advance(userId:string,batchId:string,reqHost?:string,idToken?:string){await assertEnabled();let row=await this.get(userId,batchId);if(['PAUSED','CANCELLED','SUCCEEDED','PARTIAL','FAILED'].includes(row.status))return row;if(row.status==='DRAFT')fail('BATCH_CONFIRMATION_REQUIRED','Confirme a exposição econômica antes de iniciar.');row={...row,status:'RUNNING',started_at:row.started_at||now()};const items=[...row.items];const running=items.filter(x=>x.status==='RUNNING');await Promise.all(running.map(async item=>{try{const run:any=await betaFlowEconomicRuntimeService.advance(userId,item.flow_run_id!,reqHost,idToken);item.status=run.status==='SUCCEEDED'?'SUCCEEDED':run.status==='FAILED'?'FAILED':run.status==='CANCELLED'?'CANCELLED':'RUNNING';item.error_code=run.error_code||null;item.error_message=run.error_message||null;item.updated_at=now();}catch(e:any){item.status='FAILED';item.error_code=String(e?.code||'BATCH_ITEM_FAILED');item.error_message=String(e?.message||'Falha no item.');item.updated_at=now();}}));const capacity=Math.max(0,row.concurrency-items.filter(x=>x.status==='RUNNING').length),pending=items.filter(x=>x.status==='PENDING').slice(0,capacity);await Promise.all(pending.map(async item=>{try{const run:any=await betaFlowEconomicRuntimeService.start(userId,row.runtime_flow_id,{inputs:item.input,max_credits:row.max_credits_per_item},`batch:${row.batch_id}:item:${item.item_id}`,reqHost,idToken);item.flow_run_id=run.run_id;item.status=run.status==='SUCCEEDED'?'SUCCEEDED':run.status==='FAILED'?'FAILED':run.status==='CANCELLED'?'CANCELLED':'RUNNING';item.error_code=run.error_code||null;item.error_message=run.error_message||null;item.updated_at=now();}catch(e:any){item.status='FAILED';item.error_code=String(e?.code||'BATCH_ITEM_FAILED');item.error_message=String(e?.message||'Falha no item.');item.updated_at=now();}}));row=finalize({...row,items});return batchRepository.save(row);},
 async pause(userId:string,batchId:string){const row=await this.get(userId,batchId);if(row.status!=='RUNNING'&&row.status!=='READY')return row;return batchRepository.save({...row,status:'PAUSED'});},
 async resume(userId:string,batchId:string,reqHost?:string,idToken?:string){const row=await this.get(userId,batchId);if(row.status!=='PAUSED')return row;await batchRepository.save({...row,status:'RUNNING'});return this.advance(userId,batchId,reqHost,idToken);},
 async retryFailed(userId:string,batchId:string,reqHost?:string,idToken?:string){const row=await this.get(userId,batchId);const items=row.items.map(x=>x.status==='FAILED'?{...x,status:'PENDING' as const,flow_run_id:null,error_code:null,error_message:null,updated_at:now()}:x);await batchRepository.save({...row,items,status:'RUNNING',completed_at:null});return this.advance(userId,batchId,reqHost,idToken);},
 async cancel(userId:string,batchId:string){const row=await this.get(userId,batchId);await Promise.all(row.items.filter(x=>x.status==='RUNNING'&&x.flow_run_id).map(x=>betaFlowEconomicRuntimeService.cancel(userId,x.flow_run_id!).catch(()=>null)));const items=row.items.map(x=>x.status==='PENDING'||x.status==='RUNNING'?{...x,status:'CANCELLED' as const,updated_at:now()}:x),next=finalize({...row,items,status:'CANCELLED'});return batchRepository.save(next);}
};
