import React,{useEffect,useMemo,useRef,useState}from'react';
import{ModelRegistryItem}from'../../types/index.js';
import{Check,ChevronDown,Clock3,Gauge,Images,Search,Sparkles,Star,Video}from'lucide-react';

interface Props{
 models:ModelRegistryItem[];selectionMode:'AUTO'|'MANUAL';selectedModelId:string;autoResolvedModel?:ModelRegistryItem|null;
 onSelectAuto:()=>void;onSelectModel:(m:ModelRegistryItem)=>void;favoriteModelIds:string[];recentModelIds:string[];onToggleFavorite:(id:string)=>void;
 unitPricesByModelId?:Record<string,number|null>;priceLoadingModelIds?:string[];selectedCoverUrl?:string|null;
}
const accentFor=(id?:string)=>{if(!id)return'from-violet-500/35 via-fuchsia-500/15 to-cyan-400/25';if(id.includes('seedance'))return'from-rose-500/35 via-orange-400/15 to-fuchsia-500/25';if(id.includes('wan'))return'from-cyan-500/30 via-blue-500/15 to-violet-500/25';if(id.includes('minimax'))return'from-amber-500/25 via-rose-500/15 to-violet-500/25';return'from-violet-500/30 via-fuchsia-500/15 to-cyan-400/20';};
const initials=(name?:string)=>(name||'AI').split(/\s+/).slice(0,2).map(p=>p[0]).join('').toUpperCase();

export const CompactModelPicker:React.FC<Props>=(p)=>{
 const[open,setOpen]=useState(false),[search,setSearch]=useState(''),ref=useRef<HTMLDivElement>(null);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(ref.current&&!ref.current.contains(e.target as Node))setOpen(false)};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close)},[]);
 const selected=p.models.find(m=>m.model_id===p.selectedModelId)||null;
 const isLoading=(id?:string|null)=>Boolean(id&&p.priceLoadingModelIds?.includes(id));
 const unitPriceText=(model:ModelRegistryItem)=>{
  if(isLoading(model.model_id))return'—';
  const value=p.unitPricesByModelId?.[model.model_id];
  if(value==null||!Number.isFinite(Number(value)))return'—';
  const unit=model.category==='VIDEO'?'cr/s':'cr/img';
  return`${Math.max(0,Math.round(Number(value))).toLocaleString('pt-BR')} ${unit}`;
 };
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return p.models.filter(m=>m.status!=='INACTIVE'&&(!q||`${m.name} ${m.description} ${m.best_for||''}`.toLowerCase().includes(q)))},[p.models,search]);
 const sorted=[...filtered].sort((a,b)=>Number(p.favoriteModelIds.includes(b.model_id))-Number(p.favoriteModelIds.includes(a.model_id))||Number(p.recentModelIds.includes(b.model_id))-Number(p.recentModelIds.includes(a.model_id))||a.name.localeCompare(b.name));
 const autoSelected=p.selectionMode==='AUTO',displayModel=autoSelected?null:selected,maxDuration=displayModel?.supported_durations?.length?Math.max(...displayModel.supported_durations):null,coverUrl=!autoSelected?p.selectedCoverUrl:null;
 return <div className="ia-model-picker relative" ref={ref}>
  <button type="button" onClick={()=>setOpen(v=>!v)} className={`group relative w-full ${coverUrl?'ia-model-cover-card min-h-[148px]':'min-h-[112px]'} overflow-hidden rounded-[16px] border border-white/[0.08] bg-gradient-to-br ${accentFor(displayModel?.model_id)} text-left shadow-[0_16px_45px_rgba(0,0,0,.2)]`}>
   {coverUrl?<><img src={coverUrl} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full object-cover object-center scale-[1.01]"/><div className="absolute inset-0" style={{background:'linear-gradient(180deg,rgba(3,7,18,.18) 0%,rgba(3,7,18,.34) 44%,rgba(3,7,18,.92) 100%)'}}/></>:<div className="absolute inset-0 bg-[radial-gradient(circle_at_72%_25%,rgba(255,255,255,.12),transparent_28%),linear-gradient(to_top,rgba(4,6,10,.92),rgba(4,6,10,.18))]"/>}
   <div className="relative h-full p-3 flex flex-col justify-between gap-6">
    <div className="flex items-start justify-between gap-3">
     <div className="flex items-center gap-2 min-w-0"><div className="w-9 h-9 rounded-xl border border-white/10 bg-black/30 backdrop-blur grid place-items-center text-[11px] font-black text-white">{autoSelected?'AI':initials(displayModel?.name)}</div><div className="min-w-0"><p className="text-[13px] font-black text-white truncate">{autoSelected?'Auto':(selected?.name||'Escolher IA')}</p><p className="text-[9px] text-white/65 truncate">{autoSelected?'Escolha automática do melhor modelo':displayModel?.best_for||'Modelo manual'}</p></div></div>
     <span className="rounded-lg border border-white/10 bg-black/35 backdrop-blur px-2 py-1 text-[9px] font-semibold text-white flex items-center gap-1">Alterar <ChevronDown className={`w-3.5 h-3.5 transition-transform ${open?'rotate-180':''}`}/></span>
    </div>
    {autoSelected?<div className="flex flex-wrap gap-1.5 text-[9px] text-white/75"><span className="inline-flex items-center gap-1 rounded-md bg-black/30 px-1.5 py-1"><Sparkles className="w-3 h-3"/> Auto Router</span></div>:<div className="flex flex-wrap gap-1.5 text-[8px] text-white/70">{maxDuration&&<span className="inline-flex items-center gap-1 rounded-md bg-black/30 px-1.5 py-1"><Clock3 className="w-3 h-3"/> até {maxDuration}s</span>}{displayModel?.supported_resolutions?.length?<span className="inline-flex items-center gap-1 rounded-md bg-black/30 px-1.5 py-1"><Gauge className="w-3 h-3"/> {displayModel.supported_resolutions.join(' · ')}</span>:null}{displayModel?.supports_image_reference&&<span className="inline-flex items-center gap-1 rounded-md bg-black/30 px-1.5 py-1"><Images className="w-3 h-3"/> refs</span>}</div>}
   </div>
  </button>
  {open&&<div className="absolute z-[80] top-full mt-2 inset-x-0 overflow-hidden rounded-2xl border border-white/[0.09] bg-[#0d1117] shadow-2xl shadow-black/60">
   <div className="p-2 border-b border-white/[0.06]"><button onClick={()=>{p.onSelectAuto();setOpen(false)}} className={`w-full flex items-center gap-2.5 p-2.5 rounded-xl text-left ${p.selectionMode==='AUTO'?'bg-violet-500/12 ring-1 ring-violet-400/15':'hover:bg-white/[0.04]'}`}><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-violet-500/30 to-cyan-400/20 grid place-items-center"><Sparkles className="w-4 h-4 text-cyan-300"/></div><div className="flex-1 min-w-0"><p className="text-[11px] font-bold text-white">Auto Router</p><p className="text-[9px] text-zinc-500">Escolhe a melhor IA compatível dentro do orçamento econômico seguro.</p></div>{p.selectionMode==='AUTO'&&<Check className="w-3.5 h-3.5 text-cyan-300"/>}</button></div>
   <div className="p-2 border-b border-white/[0.06]"><div className="relative"><Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-zinc-600"/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar modelo..." className="w-full h-9 pl-8 pr-3 rounded-xl bg-[#090c11] border border-white/[0.07] text-[10px] text-zinc-300 placeholder:text-zinc-700 outline-none focus:border-violet-400/30"/></div></div>
   <div className="max-h-[420px] overflow-y-auto p-2 space-y-1.5">{sorted.map(m=>{const active=p.selectionMode==='MANUAL'&&m.model_id===p.selectedModelId,fav=p.favoriteModelIds.includes(m.model_id),max=m.supported_durations?.length?Math.max(...m.supported_durations):null;return <button key={m.model_id} type="button" onClick={()=>{p.onSelectModel(m);setOpen(false)}} className={`w-full group/model flex items-center gap-3 p-2.5 rounded-xl text-left border transition-all ${active?'bg-white/[0.075] border-cyan-400/20':'border-transparent hover:bg-white/[0.04] hover:border-white/[0.05]'}`}><div className={`w-12 h-12 rounded-xl bg-gradient-to-br ${accentFor(m.model_id)} border border-white/[0.07] grid place-items-center shrink-0`}><span className="text-[11px] font-black text-white">{initials(m.name)}</span></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-[10px] font-bold text-white truncate">{m.name}</p>{active&&<Check className="w-3 h-3 text-cyan-300 shrink-0"/>}</div><p className="mt-0.5 text-[8px] text-zinc-600 truncate">{m.best_for||m.description}</p><div className="mt-1.5 flex flex-wrap gap-1 text-[7.5px] text-zinc-500">{max&&<span className="rounded bg-white/[0.035] px-1.5 py-0.5">até {max}s</span>}{m.supported_resolutions?.slice(0,3).map(r=><span key={r} className="rounded bg-white/[0.035] px-1.5 py-0.5">{r}</span>)}{m.supports_image_reference&&<span className="rounded bg-white/[0.035] px-1.5 py-0.5">imagem</span>}{m.supports_video_reference&&<span className="rounded bg-white/[0.035] px-1.5 py-0.5">vídeo ref</span>}{m.supports_audio_reference&&<span className="rounded bg-white/[0.035] px-1.5 py-0.5">áudio</span>}</div></div><div className="shrink-0 text-right"><p className="text-[9px] font-black text-white tabular-nums">{unitPriceText(m)}</p></div><span onClick={e=>{e.stopPropagation();p.onToggleFavorite(m.model_id)}} className={fav?'text-amber-400':'text-zinc-700 group-hover/model:text-zinc-500'}><Star className={`w-3.5 h-3.5 ${fav?'fill-current':''}`}/></span></button>})}{!sorted.length&&<div className="py-8 text-center"><Video className="w-5 h-5 mx-auto text-zinc-800"/><p className="mt-2 text-[10px] text-zinc-600">Nenhum modelo encontrado.</p></div>}</div>
  </div>}
 </div>;
};
