import React from'react';
import{ChevronDown,Sparkles}from'lucide-react';
import{CreditAmount}from'../common/CreditAmount.js';

export const GeneratorPanel:React.FC<React.PropsWithChildren<{ariaLabel:string;className?:string}>>=({ariaLabel,className='',children})=><aside className={`ia-generator-panel w-full md:w-[352px] xl:w-[368px] h-full shrink-0 flex flex-col ${className}`} aria-label={ariaLabel}>{children}</aside>;
export const GeneratorScroll:React.FC<React.PropsWithChildren>=({children})=><div className="ia-generator-scroll flex-1 min-h-0 overflow-y-auto px-3.5 py-3.5 space-y-3">{children}</div>;

interface UniversalCreatorShellProps{
 ariaLabel:string;
 modelPicker:React.ReactNode;
 children:React.ReactNode;
 footer:React.ReactNode;
 className?:string;
}
export const UniversalCreatorShell:React.FC<UniversalCreatorShellProps>=({ariaLabel,modelPicker,children,footer,className=''})=><GeneratorPanel ariaLabel={ariaLabel} className={className}><GeneratorScroll>{modelPicker}{children}</GeneratorScroll>{footer}</GeneratorPanel>;
export const GeneratorField:React.FC<React.PropsWithChildren<{label:string;count?:string;htmlFor?:string}>>=({label,count,htmlFor,children})=><section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><div className="flex items-center justify-between gap-2 mb-1.5"><label htmlFor={htmlFor} className="text-[10px] font-semibold text-zinc-300">{label}</label>{count&&<span className="text-[8px] text-zinc-700">{count}</span>}</div>{children}</section>;
export const GeneratorTextarea:React.FC<React.TextareaHTMLAttributes<HTMLTextAreaElement>>=(props)=><textarea {...props} className={`w-full resize-y min-h-[132px] border-0 bg-transparent text-[11px] leading-[1.55] text-white outline-none placeholder:text-zinc-700 ${props.className||''}`}/>;

export const GeneratorSettingRow:React.FC<{icon:React.ComponentType<{className?:string}>;label:string;value:string;open:boolean;onToggle:()=>void;children:React.ReactNode;accent?:'cyan'|'violet'|'emerald'|'sky';semantic?:'duration'|'ratio'|'resolution'|'outputs'}>=({icon:Icon,label,value,open,onToggle,children,semantic})=> <div className={`rounded-xl border transition-colors ${open?'border-cyan-300/20 bg-cyan-300/[0.035]':'border-white/[0.065] bg-white/[0.025]'}`}><button type="button" onClick={onToggle} className="h-10 w-full px-3 flex items-center gap-2"><span className={`ia-generator-setting-icon${semantic?` ia-generator-setting-icon-${semantic}`:''}`}><Icon className="w-3.5 h-3.5"/></span><span className="text-[10px] font-semibold text-zinc-300">{label}</span><span className="ml-auto text-[10px] font-bold text-white">{value}</span><ChevronDown className={`w-3.5 h-3.5 text-zinc-600 transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div className="px-2.5 pb-2.5 pt-0.5">{children}</div>}</div>;

export const GeneratorOptionGrid:React.FC<{values:Array<{value:string;label:string}>;current:string;onSelect:(value:string)=>void;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({values,current,onSelect})=><div className="flex flex-wrap gap-1.5">{values.map(item=><button key={item.value} type="button" onClick={()=>onSelect(item.value)} className={`min-w-12 px-2.5 py-1.5 rounded-lg border text-[9px] font-semibold transition-colors ${current===item.value?'border-cyan-300/35 bg-cyan-300/10 text-cyan-200':'border-white/[0.06] bg-black/15 text-zinc-500 hover:text-zinc-200'}`}>{item.label}</button>)}</div>;

export const GeneratorDiscreteSlider:React.FC<{values:number[];value:number;onChange:(value:number)=>void;headline?:string;subtitle?:string;suffix?:string;rightLabel?:string;rightValue?:React.ReactNode;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({values,value,onChange,headline,subtitle,suffix='',rightLabel,rightValue})=>{const sorted=[...values].sort((a,b)=>a-b),index=Math.max(0,sorted.findIndex(item=>item===value));return <div className="px-1 pt-1 pb-0.5"><div className="flex items-end justify-between gap-3 mb-2"><div><p className="text-[17px] font-black text-white tabular-nums">{headline||`${value}${suffix}`}</p>{subtitle&&<p className="text-[8px] text-zinc-600">{subtitle}</p>}</div>{rightValue&&<div className="text-right">{rightLabel&&<p className="text-[8px] text-zinc-600">{rightLabel}</p>}<p className="text-[9px] font-bold text-cyan-200">{rightValue}</p></div>}</div><input type="range" min={0} max={Math.max(0,sorted.length-1)} step={1} value={index} disabled={sorted.length<=1} onChange={event=>onChange(sorted[Number(event.target.value)]??sorted[0])} className="w-full h-1.5 accent-cyan-300 cursor-pointer disabled:opacity-40"/><div className="mt-1.5 flex justify-between text-[7px] text-zinc-700"><span>{sorted[0]}{suffix}</span>{sorted.length>2&&<span>arraste para ajustar</span>}<span>{sorted[sorted.length-1]}{suffix}</span></div></div>};

export const GeneratorRangeSlider:React.FC<{min:number;max:number;step:number;value:number;onChange:(value:number)=>void;headline:string;subtitle?:string;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({min,max,step,value,onChange,headline,subtitle})=><div className="px-1 pt-1 pb-0.5"><p className="text-[17px] font-black text-white tabular-nums">{headline}</p>{subtitle&&<p className="mb-2 text-[8px] text-zinc-600">{subtitle}</p>}<input type="range" min={min} max={max} step={step} value={value} onChange={event=>onChange(Number(event.target.value))} className="w-full h-1.5 accent-cyan-300 cursor-pointer"/><div className="mt-1.5 flex justify-between text-[7px] text-zinc-700"><span>{min.toLocaleString('pt-BR')}</span><span>arraste para ajustar</span><span>{max.toLocaleString('pt-BR')}</span></div></div>;

export const GeneratorToggle:React.FC<{checked:boolean;onChange:(checked:boolean)=>void;label:string;description:string;disabled?:boolean;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({checked,onChange,label,description,disabled=false})=><button type="button" disabled={disabled} onClick={()=>onChange(!checked)} className="w-full rounded-xl border border-white/[0.065] bg-white/[0.025] px-3 py-2.5 flex items-center gap-3 text-left disabled:opacity-40"><span className={`relative w-8 h-[18px] rounded-full transition-colors ${checked?'bg-cyan-300':'bg-white/[0.08]'}`}><span className={`absolute top-[3px] w-3 h-3 rounded-full bg-white transition-transform ${checked?'translate-x-[17px]':'translate-x-[3px]'}`}/></span><span><strong className="block text-[10px] text-white">{label}</strong><small className="block mt-0.5 text-[8px] text-zinc-600">{description}</small></span></button>;

export const GeneratorActionBar:React.FC<React.PropsWithChildren<{error?:string}>>=({error,children})=><div className="ia-generator-actionbar shrink-0 p-3.5">{error&&<div className="mb-2 rounded-xl border border-rose-400/15 bg-rose-500/[0.08] px-3 py-2 text-[9px] leading-relaxed text-rose-300" role="alert" aria-live="assertive">{error}</div>}{children}</div>;

interface GeneratorFooterProps{
 error?:string;notice?:string;price:number|null;balance:number;hasBalance?:boolean;primaryLabel:string;primaryPrice?:number|null;busyLabel?:string;onPrimary?:()=>void;primaryDisabled?:boolean;primaryBusy?:boolean;secondaryLabel?:string;onSecondary?:()=>void;secondaryDisabled?:boolean;
}
export const GeneratorFooter:React.FC<GeneratorFooterProps>=({error,notice,price,balance,hasBalance=true,primaryLabel,primaryPrice=null,busyLabel='Enviando...',onPrimary,primaryDisabled=false,primaryBusy=false,secondaryLabel,onSecondary,secondaryDisabled=false})=><GeneratorActionBar error={error}>{notice&&<div aria-live="polite" className="mb-2 rounded-xl border border-cyan-300/10 bg-cyan-300/[0.05] px-3 py-2 text-[9px] text-cyan-200">{notice}</div>}<div className="mb-2 flex items-center justify-between"><div><p className="text-[8px] uppercase tracking-wider text-zinc-700">Preço</p><p className="text-[11px] font-bold text-white">{price==null?'Preço indisponível':<CreditAmount value={price} size="sm" className="font-bold text-white"/>}</p></div><div className="text-right"><p className="text-[8px] text-zinc-700">Saldo</p><p className={`text-[10px] font-semibold ${hasBalance?'text-zinc-400':'text-rose-400'}`}><CreditAmount value={balance} size="xs"/></p></div></div>{secondaryLabel?<div className="flex gap-2"><button type="button" onClick={onSecondary} disabled={secondaryDisabled} className="h-11.5 rounded-[12px] border border-white/[0.07] bg-white/[0.035] px-3 text-[10px] font-bold text-zinc-300 disabled:opacity-35">{secondaryLabel}</button><button type="button" onClick={onPrimary} disabled={primaryDisabled} className="ia-generator-generate flex-1 h-11.5 rounded-[12px] text-[12px] font-black flex items-center justify-center gap-2 disabled:opacity-35 disabled:grayscale"><Sparkles className="w-4 h-4"/>{primaryBusy?busyLabel:<>{primaryLabel}{primaryPrice!=null&&<CreditAmount value={primaryPrice} size="xs" className="ml-1 font-black text-current"/>}</>}</button></div>:<button type="button" onClick={onPrimary} disabled={primaryDisabled} className="ia-generator-generate w-full h-11.5 rounded-[12px] text-[12px] font-black flex items-center justify-center gap-2 disabled:opacity-35 disabled:grayscale"><Sparkles className="w-4 h-4"/>{primaryBusy?busyLabel:<>{primaryLabel}{primaryPrice!=null&&<CreditAmount value={primaryPrice} size="xs" className="ml-1 font-black text-current"/>}</>}</button>}</GeneratorActionBar>;
