import React from'react';
import{ChevronDown}from'lucide-react';

export const GeneratorPanel:React.FC<React.PropsWithChildren<{ariaLabel:string}>>=({ariaLabel,children})=><aside className="ia-generator-panel w-full md:w-[352px] xl:w-[368px] h-full shrink-0 flex flex-col" aria-label={ariaLabel}>{children}</aside>;

export const GeneratorScroll:React.FC<React.PropsWithChildren>=({children})=><div className="ia-generator-scroll flex-1 min-h-0 overflow-y-auto px-3.5 py-3.5 space-y-3">{children}</div>;

export const GeneratorField:React.FC<React.PropsWithChildren<{label:string;count?:string;htmlFor?:string}>>=({label,count,htmlFor,children})=><section className="rounded-xl border border-white/[0.065] bg-white/[0.025] p-2.5"><div className="flex items-center justify-between gap-2 mb-1.5"><label htmlFor={htmlFor} className="text-[10px] font-semibold text-zinc-300">{label}</label>{count&&<span className="text-[8px] text-zinc-700">{count}</span>}</div>{children}</section>;

export const GeneratorTextarea:React.FC<React.TextareaHTMLAttributes<HTMLTextAreaElement>>=(props)=><textarea {...props} className={`w-full resize-y min-h-[132px] border-0 bg-transparent text-[11px] leading-[1.55] text-white outline-none placeholder:text-zinc-700 ${props.className||''}`}/>;

export const GeneratorSettingRow:React.FC<{icon:React.ComponentType<{className?:string}>;label:string;value:string;open:boolean;onToggle:()=>void;children:React.ReactNode;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({icon:Icon,label,value,open,onToggle,children,accent='cyan'})=>{const tone=accent==='violet'?'border-violet-300/20 bg-violet-300/[0.035]':accent==='emerald'?'border-emerald-300/20 bg-emerald-300/[0.035]':accent==='sky'?'border-sky-300/20 bg-sky-300/[0.035]':'border-cyan-300/20 bg-cyan-300/[0.035]';return <div className={`rounded-xl border transition-colors ${open?tone:'border-white/[0.065] bg-white/[0.025]'}`}><button type="button" onClick={onToggle} className="h-10 w-full px-3 flex items-center gap-2"><span className="ia-generator-setting-icon"><Icon className="w-3.5 h-3.5"/></span><span className="text-[10px] font-semibold text-zinc-300">{label}</span><span className="ml-auto text-[10px] font-bold text-white">{value}</span><ChevronDown className={`w-3.5 h-3.5 text-zinc-600 transition-transform ${open?'rotate-180':''}`}/></button>{open&&<div className="px-2.5 pb-2.5 pt-0.5">{children}</div>}</div>};

export const GeneratorOptionGrid:React.FC<{values:Array<{value:string;label:string}>;current:string;onSelect:(value:string)=>void;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({values,current,onSelect,accent='cyan'})=>{const active=accent==='violet'?'border-violet-300/35 bg-violet-300/10 text-violet-200':accent==='emerald'?'border-emerald-300/35 bg-emerald-300/10 text-emerald-200':accent==='sky'?'border-sky-300/35 bg-sky-300/10 text-sky-200':'border-cyan-300/35 bg-cyan-300/10 text-cyan-200';return <div className="flex flex-wrap gap-1.5">{values.map(item=><button key={item.value} type="button" onClick={()=>onSelect(item.value)} className={`min-w-12 px-2.5 py-1.5 rounded-lg border text-[9px] font-semibold transition-colors ${current===item.value?active:'border-white/[0.06] bg-black/15 text-zinc-500 hover:text-zinc-200'}`}>{item.label}</button>)}</div>};

export const GeneratorDiscreteSlider:React.FC<{values:number[];value:number;onChange:(value:number)=>void;headline?:string;subtitle?:string;suffix?:string;rightLabel?:string;rightValue?:string;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({values,value,onChange,headline,subtitle,suffix='',rightLabel,rightValue,accent='cyan'})=>{const sorted=[...values].sort((a,b)=>a-b),index=Math.max(0,sorted.findIndex(item=>item===value)),accentClass=accent==='violet'?'accent-violet-300':accent==='emerald'?'accent-emerald-300':accent==='sky'?'accent-sky-300':'accent-cyan-300';return <div className="px-1 pt-1 pb-0.5"><div className="flex items-end justify-between gap-3 mb-2"><div><p className="text-[17px] font-black text-white tabular-nums">{headline||`${value}${suffix}`}</p>{subtitle&&<p className="text-[8px] text-zinc-600">{subtitle}</p>}</div>{rightValue&&<div className="text-right">{rightLabel&&<p className="text-[8px] text-zinc-600">{rightLabel}</p>}<p className="text-[9px] font-bold text-cyan-200">{rightValue}</p></div>}</div><input type="range" min={0} max={Math.max(0,sorted.length-1)} step={1} value={index} disabled={sorted.length<=1} onChange={event=>onChange(sorted[Number(event.target.value)]??sorted[0])} className={`w-full h-1.5 ${accentClass} cursor-pointer disabled:opacity-40`}/><div className="mt-1.5 flex justify-between text-[7px] text-zinc-700"><span>{sorted[0]}{suffix}</span>{sorted.length>2&&<span>arraste para ajustar</span>}<span>{sorted[sorted.length-1]}{suffix}</span></div></div>};

export const GeneratorRangeSlider:React.FC<{min:number;max:number;step:number;value:number;onChange:(value:number)=>void;headline:string;subtitle?:string;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({min,max,step,value,onChange,headline,subtitle,accent='cyan'})=>{const accentClass=accent==='violet'?'accent-violet-300':accent==='emerald'?'accent-emerald-300':accent==='sky'?'accent-sky-300':'accent-cyan-300';return <div className="px-1 pt-1 pb-0.5"><p className="text-[17px] font-black text-white tabular-nums">{headline}</p>{subtitle&&<p className="mb-2 text-[8px] text-zinc-600">{subtitle}</p>}<input type="range" min={min} max={max} step={step} value={value} onChange={event=>onChange(Number(event.target.value))} className={`w-full h-1.5 ${accentClass} cursor-pointer`}/><div className="mt-1.5 flex justify-between text-[7px] text-zinc-700"><span>{min.toLocaleString('pt-BR')}</span><span>arraste para ajustar</span><span>{max.toLocaleString('pt-BR')}</span></div></div>};

export const GeneratorToggle:React.FC<{checked:boolean;onChange:(checked:boolean)=>void;label:string;description:string;disabled?:boolean;accent?:'cyan'|'violet'|'emerald'|'sky'}>=({checked,onChange,label,description,disabled=false,accent='cyan'})=>{const bg=accent==='violet'?'bg-violet-300':accent==='emerald'?'bg-emerald-300':accent==='sky'?'bg-sky-300':'bg-cyan-300';return <button type="button" disabled={disabled} onClick={()=>onChange(!checked)} className="w-full rounded-xl border border-white/[0.065] bg-white/[0.025] px-3 py-2.5 flex items-center gap-3 text-left disabled:opacity-40"><span className={`relative w-8 h-[18px] rounded-full transition-colors ${checked?bg:'bg-white/[0.08]'}`}><span className={`absolute top-[3px] w-3 h-3 rounded-full bg-white transition-transform ${checked?'translate-x-[17px]':'translate-x-[3px]'}`}/></span><span><strong className="block text-[10px] text-white">{label}</strong><small className="block mt-0.5 text-[8px] text-zinc-600">{description}</small></span></button>};

export const GeneratorActionBar:React.FC<React.PropsWithChildren<{error?:string}>>=({error,children})=><div className="ia-generator-actionbar flex-none px-3.5 py-3 border-t border-white/[0.065] bg-[#050e17]/95">{error&&<div className="mb-2 rounded-xl border border-rose-400/20 bg-rose-400/[0.07] px-2.5 py-2 text-[9px] leading-relaxed text-rose-300" role="status">{error}</div>}{children}</div>;
