import React, { useEffect, useState } from 'react';
import { WorkspacePreset, Generation } from '../../types/index.js';
import { Film, AlertCircle, Loader2, CheckCircle2, Bookmark, ExternalLink } from 'lucide-react';
interface Props{lastSavedTime:string|null;validating:boolean;validationErrors:string[];validationWarnings:string[];onOpenPresets:()=>void;presets:WorkspacePreset[];onApplyPreset:(p:WorkspacePreset)=>void;prompt:string;hasReferences:boolean;}
export const ResultsCanvas:React.FC<Props>=({lastSavedTime,validationErrors,onOpenPresets,presets,prompt})=>{
 const [generation,setGeneration]=useState<Generation|null>(null);
 useEffect(()=>{const handler=(e:Event)=>setGeneration((e as CustomEvent<Generation>).detail);window.addEventListener('generation:updated',handler);return()=>window.removeEventListener('generation:updated',handler);},[]);
 return <div className="flex-1 h-full flex flex-col bg-[#F7F7F8] p-4 lg:p-6 overflow-y-auto"><div className="flex justify-between items-center pb-4"><span className="text-xs text-zinc-400">{lastSavedTime?`Saved ${lastSavedTime}`:'Ready'}</span><button onClick={onOpenPresets} className="px-3 py-1.5 bg-white border border-zinc-200 rounded-xl text-xs font-medium flex gap-1.5 items-center"><Bookmark className="w-3.5 h-3.5"/>Presets ({presets.length})</button></div><div className="flex-1 flex items-center justify-center min-h-[440px]"><div className="w-full max-w-3xl aspect-video bg-white border border-zinc-200 rounded-2xl overflow-hidden flex items-center justify-center">
 {generation?.result_url?<div className="w-full h-full relative bg-black"><video src={generation.result_url} controls autoPlay className="w-full h-full object-contain"/><a href={generation.result_url} target="_blank" rel="noreferrer" className="absolute top-3 right-3 bg-white/90 rounded-lg px-2 py-1 text-xs flex gap-1 items-center">Abrir <ExternalLink className="w-3 h-3"/></a></div>:generation&&['QUEUED','RESERVING_FUNDS','SUBMITTED','PROCESSING'].includes(generation.status)?<div className="text-center"><Loader2 className="w-8 h-8 mx-auto text-zinc-500 animate-spin mb-3"/><h3 className="font-semibold">Gerando seu vídeo</h3><p className="text-xs text-zinc-500 mt-1">{generation.status}{generation.progress_percent!=null?` · ${generation.progress_percent}%`:''}</p></div>:generation?.status==='FAILED'?<div className="text-center max-w-md px-6"><AlertCircle className="w-8 h-8 mx-auto text-red-500 mb-3"/><h3 className="font-semibold">A geração falhou</h3><p className="text-xs text-zinc-500 mt-1">{generation.error_message||'O saldo reservado foi liberado.'}</p></div>:<div className="text-center max-w-md px-6"><Film className="w-8 h-8 mx-auto text-zinc-400 mb-3"/><h3 className="font-semibold">{prompt.trim()?'Pronto para gerar':'Crie seu próximo vídeo'}</h3><p className="text-xs text-zinc-500 mt-1">As gerações aparecerão aqui.</p>{validationErrors.length>0&&<p className="text-xs text-red-600 mt-3">{validationErrors[0]}</p>}</div>}
 </div></div></div>;
};
