import { Router } from 'express';
import { requireAuth, requireAdmin, AuthenticatedRequest } from '../middleware/authMiddleware.js';
import { pricingSyncService } from '../services/pricingSyncService.js';
import { pricingSettingsService } from '../services/pricingSettingsService.js';
import { quoteCacheService } from '../services/quoteCacheService.js';
import { billingControlService } from '../services/billingControlService.js';
import { retailPricingService } from '../services/retailPricingService.js';
import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';

export const adminPricingRouter = Router();
adminPricingRouter.get('/admin/pricing/live',requireAuth,requireAdmin,async(_req:AuthenticatedRequest,res)=>{try{let result=await pricingSyncService.getLatestSnapshot();if(!result.rows.length)result=await pricingSyncService.runHourlySync();return res.json({success:true,data:result});}catch(err:any){return res.status(500).json({success:false,error:{code:'PRICING_SNAPSHOT_FAILED',message:err?.message||'Não foi possível executar a verificação dos provedores.'}});}});
adminPricingRouter.get('/admin/pricing/settings',requireAuth,requireAdmin,async(_req,res)=>{try{return res.json({success:true,data:await pricingSettingsService.get(true)});}catch(err:any){return res.status(500).json({success:false,error:{code:'PRICING_SETTINGS_FAILED',message:err?.message||'Não foi possível carregar os parâmetros de proteção.'}});}});
adminPricingRouter.post('/admin/pricing/settings',requireAuth,requireAdmin,async(req:AuthenticatedRequest,res)=>{try{const margin=Number(req.body?.gross_margin_percent);if(!Number.isFinite(margin)||margin<10||margin>80)return res.status(400).json({success:false,error:{code:'INVALID_MARGIN',message:'A margem alvo deve ficar entre 10% e 80%.'}});const settings=await pricingSettingsService.set(margin,req.user?.uid);quoteCacheService.invalidateAll();return res.json({success:true,data:{settings,snapshot:null}});}catch(err:any){return res.status(500).json({success:false,error:{code:'PRICING_SETTINGS_SAVE_FAILED',message:err?.message||'Não foi possível salvar os parâmetros.'}});}});
adminPricingRouter.post('/admin/pricing/sync',requireAuth,requireAdmin,async(_req,res)=>{try{return res.json({success:true,data:await pricingSyncService.runHourlySync()});}catch(err:any){return res.status(500).json({success:false,error:{code:err?.code||'PRICING_SYNC_FAILED',message:err?.message||'Não foi possível atualizar o monitor agora.'}});}});

adminPricingRouter.get('/admin/billing-control',requireAuth,requireAdmin,async(_req,res)=>{try{return res.json({success:true,data:await billingControlService.get(true)});}catch(err:any){return res.status(500).json({success:false,error:{code:'BILLING_CONTROL_FAILED',message:err?.message||'Não foi possível carregar os controles.'}});}});
adminPricingRouter.post('/admin/billing-control',requireAuth,requireAdmin,async(req:AuthenticatedRequest,res)=>{try{const allowed=['credit_v2_enabled','new_generations_enabled','provider_execution_enabled','yellow_execution_enabled','legacy_wallet_write_enabled'];const patch:any={};for(const k of allowed)if(req.body?.[k]!==undefined)patch[k]=Boolean(req.body[k]);if(patch.legacy_wallet_write_enabled===true)return res.status(400).json({success:false,error:{code:'LEGACY_WRITE_FORBIDDEN',message:'Novas escritas na carteira BRL legada permanecem bloqueadas por segurança.'}});return res.json({success:true,data:await billingControlService.set(patch,req.user?.uid)});}catch(err:any){return res.status(500).json({success:false,error:{code:'BILLING_CONTROL_SAVE_FAILED',message:err?.message||'Não foi possível salvar os controles.'}});}});

adminPricingRouter.get('/admin/pricing/retail-active',requireAuth,requireAdmin,async(_req,res)=>{try{const pointers=await firestoreAdminRest.runQuery({from:[{collectionId:'retail_pricing_active'}]}),rows=[];for(const p of pointers){const hash=String(p.data?.pricing_signature_hash||''),version=Number(p.data?.version||0);if(!hash||!version)continue;const d=await firestoreAdminRest.get(`retail_pricing_versions/${encodeURIComponent(hash)}_v${version}`);if(d.exists)rows.push(d.data);}return res.json({success:true,data:rows});}catch(err:any){return res.status(500).json({success:false,error:{code:'RETAIL_LIST_FAILED',message:err?.message||'Não foi possível listar os preços publicados.'}});}});
adminPricingRouter.post('/admin/pricing/retail/:hash/publish',requireAuth,requireAdmin,async(req:AuthenticatedRequest,res)=>{try{const current=await retailPricingService.get(req.params.hash);if(!current)return res.status(404).json({success:false,error:{code:'RETAIL_NOT_FOUND',message:'Preço publicado não encontrado.'}});const price=Math.round(Number(req.body?.retail_credit_price));if(!Number.isInteger(price)||price<=0)return res.status(400).json({success:false,error:{code:'INVALID_RETAIL_PRICE',message:'Informe um preço válido em créditos.'}});const {version:_v,retail_pricing_id:_id,created_at:_c,updated_at:_u,...base}=current;const next=await retailPricingService.publish({...base,retail_credit_price:price,active:true} as any);return res.json({success:true,data:next});}catch(err:any){return res.status(500).json({success:false,error:{code:err?.code||'RETAIL_PUBLISH_FAILED',message:err?.message||'Não foi possível publicar a nova versão.'}});}});
