import { Router } from 'express';
import { requireAuth, requireAdmin, AuthenticatedRequest } from '../middleware/authMiddleware.js';
import { creditWalletService } from '../services/creditWalletService.js';
import { packCatalogService } from '../services/packCatalogService.js';
import { paymentService } from '../services/paymentService.js';
import { adminService } from '../services/adminService.js';
import { billingControlService } from '../services/billingControlService.js';
import { couponService } from '../services/couponService.js';

export const creditRuntimeRouter=Router();

creditRuntimeRouter.get('/credits/account',requireAuth,async(req:AuthenticatedRequest,res)=>{try{res.json({success:true,data:await creditWalletService.getAccount(req.user!.uid)});}catch(err:any){res.status(500).json({success:false,error:{code:'CREDIT_ACCOUNT_ERROR',message:err?.message||'Não foi possível carregar os créditos.'}});}});
creditRuntimeRouter.get('/credits/transactions',requireAuth,async(req:AuthenticatedRequest,res)=>{try{const rows=await creditWalletService.listTransactions(req.user!.uid,Number(req.query.limit||50));res.json({success:true,data:{transactions:rows,total:rows.length}});}catch(err:any){res.status(500).json({success:false,error:{code:'CREDIT_LEDGER_ERROR',message:err?.message||'Não foi possível carregar as movimentações.'}});}});
creditRuntimeRouter.get('/credits/packs',requireAuth,(_req,res)=>res.json({success:true,data:packCatalogService.list()}));
creditRuntimeRouter.post('/credits/coupon/inspect',requireAuth,async(req:AuthenticatedRequest,res)=>{try{const packId=String(req.body?.pack_id||''),version=Number(req.body?.pack_version),pack=packId?packCatalogService.get(packId,version):undefined;const data=await couponService.inspect(req.user!.uid,String(req.body?.coupon_code||''),pack||undefined);return res.json({success:true,data});}catch(err:any){return res.status(400).json({success:false,error:{code:err?.code||'COUPON_INVALID',message:err?.message||'Não foi possível verificar este cupom.'}});}});
creditRuntimeRouter.post('/credits/coupon/redeem',requireAuth,async(req:AuthenticatedRequest,res)=>{try{const data=await couponService.redeemDirect(req.user!.uid,String(req.body?.coupon_code||''));return res.json({success:true,data});}catch(err:any){return res.status(400).json({success:false,error:{code:err?.code||'COUPON_REDEEM_ERROR',message:err?.message||'Não foi possível resgatar este cupom.'}});}});
creditRuntimeRouter.post('/credits/coupon/quote',requireAuth,async(req:AuthenticatedRequest,res)=>{try{const pack=packCatalogService.get(String(req.body?.pack_id||''),Number(req.body?.pack_version));if(!pack)return res.status(409).json({success:false,error:{code:'PACK_VERSION_STALE',message:'Atualize os packs antes de aplicar o cupom.'}});const quote=await couponService.quote(req.user!.uid,String(req.body?.coupon_code||''),pack);return res.json({success:true,data:quote});}catch(err:any){return res.status(400).json({success:false,error:{code:err?.code||'COUPON_INVALID',message:err?.message||'Não foi possível aplicar este cupom.'}});}});
creditRuntimeRouter.post('/credits/purchase',requireAuth,async(req:AuthenticatedRequest,res)=>{try{const controls=await billingControlService.get(false);if(!controls.credit_v2_enabled)return res.status(503).json({success:false,error:{code:'CREDIT_BILLING_DISABLED',message:'A compra de créditos está temporariamente indisponível.'}});const packId=String(req.body?.pack_id||''),packVersion=Number(req.body?.pack_version),pack=packCatalogService.get(packId,packVersion);if(!pack)return res.status(409).json({success:false,error:{code:'PACK_VERSION_STALE',message:'Este pack foi atualizado. Recarregue os packs antes de pagar.'}});const payment=await paymentService.createPayment({userId:req.user!.uid,amount_cents:pack.price_brl_cents,method:'PIX',pack_id:pack.pack_id,pack_version:pack.version,coupon_code:String(req.body?.coupon_code||'').trim()||undefined});return res.json({success:true,data:payment});}catch(err:any){return res.status(err?.code==='CREDIT_BILLING_DISABLED'?503:400).json({success:false,error:{code:err?.code||'CREDIT_PURCHASE_ERROR',message:err?.message||'Não foi possível iniciar a compra de créditos.'}});}});
creditRuntimeRouter.post('/admin/users/:userId/adjust-credits',requireAuth,requireAdmin,async(req:AuthenticatedRequest,res)=>{try{const type=String(req.body?.type||'') as 'ADMIN_CREDIT'|'ADMIN_DEBIT',amount=Number(req.body?.amount_credits),reason=String(req.body?.reason||''),key=String(req.body?.idempotency_key||`credit-adj:${Date.now()}:${Math.random()}`);if(!['ADMIN_CREDIT','ADMIN_DEBIT'].includes(type))return res.status(400).json({success:false,error:{code:'INVALID_TYPE',message:'Tipo de ajuste inválido.'}});const account=await adminService.adjustCredits({adminId:req.user!.uid,adminEmail:req.user!.email||'',targetUserId:req.params.userId,type,amount_credits:amount,reason,idempotency_key:key});return res.json({success:true,data:{account}});}catch(err:any){return res.status(err?.code==='CREDIT_INSUFFICIENT_FUNDS'?400:500).json({success:false,error:{code:err?.code||'CREDIT_ADJUST_ERROR',message:err?.message||'Não foi possível ajustar créditos.'}});}});
creditRuntimeRouter.get('/admin/coupons',requireAuth,requireAdmin,async(_req,res)=>{try{return res.json({success:true,data:await couponService.listAdmin()});}catch(err:any){return res.status(500).json({success:false,error:{code:'COUPON_LIST_ERROR',message:err?.message||'Falha ao listar cupons.'}});}});
creditRuntimeRouter.post('/admin/coupons',requireAuth,requireAdmin,async(req:AuthenticatedRequest,res)=>{try{return res.json({success:true,data:await couponService.publish(req.body||{},req.user!.uid)});}catch(err:any){return res.status(400).json({success:false,error:{code:err?.code||'COUPON_SAVE_ERROR',message:err?.message||'Falha ao publicar cupom.'}});}});
creditRuntimeRouter.post('/admin/coupons/:code/status',requireAuth,requireAdmin,async(req:AuthenticatedRequest,res)=>{try{return res.json({success:true,data:await couponService.setActive(req.params.code,Boolean(req.body?.active),req.user!.uid)});}catch(err:any){return res.status(400).json({success:false,error:{code:err?.code||'COUPON_STATUS_ERROR',message:err?.message||'Falha ao alterar cupom.'}});}});
