import { Router, json } from 'express';
import { serverTimingMiddleware } from '../middleware/serverTiming.js';
import { systemRouter } from './systemRoutes.js';
import { authRouter } from './authRoutes.js';
import { creditRouter } from './creditRoutes.js';
import { paymentRouter } from './paymentRoutes.js';
import { catalogRouter } from './catalogRoutes.js';
import { assetRouter } from './assetRoutes.js';
import { workspaceRouter } from './workspaceRoutes.js';
import { entityRouter } from './entityRoutes.js';
import { generationRouter } from './generationRoutes.js';
import { communityRouter } from './communityRoutes.js';
import { adminRouter } from './adminRoutes.js';
import { adminBillingRouter } from './adminBillingRoutes.js';
import { adminEconomicsRouter } from './adminEconomicsRoutes.js';
import { adminRoutingV2Router } from './adminRoutingV2Routes.js';
import { spacesRouter } from './spacesRoutes.js';
import { betaCapabilityRouter } from './betaCapabilityRoutes.js';
import { betaJobRouter } from './betaJobRoutes.js';
import { betaTaskRouter } from './betaTaskRoutes.js';
import { betaAssetRouter } from './betaAssetRoutes.js';
import { betaLibraryRouter } from './betaLibraryRoutes.js';
import { betaAudioRouter } from './betaAudioRoutes.js';
import { betaFlowRouter } from './betaFlowRoutes.js';
import { betaFlowRuntimeRouter } from './betaFlowRuntimeRoutes.js';
import { betaTemplateRouter } from './betaTemplateRoutes.js';
import { betaWorkflowAppRouter } from './betaWorkflowAppRoutes.js';
import { betaBatchRouter } from './betaBatchRoutes.js';
import { betaContextRouter } from './betaContextRoutes.js';
import { betaCopilotRouter } from './betaCopilotRoutes.js';
import { betaSharingRouter } from './betaSharingRoutes.js';
import { previewRoutingV2ValidationRouter } from './previewRoutingV2ValidationRoutes.js';

export const apiRootRouter = Router();
apiRootRouter.use(serverTimingMiddleware);
apiRootRouter.use(json({ limit: '4mb' }));
apiRootRouter.use(systemRouter);
apiRootRouter.use(authRouter);
apiRootRouter.use(creditRouter);
apiRootRouter.use(paymentRouter);
apiRootRouter.use(catalogRouter);
apiRootRouter.use(assetRouter);
apiRootRouter.use(workspaceRouter);
apiRootRouter.use(entityRouter);
apiRootRouter.use(generationRouter);
apiRootRouter.use(communityRouter);
apiRootRouter.use(previewRoutingV2ValidationRouter);
apiRootRouter.use(adminRouter);
apiRootRouter.use(adminBillingRouter);
apiRootRouter.use(adminEconomicsRouter);
apiRootRouter.use(spacesRouter);
apiRootRouter.use(betaCapabilityRouter);
apiRootRouter.use(betaJobRouter);
apiRootRouter.use(betaTaskRouter);
apiRootRouter.use(betaAssetRouter);
apiRootRouter.use(betaLibraryRouter);
apiRootRouter.use(betaAudioRouter);
apiRootRouter.use(betaFlowRouter);
apiRootRouter.use(betaFlowRuntimeRouter);
apiRootRouter.use(betaTemplateRouter);
apiRootRouter.use(betaWorkflowAppRouter);
apiRootRouter.use(betaBatchRouter);
apiRootRouter.use(betaContextRouter);
apiRootRouter.use(betaCopilotRouter);
apiRootRouter.use(betaSharingRouter);
apiRootRouter.use(adminRoutingV2Router);
