import { Router } from 'express';
import { requireAuth, AuthenticatedRequest } from '../middleware/authMiddleware.js';
import { GenerationMode } from '../../src/types/index.js';
import { creditPricingService } from '../services/creditPricingService.js';

export const pricingRuntimeRouter=Router();

pricingRuntimeRouter.post('/workspace/validate-and-preview',requireAuth,async(req:AuthenticatedRequest,res)=>{
 try{
  const uid=req.user!.uid;const{model_id,mode,prompt,negative_prompt,references,settings}=req.body||{};if(!model_id||!prompt?.trim())return res.status(400).json({success:false,error:{code:'VALIDATION_ERROR',message:'Modelo e prompt são obrigatórios.'}});
  const generationMode=String(mode||'TEXT_TO_VIDEO') as GenerationMode;const imageMode=generationMode==='TEXT_TO_IMAGE'||generationMode==='IMAGE_TO_IMAGE';const duration=imageMode?1:Math.max(1,Number(settings?.duration_seconds||5));const resolution=String(settings?.resolution||(imageMode?'1K':'720p'));const aspectRatio=String(settings?.aspect_ratio||'16:9');const outputs=Math.max(1,Math.min(4,Number(settings?.number_of_outputs||1)));
  const quote=await creditPricingService.preview({userId:uid,model_id,mode:generationMode,prompt:String(prompt).trim(),negative_prompt,duration_seconds:duration,resolution,aspect_ratio:aspectRatio,number_of_outputs:outputs,seed:settings?.seed,motion_strength:settings?.motion_strength,references:references||[],audio_enabled:settings?.audio_enabled===undefined?undefined:Boolean(settings.audio_enabled),model_variant:settings?.model_variant,pricing_options:settings?.pricing_options});const price=quote.retail.retail_credit_price,available=quote.account.available_credits;const requestId=`req_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
  return res.json({success:true,data:{request_draft:{request_id:requestId,user_id:uid,model_id,mode:generationMode,prompt:String(prompt).trim(),negative_prompt,references:references||[],settings:{duration_seconds:duration,resolution,aspect_ratio:aspectRatio,number_of_outputs:outputs,seed:settings?.seed??null,motion_strength:settings?.motion_strength,audio_enabled:quote.signature.audio_enabled,model_variant:quote.signature.model_variant,pricing_options:quote.signature.pricing_options},has_pricing:true,retail_credit_price:price,authorized_credit_price:price,credit_balance_available:available,balance_after_generation_credits:available-price,has_sufficient_funds:available>=price,pricing_signature_hash:quote.signature.hash,retail_pricing_id:quote.retail.retail_pricing_id,retail_pricing_version:quote.retail.version,pricing_health:quote.health,max_allowed_cogs_cents:quote.max_allowed_cogs_cents,
  estimated_cost_cents:price,customer_balance_available_cents:available,balance_after_generation_cents:available-price,
  pricing_snapshot:{provider_id:quote.decision.selected.provider_id,provider_cost_usd:quote.decision.selected.provider_cost_usd,provider_cost_brl_cents:quote.decision.selected.provider_cost_cents,safe_cost_brl_cents:quote.decision.selected.safe_cost_cents,fully_loaded_safe_cogs_cents:quote.decision.selected.fully_loaded_safe_cogs_cents,retail_credit_price:price,margin_percent:quote.margin_percent,quoted_at:quote.decision.selected.quoted_at,quote_estimated:quote.decision.selected.quote_estimated},created_at:new Date().toISOString()},notice:`Preço fixo: ${price.toLocaleString('pt-BR')} créditos. Custos de provider são validados em segundo plano e não alteram este preço automaticamente.`}});
 }catch(err:any){const code=err?.code||'CREDIT_PRICING_FAILED';const status=code==='NO_SAFE_PROVIDER_AVAILABLE'?503:code==='CREDIT_INSUFFICIENT_FUNDS'?402:400;return res.status(status).json({success:false,error:{code,message:err?.message||'Não foi possível validar esta configuração em créditos.'}});}
});
