import express from 'express';
import path from 'path';
import crypto from 'crypto';
import { requireAuth, AuthenticatedRequest } from '../middleware/authMiddleware.js';
import { getAdminStorage } from '../repositories/firebaseAdminClient.js';
import { getFirebaseConfig } from '../repositories/firestoreClient.js';
import { assetRepository, sanitizeAlias } from '../repositories/assetRepository.js';
import { catalogRepository } from '../repositories/catalogRepository.js';
import { smartRouterService } from '../services/smartRouterService.js';
import { walletService } from '../services/walletService.js';
import { promptCompilerService } from '../services/promptCompilerService.js';
import { ASSET_UPLOAD_LIMITS } from '../../src/config/constants.js';
import { AssetType, AssetCategory, GenerationMode } from '../../src/types/index.js';

export const runtimeRouter=express.Router();
const rawUpload=express.raw({type:()=>true,limit:'500mb'});const jsonBody=express.json({limit:'4mb'});
function classify(mime:string,filename:string):AssetType{const ext=path.extname(filename).slice(1).toLowerCase();if(mime.startsWith('video/')||ASSET_UPLOAD_LIMITS.VIDEO.allowed_extensions.includes(ext))return'VIDEO';if(mime.startsWith('audio/')||ASSET_UPLOAD_LIMITS.AUDIO.allowed_extensions.includes(ext))return'AUDIO';return'IMAGE';}

runtimeRouter.post('/assets/upload',requireAuth,rawUpload,async(req:AuthenticatedRequest,res)=>{const uid=req.user!.uid;try{const body=req.body as Buffer;if(!Buffer.isBuffer(body)||!body.length)return res.status(400).json({success:false,error:{code:'EMPTY_FILE',message:'Arquivo vazio ou inválido.'}});const originalName=decodeURIComponent(String(req.header('x-file-name')||'asset.bin'));const displayName=decodeURIComponent(String(req.header('x-asset-name')||originalName));const alias=sanitizeAlias(decodeURIComponent(String(req.header('x-asset-alias')||displayName)));const category=(String(req.header('x-asset-category')||'GENERIC').toUpperCase()) as AssetCategory;const mime=String(req.header('content-type')||'application/octet-stream').split(';')[0];const type=classify(mime,originalName);if(body.length>ASSET_UPLOAD_LIMITS[type].max_bytes)return res.status(413).json({success:false,error:{code:'FILE_TOO_LARGE',message:'Arquivo excede o limite permitido.'}});const storage=getAdminStorage(),cfg=getFirebaseConfig();if(!storage||!cfg.storageBucket)return res.status(503).json({success:false,error:{code:'STORAGE_NOT_CONFIGURED',message:'Firebase Storage ainda não está provisionado.'}});const bucket=storage.bucket(cfg.storageBucket);const tempId=`ast_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`;const ext=path.extname(originalName).replace(/[^.a-zA-Z0-9]/g,'').toLowerCase();const storagePath=`users/${uid}/assets/${tempId}/original${ext}`;const file=bucket.file(storagePath);await file.save(body,{resumable:false,contentType:mime,metadata:{cacheControl:'private,max-age=3600'}});try{const asset=await assetRepository.createAsset({owner_user_id:uid,type,category,name:displayName,alias,storage_path:storagePath,mime_type:mime,size_bytes:body.length,status:'READY'});return res.json({success:true,data:asset});}catch(err){await file.delete({ignoreNotFound:true}).catch(()=>{});throw err;}}catch(err:any){console.error('[AssetUpload]',err?.code||err?.message);return res.status(500).json({success:false,error:{code:'ASSET_UPLOAD_FAILED',message:err?.message||'Falha ao enviar asset.'}});}});

runtimeRouter.get('/assets/:assetId/content',requireAuth,async(req:AuthenticatedRequest,res)=>{try{const asset=await assetRepository.getAsset(req.params.assetId,req.user!.uid);if(!asset)return res.status(404).end();const storage=getAdminStorage(),cfg=getFirebaseConfig();if(!storage||!cfg.storageBucket)return res.status(503).end();res.setHeader('Content-Type',asset.mime_type||'application/octet-stream');res.setHeader('Cache-Control','private,max-age=300');storage.bucket(cfg.storageBucket).file(asset.storage_path).createReadStream().on('error',()=>res.status(404).end()).pipe(res);}catch{res.status(500).end();}});

// Accurate quote/preview route mounted before the legacy Stage-2 handler.
runtimeRouter.post('/workspace/validate-and-preview',requireAuth,jsonBody,async(req:AuthenticatedRequest,res)=>{try{const uid=req.user!.uid;const {model_id,mode,prompt,negative_prompt,references=[],settings={}}=req.body;if(!prompt?.trim())return res.status(400).json({success:false,error:{code:'VALIDATION_ERROR',message:'O prompt é obrigatório.'}});const model=await catalogRepository.getModel(model_id);if(!model||model.status==='INACTIVE')return res.status(400).json({success:false,error:{code:'MODEL_NOT_FOUND',message:'Modelo indisponível.'}});const resolvedMode=(mode||'TEXT_TO_VIDEO') as GenerationMode;let quote:any=null;try{quote=await smartRouterService.selectProvider({userId:uid,model_id:model.model_id,mode:resolvedMode,duration_seconds:Number(settings.duration_seconds||5),resolution:String(settings.resolution||'720p'),number_of_outputs:Number(settings.number_of_outputs||1)});}catch(e:any){if(e?.code!=='NO_PROVIDER_AVAILABLE')throw e;}const wallet=await walletService.getSummary(uid);const estimated=quote?.selected?.customer_price_cents??null;const compiled=promptCompilerService.compile({original_prompt:prompt,references,negative_prompt,generation_settings:{model_id:model.model_id,mode:resolvedMode,duration_seconds:Number(settings.duration_seconds||5),resolution:String(settings.resolution||'720p'),aspect_ratio:String(settings.aspect_ratio||'16:9')}});const requestDraft={request_id:`req_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,user_id:uid,model_id:model.model_id,model_name:model.name,mode:resolvedMode,prompt:prompt.trim(),compiled_prompt:compiled.compiled_prompt,prompt_compiler_version:compiled.prompt_compiler_version,references,settings:{...settings,duration_seconds:Number(settings.duration_seconds||5),resolution:String(settings.resolution||'720p'),aspect_ratio:String(settings.aspect_ratio||'16:9'),number_of_outputs:Number(settings.number_of_outputs||1)},estimated_cost_cents:estimated,customer_balance_available_cents:wallet.available_balance_cents,balance_after_generation_cents:estimated==null?wallet.available_balance_cents:wallet.available_balance_cents-estimated,has_sufficient_funds:estimated!=null&&wallet.available_balance_cents>=estimated,created_at:new Date().toISOString()};return res.json({success:true,data:{request_draft:requestDraft,notice:estimated!=null?'Preço calculado pela rota configurada mais econômica. Nenhum saldo foi debitado ainda.':'Nenhum provider configurado e precificado está disponível para esta combinação.'}});}catch(err:any){return res.status(400).json({success:false,error:{code:err?.code||'VALIDATION_FAILED',message:err?.message||'Falha na validação.'}});}});
