import React,{useEffect,useMemo,useState}from'react';
import{Activity,Boxes,Database,HeartPulse,Plus,RefreshCw,Route,Search,Server,Settings2,ShieldCheck}from'lucide-react';
import{routingV2AdminService,RoutingV2BillingType,RoutingV2CatalogModelAdmin,RoutingV2CutoverAdmin,RoutingV2HealthAdmin,RoutingV2ReadinessAdmin,RoutingV2ModelAdmin,RoutingV2PricingSettingsAdmin,RoutingV2ProviderAdmin,RoutingV2RouteAdmin}from'../../services/routingV2AdminService.js';

type Tab='providers'|'models'|'routes'|'pricing'|'health';
const input='h-9 w-full rounded-lg border border-white/[0.08] bg-[#07111a] px-3 text-[11px] text-white outline-none focus:border-sky-300/30';
const btn='h-9 rounded-lg border border-white/[0.09] bg-white/[0.04] px-3 text-[10px] font-bold text-zinc-200 hover:bg-white/[0.07] disabled:opacity-40';
const primary='h-9 rounded-lg bg-sky-300 px-3 text-[10px] font-black text-[#061015] hover:bg-sky-200 disabled:opacity-40';
const panel='rounded-2xl border border-white/[0.07] bg-[#08131e]';
const caps=(value:string)=>Array.from(new Set(value.split(',').map(v=>v.trim()).filter(Boolean)));

export const AdminRoutingV2:React.FC=()=>{
 const[tab,setTab]=useState<Tab>('providers'),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const[providers,setProviders]=useState<RoutingV2ProviderAdmin[]>([]),[models,setModels]=useState<RoutingV2ModelAdmin[]>([]),[routes,setRoutes]=useState<RoutingV2RouteAdmin[]>([]);
 const[pricing,setPricing]=useState<RoutingV2PricingSettingsAdmin|null>(null),[health,setHealth]=useState<RoutingV2HealthAdmin|null>(null),[readiness,setReadiness]=useState<RoutingV2ReadinessAdmin|null>(null),[cutover,setCutover]=useState<RoutingV2CutoverAdmin|null>(null);
 const[pName,setPName]=useState(''),[pId,setPId]=useState(''),[pType,setPType]=useState<'AGGREGATOR'|'OFFICIAL'>('AGGREGATOR');
 const[mId,setMId]=useState(''),[mName,setMName]=useState(''),[mVendor,setMVendor]=useState(''),[mCategory,setMCategory]=useState<'VIDEO'|'IMAGE'|'AUDIO'|'MODEL_3D'|'OTHER'>('VIDEO'),[mCaps,setMCaps]=useState('');
 const[rModel,setRModel]=useState(''),[rCap,setRCap]=useState(''),[rProvider,setRProvider]=useState(''),[rIdentifier,setRIdentifier]=useState(''),[rBilling,setRBilling]=useState<RoutingV2BillingType>('PER_GENERATION'),[rUnitPrice,setRUnitPrice]=useState('0'),[rPriority,setRPriority]=useState('100'),[rFormulaId,setRFormulaId]=useState('');
 const[catalogProvider,setCatalogProvider]=useState(''),[catalogQuery,setCatalogQuery]=useState(''),[catalogRows,setCatalogRows]=useState<RoutingV2CatalogModelAdmin[]>([]),[catalogLoading,setCatalogLoading]=useState(false);

 const load=async()=>{
  setLoading(true);setMessage('');
  try{
   const[p,m,r,s,h,ma,co]=await Promise.all([routingV2AdminService.listProviders(),routingV2AdminService.listModels(),routingV2AdminService.listRoutes(),routingV2AdminService.getPricingSettings(),routingV2AdminService.getHealth(),routingV2AdminService.getReadiness(),routingV2AdminService.getCutover()]);
   setProviders(p);setModels(m);setRoutes(r);setPricing(s);setHealth(h);setReadiness(ma);setCutover(co);
   if(!rModel&&m[0])setRModel(m[0].model_id);if(!rProvider&&p[0])setRProvider(p[0].provider_id);if(!catalogProvider&&p[0])setCatalogProvider(p[0].provider_id);
  }catch(e:any){setMessage(e?.message||'Falha ao carregar Routing Core V2.')}finally{setLoading(false)}
 };
 useEffect(()=>{void load()},[]);
 const modelById=useMemo(()=>new Map(models.map(m=>[m.model_id,m])),[models]),providerById=useMemo(()=>new Map(providers.map(p=>[p.provider_id,p])),[providers]);

 const billingConfig=()=>{
  const value=Math.max(0,Number(rUnitPrice)||0);
  if(rBilling==='PER_GENERATION')return{type:rBilling,currency:'USD',price_per_generation:value};
  if(rBilling==='PER_OUTPUT')return{type:rBilling,currency:'USD',price_per_output:value};
  if(rBilling==='PER_SECOND')return{type:rBilling,currency:'USD',price_per_second:value};
  if(rBilling==='PER_MINUTE')return{type:rBilling,currency:'USD',price_per_minute:value};
  if(rBilling==='PER_CHARACTER')return{type:rBilling,currency:'USD',price_per_unit:value,characters_per_unit:1000};
  if(rBilling==='FIXED_MATRIX')return{type:rBilling,currency:'USD',entries:[{match:{default:true},price:value}]};
  return{type:rBilling,currency:'USD',formula_id:rFormulaId.trim()};
 };
 const createProvider=async()=>{try{await routingV2AdminService.createProvider({provider_id:pId.trim(),name:pName.trim(),type:pType,priority:100});setPId('');setPName('');await load();setMessage('Provider V2 criado.')}catch(e:any){setMessage(e?.message||'Falha ao criar provider.')}};
 const bootstrapCoreProviders=async()=>{try{const r=await routingV2AdminService.bootstrapCoreProviders();await load();const created=r.created?.length||0,existing=r.existing?.length||0,failed=r.failed?.length||0;setMessage(`Providers base: ${created} criado(s), ${existing} já existente(s), ${failed} falha(s).`);}catch(e:any){setMessage(e?.message||'Falha ao cadastrar providers base.')}};
 const createModel=async()=>{try{await routingV2AdminService.createModel({model_id:mId.trim(),name:mName.trim(),vendor:mVendor.trim(),category:mCategory,description:'',capabilities:caps(mCaps)});setMId('');setMName('');setMVendor('');setMCaps('');await load();setMessage('Model V2 criado.')}catch(e:any){setMessage(e?.message||'Falha ao criar model.')}};
 const createRoute=async()=>{try{await routingV2AdminService.createRoute({model_id:rModel,capability_id:rCap.trim(),provider_id:rProvider,provider_model_identifier:rIdentifier.trim(),billing_config:billingConfig(),priority:Number(rPriority)||100});setRIdentifier('');setRCap('');await load();setMessage('Route V2 criada em MAPPED.')}catch(e:any){setMessage(e?.message||'Falha ao criar Route.')}};
 const searchCatalog=async()=>{if(!catalogProvider)return;setCatalogLoading(true);try{setCatalogRows(await routingV2AdminService.searchProviderModels(catalogProvider,catalogQuery));}catch(e:any){setCatalogRows([]);setMessage(e?.message||'Catálogo não disponível.')}finally{setCatalogLoading(false)}};
 const importCatalogModel=(row:RoutingV2CatalogModelAdmin)=>{setMId(row.provider_model_identifier.replace(/[^a-zA-Z0-9._-]+/g,'-').toLowerCase());setMName(row.name);setMVendor(row.vendor||providerById.get(catalogProvider)?.name||'');setMCaps((row.capabilities||[]).join(','));setTab('models');setMessage('Modelo carregado do catálogo para revisão. Confirme categoria e capabilities antes de salvar.');};
 const savePricing=async()=>{if(!pricing)return;try{const next=await routingV2AdminService.savePricingSettings(pricing);setPricing(next);setMessage('Economics V2 atualizado.')}catch(e:any){setMessage(e?.message||'Falha ao salvar pricing.')}};
 const syncPricing=async()=>{try{let cursor=0,updated=0,failed=0;for(let i=0;i<50;i++){const r=await routingV2AdminService.syncPricing(cursor,10);updated+=Number(r.updated||0);failed+=Number(r.failed||0);if(r.done||r.next_cursor==null)break;cursor=r.next_cursor;}await load();setMessage(`Sync V2 concluído: ${updated} atualizada(s), ${failed} falha(s).`);}catch(e:any){setMessage(e?.message||'Falha no sync V2.')}};
 const changeCutover=async()=>{try{const next=await routingV2AdminService.setCutover('HYBRID');setCutover(next);setMessage('Modo HYBRID confirmado.');}catch(e:any){setMessage(e?.message||'Não foi possível confirmar o modo HYBRID.')}};

 const tabs:[Tab,string,React.ReactNode][]=[['providers','Providers',<Server className="w-3.5 h-3.5"/>],['models','Modelos',<Boxes className="w-3.5 h-3.5"/>],['routes','Rotas',<Route className="w-3.5 h-3.5"/>],['pricing','Pricing',<Database className="w-3.5 h-3.5"/>],['health','Health',<HeartPulse className="w-3.5 h-3.5"/>]];
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-sky-300"/><h2 className="text-sm font-black text-white">IA & Roteamento</h2><span className="rounded-full border border-amber-300/20 bg-amber-300/[0.07] px-2 py-1 text-[9px] font-bold text-amber-200">{cutover?.mode||'HYBRID'}</span></div><p className="mt-1 text-[10px] text-zinc-500">Inventário único. Somente rotas READY são publicadas para os geradores.</p></div><button className={btn} onClick={()=>void load()}><RefreshCw className="mr-1.5 inline w-3 h-3"/>Atualizar</button></div>
  <div className="flex gap-1 overflow-x-auto">{tabs.map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)} className={`h-9 whitespace-nowrap rounded-lg px-3 text-[10px] font-bold ${tab===id?'bg-sky-300 text-[#061015]':'border border-white/[0.07] text-zinc-400'}`}>{icon}<span className="ml-1.5">{label}</span></button>)}</div>
  {message&&<div className="rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-[10px] text-zinc-300">{message}</div>}
  {loading?<div className={panel+" p-8 text-center text-xs text-zinc-500"}>Carregando V2...</div>:<>
   {tab==='providers'&&<div className="space-y-3">
    <div className={panel+" p-4"}><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-xs font-bold text-white">Adicionar provider</h3><p className="mt-1 text-[9px] text-zinc-600">Base inicial recomendada: WaveSpeed, Atlas Cloud e Runware. O cadastro é idempotente e pode ser executado em produção.</p></div><button className={primary} onClick={bootstrapCoreProviders}>Cadastrar 3 providers base</button></div><p className="mt-1 text-[9px] text-zinc-600">Este botão cadastra apenas a configuração dos providers. As API keys precisam existir como secrets no servidor e nunca são armazenadas neste painel.</p><div className="mt-3 grid gap-2 md:grid-cols-3"><input className={input} placeholder="provider-id" value={pId} onChange={e=>setPId(e.target.value)}/><input className={input} placeholder="Nome" value={pName} onChange={e=>setPName(e.target.value)}/><select className={input} value={pType} onChange={e=>setPType(e.target.value as any)}><option>AGGREGATOR</option><option>OFFICIAL</option></select></div><button className={primary+" mt-2"} onClick={createProvider}><Plus className="mr-1 inline w-3 h-3"/>Criar provider</button></div>
    <div className={panel+" overflow-x-auto"}><table className="w-full min-w-[760px] text-[10px]"><thead className="border-b border-white/[0.06] text-zinc-600"><tr><th className="p-3 text-left">Provider</th><th>Tipo</th><th>Status</th><th>Health</th><th>Balance</th><th>Recursos</th><th></th></tr></thead><tbody className="divide-y divide-white/[0.05]">{providers.map(p=><tr key={p.provider_id}><td className="p-3"><div className="font-bold text-white">{p.name}</div><div className="text-zinc-600">{p.provider_id}</div></td><td className="text-center text-zinc-300">{p.type}</td><td className="text-center text-zinc-300">{p.status}</td><td className="text-center text-zinc-300">{p.health_status}</td><td className="text-center text-zinc-300">{p.balance_amount==null?'—':`${p.balance_amount} ${p.balance_currency||''}`}</td><td className="text-center text-zinc-500">{p.supports_catalog_sync?'catálogo ':''}{p.supports_pricing_sync?'pricing ':''}{p.supports_balance?'saldo':''}</td><td className="p-2 text-right">{p.status!=='DISABLED'&&<button className={btn} onClick={async()=>{await routingV2AdminService.disableProvider(p.provider_id);await load()}}>Desativar</button>}</td></tr>)}</tbody></table></div>
    <div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Buscar modelos no provider</h3><div className="mt-3 flex flex-wrap gap-2"><select className={input+" max-w-xs"} value={catalogProvider} onChange={e=>setCatalogProvider(e.target.value)}>{providers.map(p=><option key={p.provider_id} value={p.provider_id}>{p.name}</option>)}</select><input className={input+" max-w-xs"} placeholder="Pesquisar modelo" value={catalogQuery} onChange={e=>setCatalogQuery(e.target.value)}/><button className={btn} disabled={catalogLoading} onClick={searchCatalog}><Search className="mr-1 inline w-3 h-3"/>Buscar</button></div>{catalogRows.length>0&&<div className="mt-3 divide-y divide-white/[0.05]">{catalogRows.map(row=><div key={row.provider_model_identifier} className="flex items-center justify-between gap-3 py-2"><div><div className="text-[10px] font-bold text-white">{row.name}</div><div className="font-mono text-[9px] text-zinc-600">{row.provider_model_identifier}</div></div><button className={btn} onClick={()=>importCatalogModel(row)}>Usar no cadastro</button></div>)}</div>}</div>
   </div>}
   {tab==='models'&&<div className="space-y-3">
    <div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Adicionar model</h3><div className="mt-3 grid gap-2 md:grid-cols-5"><input className={input} placeholder="model-id" value={mId} onChange={e=>setMId(e.target.value)}/><input className={input} placeholder="Nome" value={mName} onChange={e=>setMName(e.target.value)}/><input className={input} placeholder="Vendor" value={mVendor} onChange={e=>setMVendor(e.target.value)}/><select className={input} value={mCategory} onChange={e=>setMCategory(e.target.value as any)}><option>VIDEO</option><option>IMAGE</option><option>AUDIO</option><option>MODEL_3D</option><option>OTHER</option></select><input className={input} placeholder="capabilities, separadas por vírgula" value={mCaps} onChange={e=>setMCaps(e.target.value)}/></div><button className={primary+" mt-2"} onClick={createModel}><Plus className="mr-1 inline w-3 h-3"/>Criar model</button></div>
    <div className={panel+" overflow-x-auto"}><table className="w-full min-w-[760px] text-[10px]"><thead className="border-b border-white/[0.06] text-zinc-600"><tr><th className="p-3 text-left">Model</th><th>Vendor</th><th>Categoria</th><th>Capabilities</th><th>Status</th><th></th></tr></thead><tbody className="divide-y divide-white/[0.05]">{models.map(m=><tr key={m.model_id}><td className="p-3"><div className="font-bold text-white">{m.name}</div><div className="text-zinc-600">{m.model_id}</div></td><td className="text-center text-zinc-300">{m.vendor}</td><td className="text-center text-zinc-300">{m.category}</td><td className="max-w-[340px] px-3 text-zinc-400">{m.capabilities.join(', ')}</td><td className="text-center text-zinc-300">{m.status}</td><td className="p-2 text-right">{m.status==='ACTIVE'&&<button className={btn} onClick={async()=>{await routingV2AdminService.disableModel(m.model_id);await load()}}>Desativar</button>}</td></tr>)}</tbody></table></div>
   </div>}
   {tab==='routes'&&<div className="space-y-3">
    <div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Criar Route</h3><p className="mt-1 text-[9px] text-zinc-600">A Route nasce MAPPED. READY só será derivado depois de pricing CURRENT + runtime HEALTHY.</p><div className="mt-3 grid gap-2 md:grid-cols-4"><select className={input} value={rModel} onChange={e=>setRModel(e.target.value)}>{models.filter(m=>m.status==='ACTIVE').map(m=><option key={m.model_id} value={m.model_id}>{m.name}</option>)}</select><input className={input} placeholder="capability_id" value={rCap} onChange={e=>setRCap(e.target.value)}/><select className={input} value={rProvider} onChange={e=>setRProvider(e.target.value)}>{providers.filter(p=>p.status!=='DISABLED').map(p=><option key={p.provider_id} value={p.provider_id}>{p.name}</option>)}</select><input className={input} placeholder="provider_model_identifier" value={rIdentifier} onChange={e=>setRIdentifier(e.target.value)}/><select className={input} value={rBilling} onChange={e=>setRBilling(e.target.value as RoutingV2BillingType)}>{['PER_GENERATION','PER_OUTPUT','PER_SECOND','PER_MINUTE','PER_CHARACTER','FIXED_MATRIX','CUSTOM_FORMULA'].map(x=><option key={x}>{x}</option>)}</select><input className={input} type="number" step="0.000001" min="0" placeholder="Preço unitário provider" value={rUnitPrice} onChange={e=>setRUnitPrice(e.target.value)}/><input className={input} type="number" placeholder="Prioridade" value={rPriority} onChange={e=>setRPriority(e.target.value)}/>{rBilling==='CUSTOM_FORMULA'&&<input className={input} placeholder="formula_id registrada no adapter" value={rFormulaId} onChange={e=>setRFormulaId(e.target.value)}/>}</div><button className={primary+" mt-2"} onClick={createRoute}><Plus className="mr-1 inline w-3 h-3"/>Criar Route</button></div>
    <div className={panel+" overflow-x-auto"}><table className="w-full min-w-[1150px] text-[10px]"><thead className="border-b border-white/[0.06] text-zinc-600"><tr><th className="p-3 text-left">Model / Capability</th><th>Provider</th><th>Identifier</th><th>Billing</th><th>Provider Cost</th><th>Safe COGS</th><th>Retail</th><th>Status</th><th>Last Sync</th><th></th></tr></thead><tbody className="divide-y divide-white/[0.05]">{routes.map(r=><tr key={r.route_id}><td className="p-3"><div className="font-bold text-white">{modelById.get(r.model_id)?.name||r.model_id}</div><div className="text-zinc-500">{r.capability_id}</div></td><td className="text-center text-zinc-300">{providerById.get(r.provider_id)?.name||r.provider_id}</td><td className="max-w-[260px] px-2 font-mono text-zinc-500">{r.provider_model_identifier}</td><td className="text-center text-zinc-400">{r.billing_type}</td><td className="text-center text-zinc-300">{r.pricing_snapshot?.provider_cost_reference??'—'}</td><td className="text-center text-zinc-300">{r.pricing_snapshot?.safe_cogs_brl==null?'—':`R$ ${r.pricing_snapshot.safe_cogs_brl.toFixed(4)}`}</td><td className="text-center font-bold text-white">{r.pricing_snapshot?.retail_price_credits==null?'—':`${r.pricing_snapshot.retail_price_credits} cr`}</td><td className="text-center"><div className={r.status==='READY'?'text-emerald-300':r.status==='DEGRADED'?'text-amber-300':'text-zinc-400'}>{r.status}</div><div className="text-[8px] text-zinc-600">{r.pricing_status} · {r.runtime_status}</div></td><td className="text-center text-zinc-500">{r.last_price_sync_at?new Date(r.last_price_sync_at).toLocaleString('pt-BR'):'—'}</td><td className="p-2 text-right">{r.status!=='DISABLED'&&<button className={btn} onClick={async()=>{await routingV2AdminService.disableRoute(r.route_id);await load()}}>Desativar</button>}</td></tr>)}</tbody></table></div>
   </div>}
   {tab==='pricing'&&pricing&&<div className="space-y-3"><div className={panel+" p-4"}><div className="flex items-center justify-between gap-3"><div><h3 className="text-xs font-bold text-white">Economics Engine</h3><p className="mt-1 text-[9px] text-zinc-600">Configuração econômica única para todas as Routes.</p></div><button className={btn} onClick={syncPricing}><RefreshCw className="mr-1 inline w-3 h-3"/>Sincronizar agora</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{([['target_margin_percent','Margem alvo (%)'],['safety_buffer_percent','Safety buffer (%)'],['reference_credit_value_brl','Valor referência / crédito (R$)'],['price_sync_interval_minutes','Sync (min)'],['price_freshness_ttl_minutes','TTL preço (min)'],['stale_grace_minutes','Grace stale (min)']] as const).map(([key,label])=><label key={key} className="text-[9px] text-zinc-500">{label}<input className={input+" mt-1"} type="number" step={key==='reference_credit_value_brl'?'0.0001':'1'} value={pricing[key]} onChange={e=>setPricing({...pricing,[key]:Number(e.target.value)})}/></label>)}</div><button className={primary+" mt-3"} onClick={savePricing}><Settings2 className="mr-1 inline w-3 h-3"/>Salvar economics</button></div></div>}
   {tab==='health'&&<div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Providers ativos',health?.providers.active||0],['Providers healthy',health?.providers.healthy||0],['Rotas READY',health?.routes.ready||0],['Rotas degradadas/stale',(health?.routes.degraded||0)+(health?.routes.stale||0)]].map(([label,value])=><div key={String(label)} className={panel+" p-4"}><Activity className="w-4 h-4 text-sky-300"/><div className="mt-2 text-[9px] text-zinc-600">{label}</div><div className="text-xl font-black text-white">{value}</div></div>)}</div><div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Readiness & modo operacional</h3><p className="mt-2 text-[10px] text-zinc-400">Cobertura READY: {readiness?.coverage.ready_model_capabilities||0}/{readiness?.coverage.required_model_capabilities||0} modelo-capability(s). Modo atual: <strong className="text-white">{cutover?.mode||'HYBRID'}</strong>.</p><p className="mt-1 text-[9px] text-zinc-600">HYBRID permanece obrigatório durante a reconstrução do inventário. V2_ONLY está bloqueado.</p><div className="mt-3"><button className={btn} disabled={cutover?.mode==='HYBRID'} onClick={changeCutover}>Confirmar HYBRID</button></div>{readiness?.coverage.missing?.length? <div className="mt-3 max-h-36 overflow-auto rounded-lg border border-white/[0.06] bg-black/10 p-2 text-[9px] text-zinc-500">{readiness.coverage.missing.slice(0,30).map(x=><div key={x.model_id+'|'+x.capability_id}>{x.model_id} · {x.capability_id}</div>)}{readiness.coverage.missing.length>30&&<div>+ {readiness.coverage.missing.length-30} pendência(s)</div>}</div>:null}</div><div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Estado operacional</h3><p className="mt-2 text-[10px] text-zinc-400">Modelos: {health?.models.active||0}/{health?.models.total||0} ativos · Rotas: {health?.routes.ready||0}/{health?.routes.total||0} READY · Desativadas: {health?.routes.disabled||0} · Sync: {health?.pricing.price_sync_interval_minutes||0} min · TTL: {health?.pricing.price_freshness_ttl_minutes||0} min</p><p className="mt-1 text-[9px] text-zinc-600">Última leitura: {health?.checked_at?new Date(health.checked_at).toLocaleString('pt-BR'):'—'}</p></div></div>}
  </>}
 </div>;
};
