import React,{useEffect,useState}from'react';
import{Search,Wallet,RefreshCw}from'lucide-react';
import{adminService}from'../../services/adminService.js';
import{UserProfile}from'../../types/index.js';
import{CreditAccount,CreditTransaction}from'../../types/credits.js';
import{Card}from'../common/Card.js';import{Button}from'../common/Button.js';import{Badge}from'../common/Badge.js';import{AdminUserDetailModal}from'./AdminUserDetailModal.js';

export const AdminUsersList:React.FC=()=>{
 const[users,setUsers]=useState<UserProfile[]>([]),[total,setTotal]=useState(0),[search,setSearch]=useState(''),[loading,setLoading]=useState(true),[selectedUser,setSelectedUser]=useState<UserProfile|null>(null),[selectedWallet,setSelectedWallet]=useState<CreditAccount|null>(null),[selectedRecentTx,setSelectedRecentTx]=useState<CreditTransaction[]>([]),[modalOpen,setModalOpen]=useState(false);
 const fetchUsers=async()=>{try{setLoading(true);const res=await adminService.listUsers(search);setUsers(res.users);setTotal(res.total)}catch(err){console.error('Falha ao listar usuários:',err)}finally{setLoading(false)}};useEffect(()=>{void fetchUsers()},[search]);
 const open=async(u:UserProfile)=>{try{const d=await adminService.getUserDetails(u.user_id);setSelectedUser(d.user);setSelectedWallet(d.wallet);setSelectedRecentTx(d.recent_transactions);setModalOpen(true)}catch(err){console.error('Erro ao abrir usuário:',err)}};
 const updated=async()=>{if(selectedUser){const d=await adminService.getUserDetails(selectedUser.user_id);setSelectedUser(d.user);setSelectedWallet(d.wallet);setSelectedRecentTx(d.recent_transactions)}void fetchUsers()};
 return <div className="space-y-4"><div className="rounded-2xl border border-sky-400/10 bg-sky-400/[0.04] p-4"><h3 className="text-sm font-bold text-white">Créditos são a única carteira operacional</h3><p className="mt-1 text-[10px] text-zinc-500">Ajustes administrativos são gravados no Credit Ledger. A carteira BRL legada não é usada para novas operações.</p></div><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><div className="relative flex-1 max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-zinc-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por e-mail ou nome..." className="w-full h-9 pl-9 pr-3 rounded-xl border border-white/[0.08] bg-[#0b0e13] text-xs text-white outline-none"/></div><Button id="admin-refresh-users-btn" variant="outline" size="sm" onClick={fetchUsers} icon={<RefreshCw className="w-3.5 h-3.5"/>}>Recarregar ({total})</Button></div><Card id="admin-users-table-card">{loading?<div className="py-12 text-center text-xs text-zinc-500">Carregando usuários...</div>:users.length===0?<div className="py-12 text-center text-xs text-zinc-500">Nenhum usuário encontrado.</div>:<div className="overflow-x-auto -mx-5 sm:-mx-6"><table className="w-full text-left text-xs"><thead><tr className="border-b border-white/[0.06] text-zinc-500"><th className="py-3 px-4 sm:px-6">Usuário</th><th className="py-3 px-4">Papel</th><th className="py-3 px-4">Status</th><th className="py-3 px-4 sm:px-6 text-right">Ação</th></tr></thead><tbody className="divide-y divide-white/[0.05]">{users.map(u=><tr key={u.user_id}><td className="py-3 px-4 sm:px-6"><span className="font-semibold text-white block">{u.display_name}</span><span className="text-[10px] text-zinc-600">{u.email}</span></td><td className="py-3 px-4"><Badge variant={u.role==='ADMIN'?'warning':'neutral'}>{u.role}</Badge></td><td className="py-3 px-4"><Badge variant={u.status==='ACTIVE'?'success':'danger'}>{u.status==='ACTIVE'?'Ativo':'Suspenso'}</Badge></td><td className="py-3 px-4 sm:px-6 text-right"><Button id={`btn-manage-user-${u.user_id}`} variant="secondary" size="sm" onClick={()=>open(u)} icon={<Wallet className="w-3.5 h-3.5"/>}>Gerenciar créditos</Button></td></tr>)}</tbody></table></div>}</Card><AdminUserDetailModal isOpen={modalOpen} onClose={()=>setModalOpen(false)} user={selectedUser} wallet={selectedWallet} recentTransactions={selectedRecentTx} onUpdated={updated}/></div>;
};
