import React,{useEffect,useMemo,useState}from'react';
import{CheckCircle2,RefreshCw,AlertTriangle,Clock3,Activity,Database,ShieldCheck,Save,Power,Coins}from'lucide-react';
import{adminService}from'../../services/adminService.js';import{apiRequest}from'../../services/apiClient.js';import{ModelRegistryItem}from'../../types/index.js';import{formatCentsToBRL}from'../../config/constants.js';import{Card}from'../common/Card.js';import{Button}from'../common/Button.js';

type LiveRow={key:string;provider_id:string;provider_name:string;model_id:string;mode:string;duration_seconds:number;resolution:string;provider_cost_brl_cents:number|null;safe_cost_brl_cents:number|null;fully_loaded_safe_cogs_cents?:number|null;retail_credit_price?:number|null;retail_pricing_version?:number|null;margin_percent:number|null;status:'OK'|'FAILED';checked_at:string;error?:string;pricing_signature_hash?:string;};
type ProviderFinance={provider_id:string;provider_name:string;status:string;balance_brl_cents:number|null;low_balance?:boolean;error?:string;};
type SyncResult={checked_at:string|null;checked:number;healthy:number;failed:number;fx_rate:number|null;fx_source:string|null;cache_ttl_minutes:number;provider_finance:ProviderFinance[];rows:LiveRow[];signatures_checked?:number;};
type BillingControl={credit_v2_enabled:boolean;new_generations_enabled:boolean;provider_execution_enabled:boolean;yellow_execution_enabled:boolean;updated_at:string;};
type RetailRow={retail_pricing_id:string;pricing_signature_hash:string;retail_credit_price:number;target_margin_percent:number;normal_floor_margin_percent:number;emergency_floor_margin_percent:number;version:number;active:boolean;signature:any;};
const credit=(v:number|null|undefined)=>v==null?'—':`${Number(v).toLocaleString('pt-BR')} cr`;
export const AdminPricing:React.FC=()=>{
 const[data,setData]=useState<SyncResult|null>(null),[models,setModels]=useState<ModelRegistryItem[]>([]),[loading,setLoading]=useState(true),[syncing,setSyncing]=useState(false),[message,setMessage]=useState(''),[margin,setMargin]=useState(45),[savingMargin,setSavingMargin]=useState(false),[controls,setControls]=useState<BillingControl|null>(null),[retail,setRetail]=useState<RetailRow[]>([]),[editing,setEditing]=useState<Record<string,string>>({});
 const load=async()=>{setLoading(true);setMessage('');try{const[snapshot,m,settings,c,r]=await Promise.all([apiRequest<SyncResult>('/api/admin/pricing/live'),adminService.listModels(),adminService.getPricingSettings(),apiRequest<BillingControl>('/api/admin/billing-control'),apiRequest<RetailRow[]>('/api/admin/pricing/retail-active')]);setData(snapshot);setModels(m);setMargin(settings.target_margin_percent??settings.gross_margin_percent);setControls(c);setRetail(r);}catch(e:any){setMessage(e?.message||'Falha ao carregar Pricing & Créditos.')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const syncNow=async()=>{setSyncing(true);setMessage('');try{const r=await apiRequest<SyncResult>('/api/admin/pricing/sync',{method:'POST'});setData(r);setMessage(`Monitor atualizado: ${r.healthy}/${r.checked} rota(s) saudáveis em ${r.signatures_checked||0} assinatura(s).`)}catch(e:any){setMessage(e?.message||'Falha ao consultar os provedores.')}finally{setSyncing(false)}};
 const saveMargin=async()=>{setSavingMargin(true);setMessage('');try{const r=await adminService.updatePricingSettings(margin);setMargin(r.settings.target_margin_percent??r.settings.gross_margin_percent);setMessage('Parâmetros de proteção atualizados. Preços públicos existentes não foram alterados automaticamente.')}catch(e:any){setMessage(e?.message||'Não foi possível atualizar a margem alvo.')}finally{setSavingMargin(false)}};
 const toggle=async(key:keyof BillingControl)=>{if(!controls)return;try{const next=await apiRequest<BillingControl>('/api/admin/billing-control',{method:'POST',body:JSON.stringify({[key]:!controls[key]})});setControls(next);setMessage('Controle operacional atualizado.')}catch(e:any){setMessage(e?.message||'Não foi possível atualizar o controle.')}};
 const publish=async(row:RetailRow)=>{const value=Math.round(Number(editing[row.pricing_signature_hash]||row.retail_credit_price));if(!value||value<=0)return;try{const next=await apiRequest<RetailRow>(`/api/admin/pricing/retail/${row.pricing_signature_hash}/publish`,{method:'POST',body:JSON.stringify({retail_credit_price:value})});setRetail(prev=>prev.map(x=>x.pricing_signature_hash===row.pricing_signature_hash?next:x));setEditing(prev=>({...prev,[row.pricing_signature_hash]:''}));setMessage(`Nova versão v${next.version} publicada com ${next.retail_credit_price.toLocaleString('pt-BR')} créditos.`)}catch(e:any){setMessage(e?.message||'Não foi possível publicar o novo preço.')}};
 const modelName=(id:string)=>models.find(m=>m.model_id===id)?.name||id;const rows=useMemo(()=>[...(data?.rows||[])].sort((a,b)=>modelName(a.model_id).localeCompare(modelName(b.model_id))||a.provider_name.localeCompare(b.provider_name)),[data,models]);
 return <div className="space-y-4"><div className="flex items-center justify-between gap-3 flex-wrap"><div><h2 className="text-base font-semibold text-white">Pricing & Créditos v2</h2><p className="text-xs text-zinc-500">Preço público em créditos é versionado. COGS e margem são monitorados separadamente.</p></div><Button id="btn-sync-pricing" variant="secondary" size="sm" onClick={syncNow} isLoading={syncing} icon={<RefreshCw className="w-3.5 h-3.5"/>}>Atualizar monitor</Button></div>{message&&<div className="text-xs px-3 py-2 rounded-lg border border-white/[0.08] bg-white/[0.03] text-zinc-300">{message}</div>}
 {controls&&<div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex items-center gap-2"><Power className="w-4 h-4 text-sky-300"/><h3 className="text-sm font-bold text-white">Controles operacionais</h3></div><p className="mt-1 text-[10px] text-zinc-500">Kill switches persistentes. Podem pausar cobrança, novas gerações ou execução de provider sem deploy.</p><div className="mt-3 grid sm:grid-cols-2 lg:grid-cols-4 gap-2">{([['credit_v2_enabled','Billing em créditos'],['new_generations_enabled','Novas gerações'],['provider_execution_enabled','Execução em providers'],['yellow_execution_enabled','Faixa YELLOW']] as const).map(([key,label])=><button key={key} onClick={()=>toggle(key)} className={`rounded-xl border p-3 text-left ${controls[key]?'border-emerald-300/20 bg-emerald-300/[0.06]':'border-rose-300/20 bg-rose-300/[0.06]'}`}><p className="text-[10px] font-bold text-white">{label}</p><p className={`mt-1 text-[9px] ${controls[key]?'text-emerald-300':'text-rose-300'}`}>{controls[key]?'ATIVO':'PAUSADO'}</p></button>)}</div></div>}
 <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-4"><div className="flex flex-col md:flex-row md:items-center justify-between gap-4"><div><div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-emerald-300"/><h3 className="text-sm font-bold text-white">Margem alvo de proteção</h3></div><p className="mt-1 text-[10px] text-zinc-500">Ajusta proteção econômica e roteamento. Não altera automaticamente preços públicos já publicados.</p></div><div className="flex items-center gap-2"><div className="relative"><input type="number" min={10} max={80} value={margin} onChange={e=>setMargin(Math.max(10,Math.min(80,Number(e.target.value)||10)))} className="w-24 h-10 rounded-xl border border-white/[0.09] bg-[#0b0e13] px-3 pr-8 text-sm font-bold text-white outline-none"/><span className="absolute right-3 top-1/2 -translate-y-1/2 text-xs text-zinc-500">%</span></div><button disabled={savingMargin} onClick={saveMargin} className="h-10 px-4 rounded-xl bg-cyan-300 text-[#061015] text-[10px] font-black inline-flex items-center gap-2"><Save className="w-3.5 h-3.5"/>{savingMargin?'Salvando...':'Salvar proteção'}</button></div></div></div>
 {loading?<Card id="pricing-loading"><div className="py-10 text-center text-xs text-zinc-400">Carregando...</div></Card>:<><div className="grid grid-cols-2 lg:grid-cols-4 gap-3"><Card id="pricing-health"><Activity className="w-4 h-4 text-emerald-400"/><p className="mt-2 text-[9px] uppercase text-zinc-600">Rotas saudáveis</p><p className="text-lg font-bold text-white">{data?.healthy||0}/{data?.checked||0}</p></Card><Card id="pricing-signatures"><Database className="w-4 h-4 text-sky-400"/><p className="mt-2 text-[9px] uppercase text-zinc-600">Assinaturas monitoradas</p><p className="text-lg font-bold text-white">{data?.signatures_checked||0}</p></Card><Card id="pricing-margin"><ShieldCheck className="w-4 h-4 text-emerald-400"/><p className="mt-2 text-[9px] uppercase text-zinc-600">Margem alvo</p><p className="text-lg font-bold text-white">{margin}%</p></Card><Card id="pricing-last"><Clock3 className="w-4 h-4 text-zinc-500"/><p className="mt-2 text-[9px] uppercase text-zinc-600">Última verificação</p><p className="text-[10px] font-semibold text-white">{data?.checked_at?new Date(data.checked_at).toLocaleString('pt-BR'):'—'}</p></Card></div>
 <div className="rounded-2xl border border-white/[0.07] bg-[#08131e] overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.06]"><div className="flex items-center gap-2"><Coins className="w-4 h-4 text-sky-300"/><h3 className="text-sm font-bold text-white">Retail Pricing publicado</h3></div><p className="mt-1 text-[9px] text-zinc-600">Alterar preço cria uma nova versão. Versões antigas permanecem imutáveis.</p></div><div className="overflow-x-auto"><table className="w-full text-[10px]"><thead className="text-zinc-600 border-b border-white/[0.05]"><tr><th className="text-left px-4 py-3">Modelo/configuração</th><th className="text-right px-3 py-3">Preço atual</th><th className="text-right px-3 py-3">Versão</th><th className="text-right px-4 py-3">Publicar novo preço</th></tr></thead><tbody className="divide-y divide-white/[0.045]">{retail.map(r=><tr key={r.pricing_signature_hash}><td className="px-4 py-3 text-zinc-300">{modelName(r.signature?.model_id||'')} · {r.signature?.resolution||'—'} · {r.signature?.duration_seconds||1}s</td><td className="px-3 py-3 text-right font-bold text-white">{credit(r.retail_credit_price)}</td><td className="px-3 py-3 text-right text-zinc-500">v{r.version}</td><td className="px-4 py-3"><div className="flex justify-end gap-2"><input type="number" min="1" value={editing[r.pricing_signature_hash]??''} onChange={e=>setEditing(p=>({...p,[r.pricing_signature_hash]:e.target.value}))} placeholder={String(r.retail_credit_price)} className="w-24 h-8 px-2 rounded-lg bg-[#0b0e13] border border-white/[0.07] text-white text-right"/><button onClick={()=>publish(r)} className="h-8 px-3 rounded-lg border border-sky-300/20 bg-sky-300/[0.08] text-sky-200 font-semibold">Publicar</button></div></td></tr>)}{!retail.length&&<tr><td colSpan={4} className="py-8 text-center text-zinc-600">Nenhum retail pricing publicado ainda.</td></tr>}</tbody></table></div></div>
 <div className="rounded-2xl border border-white/[0.07] bg-[#08131e] overflow-hidden"><div className="px-4 py-3 border-b border-white/[0.06]"><h3 className="text-sm font-bold text-white">Monitor de COGS</h3><p className="mt-1 text-[9px] text-zinc-600">Custos reais dos providers separados do preço em créditos.</p></div><div className="overflow-x-auto"><table className="w-full text-[10px]"><thead className="text-zinc-600 border-b border-white/[0.05]"><tr><th className="text-left px-4 py-3">Modelo</th><th className="text-left px-3 py-3">Provider</th><th className="text-left px-3 py-3">Configuração</th><th className="text-right px-3 py-3">Safe COGS</th><th className="text-right px-3 py-3">Retail</th><th className="text-right px-4 py-3">Health</th></tr></thead><tbody className="divide-y divide-white/[0.045]">{rows.map(r=>{const health=r.status==='FAILED'?'RED':r.margin_percent==null?'PROBE':r.margin_percent>=35?'GREEN':r.margin_percent>=25?'YELLOW':'RED';return <tr key={r.key}><td className="px-4 py-3 font-semibold text-white">{modelName(r.model_id)}</td><td className="px-3 py-3 text-zinc-400">{r.provider_name}</td><td className="px-3 py-3 text-zinc-500">{r.resolution} · {r.duration_seconds}s · {r.mode}</td><td className="px-3 py-3 text-right text-zinc-300">{r.fully_loaded_safe_cogs_cents==null?'—':formatCentsToBRL(r.fully_loaded_safe_cogs_cents)}</td><td className="px-3 py-3 text-right text-zinc-300">{credit(r.retail_credit_price)}{r.retail_pricing_version?` · v${r.retail_pricing_version}`:''}</td><td className="px-4 py-3 text-right">{health==='GREEN'?<span className="inline-flex items-center gap-1 text-emerald-300"><CheckCircle2 className="w-3 h-3"/>GREEN</span>:health==='YELLOW'?<span className="inline-flex items-center gap-1 text-amber-300"><AlertTriangle className="w-3 h-3"/>YELLOW</span>:health==='PROBE'?<span className="text-zinc-500">PROBE</span>:<span title={r.error} className="inline-flex items-center gap-1 text-rose-300"><AlertTriangle className="w-3 h-3"/>RED</span>}</td></tr>})}</tbody></table></div></div></>}
 </div>;
};
