import React,{useEffect,useMemo,useState}from'react';
import{Activity,Boxes,Database,HeartPulse,Plus,RefreshCw,Route,Search,Server,Settings2,ShieldCheck}from'lucide-react';
import{routingV2AdminService,RoutingV2BillingType,RoutingV2CutoverAdmin,RoutingV2HealthAdmin,RoutingV2ReadinessAdmin,RoutingV2ModelAdmin,RoutingV2PricingSettingsAdmin,RoutingV2ProviderAdmin,RoutingV2RouteAdmin,RoutingV2UnifiedCatalogModelAdmin,RoutingV2UnifiedCatalogProviderAdmin,RoutingV2UnifiedCatalogDiagnosticAdmin}from'../../services/routingV2AdminService.js';

type Tab='providers'|'models'|'routes'|'pricing'|'health';
const input='h-9 w-full rounded-lg border border-white/[0.08] bg-[#07111a] px-3 text-[11px] text-white outline-none focus:border-sky-300/30';
const btn='h-9 rounded-lg border border-white/[0.09] bg-white/[0.04] px-3 text-[10px] font-bold text-zinc-200 hover:bg-white/[0.07] disabled:opacity-40';
const primary='h-9 rounded-lg bg-sky-300 px-3 text-[10px] font-black text-[#061015] hover:bg-sky-200 disabled:opacity-40';
const panel='rounded-2xl border border-white/[0.07] bg-[#08131e]';
const caps=(value:string)=>Array.from(new Set(value.split(',').map(v=>v.trim()).filter(Boolean)));
const uniqueCatalogProviders=(rows:RoutingV2UnifiedCatalogProviderAdmin[])=>Array.from(new Map<string,RoutingV2UnifiedCatalogProviderAdmin>(rows.map(p=>[p.provider_id,p])).values());

export const AdminRoutingV2:React.FC=()=>{
 const[tab,setTab]=useState<Tab>('providers'),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const[providers,setProviders]=useState<RoutingV2ProviderAdmin[]>([]),[models,setModels]=useState<RoutingV2ModelAdmin[]>([]),[routes,setRoutes]=useState<RoutingV2RouteAdmin[]>([]);
 const[pricing,setPricing]=useState<RoutingV2PricingSettingsAdmin|null>(null),[health,setHealth]=useState<RoutingV2HealthAdmin|null>(null),[readiness,setReadiness]=useState<RoutingV2ReadinessAdmin|null>(null),[cutover,setCutover]=useState<RoutingV2CutoverAdmin|null>(null);
 const[pName,setPName]=useState(''),[pId,setPId]=useState(''),[pType,setPType]=useState<'AGGREGATOR'|'OFFICIAL'>('AGGREGATOR');
 const[mId,setMId]=useState(''),[mName,setMName]=useState(''),[mVendor,setMVendor]=useState(''),[mCategory,setMCategory]=useState<'VIDEO'|'IMAGE'|'AUDIO'|'MODEL_3D'|'OTHER'>('VIDEO'),[mCaps,setMCaps]=useState('');
 const[rModel,setRModel]=useState(''),[rCap,setRCap]=useState(''),[rProvider,setRProvider]=useState(''),[rIdentifier,setRIdentifier]=useState(''),[rBilling,setRBilling]=useState<RoutingV2BillingType>('PER_GENERATION'),[rUnitPrice,setRUnitPrice]=useState('0'),[rPriority,setRPriority]=useState('100'),[rFormulaId,setRFormulaId]=useState('');
 const[catalogQuery,setCatalogQuery]=useState(''),[unifiedRows,setUnifiedRows]=useState<RoutingV2UnifiedCatalogModelAdmin[]>([]),[catalogDiagnostics,setCatalogDiagnostics]=useState<RoutingV2UnifiedCatalogDiagnosticAdmin[]>([]),[catalogLoading,setCatalogLoading]=useState(false);
 const[selectedCatalog,setSelectedCatalog]=useState<string[]>([]),[expandedCatalog,setExpandedCatalog]=useState<string|null>(null),[expandedRouteModels,setExpandedRouteModels]=useState<string[]>([]),[operationalizing,setOperationalizing]=useState(false);
 const[bulkDrafts,setBulkDrafts]=useState<Record<string,{name:string;vendor:string;category:'VIDEO'|'IMAGE'|'AUDIO'|'MODEL_3D'|'OTHER';caps:string;providerIds:string[]}>>({}),[bulkSaving,setBulkSaving]=useState(false);

 const load=async()=>{
  setLoading(true);setMessage('');
  try{
   const[p,m,r,s,h,ma,co]=await Promise.all([routingV2AdminService.listProviders(),routingV2AdminService.listModels(),routingV2AdminService.listRoutes(),routingV2AdminService.getPricingSettings(),routingV2AdminService.getHealth(),routingV2AdminService.getReadiness(),routingV2AdminService.getCutover()]);
   setProviders(p);setModels(m);setRoutes(r);setPricing(s);setHealth(h);setReadiness(ma);setCutover(co);
   if(!rModel&&m[0])setRModel(m[0].model_id);if(!rProvider&&p[0])setRProvider(p[0].provider_id);
  }catch(e:any){setMessage(e?.message||'Falha ao carregar Routing Core V2.')}finally{setLoading(false)}
 };
 useEffect(()=>{void load()},[]);
 const modelById=useMemo(()=>new Map(models.map(m=>[m.model_id,m])),[models]),providerById=useMemo(()=>new Map(providers.map(p=>[p.provider_id,p])),[providers]);
 const routeGroups=useMemo(()=>{
  const grouped=new Map<string,RoutingV2RouteAdmin[]>();
  for(const route of routes){const list=grouped.get(route.model_id)||[];list.push(route);grouped.set(route.model_id,list);}
  return Array.from(grouped.entries()).map(([modelId,rows])=>{
   const model=modelById.get(modelId);
   const ready=rows.filter(r=>r.status==='READY');
   const best=[...ready].sort((a,b)=>(Number(a.pricing_snapshot?.safe_cogs_brl)||Infinity)-(Number(b.pricing_snapshot?.safe_cogs_brl)||Infinity)||b.priority-a.priority)[0]||null;
   return{modelId,model,rows:[...rows].sort((a,b)=>a.capability_id.localeCompare(b.capability_id)||a.provider_id.localeCompare(b.provider_id)),ready,best,providers:new Set(rows.map(r=>r.provider_id)).size,capabilities:new Set(rows.map(r=>r.capability_id)).size};
  }).sort((a,b)=>(a.model?.name||a.modelId).localeCompare(b.model?.name||b.modelId));
 },[routes,modelById]);

 const billingConfig=()=>{
  const value=Math.max(0,Number(rUnitPrice)||0);
  if(rBilling==='PER_GENERATION')return{type:rBilling,currency:'USD',price_per_generation:value};
  if(rBilling==='PER_OUTPUT')return{type:rBilling,currency:'USD',price_per_output:value};
  if(rBilling==='PER_SECOND')return{type:rBilling,currency:'USD',price_per_second:value};
  if(rBilling==='PER_MINUTE')return{type:rBilling,currency:'USD',price_per_minute:value};
  if(rBilling==='PER_CHARACTER')return{type:rBilling,currency:'USD',price_per_unit:value,characters_per_unit:1000};
  if(rBilling==='FIXED_MATRIX')return{type:rBilling,currency:'USD',entries:[{match:{default:true},price:value}]};
  return{type:rBilling,currency:'USD',formula_id:rFormulaId.trim()};
 };
 const createProvider=async()=>{try{await routingV2AdminService.createProvider({provider_id:pId.trim(),name:pName.trim(),type:pType,priority:100});setPId('');setPName('');await load();setMessage('Provider V2 criado.')}catch(e:any){setMessage(e?.message||'Falha ao criar provider.')}};
 const bootstrapCoreProviders=async()=>{try{const r=await routingV2AdminService.bootstrapCoreProviders();await load();const created=r.created?.length||0,existing=r.existing?.length||0,failed=r.failed?.length||0;setMessage(`Providers base: ${created} criado(s), ${existing} já existente(s), ${failed} falha(s).`);}catch(e:any){setMessage(e?.message||'Falha ao cadastrar providers base.')}};
 const createModel=async()=>{try{await routingV2AdminService.createModel({model_id:mId.trim(),name:mName.trim(),vendor:mVendor.trim(),category:mCategory,description:'',capabilities:caps(mCaps)});setMId('');setMName('');setMVendor('');setMCaps('');await load();setMessage('Model V2 criado.')}catch(e:any){setMessage(e?.message||'Falha ao criar model.')}};
 const createRoute=async()=>{try{await routingV2AdminService.createRoute({model_id:rModel,capability_id:rCap.trim(),provider_id:rProvider,provider_model_identifier:rIdentifier.trim(),billing_config:billingConfig(),priority:Number(rPriority)||100});setRIdentifier('');setRCap('');await load();setMessage('Route V2 criada em MAPPED.')}catch(e:any){setMessage(e?.message||'Falha ao criar Route.')}};
 const slugModel=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');
 const searchCatalog=async()=>{setCatalogLoading(true);setMessage('');try{const r=await routingV2AdminService.searchUnifiedCatalog(catalogQuery);setUnifiedRows(r.rows);setCatalogDiagnostics(r.provider_diagnostics||[]);if(r.failures.length)setMessage(`Catálogo carregado com ${r.failures.length} provider(s) indisponível(is).`);}catch(e:any){setUnifiedRows([]);setCatalogDiagnostics([]);setMessage(e?.message||'Catálogo unificado não disponível.')}finally{setCatalogLoading(false)}};
 const toggleCatalog=(row:RoutingV2UnifiedCatalogModelAdmin)=>{setSelectedCatalog(current=>{const exists=current.includes(row.catalog_key);if(exists){setBulkDrafts(d=>{const next={...d};delete next[row.catalog_key];return next});return current.filter(x=>x!==row.catalog_key)}setBulkDrafts(d=>({...d,[row.catalog_key]:{name:row.name,vendor:row.vendor||'Unknown',category:'IMAGE',caps:(row.capabilities?.length?row.capabilities:['text-to-image']).join(','),providerIds:row.providers.map(p=>p.provider_id)}}));return[...current,row.catalog_key]})};
 const updateDraft=(key:string,patch:Partial<{name:string;vendor:string;category:'VIDEO'|'IMAGE'|'AUDIO'|'MODEL_3D'|'OTHER';caps:string;providerIds:string[]}>)=>setBulkDrafts(d=>({...d,[key]:{...d[key],...patch}}));
 const bulkImport=async()=>{const chosen=unifiedRows.filter(row=>selectedCatalog.includes(row.catalog_key));if(!chosen.length)return;setBulkSaving(true);try{const items=chosen.map(row=>{const draft=bulkDrafts[row.catalog_key];return{model_id:slugModel(draft?.name||row.name),name:draft?.name||row.name,vendor:draft?.vendor||row.vendor||'Unknown',category:draft?.category||'IMAGE',capabilities:caps(draft?.caps||'text-to-image'),providers:row.providers.filter(p=>(draft?.providerIds||[]).includes(p.provider_id)).map(p=>({provider_id:p.provider_id,provider_model_identifier:p.provider_model_identifier,capabilities:p.capabilities,priority:providerById.get(p.provider_id)?.priority||100}))}});const r=await routingV2AdminService.bulkImportModels(items);setSelectedCatalog([]);setBulkDrafts({});const op=await operationalizeAll();await load();setMessage(`Importação concluída: ${r.created_models.length} modelo(s), ${r.created_routes.length} binding(s). Rotas READY: ${op.readiness?.v2?.ready_routes||0}. Falhas de sync: ${op.failed}.`);}catch(e:any){setMessage(e?.message||'Falha na importação/ativação em massa.')}finally{setBulkSaving(false)}};
 const savePricing=async()=>{if(!pricing)return;try{const next=await routingV2AdminService.savePricingSettings(pricing);setPricing(next);setMessage('Economics V2 atualizado.')}catch(e:any){setMessage(e?.message||'Falha ao salvar pricing.')}};
 const operationalizeAll=async()=>{let cursor=0,updated=0,failed=0,processed=0,readiness:any=null;for(let i=0;i<100;i++){const r=await routingV2AdminService.operationalize(cursor,5);updated+=Number(r?.updated||0);failed+=Number(r?.failed||0);processed+=Number(r?.processed||0);if(r?.readiness)readiness=r.readiness;if(r?.done||r?.next_cursor==null)break;cursor=Number(r.next_cursor||0);}return{updated,failed,processed,readiness};};
 const syncPricing=async()=>{setOperationalizing(true);try{const r=await operationalizeAll();await load();setMessage(`Ativação V2 concluída: ${r.updated} rota(s) sincronizada(s), ${r.readiness?.v2?.ready_routes||0} READY, ${r.failed} falha(s).`);}catch(e:any){setMessage(e?.message||'Falha ao ativar rotas V2.')}finally{setOperationalizing(false)}};
 const changeCutover=async()=>{try{const next=await routingV2AdminService.setCutover('HYBRID');setCutover(next);setMessage('Modo HYBRID confirmado.');}catch(e:any){setMessage(e?.message||'Não foi possível confirmar o modo HYBRID.')}};

 const toggleRouteModel=(modelId:string)=>setExpandedRouteModels(current=>current.includes(modelId)?current.filter(id=>id!==modelId):[...current,modelId]);
 const groupedRoutesView=(pricingMode=false)=><div className="space-y-2">
  <div className="rounded-xl border border-sky-300/10 bg-sky-300/[0.03] px-3 py-2 text-[9px] text-zinc-400">Roteamento: somente rotas <strong className="text-emerald-300">READY</strong> entram na seleção. Entre elas, vence o menor <strong className="text-white">Safe COGS</strong>; prioridade só desempata.</div>
  {routeGroups.map(group=>{const expanded=expandedRouteModels.includes(group.modelId);const best=group.best;return <div key={group.modelId} className={panel+" overflow-hidden"}>
   <button className="grid w-full grid-cols-[1fr_auto] items-center gap-3 px-4 py-3 text-left hover:bg-white/[0.02]" onClick={()=>toggleRouteModel(group.modelId)}>
    <div className="min-w-0"><div className="truncate text-[11px] font-black text-white">{group.model?.name||group.modelId}</div><div className="mt-1 flex flex-wrap gap-2 text-[8px] text-zinc-500"><span>{group.rows.length} rota(s)</span><span>·</span><span className={group.ready.length?'text-emerald-300':'text-amber-300'}>{group.ready.length} READY</span><span>·</span><span>{group.providers} provider(s)</span><span>·</span><span>{group.capabilities} capability(s)</span></div></div>
    <div className="flex items-center gap-3">{best?<div className="text-right"><div className="text-[8px] uppercase text-zinc-600">Melhor READY</div><div className="text-[9px] font-bold text-white">{providerById.get(best.provider_id)?.name||best.provider_id}</div><div className="text-[8px] text-emerald-300">{best.pricing_snapshot?.safe_cogs_brl==null?'—':`R$ ${best.pricing_snapshot.safe_cogs_brl.toFixed(4)}`} · {best.pricing_snapshot?.retail_price_credits??'—'} cr</div></div>:<div className="rounded-md border border-amber-300/15 bg-amber-300/[0.05] px-2 py-1 text-[8px] font-bold text-amber-200">Sem READY</div>}<span className="text-[10px] text-zinc-500">{expanded?'▲':'▼'}</span></div>
   </button>
   {expanded&&<div className="border-t border-white/[0.06] bg-black/10 p-3"><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-[9px]"><thead className="text-zinc-600"><tr><th className="pb-2 text-left">Capability</th><th>Provider</th><th className="text-left">Identifier</th><th>Provider Cost</th><th>Safe COGS</th><th>Retail</th><th>Prioridade</th><th>Status</th><th>Last Sync</th>{!pricingMode&&<th></th>}</tr></thead><tbody className="divide-y divide-white/[0.05]">{group.rows.map(r=><tr key={r.route_id}><td className="py-2 pr-2 font-medium text-zinc-300">{r.capability_id}</td><td className="px-2 text-center text-zinc-300">{providerById.get(r.provider_id)?.name||r.provider_id}</td><td className="max-w-[300px] px-2 font-mono text-[8px] text-zinc-500">{r.provider_model_identifier}</td><td className="px-2 text-center text-zinc-300">{r.pricing_snapshot?.provider_cost_reference??'—'}</td><td className="px-2 text-center text-zinc-300">{r.pricing_snapshot?.safe_cogs_brl==null?'—':`R$ ${r.pricing_snapshot.safe_cogs_brl.toFixed(4)}`}</td><td className="px-2 text-center font-bold text-white">{r.pricing_snapshot?.retail_price_credits==null?'—':`${r.pricing_snapshot.retail_price_credits} cr`}</td><td className="px-2 text-center text-zinc-400">{r.priority}</td><td className="px-2 text-center"><div className={r.status==='READY'?'font-bold text-emerald-300':r.status==='DEGRADED'?'font-bold text-amber-300':'text-zinc-400'}>{r.status}</div><div className="text-[7px] text-zinc-600">{r.pricing_status} · {r.runtime_status}</div></td><td className="px-2 text-center text-zinc-500">{r.last_price_sync_at?new Date(r.last_price_sync_at).toLocaleString('pt-BR'):'—'}</td>{!pricingMode&&<td className="pl-2 text-right">{r.status!=='DISABLED'&&<button className={btn} onClick={async()=>{await routingV2AdminService.disableRoute(r.route_id);await load()}}>Desativar</button>}</td>}</tr>)}</tbody></table></div></div>}
  </div>})}
 </div>;

 const tabs:[Tab,string,React.ReactNode][]=[['providers','Providers',<Server className="w-3.5 h-3.5"/>],['models','Modelos',<Boxes className="w-3.5 h-3.5"/>],['routes','Rotas',<Route className="w-3.5 h-3.5"/>],['pricing','Pricing',<Database className="w-3.5 h-3.5"/>],['health','Health',<HeartPulse className="w-3.5 h-3.5"/>]];
 return <div className="space-y-4">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck className="w-4 h-4 text-sky-300"/><h2 className="text-sm font-black text-white">IA & Roteamento</h2><span className="rounded-full border border-amber-300/20 bg-amber-300/[0.07] px-2 py-1 text-[9px] font-bold text-amber-200">{cutover?.mode||'HYBRID'}</span></div><p className="mt-1 text-[10px] text-zinc-500">Inventário único. Somente rotas READY são publicadas para os geradores.</p></div><button className={btn} onClick={()=>void load()}><RefreshCw className="mr-1.5 inline w-3 h-3"/>Atualizar</button></div>
  <div className="flex gap-1 overflow-x-auto">{tabs.map(([id,label,icon])=><button key={id} onClick={()=>setTab(id)} className={`h-9 whitespace-nowrap rounded-lg px-3 text-[10px] font-bold ${tab===id?'bg-sky-300 text-[#061015]':'border border-white/[0.07] text-zinc-400'}`}>{icon}<span className="ml-1.5">{label}</span></button>)}</div>
  {message&&<div className="rounded-lg border border-white/[0.08] bg-white/[0.03] px-3 py-2 text-[10px] text-zinc-300">{message}</div>}
  {loading?<div className={panel+" p-8 text-center text-xs text-zinc-500"}>Carregando V2...</div>:<>
   {tab==='providers'&&<div className="space-y-3">
    <div className={panel+" p-4"}><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-xs font-bold text-white">Adicionar provider</h3><p className="mt-1 text-[9px] text-zinc-600">Base inicial recomendada: WaveSpeed, Atlas Cloud e Runware. O cadastro é idempotente e pode ser executado em produção.</p></div><button className={primary} onClick={bootstrapCoreProviders}>Cadastrar 3 providers base</button></div><p className="mt-1 text-[9px] text-zinc-600">Este botão cadastra apenas a configuração dos providers. As API keys precisam existir como secrets no servidor e nunca são armazenadas neste painel.</p><div className="mt-3 grid gap-2 md:grid-cols-3"><input className={input} placeholder="provider-id" value={pId} onChange={e=>setPId(e.target.value)}/><input className={input} placeholder="Nome" value={pName} onChange={e=>setPName(e.target.value)}/><select className={input} value={pType} onChange={e=>setPType(e.target.value as any)}><option>AGGREGATOR</option><option>OFFICIAL</option></select></div><button className={primary+" mt-2"} onClick={createProvider}><Plus className="mr-1 inline w-3 h-3"/>Criar provider</button></div>
    <div className={panel+" overflow-x-auto"}><table className="w-full min-w-[760px] text-[10px]"><thead className="border-b border-white/[0.06] text-zinc-600"><tr><th className="p-3 text-left">Provider</th><th>Tipo</th><th>Status</th><th>Health</th><th>Balance</th><th>Recursos</th><th></th></tr></thead><tbody className="divide-y divide-white/[0.05]">{providers.map(p=><tr key={p.provider_id}><td className="p-3"><div className="font-bold text-white">{p.name}</div><div className="text-zinc-600">{p.provider_id}</div></td><td className="text-center text-zinc-300">{p.type}</td><td className="text-center text-zinc-300">{p.status}</td><td className="text-center text-zinc-300">{p.health_status}</td><td className="text-center text-zinc-300">{p.balance_amount==null?'—':`${p.balance_amount} ${p.balance_currency||''}`}</td><td className="text-center text-zinc-500">{p.supports_catalog_sync?'catálogo ':''}{p.supports_pricing_sync?'pricing ':''}{p.supports_balance?'saldo':''}</td><td className="p-2 text-right">{p.status!=='DISABLED'&&<button className={btn} onClick={async()=>{await routingV2AdminService.disableProvider(p.provider_id);await load()}}>Desativar</button>}</td></tr>)}</tbody></table></div>

   </div>}
   {tab==='models'&&<div className="space-y-3">
    <div className={panel+" p-4"}>
     <div className="flex flex-wrap items-end justify-between gap-3"><div><h3 className="text-xs font-bold text-white">Catálogo unificado de modelos</h3><p className="mt-1 text-[9px] text-zinc-500">Busca Atlas Cloud, WaveSpeed e Runware ao mesmo tempo, agrupa o mesmo modelo e permite cadastro com todos os providers em uma operação.</p></div><div className="flex gap-2"><input className={input+" w-64"} placeholder="Pesquisar em todos os providers" value={catalogQuery} onChange={e=>setCatalogQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')void searchCatalog()}}/><button className={btn} disabled={catalogLoading} onClick={searchCatalog}><Search className="mr-1 inline w-3 h-3"/>{catalogLoading?'Buscando...':'Buscar todos'}</button></div></div>
     {catalogDiagnostics.length>0&&<div className="mt-3 flex flex-wrap gap-2">{catalogDiagnostics.map(d=><div key={d.provider_id} className={`rounded-lg border px-2.5 py-1.5 text-[9px] ${d.status==='OK'?'border-emerald-300/15 bg-emerald-300/[0.05] text-emerald-200':'border-rose-300/15 bg-rose-300/[0.05] text-rose-200'}`}><strong>{d.provider_name}</strong> · {d.status==='OK'?d.count+' resultado(s)':d.message||'erro'}</div>)}</div>}
     {unifiedRows.length>0&&<div className="mt-4 overflow-hidden rounded-xl border border-white/[0.06]"><div className="grid grid-cols-[32px_1fr_150px_130px] items-center gap-2 bg-white/[0.025] px-3 py-2 text-[9px] font-bold uppercase text-zinc-600"><span></span><span>Modelo</span><span>Providers</span><span className="text-right">Ação</span></div>{unifiedRows.map(row=>{const selected=selectedCatalog.includes(row.catalog_key);return <div key={row.catalog_key} className="border-t border-white/[0.05]"><div className="grid grid-cols-[32px_1fr_150px_130px] items-center gap-2 px-3 py-2.5"><input type="checkbox" checked={selected} onChange={()=>toggleCatalog(row)} className="accent-sky-300"/><button className="min-w-0 text-left" onClick={()=>setExpandedCatalog(expandedCatalog===row.catalog_key?null:row.catalog_key)}><div className="truncate text-[10px] font-bold text-white">{row.name}</div><div className="truncate text-[9px] text-zinc-600">{row.vendor||'Vendor não identificado'}</div></button><div className="flex flex-wrap gap-1">{uniqueCatalogProviders(row.providers).slice(0,3).map(p=><span key={p.provider_id} className="rounded-md border border-white/[0.07] bg-white/[0.03] px-1.5 py-1 text-[8px] text-zinc-400">{p.provider_name}</span>)}{new Set(row.providers.map(p=>p.provider_id)).size>3&&<span className="text-[8px] text-zinc-600">+{new Set(row.providers.map(p=>p.provider_id)).size-3}</span>}</div><button className={btn} onClick={()=>{if(!selected)toggleCatalog(row);setExpandedCatalog(row.catalog_key)}}>{selected?'Selecionado':'Selecionar'}</button></div>{expandedCatalog===row.catalog_key&&<div className="bg-black/10 px-12 py-3"><div className="text-[9px] font-bold text-zinc-400">Bindings encontrados</div><div className="mt-2 grid gap-2">{row.providers.map(p=><div key={p.provider_id} className="flex items-center justify-between gap-3 rounded-lg border border-white/[0.05] px-3 py-2"><div><div className="text-[9px] font-bold text-zinc-300">{p.provider_name}</div><div className="font-mono text-[8px] text-zinc-600">{p.provider_model_identifier}</div></div><span className="text-[8px] text-emerald-300">Disponível</span></div>)}</div></div>}</div>})}</div>}
    </div>
    {selectedCatalog.length>0&&<div className={panel+" p-4"}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xs font-bold text-white">Configurar selecionados</h3><p className="mt-1 text-[9px] text-zinc-500">{selectedCatalog.length} modelo(s) selecionado(s). Ajuste categoria, capabilities e providers antes de criar.</p></div><button className={primary} disabled={bulkSaving} onClick={bulkImport}>{bulkSaving?'Criando...':`Criar ${selectedCatalog.length} modelo(s)`}</button></div><div className="mt-3 space-y-3">{unifiedRows.filter(row=>selectedCatalog.includes(row.catalog_key)).map(row=>{const d=bulkDrafts[row.catalog_key];if(!d)return null;return <div key={row.catalog_key} className="rounded-xl border border-white/[0.06] bg-black/10 p-3"><div className="grid gap-2 md:grid-cols-4"><input className={input} value={d.name} onChange={e=>updateDraft(row.catalog_key,{name:e.target.value})}/><input className={input} value={d.vendor} onChange={e=>updateDraft(row.catalog_key,{vendor:e.target.value})}/><select className={input} value={d.category} onChange={e=>updateDraft(row.catalog_key,{category:e.target.value as any})}><option>IMAGE</option><option>VIDEO</option><option>AUDIO</option><option>MODEL_3D</option><option>OTHER</option></select><input className={input} value={d.caps} onChange={e=>updateDraft(row.catalog_key,{caps:e.target.value})} placeholder="text-to-image,image-to-image"/></div><div className="mt-2 flex flex-wrap gap-2">{uniqueCatalogProviders(row.providers).map(p=>{const checked=d.providerIds.includes(p.provider_id);return <label key={p.provider_id} className={`flex cursor-pointer items-center gap-2 rounded-lg border px-2 py-1.5 text-[9px] ${checked?'border-sky-300/30 bg-sky-300/[0.07] text-sky-200':'border-white/[0.06] text-zinc-500'}`}><input type="checkbox" checked={checked} onChange={()=>updateDraft(row.catalog_key,{providerIds:checked?d.providerIds.filter(id=>id!==p.provider_id):[...d.providerIds,p.provider_id]})}/>{p.provider_name}</label>})}</div></div>})}</div></div>}
    <div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Adicionar model manualmente</h3><div className="mt-3 grid gap-2 md:grid-cols-5"><input className={input} placeholder="model-id" value={mId} onChange={e=>setMId(e.target.value)}/><input className={input} placeholder="Nome" value={mName} onChange={e=>setMName(e.target.value)}/><input className={input} placeholder="Vendor" value={mVendor} onChange={e=>setMVendor(e.target.value)}/><select className={input} value={mCategory} onChange={e=>setMCategory(e.target.value as any)}><option>VIDEO</option><option>IMAGE</option><option>AUDIO</option><option>MODEL_3D</option><option>OTHER</option></select><input className={input} placeholder="capabilities, separadas por vírgula" value={mCaps} onChange={e=>setMCaps(e.target.value)}/></div><button className={primary+" mt-2"} onClick={createModel}><Plus className="mr-1 inline w-3 h-3"/>Criar model</button></div>
    <div className={panel+" overflow-x-auto"}><table className="w-full min-w-[760px] text-[10px]"><thead className="border-b border-white/[0.06] text-zinc-600"><tr><th className="p-3 text-left">Model</th><th>Vendor</th><th>Categoria</th><th>Capabilities</th><th>Status</th><th></th></tr></thead><tbody className="divide-y divide-white/[0.05]">{models.map(m=><tr key={m.model_id}><td className="p-3"><div className="font-bold text-white">{m.name}</div><div className="text-zinc-600">{m.model_id}</div></td><td className="text-center text-zinc-300">{m.vendor}</td><td className="text-center text-zinc-300">{m.category}</td><td className="max-w-[340px] px-3 text-zinc-400">{m.capabilities.join(', ')}</td><td className="text-center text-zinc-300">{m.status}</td><td className="p-2 text-right">{m.status==='ACTIVE'&&<button className={btn} onClick={async()=>{await routingV2AdminService.disableModel(m.model_id);await load()}}>Desativar</button>}</td></tr>)}</tbody></table></div>
   </div>}
   {tab==='routes'&&<div className="space-y-3">
    <div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Criar Route</h3><p className="mt-1 text-[9px] text-zinc-600">A Route nasce MAPPED. READY só será derivado depois de pricing CURRENT + runtime HEALTHY.</p><div className="mt-3 grid gap-2 md:grid-cols-4"><select className={input} value={rModel} onChange={e=>setRModel(e.target.value)}>{models.filter(m=>m.status==='ACTIVE').map(m=><option key={m.model_id} value={m.model_id}>{m.name}</option>)}</select><input className={input} placeholder="capability_id" value={rCap} onChange={e=>setRCap(e.target.value)}/><select className={input} value={rProvider} onChange={e=>setRProvider(e.target.value)}>{providers.filter(p=>p.status!=='DISABLED').map(p=><option key={p.provider_id} value={p.provider_id}>{p.name}</option>)}</select><input className={input} placeholder="provider_model_identifier" value={rIdentifier} onChange={e=>setRIdentifier(e.target.value)}/><select className={input} value={rBilling} onChange={e=>setRBilling(e.target.value as RoutingV2BillingType)}>{['PER_GENERATION','PER_OUTPUT','PER_SECOND','PER_MINUTE','PER_CHARACTER','FIXED_MATRIX','CUSTOM_FORMULA'].map(x=><option key={x}>{x}</option>)}</select><input className={input} type="number" step="0.000001" min="0" placeholder="Preço unitário provider" value={rUnitPrice} onChange={e=>setRUnitPrice(e.target.value)}/><input className={input} type="number" placeholder="Prioridade" value={rPriority} onChange={e=>setRPriority(e.target.value)}/>{rBilling==='CUSTOM_FORMULA'&&<input className={input} placeholder="formula_id registrada no adapter" value={rFormulaId} onChange={e=>setRFormulaId(e.target.value)}/>}</div><button className={primary+" mt-2"} onClick={createRoute}><Plus className="mr-1 inline w-3 h-3"/>Criar Route</button></div>
    {groupedRoutesView(false)}
   </div>}
   {tab==='pricing'&&pricing&&<div className="space-y-3"><div className={panel+" p-4"}><div className="flex items-center justify-between gap-3"><div><h3 className="text-xs font-bold text-white">Economics Engine</h3><p className="mt-1 text-[9px] text-zinc-600">Configuração econômica única para todas as Routes.</p></div><button className={btn} disabled={operationalizing} onClick={syncPricing}><RefreshCw className="mr-1 inline w-3 h-3"/>{operationalizing?'Ativando...':'Sincronizar e ativar rotas'}</button></div><div className="mt-4 grid gap-3 md:grid-cols-3">{([['target_margin_percent','Margem alvo (%)'],['safety_buffer_percent','Safety buffer (%)'],['reference_credit_value_brl','Valor referência / crédito (R$)'],['price_sync_interval_minutes','Sync (min)'],['price_freshness_ttl_minutes','TTL preço (min)'],['stale_grace_minutes','Grace stale (min)']] as const).map(([key,label])=><label key={key} className="text-[9px] text-zinc-500">{label}<input className={input+" mt-1"} type="number" step={key==='reference_credit_value_brl'?'0.0001':'1'} value={pricing[key]} onChange={e=>setPricing({...pricing,[key]:Number(e.target.value)})}/></label>)}</div><button className={primary+" mt-3"} onClick={savePricing}><Settings2 className="mr-1 inline w-3 h-3"/>Salvar economics</button></div>{groupedRoutesView(true)}</div>}
   {tab==='health'&&<div className="space-y-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Providers ativos',health?.providers.active||0],['Providers healthy',health?.providers.healthy||0],['Rotas READY',health?.routes.ready||0],['Rotas degradadas/stale',(health?.routes.degraded||0)+(health?.routes.stale||0)]].map(([label,value])=><div key={String(label)} className={panel+" p-4"}><Activity className="w-4 h-4 text-sky-300"/><div className="mt-2 text-[9px] text-zinc-600">{label}</div><div className="text-xl font-black text-white">{value}</div></div>)}</div><div className={panel+" p-4"}><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="text-xs font-bold text-white">Readiness & modo operacional</h3><p className="mt-2 text-[10px] text-zinc-400">Cobertura READY: {readiness?.coverage.ready_model_capabilities||0}/{readiness?.coverage.required_model_capabilities||0} modelo-capability(s). Modo atual: <strong className="text-white">{cutover?.mode||'HYBRID'}</strong>.</p></div><button className={primary} disabled={operationalizing} onClick={syncPricing}>{operationalizing?'Ativando rotas...':'Ativar rotas agora'}</button></div><p className="mt-1 text-[9px] text-zinc-600">HYBRID permanece obrigatório durante a reconstrução do inventário. V2_ONLY está bloqueado.</p><div className="mt-3"><button className={btn} disabled={cutover?.mode==='HYBRID'} onClick={changeCutover}>Confirmar HYBRID</button></div>{readiness?.coverage.missing?.length? <div className="mt-3 max-h-36 overflow-auto rounded-lg border border-white/[0.06] bg-black/10 p-2 text-[9px] text-zinc-500">{readiness.coverage.missing.slice(0,30).map(x=><div key={x.model_id+'|'+x.capability_id}>{x.model_id} · {x.capability_id}</div>)}{readiness.coverage.missing.length>30&&<div>+ {readiness.coverage.missing.length-30} pendência(s)</div>}</div>:null}</div><div className={panel+" p-4"}><h3 className="text-xs font-bold text-white">Estado operacional</h3><p className="mt-2 text-[10px] text-zinc-400">Modelos: {health?.models.active||0}/{health?.models.total||0} ativos · Rotas: {health?.routes.ready||0}/{health?.routes.total||0} READY · Desativadas: {health?.routes.disabled||0} · Sync: {health?.pricing.price_sync_interval_minutes||0} min · TTL: {health?.pricing.price_freshness_ttl_minutes||0} min</p><p className="mt-1 text-[9px] text-zinc-600">Última leitura: {health?.checked_at?new Date(health.checked_at).toLocaleString('pt-BR'):'—'}</p></div></div>}
  </>}
 </div>;
};
