import React,{useId}from'react';

const palette=['#38bdf8','#a78bfa','#34d399','#f59e0b','#fb7185','#22d3ee','#f472b6','#818cf8'];
const safe=(n:any)=>Number.isFinite(Number(n))?Number(n):0;

export const AdminDonutChart:React.FC<{title:string;center:string;subtitle?:string;segments:Array<{label:string;value:number;color?:string}>}>=({title,center,subtitle,segments})=>{
 const total=Math.max(1,segments.reduce((sum,item)=>sum+Math.max(0,safe(item.value)),0));
 let offset=0;
 return <section className="ia-admin-panel overflow-hidden"><div><h3 className="text-xs font-black text-white">{title}</h3>{subtitle&&<p className="mt-1 text-[9px] text-zinc-600">{subtitle}</p>}</div><div className="mt-4 grid grid-cols-[132px_1fr] items-center gap-4"><div className="relative w-[132px] h-[132px]"><svg viewBox="0 0 120 120" className="w-full h-full -rotate-90"><circle cx="60" cy="60" r="46" fill="none" stroke="rgba(255,255,255,.055)" strokeWidth="14"/>{segments.map((item,index)=>{const fraction=Math.max(0,safe(item.value))/total,dash=fraction*289.03,current=offset;offset+=dash;return <circle key={`${item.label}-${index}`} cx="60" cy="60" r="46" fill="none" stroke={item.color||palette[index%palette.length]} strokeWidth="14" strokeLinecap="round" strokeDasharray={`${dash} ${Math.max(0,289.03-dash)}`} strokeDashoffset={-current}/>})}</svg><div className="absolute inset-0 grid place-items-center text-center"><div><strong className="block text-xl font-black text-white tabular-nums">{center}</strong><span className="text-[8px] uppercase tracking-[.18em] text-zinc-600">total</span></div></div></div><div className="space-y-2.5">{segments.map((item,index)=><div key={item.label} className="flex items-center justify-between gap-3 text-[9px]"><span className="flex min-w-0 items-center gap-2 text-zinc-400"><i className="h-2 w-2 shrink-0 rounded-full" style={{background:item.color||palette[index%palette.length]}}/><span className="truncate">{item.label}</span></span><strong className="text-zinc-200 tabular-nums">{safe(item.value).toLocaleString('pt-BR')}</strong></div>)}</div></div></section>;
};

export const AdminAreaChart:React.FC<{title:string;subtitle?:string;labels:string[];series:Array<{name:string;values:number[];format?:(value:number)=>string;color?:string}>}>=({title,subtitle,labels,series})=>{
 const gradientId=useId().replace(/:/g,'');
 const all=series.flatMap(item=>item.values.map(safe));
 const max=Math.max(1,...all),min=Math.min(0,...all),range=Math.max(1,max-min),left=38,right=590,top=18,bottom=184;
 const x=(i:number,count:number)=>count<=1?left:left+(right-left)*(i/(count-1));
 const y=(v:number)=>bottom-((safe(v)-min)/range)*(bottom-top);
 return <section className="ia-admin-panel overflow-hidden"><div><h3 className="text-xs font-black text-white">{title}</h3>{subtitle&&<p className="mt-1 text-[9px] text-zinc-600">{subtitle}</p>}</div><div className="mt-3 overflow-x-auto rounded-xl border border-white/[0.05] bg-black/10 p-2"><svg viewBox="0 0 620 220" className="w-full min-w-[520px]" role="img" aria-label={title}><defs>{series.map((item,index)=><linearGradient key={item.name} id={`${gradientId}-${index}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={item.color||palette[index%palette.length]} stopOpacity=".25"/><stop offset="1" stopColor={item.color||palette[index%palette.length]} stopOpacity="0"/></linearGradient>)}</defs>{[0,.25,.5,.75,1].map(p=>{const yy=top+(bottom-top)*p;return <g key={p}><line x1={left} x2={right} y1={yy} y2={yy} stroke="rgba(255,255,255,.055)"/><text x="3" y={yy+3} fill="rgba(161,161,170,.62)" fontSize="8">{Math.round(max-(max-min)*p).toLocaleString('pt-BR')}</text></g>})}{series.map((item,index)=>{const points=item.values.map((v,i)=>`${x(i,item.values.length)},${y(v)}`).join(' '),area=`${left},${bottom} ${points} ${right},${bottom}`;return <g key={item.name}><polygon points={area} fill={`url(#${gradientId}-${index})`}/><polyline points={points} fill="none" stroke={item.color||palette[index%palette.length]} strokeWidth="2.5" strokeLinejoin="round" strokeLinecap="round"/>{item.values.map((v,i)=><circle key={i} cx={x(i,item.values.length)} cy={y(v)} r="2.5" fill={item.color||palette[index%palette.length]}><title>{labels[i]||i}: {item.format?item.format(v):safe(v).toLocaleString('pt-BR')}</title></circle>)}</g>})}{labels.map((label,i)=>i%Math.max(1,Math.ceil(labels.length/6))===0?<text key={`${label}-${i}`} x={x(i,labels.length)} y="205" textAnchor="middle" fill="rgba(161,161,170,.66)" fontSize="8">{label}</text>:null)}</svg></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2">{series.map((item,index)=><span key={item.name} className="flex items-center gap-2 text-[9px] text-zinc-500"><i className="h-2 w-2 rounded-full" style={{background:item.color||palette[index%palette.length]}}/>{item.name}</span>)}</div></section>;
};

export const AdminRankedBars:React.FC<{title:string;subtitle?:string;rows:Array<{label:string;value:number;detail?:string;color?:string}>;format?:(value:number)=>string}>=({title,subtitle,rows,format})=>{
 const max=Math.max(1,...rows.map(row=>safe(row.value)));
 return <section className="ia-admin-panel"><div><h3 className="text-xs font-black text-white">{title}</h3>{subtitle&&<p className="mt-1 text-[9px] text-zinc-600">{subtitle}</p>}</div><div className="mt-4 space-y-3.5">{rows.length?rows.map((row,index)=><div key={`${row.label}-${index}`}><div className="flex items-center justify-between gap-3 text-[9px]"><span className="min-w-0 truncate font-semibold text-zinc-300"><span className="mr-2 text-zinc-700">{String(index+1).padStart(2,'0')}</span>{row.label}</span><span className="shrink-0 text-zinc-500 tabular-nums">{format?format(row.value):safe(row.value).toLocaleString('pt-BR')}{row.detail?` · ${row.detail}`:''}</span></div><div className="mt-1.5 h-3 overflow-hidden rounded-full bg-white/[0.045] p-[2px]"><div className="h-full rounded-full shadow-[0_0_18px_rgba(56,189,248,.16)] transition-all" style={{width:`${Math.max(2,(safe(row.value)/max)*100)}%`,background:row.color||palette[index%palette.length]}}/></div></div>):<div className="py-8 text-center text-[10px] text-zinc-600">Sem dados suficientes.</div>}</div></section>;
};
