import fs from'fs';import path from'path';import{describe,expect,it}from'vitest';const read=(f:string)=>fs.readFileSync(path.join(process.cwd(),f),'utf8');
describe('PR-19 Sharing / Analytics architecture',()=>{
 it('stores only a token hash and exposes immutable snapshots',()=>{const service=read('server/beta/sharing/sharingService.ts'),types=read('server/beta/sharing/sharingTypes.ts');expect(service).toContain("createHash('sha256')");expect(service).toContain('token_hash:hash(token)');expect(types).toContain('snapshot:Record<string,any>');expect(service).not.toMatch(/ip_address|fingerprint|user_agent/i);});
 it('delegates ownership to existing resource services',()=>{const service=read('server/beta/sharing/sharingService.ts');expect(service).toContain('universalAssetService.get(userId,id)');expect(service).toContain('betaFlowService.get(userId,id)');expect(service).toContain('betaTemplateService.get(userId,id)');expect(service).toContain('workflowAppService.get(userId,id)');});
 it('derives analytics from existing systems instead of a parallel event pipeline',()=>{const service=read('server/beta/sharing/analyticsService.ts');expect(service).toContain('universalAssetService.list(userId)');expect(service).toContain('betaFlowRuntimeRepository.listRuns(userId,100)');expect(service).not.toMatch(/provider_id|provider_model_identifier|analytics_event_queue|segment|mixpanel/i);});
 it('keeps public shares read-only and owner mutations authenticated',()=>{const route=read('server/routes/betaSharingRoutes.ts');expect(route).toContain("get('/beta/shared/:token'");expect(route).toContain("use('/beta/sharing',requireAuth");expect(route).not.toMatch(/post\('\/beta\/shared|put\('\/beta\/shared|patch\('\/beta\/shared|delete\('\/beta\/shared/);});
 it('lazy loads workspace and has responsive contracts',()=>{const beta=read('src/beta/BetaApp.tsx'),css=read('src/beta/styles/sharing.css');expect(beta).toContain("lazy(()=>import('./views/BetaSharingView.js')");expect(css).toContain('@media(max-width:800px)');expect(css).toContain('@media(max-width:480px)');});
});

describe('PR-19 rollout contract',()=>{it('has independent sharing and analytics flags and release markers',()=>{const flags=read('src/beta/betaFlags.ts'),service=read('server/services/featureFlagService.ts');expect(flags).toContain("'beta.sharing'");expect(flags).toContain("'beta.analytics'");expect(service).toContain('beta_sharing_v1_release');expect(service).toContain('beta_analytics_v1_release');});it('never exposes token hash to owner list or public view',()=>{const service=read('server/beta/sharing/sharingService.ts');expect(service).toContain('({token_hash,snapshot,...row})');expect(service).not.toContain('token_hash:row.token_hash');});});
