export interface CreditAccount{user_id:string;available_credits:number;reserved_credits:number;total_credits:number;total_purchased_credits:number;total_promotional_credits:number;total_used_credits:number;total_expired_credits:number;total_revoked_credits:number;updated_at:string;}
export interface CreditLotAllocation{credit_lot_id:string;credits:number;net_cash_value_per_credit_micros:number;source:string;expires_at:string|null;}
export interface CreditTransaction{transaction_id:string;user_id:string;type:string;amount_credits:number;status:string;reference_type:string;reference_id:string;idempotency_key:string;lot_allocations:CreditLotAllocation[];balance_after_credits:number;created_at:string;metadata?:Record<string,any>;}
export interface PackVersion{pack_id:string;version:number;price_brl_cents:number;base_credits:number;bonus_credits:number;total_credits:number;active:boolean;effective_from:string;label:string;name:string;description:string;badge?:string;recommended?:boolean;features:string[];}
export interface RetailPricingVersion{retail_pricing_id:string;pricing_signature_hash:string;retail_credit_price:number;target_margin_percent:number;normal_floor_margin_percent:number;emergency_floor_margin_percent:number;version:number;active:boolean;}

export type SubscriptionStatus='PENDING'|'ACTIVE'|'PAUSED'|'CANCELED'|'FAILED';
export interface UserSubscription{subscription_id:string;user_id:string;email:string;pack_id:string;pack_version:number;plan_name:string;price_brl_cents:number;monthly_credits:number;status:SubscriptionStatus;gateway:'MERCADOPAGO';gateway_subscription_id:string;checkout_url?:string;next_payment_date?:string|null;pending_plan_change?:{pack_id:string;pack_version:number;plan_name:string;price_brl_cents:number;monthly_credits:number}|null;created_at:string;updated_at:string;canceled_at?:string|null;}

export interface CreditWalletSummary{available_credits:number;reserved_credits:number;subscription_credits:number;promotional_credits:number;other_credits:number;nearest_expiration_at:string|null;rollover_multiplier:number;}
