/**
 * Core Types & Interfaces for AI Generation Platform (Stage 1)
 * All financial values represent integer cents (e.g. R$ 10,50 = 1050).
 */

export type UserRole = 'USER' | 'ADMIN';
export type UserStatus = 'ACTIVE' | 'SUSPENDED';
export interface UserProfile { user_id:string; email:string; display_name:string; avatar_url?:string; role:UserRole; status:UserStatus; created_at:string; updated_at:string; last_login_at?:string; }
export type GenerationStatus='DRAFT'|'QUEUED'|'RESERVING_FUNDS'|'SUBMITTED'|'PROCESSING'|'SUCCEEDED'|'FAILED'|'CANCELLED'|'REFUNDED';
export type GenerationMode='TEXT_TO_VIDEO'|'IMAGE_TO_VIDEO'|'REFERENCE_TO_VIDEO'|'VIDEO_TO_VIDEO'|'TEXT_TO_IMAGE'|'IMAGE_TO_IMAGE';
export interface GenerationReferenceSnapshot { asset_id:string; slot_type?:'INITIAL'|'END'|'GENERAL'; alias?:string; }
export interface Generation {
 generation_id:string; user_id:string; status:GenerationStatus; model_id:string; provider_id:string; mode?:GenerationMode; original_prompt:string; compiled_prompt?:string; prompt_compiler_version?:string;
 negative_prompt?:string; duration_seconds?:number; resolution?:string; aspect_ratio?:string; number_of_outputs?:number; seed?:number|null; motion_strength?:number|null; references?:GenerationReferenceSnapshot[];
 retail_credit_price?:number; final_credit_cost?:number; currency:'CREDITS'; provider_job_id?:string; client_request_id?:string; progress_percent?:number; result_asset_id?:string|null; result_asset_ids?:string[]; result_url?:string|null; result_urls?:string[]; thumbnail_url?:string|null; error_code?:string|null; error_message?:string|null; attempt_count?:number; references_count?:number; created_at:string; submitted_at?:string|null; completed_at?:string|null; failed_at?:string|null;
}
export type AssetType='IMAGE'|'VIDEO'|'AUDIO';
export type AssetCategory='PRODUCT'|'CHARACTER'|'ENVIRONMENT'|'STYLE'|'MOTION'|'AUDIO_REFERENCE'|'GENERIC';
export type AssetStatus='READY'|'UPLOADING'|'PROCESSING'|'FAILED';
export interface Asset { asset_id:string; owner_user_id:string; type:AssetType; category:AssetCategory; name:string; alias:string; storage_path:string; public_url?:string; thumbnail_url?:string; mime_type:string; size_bytes:number; width?:number|null; height?:number|null; duration_seconds?:number|null; status:AssetStatus; created_at:string; updated_at:string; deleted_at?:string|null; origin?:string; source_generation_id?:string; source_model_id?:string; source_provider_id?:string; }
export interface ModelCapabilities { supported_modes:GenerationMode[]; supported_resolutions:string[]; supported_durations:number[]; supported_aspect_ratios:string[]; supports_image_reference:boolean; supports_multiple_images:boolean; supports_video_reference:boolean; supports_audio_reference:boolean; supports_negative_prompt:boolean; supports_seed:boolean; max_reference_images:number; max_reference_videos:number; max_reference_audio:number; max_prompt_length:number; supports_camera_control?:boolean; supports_motion_strength?:boolean; supports_loop?:boolean; supports_start_end_image?:boolean; }
export type ModelCategory='VIDEO'|'IMAGE'|'AUDIO'|'OTHER'; export type ModelStatus='ACTIVE'|'INACTIVE'|'EXPERIMENTAL';
export interface ModelRegistryItem extends Partial<ModelCapabilities>{model_id:string;name:string;slug:string;category:ModelCategory;description:string;status:ModelStatus;best_for?:string;recommended_aspect_ratio?:string;created_at:string;updated_at:string;}
export type ReferencePriority='LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export interface WorkspaceReference {asset_id:string;alias_snapshot:string;asset?:Asset;role?:string;priority:ReferencePriority;preservation_rules:string[];flexible_rules:string[];notes?:string;}
export type PromptImproveObjective='GENERAL'|'CINEMATIC'|'PRODUCT_FIDELITY'|'CHARACTER_CONSISTENCY'|'MOTION'|'REALISM'|'PROMPT_CLARITY'|'COST_EFFICIENCY';
export interface CompiledPromptResult {original_prompt:string;compiled_prompt:string;structured_context:{subject?:string;action?:string;environment?:string;camera?:string;motion?:string;lighting?:string;style?:string;continuity?:string;references:Array<{asset_id:string;alias:string;type:string;category:string;priority:string;preservation_rules:string[];flexible_rules:string[]}>;negative_constraints?:string[];settings_summary:{model_id:string;mode:GenerationMode;duration_seconds:number;resolution:string;aspect_ratio:string}};prompt_compiler_version:string;}
export interface WorkspacePreset {preset_id:string;user_id:string;name:string;description:string;category:string;prompt_template:string;negative_prompt_template?:string;generation_settings:{model_id?:string;mode:GenerationMode;duration_seconds:number;resolution:string;aspect_ratio:string;number_of_outputs?:number;seed?:number|null;motion_strength?:number};reference_rules_template?:{priority:ReferencePriority;preservation_rules:string[];flexible_rules:string[]};included_asset_ids?:string[];created_at:string;updated_at:string;}
export interface WorkspaceDraft {draft_id:string;user_id:string;model_id:string;mode:GenerationMode;prompt:string;negative_prompt?:string;references:WorkspaceReference[];settings:{duration_seconds:number;resolution:string;aspect_ratio:string;number_of_outputs:number;seed?:number|null;motion_strength?:number};preset_id?:string|null;updated_at:string;created_at:string;}
export interface GenerationRequestDraft {request_id:string;user_id:string;model_id:string;model_name:string;mode:GenerationMode;prompt:string;compiled_prompt:string;prompt_compiler_version:string;negative_prompt?:string;references:WorkspaceReference[];settings:{duration_seconds:number;resolution:string;aspect_ratio:string;number_of_outputs:number;seed?:number|null;motion_strength?:number;audio_enabled?:boolean;model_variant?:string;pricing_options?:Record<string,string|number|boolean|null|undefined>};retail_credit_price:number;authorized_credit_price:number;credit_balance_available:number;balance_after_generation_credits:number;has_sufficient_funds:boolean;retail_pricing_id:string;retail_pricing_version:number;pricing_signature_hash:string;created_at:string;}
export interface UserPreferences {user_id:string;favorite_model_ids:string[];recent_model_ids:string[];last_used_mode?:GenerationMode;updated_at:string;}
export type ProviderStatus='ACTIVE'|'INACTIVE'|'DEGRADED';
export interface ProviderRegistryItem {provider_id:string;name:string;slug:string;status:ProviderStatus;priority:number;is_configured:boolean;created_at:string;updated_at:string;}
export interface ProviderModelMapping {mapping_id:string;model_id:string;provider_id:string;provider_model_identifier:string;status:'ACTIVE'|'INACTIVE';capabilities?:string[];updated_at:string;}
export interface PricingEntry {pricing_id:string;provider_id:string;model_id:string;resolution:string;duration_seconds?:number;mode?:GenerationMode;unit:string;provider_cost_cents:number;customer_price_cents:number;currency:'BRL';effective_from:string;effective_until?:string|null;active:boolean;updated_at:string;}
export type DiscountType='PERCENTAGE'|'FIXED_AMOUNT'; export interface PromotionEntry {promotion_id:string;provider_id:string;model_id:string;name:string;discount_type:DiscountType;discount_value:number;starts_at:string;expires_at:string;verified_at?:string;source_note?:string;active:boolean;}
export interface FeatureFlag {flag_key:string;name:string;description:string;is_enabled:boolean;is_private:boolean;updated_at:string;}
export interface AuditLog {log_id:string;admin_id:string;admin_email:string;action:string;entity_type:'USER'|'PRICING'|'PROVIDER'|'MODEL'|'PROMOTION'|'FEATURE_FLAG'|'WALLET';entity_id:string;before?:Record<string,any>|null;after?:Record<string,any>|null;reason:string;created_at:string;}
export interface AppConfig {config_id:string;base_currency:'BRL';supported_locales:string[];min_deposit_cents:number;max_price_change_percent_warning:number;pagination_default_limit:number;updated_at:string;}
export interface StandardApiResponse<T=any>{success:boolean;data?:T;error?:{code:string;message:string}}
export type AppErrorCode='AUTH_SESSION_INVALID'|'AUTH_REQUIRED'|'ADMIN_PERMISSION_REQUIRED'|'USER_SUSPENDED'|'WALLET_INSUFFICIENT_FUNDS'|'INVALID_AMOUNT'|'DUPLICATE_TRANSACTION'|'RESOURCE_NOT_FOUND'|'VALIDATION_ERROR'|'OPERATION_REJECTED'|'PRICE_VARIATION_HIGH'|'PROMOTION_EXPIRED';
export type PaymentMethod='PIX'|'CREDIT_CARD';export type PaymentStatus='PENDING'|'CONFIRMED'|'EXPIRED'|'FAILED';export interface PaymentRecord{payment_id:string;user_id:string;amount_cents:number;method:PaymentMethod;status:PaymentStatus;pix_code?:string;pix_qr_code_base64?:string;checkout_url?:string;description:string;idempotency_key:string;created_at:string;expires_at:string;confirmed_at?:string|null;failed_at?:string|null;}
export interface RoutingLogEntry{log_id:string;generation_id?:string;user_id:string;model_id:string;selected_provider_id:string;strategy:string;candidate_providers:Array<{provider_id:string;provider_cost_cents:number;customer_price_cents:number;status:ProviderStatus;priority:number;is_healthy:boolean}>;reason:string;created_at:string;}
export interface GenerationAttemptLog{attempt_id:string;generation_id:string;attempt_number:number;provider_id:string;provider_job_id?:string;status:'SUBMITTED'|'PROCESSING'|'SUCCEEDED'|'FAILED';error_message?:string;latency_ms?:number;created_at:string;updated_at:string;}
export interface StorageDiagnosticResult{is_configured:boolean;storage_bucket:string;write_test:'PASS'|'FAIL'|'SKIPPED';signed_url_test:'PASS'|'FAIL'|'SKIPPED';message:string;details?:{latency_ms:number;bucket_accessible:boolean;error?:string};checked_at:string;}
