import { ModelRegistryItem, PricingEntry } from '../types/index.js';

const now = () => '2026-09-09T00:00:00.000Z';
const durations = (a:number,b:number) => Array.from({length:b-a+1},(_,i)=>a+i);
const imageRatios = ['1:1','3:2','2:3','3:4','4:3','4:5','5:4','9:16','16:9','21:9'];
const videoRatios = ['16:9','9:16','1:1','4:3','3:4','21:9'];

export const STUDIO_FALLBACK_MODELS: ModelRegistryItem[] = [
  {model_id:'wan-3-0-prime',name:'WAN 3.0 Prime',slug:'wan-3-0-prime',category:'VIDEO',description:'Vídeo premium all-in-one com áudio nativo, first/last frame e referências multimodais, até 30s.',status:'ACTIVE',best_for:'Qualidade máxima e takes finais',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(2,30),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:10,max_reference_videos:5,max_reference_audio:5,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'seedance-2-5',name:'Seedance 2.5',slug:'seedance-2-5',category:'VIDEO',description:'Vídeo cinematográfico multimodal com áudio nativo e até 30s.',status:'ACTIVE',best_for:'Movimento, cinematografia e referências densas',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(4,30),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:30,max_reference_videos:10,max_reference_audio:10,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'wan-3-0',name:'WAN 3.0',slug:'wan-3-0',category:'VIDEO',description:'Vídeo all-in-one com ótimo custo-benefício, áudio e referências, até 30s.',status:'ACTIVE',best_for:'Custo-benefício premium',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(2,30),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:10,max_reference_videos:5,max_reference_audio:5,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'kling-3-0',name:'Kling 3.0',slug:'kling-3-0',category:'VIDEO',description:'Kling 3.0 Standard com movimento cinematográfico, áudio opcional e controle por frame inicial/final.',status:'ACTIVE',best_for:'Movimento realista, personagens e takes cinematográficos',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO'],supported_resolutions:['720p','1080p'],supported_durations:durations(3,15),supported_aspect_ratios:['16:9','9:16','1:1'],supports_image_reference:true,supports_multiple_images:false,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:true,supports_seed:false,supports_start_end_image:true,max_reference_images:2,max_reference_videos:0,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
  {model_id:'google-omni-flash',name:'Google Omni Flash',slug:'google-omni-flash',category:'VIDEO',description:'Gemini Omni 1.1 Flash com vídeo e áudio sincronizados, 360p a 4K e referências multimodais.',status:'ACTIVE',best_for:'Iteração rápida, áudio nativo e referências',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['360p','720p','1080p','4K'],supported_durations:durations(3,10),supported_aspect_ratios:['16:9','9:16'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:false,supports_start_end_image:true,max_reference_images:10,max_reference_videos:3,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
  {model_id:'minimax-h3',name:'MiniMax H3',slug:'minimax-h3',category:'VIDEO',description:'Modelo omni-modal com áudio estéreo nativo, referências multimodais e 5–15s.',status:'ACTIVE',best_for:'Clipes de 15s e referência multimodal',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','540p','768p'],supported_durations:durations(5,15),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:9,max_reference_videos:3,max_reference_audio:3,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'seedance-2-0',name:'Seedance 2.0',slug:'seedance-2-0',category:'VIDEO',description:'Seedance cinematográfico com áudio nativo, first/last frame e clipes de até 15s.',status:'ACTIVE',best_for:'Clipes premium de 15s',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(4,15),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:false,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:2,max_reference_videos:0,max_reference_audio:0,max_prompt_length:20000,created_at:now(),updated_at:now()},

  {model_id:'nano-banana-pro-image',name:'Google Nano Banana Pro',slug:'nano-banana-pro-image',category:'IMAGE',description:'Gemini 3 Pro Image para geração e edição 4K premium.',status:'ACTIVE',best_for:'Fotorealismo, produto, branding e consistência',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','2K','4K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:false,max_reference_images:10,max_reference_videos:0,max_reference_audio:0,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'nano-banana-2-image',name:'Google Nano Banana 2',slug:'nano-banana-2-image',category:'IMAGE',description:'Gemini 3.1 Flash Image: qualidade próxima do Pro com alta velocidade e edição 4K.',status:'ACTIVE',best_for:'Produção premium rápida e referências',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','2K','4K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:false,max_reference_images:14,max_reference_videos:0,max_reference_audio:0,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'nano-banana-2-lite-image',name:'Google Nano Banana 2 Lite',slug:'nano-banana-2-lite-image',category:'IMAGE',description:'Gemini 3.1 Flash-Lite Image para geração e edição rápidas e econômicas em 1K.',status:'ACTIVE',best_for:'Rascunhos, volume, testes e edição rápida',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:false,max_reference_images:10,max_reference_videos:0,max_reference_audio:0,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'seedream-5-pro-image',name:'Seedream 5.0 Pro',slug:'seedream-5-pro-image',category:'IMAGE',description:'ByteDance flagship para imagem profissional e edição multi-referência.',status:'ACTIVE',best_for:'Campanhas, produto, tipografia e composição',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','1.5K','2K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:false,max_reference_images:10,max_reference_videos:0,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
  {model_id:'gpt-image-2',name:'GPT Image 2',slug:'gpt-image-2',category:'IMAGE',description:'Modelo premium para geração e edição com excelente texto, layout e aderência ao prompt.',status:'ACTIVE',best_for:'Branding, layouts e precisão de texto',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','2K','4K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,supports_negative_prompt:false,supports_seed:false,max_reference_images:16,max_reference_videos:0,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
];

const price=(id:string,provider:string,model:string,resolution:string,cost:number,unit:'PER_SECOND'|'PER_IMAGE'='PER_IMAGE'):PricingEntry=>({pricing_id:id,provider_id:provider,model_id:model,resolution,duration_seconds:1,unit,provider_cost_cents:cost,customer_price_cents:Math.ceil(cost*1.12),currency:'BRL',effective_from:now(),active:true,updated_at:now()});

export const STUDIO_FALLBACK_PRICING: PricingEntry[] = [
  price('img-nbp-wave-1k','provider-wavespeed','nano-banana-pro-image','1K',72),price('img-nbp-wave-2k','provider-wavespeed','nano-banana-pro-image','2K',72),price('img-nbp-wave-4k','provider-wavespeed','nano-banana-pro-image','4K',123),
  price('img-nb2-wave-1k','provider-wavespeed','nano-banana-2-image','1K',33),price('img-nb2-wave-2k','provider-wavespeed','nano-banana-2-image','2K',49),price('img-nb2-wave-4k','provider-wavespeed','nano-banana-2-image','4K',65),
  price('img-nb2lite-wave-1k','provider-wavespeed','nano-banana-2-lite-image','1K',24),
  price('img-seed5-wave-1k','provider-wavespeed','seedream-5-pro-image','1K',23),price('img-seed5-wave-15k','provider-wavespeed','seedream-5-pro-image','1.5K',23),price('img-seed5-wave-2k','provider-wavespeed','seedream-5-pro-image','2K',23),
  price('img-gpt2-wave-1k','provider-wavespeed','gpt-image-2','1K',31),price('img-gpt2-wave-2k','provider-wavespeed','gpt-image-2','2K',46),price('img-gpt2-wave-4k','provider-wavespeed','gpt-image-2','4K',61),
  price('kling30-wave-720','provider-wavespeed','kling-3-0','720p',47,'PER_SECOND'),price('omni11-wave-720','provider-wavespeed','google-omni-flash','720p',56,'PER_SECOND'),
  price('wan3-atlas-480','provider-atlas','wan-3-0','480p',20,'PER_SECOND'),price('wan3-atlas-720','provider-atlas','wan-3-0','720p',41,'PER_SECOND'),price('wan3-atlas-1080','provider-atlas','wan-3-0','1080p',82,'PER_SECOND'),
  price('wan3p-atlas-480','provider-atlas','wan-3-0-prime','480p',31,'PER_SECOND'),price('wan3p-atlas-720','provider-atlas','wan-3-0-prime','720p',64,'PER_SECOND'),price('wan3p-atlas-1080','provider-atlas','wan-3-0-prime','1080p',129,'PER_SECOND'),
  price('seed25-atlas-480','provider-atlas','seedance-2-5','480p',71,'PER_SECOND'),price('seed25-atlas-720','provider-atlas','seedance-2-5','720p',153,'PER_SECOND'),price('seed25-atlas-1080','provider-atlas','seedance-2-5','1080p',302,'PER_SECOND'),
  price('h3-wave-768','provider-wavespeed','minimax-h3','768p',51,'PER_SECOND'),price('seed20-atlas-720','provider-atlas','seedance-2-0','720p',57,'PER_SECOND'),
];