import { ModelRegistryItem } from '../types/index.js';

const now = () => '2026-09-09T00:00:00.000Z';
const durations = (a:number,b:number) => Array.from({length:b-a+1},(_,i)=>a+i);
const imageRatios = ['1:1','3:2','2:3','3:4','4:3','4:5','5:4','9:16','16:9','21:9'];
const videoRatios = ['16:9','9:16','1:1','4:3','3:4','21:9'];

export const STUDIO_SEED_MODELS: ModelRegistryItem[] = [
  {model_id:'wan-3-0-prime',name:'WAN 3.0 Prime',slug:'wan-3-0-prime',category:'VIDEO',description:'Vídeo premium all-in-one com áudio nativo, first/last frame e referências multimodais, até 30s.',status:'ACTIVE',best_for:'Qualidade máxima e takes finais',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(2,30),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_audio_generation:true,audio_generation_mode:'OPTIONAL',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:10,max_reference_videos:5,max_reference_audio:5,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'seedance-2-5',name:'Seedance 2.5',slug:'seedance-2-5',category:'VIDEO',description:'Vídeo cinematográfico multimodal com áudio nativo e até 30s.',status:'ACTIVE',best_for:'Movimento, cinematografia e referências densas',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(4,30),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_audio_generation:true,audio_generation_mode:'OPTIONAL',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:30,max_reference_videos:10,max_reference_audio:10,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'wan-3-0',name:'WAN 3.0',slug:'wan-3-0',category:'VIDEO',description:'Vídeo all-in-one com ótimo custo-benefício, áudio e referências, até 30s.',status:'ACTIVE',best_for:'Custo-benefício premium',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(2,30),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_audio_generation:true,audio_generation_mode:'OPTIONAL',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:10,max_reference_videos:5,max_reference_audio:5,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'kling-3-0',name:'Kling 3.0',slug:'kling-3-0',category:'VIDEO',description:'Kling 3.0 Standard com movimento cinematográfico, áudio opcional e controle por frame inicial/final.',status:'ACTIVE',best_for:'Movimento realista, personagens e takes cinematográficos',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO'],supported_resolutions:['Standard'],supported_durations:durations(3,15),supported_aspect_ratios:['16:9','9:16','1:1'],supports_image_reference:true,supports_multiple_images:false,supports_video_reference:false,supports_audio_reference:false,supports_audio_generation:true,audio_generation_mode:'OPTIONAL',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:true,supports_seed:false,supports_start_end_image:true,max_reference_images:2,max_reference_videos:0,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
  {model_id:'google-omni-flash',name:'Google Omni Flash',slug:'google-omni-flash',category:'VIDEO',description:'Gemini Omni 1.1 Flash com vídeo e áudio sincronizados, 360p a 4K e referências multimodais.',status:'ACTIVE',best_for:'Iteração rápida, áudio nativo e referências',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['360p','720p','1080p','4K'],supported_durations:durations(3,10),supported_aspect_ratios:['16:9','9:16'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:false,supports_audio_generation:true,audio_generation_mode:'ALWAYS',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:false,supports_seed:false,supports_start_end_image:true,max_reference_images:10,max_reference_videos:3,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
  {model_id:'minimax-h3',name:'MiniMax H3',slug:'minimax-h3',category:'VIDEO',description:'Modelo omni-modal com áudio estéreo nativo, referências multimodais e 5–15s.',status:'ACTIVE',best_for:'Clipes de 15s e referência multimodal',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','540p','768p','1080p','2K'],supported_durations:durations(3,15),supported_aspect_ratios:[...videoRatios,'9:21'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_audio_generation:true,audio_generation_mode:'ALWAYS',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:9,max_reference_videos:3,max_reference_audio:3,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'seedance-2-0',name:'Seedance 2.0',slug:'seedance-2-0',category:'VIDEO',description:'Seedance cinematográfico com áudio nativo, first/last frame e clipes de até 15s.',status:'ACTIVE',best_for:'Clipes premium de 15s',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(4,15),supported_aspect_ratios:videoRatios,supports_image_reference:true,supports_multiple_images:false,supports_video_reference:false,supports_audio_reference:false,supports_audio_generation:true,audio_generation_mode:'OPTIONAL',default_audio_enabled:true,max_outputs:1,supports_negative_prompt:false,supports_seed:true,supports_start_end_image:true,max_reference_images:2,max_reference_videos:0,max_reference_audio:0,max_prompt_length:20000,created_at:now(),updated_at:now()},
  {model_id:'nano-banana-pro-image',name:'Google Nano Banana Pro',slug:'nano-banana-pro-image',category:'IMAGE',description:'Gemini 3 Pro Image para geração e edição 4K premium.',status:'ACTIVE',best_for:'Fotorealismo, produto, branding e consistência',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','2K','4K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,max_outputs:1,supports_negative_prompt:false,supports_seed:false,max_reference_images:10,max_reference_videos:0,max_reference_audio:0,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'nano-banana-2-image',name:'Google Nano Banana 2',slug:'nano-banana-2-image',category:'IMAGE',description:'Gemini 3.1 Flash Image: qualidade próxima do Pro com alta velocidade e edição 4K.',status:'ACTIVE',best_for:'Produção premium rápida e referências',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','2K','4K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,max_outputs:1,supports_negative_prompt:false,supports_seed:false,max_reference_images:14,max_reference_videos:0,max_reference_audio:0,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'nano-banana-2-lite-image',name:'Google Nano Banana 2 Lite',slug:'nano-banana-2-lite-image',category:'IMAGE',description:'Gemini 3.1 Flash-Lite Image para geração e edição rápidas e econômicas em 1K.',status:'ACTIVE',best_for:'Rascunhos, volume, testes e edição rápida',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,max_outputs:1,supports_negative_prompt:false,supports_seed:false,max_reference_images:10,max_reference_videos:0,max_reference_audio:0,max_prompt_length:10000,created_at:now(),updated_at:now()},
  {model_id:'seedream-5-pro-image',name:'Seedream 5.0 Pro',slug:'seedream-5-pro-image',category:'IMAGE',description:'ByteDance flagship para imagem profissional e edição multi-referência.',status:'ACTIVE',best_for:'Campanhas, produto, tipografia e composição',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','1.5K','2K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,max_outputs:1,supports_negative_prompt:false,supports_seed:false,max_reference_images:10,max_reference_videos:0,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
  {model_id:'gpt-image-2',name:'GPT Image 2',slug:'gpt-image-2',category:'IMAGE',description:'Modelo premium para geração e edição com excelente texto, layout e aderência ao prompt.',status:'ACTIVE',best_for:'Branding, layouts e precisão de texto',recommended_aspect_ratio:'1:1',supported_modes:['TEXT_TO_IMAGE','IMAGE_TO_IMAGE'],supported_resolutions:['1K','2K','4K'],supported_durations:[1],supported_aspect_ratios:imageRatios,supports_image_reference:true,supports_multiple_images:true,supports_video_reference:false,supports_audio_reference:false,max_outputs:1,supports_negative_prompt:false,supports_seed:false,max_reference_images:16,max_reference_videos:0,max_reference_audio:0,max_prompt_length:12000,created_at:now(),updated_at:now()},
];
