import { ModelRegistryItem, ProviderRegistryItem, ProviderModelMapping, PricingEntry, PromotionEntry, FeatureFlag } from '../../src/types/index.js';
import { getAdminDb } from './firebaseAdminClient.js';
import { INITIAL_FEATURE_FLAGS } from '../../src/config/constants.js';

function db(){const d=getAdminDb();if(!d)throw new Error('Firestore Admin indisponível.');return d;}
const now=()=>new Date().toISOString();
const durations=(from:number,to:number)=>Array.from({length:to-from+1},(_,i)=>i+from);

const MODELS:ModelRegistryItem[]=[
 {model_id:'wan-3-0-prime',name:'WAN 3.0 Prime',slug:'wan-3-0-prime',category:'VIDEO',description:'WAN 3.0 acelerado para produção premium, com texto, imagem e referências multimodais.',status:'ACTIVE',best_for:'Alta qualidade e velocidade',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(2,30),supported_aspect_ratios:['16:9','9:16','1:1','4:3','3:4'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,max_reference_images:10,max_reference_videos:5,max_reference_audio:5,max_prompt_length:20000,supports_start_end_image:true,created_at:now(),updated_at:now()},
 {model_id:'wan-3-0',name:'WAN 3.0',slug:'wan-3-0',category:'VIDEO',description:'Modelo versátil com excelente custo-benefício, 480p a 1080p e até 30 segundos.',status:'ACTIVE',best_for:'Melhor custo-benefício',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(2,30),supported_aspect_ratios:['16:9','9:16','1:1','4:3','3:4'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,max_reference_images:10,max_reference_videos:5,max_reference_audio:5,max_prompt_length:20000,supports_start_end_image:true,created_at:now(),updated_at:now()},
 {model_id:'seedance-2-5',name:'Seedance 2.5',slug:'seedance-2-5',category:'VIDEO',description:'Geração cinematográfica multimodal com áudio sincronizado e forte aderência ao prompt.',status:'ACTIVE',best_for:'Movimento e cinematografia',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','720p','1080p'],supported_durations:durations(4,30),supported_aspect_ratios:['16:9','9:16','1:1','4:3','3:4','21:9'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,max_reference_images:30,max_reference_videos:10,max_reference_audio:10,max_prompt_length:20000,supports_start_end_image:true,created_at:now(),updated_at:now()},
 {model_id:'minimax-h3',name:'MiniMax H3',slug:'minimax-h3',category:'VIDEO',description:'Modelo multimodal rápido para referências de imagem, vídeo e áudio.',status:'ACTIVE',best_for:'Referências multimodais',recommended_aspect_ratio:'16:9',supported_modes:['TEXT_TO_VIDEO','IMAGE_TO_VIDEO','REFERENCE_TO_VIDEO'],supported_resolutions:['480p','540p','768p','1080p'],supported_durations:durations(3,15),supported_aspect_ratios:['16:9','9:16','1:1','4:3','3:4','21:9'],supports_image_reference:true,supports_multiple_images:true,supports_video_reference:true,supports_audio_reference:true,supports_negative_prompt:false,supports_seed:true,max_reference_images:9,max_reference_videos:3,max_reference_audio:3,max_prompt_length:10000,created_at:now(),updated_at:now()}
];
const PROVIDERS:ProviderRegistryItem[]=[
 {provider_id:'provider-atlas',name:'Atlas Cloud',slug:'atlas',status:'ACTIVE',priority:100,is_configured:false,created_at:now(),updated_at:now()},
 {provider_id:'provider-wavespeed',name:'WaveSpeed AI',slug:'wavespeed',status:'ACTIVE',priority:90,is_configured:false,created_at:now(),updated_at:now()}
];
const MAPPINGS:ProviderModelMapping[]=[
 ['wan-3-0-prime','provider-atlas'],['wan-3-0-prime','provider-wavespeed'],['wan-3-0','provider-atlas'],['wan-3-0','provider-wavespeed'],['seedance-2-5','provider-atlas'],['seedance-2-5','provider-wavespeed'],['minimax-h3','provider-atlas'],['minimax-h3','provider-wavespeed']
].map(([model_id,provider_id],i)=>({mapping_id:`map-${i+1}`,model_id,provider_id,provider_model_identifier:model_id,status:'ACTIVE',updated_at:now()} as ProviderModelMapping));

// Provider costs in BRL cents per output second. Snapshot 2026-09-08; editable in Admin.
const COSTS:Array<[string,string,string,number]>=[
 ['wan-3-0','provider-atlas','480p',20],['wan-3-0','provider-atlas','720p',41],['wan-3-0','provider-atlas','1080p',82],
 ['wan-3-0','provider-wavespeed','480p',24],['wan-3-0','provider-wavespeed','720p',48],['wan-3-0','provider-wavespeed','1080p',97],
 ['wan-3-0-prime','provider-atlas','480p',31],['wan-3-0-prime','provider-atlas','720p',64],['wan-3-0-prime','provider-atlas','1080p',129],
 ['wan-3-0-prime','provider-wavespeed','480p',36],['wan-3-0-prime','provider-wavespeed','720p',73],['wan-3-0-prime','provider-wavespeed','1080p',145],
 ['seedance-2-5','provider-atlas','480p',71],['seedance-2-5','provider-atlas','720p',153],['seedance-2-5','provider-atlas','1080p',302],
 ['minimax-h3','provider-atlas','768p',41],['minimax-h3','provider-wavespeed','768p',51]
];
const PRICING:PricingEntry[]=COSTS.map(([model,provider,res,cost],i)=>({pricing_id:`seed-price-${i+1}`,provider_id:provider,model_id:model,resolution:res,duration_seconds:1,unit:'PER_SECOND',provider_cost_cents:cost,customer_price_cents:Math.ceil(cost*1.12),currency:'BRL',effective_from:'2026-09-08T00:00:00.000Z',active:true,updated_at:now()}));
let initialized:Promise<void>|null=null;
async function ensure(){if(initialized)return initialized;initialized=(async()=>{const d=db();const seed=async(name:string,items:any[],idKey:string)=>{const snap=await d.collection(name).limit(1).get();if(snap.empty){const batch=d.batch();items.forEach(x=>batch.set(d.collection(name).doc(String(x[idKey])),x));await batch.commit();}};await seed('models',MODELS,'model_id');await seed('providers',PROVIDERS,'provider_id');await seed('provider_models',MAPPINGS,'mapping_id');await seed('pricing',PRICING,'pricing_id');await seed('feature_flags',INITIAL_FEATURE_FLAGS.map(f=>({...f,updated_at:now()})),'flag_key');})();return initialized;}
async function list<T>(name:string){await ensure();const snap=await db().collection(name).get();return snap.docs.map(d=>d.data() as T);}
export const catalogRepository={
 async listModels(){return (await list<ModelRegistryItem>('models')).filter(x=>x.status!=='INACTIVE');},async getModel(id:string){await ensure();const d=await db().collection('models').doc(id).get();return d.exists?d.data() as ModelRegistryItem:null;},async saveModel(x:ModelRegistryItem){await ensure();x.updated_at=now();await db().collection('models').doc(x.model_id).set(x,{merge:true});return x;},
 async listProviders(){return (await list<ProviderRegistryItem>('providers')).sort((a,b)=>b.priority-a.priority);},async getProvider(id:string){await ensure();const d=await db().collection('providers').doc(id).get();return d.exists?d.data() as ProviderRegistryItem:null;},async saveProvider(x:ProviderRegistryItem){await ensure();x.updated_at=now();await db().collection('providers').doc(x.provider_id).set(x,{merge:true});return x;},
 async listMappings(){return list<ProviderModelMapping>('provider_models');},async saveMapping(x:ProviderModelMapping){await ensure();x.updated_at=now();await db().collection('provider_models').doc(x.mapping_id).set(x,{merge:true});return x;},
 async listPricing(){return list<PricingEntry>('pricing');},async getPricing(id:string){await ensure();const d=await db().collection('pricing').doc(id).get();return d.exists?d.data() as PricingEntry:null;},async savePricing(x:PricingEntry){await ensure();x.updated_at=now();await db().collection('pricing').doc(x.pricing_id).set(x,{merge:true});return x;},
 async listPromotions(){return list<PromotionEntry>('promotions');},async getPromotion(id:string){await ensure();const d=await db().collection('promotions').doc(id).get();return d.exists?d.data() as PromotionEntry:null;},async savePromotion(x:PromotionEntry){await ensure();await db().collection('promotions').doc(x.promotion_id).set(x,{merge:true});return x;},
 async listFeatureFlags(){return list<FeatureFlag>('feature_flags');},async getFeatureFlag(id:string){await ensure();const d=await db().collection('feature_flags').doc(id).get();return d.exists?d.data() as FeatureFlag:null;},async saveFeatureFlag(x:FeatureFlag){await ensure();x.updated_at=now();await db().collection('feature_flags').doc(x.flag_key).set(x,{merge:true});return x;},clearForTesting(){}
};
