import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{Image as ImageIcon,LoaderCircle,Play,RefreshCw,Video,WandSparkles}from'lucide-react';
import type{BetaCapabilityMediaType,BetaCapabilityModel}from'../../beta/capabilityClient.js';
import type{FlowEdge,FlowNode,FlowRecord}from'../../beta/flowClient.js';
import type{FlowRunView}from'../../beta/flowRuntimeClient.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{spacesClient,SpaceAsset}from'../../services/spacesClient.js';
import{SpaceConnectionLayer}from'./canvas/SpaceConnectionLayer.js';
import{SPACE_BASE_NODE_H,SPACE_NODE_W,SPACE_WORLD_H,SPACE_WORLD_W,spaceNodeWidth}from'./canvas/spaceLayout.js';
import{SpaceQuickMenu,type SpaceQuickAction}from'./canvas/SpaceQuickMenu.js';
import{contextualActionsFor,smartConnectedNodePosition}from'./canvas/contextualCreation.js';
import{SpaceToolbar}from'./canvas/SpaceToolbar.js';
import{SpaceNodeShell}from'./nodes/SpaceNodeShell.js';
import{ImageGeneratorNode}from'./nodes/ImageGeneratorNode.js';
import{VideoGeneratorNode}from'./nodes/VideoGeneratorNode.js';
import{NodeResultPreview,type NodeOutputHistoryItem}from'./nodes/NodeResultPreview.js';
import{SpaceAdvancedInspector}from'./inspector/SpaceAdvancedInspector.js';
import{SpaceEmptyState}from'./SpaceEmptyState.js';
import{normalizeSpaceNodeV2,spaceNodeCapability,spaceNodeInputTypes,spaceNodeOutputTypes}from'./model/spaceNodeModel.js';

type QuickAction=SpaceQuickAction;
const errorText=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir a operação.';
const uid=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const capabilityLabels:Record<string,string>={
 'text-to-image':'Gerar imagem','image-to-image':'Gerar imagem','image-edit':'Editar imagem','background-remove-replace':'Remover ou trocar fundo','upscale':'Melhorar resolução','outpaint':'Expandir imagem','variations':'Criar variações','video-edit':'Editar vídeo','video-extend':'Estender vídeo','text-to-video':'Gerar vídeo','image-to-video':'Gerar vídeo',
};
const quickFor=(types:BetaCapabilityMediaType[]):QuickAction[]=>
 contextualActionsFor(types).map(action=>({...action,icon:action.capability.includes('video')?Video:action.capability==='image-edit'?WandSparkles:ImageIcon}));

interface Props{flow:FlowRecord;onBack:()=>void;onUpdated:(flow:FlowRecord)=>void;}

export const SpaceWorkspace:React.FC<Props>=({flow,onBack,onUpdated})=>{
 const[name,setName]=useState(flow.name||'Space sem título'),[nodes,setNodes]=useState<FlowNode[]>(flow.graph?.nodes||[]),[edges,setEdges]=useState<FlowEdge[]>(flow.graph?.edges||[]);
 const[models,setModels]=useState<BetaCapabilityModel[]>([]),[assets,setAssets]=useState<SpaceAsset[]>([]);
 const[selectedId,setSelectedId]=useState<string|null>(null),[inspectorOpen,setInspectorOpen]=useState(false),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[saved,setSaved]=useState(true);
 const[busy,setBusy]=useState(''),[error,setError]=useState(''),[catalogError,setCatalogError]=useState(''),[assetsError,setAssetsError]=useState('');
 const initialViewport=flow.graph?.viewport||{x:160,y:100,zoom:.9};
 const[run,setRun]=useState<FlowRunView|null>(null),[historyRuns,setHistoryRuns]=useState<FlowRunView[]>([]),[historyIndexByNode,setHistoryIndexByNode]=useState<Record<string,number>>({}),[zoom,setZoom]=useState(initialViewport.zoom),[pan,setPan]=useState({x:initialViewport.x,y:initialViewport.y});
 const[quick,setQuick]=useState<{x:number;y:number;worldX:number;worldY:number;fromId?:string|null}|null>(null),[quickQuery,setQuickQuery]=useState('');
 const[linking,setLinking]=useState<{fromId:string;clientX:number;clientY:number}|null>(null);
 const[nodeHeights,setNodeHeights]=useState<Record<string,number>>({});
 const canvasRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<{id:string;dx:number;dy:number}|null>(null),panRef=useRef<{x:number;y:number;ox:number;oy:number}|null>(null),saveTimer=useRef<number|null>(null),revisionRef=useRef(flow.revision);
 const selected=nodes.find(n=>n.node_id===selectedId)||null;
 const assetMap=useMemo(()=>new Map(assets.map(a=>[a.asset_id,a])),[assets]);
 const nodeRunMap=useMemo(()=>new Map((run?.node_runs||[]).map(n=>[n.node_id,n])),[run]);
 const nodeHistoryMap=useMemo(()=>{const map=new Map<string,NodeOutputHistoryItem[]>(),seen=new Set<string>(),runs=[...(run?[run]:[]),...historyRuns.filter(item=>item.run_id!==run?.run_id)].sort((a,b)=>Date.parse(b.created_at)-Date.parse(a.created_at));for(const flowRun of runs){for(const nodeRun of flowRun.node_runs||[]){if(nodeRun.reused_from_run_id)continue;for(const assetId of nodeRun.output_asset_ids||[]){const key=`${nodeRun.node_run_id}:${assetId}`;if(seen.has(key))continue;const asset=assetMap.get(assetId);if(!asset)continue;seen.add(key);const rows=map.get(nodeRun.node_id)||[];rows.push({asset,run_id:flowRun.run_id,node_run_id:nodeRun.node_run_id,authorized_credit_price:nodeRun.authorized_credit_price,created_at:nodeRun.created_at,completed_at:nodeRun.completed_at});map.set(nodeRun.node_id,rows);}}}return map;},[assetMap,historyRuns,run]);
 useEffect(()=>{const root=canvasRef.current;if(!root||typeof ResizeObserver==='undefined')return;const observer=new ResizeObserver(entries=>{setNodeHeights(current=>{let changed=false;const next={...current};for(const entry of entries){const id=(entry.target as HTMLElement).dataset.spaceNode;if(!id)continue;const height=Math.max(SPACE_BASE_NODE_H,Math.round(entry.contentRect.height));if(next[id]!==height){next[id]=height;changed=true;}}return changed?next:current;});});root.querySelectorAll<HTMLElement>('[data-space-node]').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[nodes.length,run?.run_id]);

 const loadCatalog=useCallback(async()=>{setCatalogError('');try{const result=await spacesClient.catalog();setModels(result.models||[]);}catch(e){setCatalogError(errorText(e));}},[]);
 const loadAssets=useCallback(async()=>{setAssetsError('');try{setAssets(await spacesClient.assets());}catch(e){setAssetsError(errorText(e));}},[]);
 const loadHistory=useCallback(async()=>{try{setHistoryRuns(await spacesClient.history(flow.flow_id,50));}catch(e){setError(errorText(e));}},[flow.flow_id]);
 useEffect(()=>{void loadCatalog();void loadAssets();void loadHistory();},[loadCatalog,loadAssets,loadHistory]);
 useEffect(()=>{const refresh=()=>void loadAssets();window.addEventListener('creations:updated',refresh);window.addEventListener('ia:asset-upload-complete',refresh);return()=>{window.removeEventListener('creations:updated',refresh);window.removeEventListener('ia:asset-upload-complete',refresh);};},[loadAssets]);

 const markDirty=()=>{setDirty(true);setSaved(false);};
 const save=useCallback(async(silent=false)=>{if(!dirty&&!silent)return flow;setSaving(true);try{const updated=await spacesClient.save(flow.flow_id,{name:name.trim()||'Space sem título',description:flow.description||'',project_id:flow.project_id||null,graph:{nodes:nodes.map(normalizeSpaceNodeV2),edges,viewport:{x:pan.x,y:pan.y,zoom},metadata:flow.graph?.metadata||{}},expected_revision:revisionRef.current});revisionRef.current=updated.revision;setDirty(false);setSaved(true);onUpdated(updated);return updated;}catch(e){setError(errorText(e));return null;}finally{setSaving(false);}},[dirty,edges,flow.description,flow.flow_id,flow.graph?.metadata,flow.project_id,name,nodes,onUpdated,pan.x,pan.y,zoom]);
 useEffect(()=>{if(!dirty)return;if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>void save(),650);return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current);};},[dirty,nodes,edges,name,save]);
 useEffect(()=>{if(!run||run.status!=='RUNNING')return;const timer=window.setTimeout(async()=>{try{const next=await spacesClient.advance(run.run_id);setRun(next);if(next.status==='SUCCEEDED'){await Promise.all([loadAssets(),loadHistory()]);setHistoryIndexByNode({});window.dispatchEvent(new CustomEvent('creations:updated'));}else if(next.status==='FAILED'){setError(next.error_message||'A execução do Space falhou. Revise o node destacado e tente novamente.');}else if(next.status==='CANCELLED'){setError('A execução do Space foi cancelada.');}}catch(e){setError(errorText(e));}},1800);return()=>window.clearTimeout(timer);},[run,loadAssets,loadHistory]);

 const canvasPoint=(clientX:number,clientY:number)=>{const r=canvasRef.current?.getBoundingClientRect();return r?{x:(clientX-r.left-pan.x)/zoom,y:(clientY-r.top-pan.y)/zoom}:{x:400,y:240};};
 const addNode=(base:Omit<FlowNode,'node_id'|'x'|'y'>,x:number,y:number)=>{const node:FlowNode=normalizeSpaceNodeV2({...base,node_id:uid('node'),x:Math.max(0,Math.min(SPACE_WORLD_W-SPACE_NODE_W,x)),y:Math.max(0,Math.min(SPACE_WORLD_H-SPACE_BASE_NODE_H,y))});setNodes(rows=>[...rows,node]);setSelectedId(node.node_id);markDirty();return node;};
 const modelFor=(capability:string)=>{const eligible=models.filter(m=>m.capabilities.some(c=>c.id===capability));return eligible.find(m=>m.model_id==='AUTO')||eligible[0]||null;};
 const focusNodePrompt=(nodeId:string)=>window.requestAnimationFrame(()=>{const el=canvasRef.current?.querySelector<HTMLTextAreaElement>(`[data-space-node="${nodeId}"] textarea`);el?.focus();});
 const addTool=(capability:string,x:number,y:number,fromId?:string|null)=>{const model=modelFor(capability),source=fromId?nodes.find(n=>n.node_id===fromId):null,position=source?smartConnectedNodePosition(source,nodes,{x,y}):{x,y};const next=addNode({kind:'TOOL',label:capabilityLabels[capability]||capability,capability_id:capability,model_id:model?.model_id||'AUTO',prompt:'',controls:{}},position.x,position.y);if(source){const out=spaceNodeOutputTypes(models,source),input=spaceNodeInputTypes(models,next),media=out.find(t=>input.includes(t));if(media)setEdges(rows=>[...rows,{edge_id:uid('edge'),from_node_id:source.node_id,to_node_id:next.node_id,media_type:media}]);}setQuick(null);setQuickQuery('');focusNodePrompt(next.node_id);};
 const addAssetNode=(asset:SpaceAsset,x:number,y:number)=>addNode({kind:'ASSET',label:asset.name||'Asset',media_type:asset.type as BetaCapabilityMediaType,asset_id:asset.asset_id},x,y);
 const patchNode=(id:string,patch:Partial<FlowNode>)=>{setNodes(rows=>rows.map(n=>n.node_id===id?{...n,...patch}:n));markDirty();};
 const removeNode=(id:string)=>{setNodes(rows=>rows.filter(n=>n.node_id!==id));setEdges(rows=>rows.filter(e=>e.from_node_id!==id&&e.to_node_id!==id));if(selectedId===id){setSelectedId(null);setInspectorOpen(false);}markDirty();};
 const duplicateNode=(node:FlowNode)=>{const{node_id:_,...base}=node;addNode(base,node.x+40,node.y+40);};

 const connectExisting=(fromId:string,toId:string)=>{if(fromId===toId)return;const a=nodes.find(n=>n.node_id===fromId),b=nodes.find(n=>n.node_id===toId);if(!a||!b)return;const media=spaceNodeOutputTypes(models,a).find(t=>spaceNodeInputTypes(models,b).includes(t));if(!media){setError('Esses nodes não possuem mídia compatível.');return;}if(!edges.some(e=>e.from_node_id===fromId&&e.to_node_id===toId&&e.media_type===media)){setEdges(rows=>[...rows,{edge_id:uid('edge'),from_node_id:fromId,to_node_id:toId,media_type:media}]);markDirty();}};

 const uploadAt=async(file:File,x:number,y:number)=>{if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return;setBusy('upload');setError('');try{const uploaded=await assetService.uploadAsset({file,name:file.name});await loadAssets();const asset:SpaceAsset={asset_id:uploaded.asset_id,type:uploaded.type,category:uploaded.category,name:uploaded.name,alias:uploaded.alias,status:uploaded.status,origin:String(uploaded.origin||'UPLOAD'),public_url:uploaded.public_url||null,preview_url:uploaded.preview_url||uploaded.thumbnail_url||uploaded.public_url||null,preview_mime_type:uploaded.preview_mime_type||null,mime_type:uploaded.mime_type,size_bytes:uploaded.size_bytes,width:uploaded.width??null,height:uploaded.height??null,duration_seconds:uploaded.duration_seconds??null,source_generation_id:uploaded.source_generation_id??null,source_job_id:uploaded.source_job_id??null,derived_from_asset_id:uploaded.derived_from_asset_id??null,source_output_index:uploaded.source_output_index??null,source_model_id:uploaded.source_model_id??null,media_metadata:uploaded.media_metadata||{},created_at:uploaded.created_at,updated_at:uploaded.updated_at};setAssets(rows=>[asset,...rows.filter(a=>a.asset_id!==asset.asset_id)]);addAssetNode(asset,x,y);}catch(e){setError(errorText(e));}finally{setBusy('');}};
 useEffect(()=>{const onPaste=(event:ClipboardEvent)=>{const clipboardFiles=event.clipboardData?Array.from(event.clipboardData.files) as File[]:[];const file=clipboardFiles.find((f:File)=>f.type.startsWith('image/')||f.type.startsWith('video/'));if(!file)return;event.preventDefault();const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const p=canvasPoint(r.left+r.width*.5,r.top+r.height*.45);void uploadAt(file,p.x-SPACE_NODE_W/2,p.y-SPACE_BASE_NODE_H/2);};window.addEventListener('paste',onPaste);return()=>window.removeEventListener('paste',onPaste);},[pan,zoom,loadAssets]);
 const onDrop=(e:React.DragEvent)=>{e.preventDefault();const droppedFiles=Array.from(e.dataTransfer.files) as File[];const file=droppedFiles.find((f:File)=>f.type.startsWith('image/')||f.type.startsWith('video/'));if(!file)return;const p=canvasPoint(e.clientX,e.clientY);void uploadAt(file,p.x-SPACE_NODE_W/2,p.y-SPACE_BASE_NODE_H/2);};

 const startRun=async(mode:'FULL'|'NODE'|'DOWNSTREAM'='FULL',targetNodeId?:string)=>{if(busy==='run'||run?.status==='RUNNING')return;setBusy('run');setError('');try{const persisted=dirty?await save():flow;if(!persisted)return;setHistoryIndexByNode(current=>targetNodeId?{...current,[targetNodeId]:0}:current);setRun(await spacesClient.start(persisted.flow_id,{},undefined,{mode,target_node_id:targetNodeId||null}));}catch(e){setError(errorText(e));}finally{setBusy('');}};
 const fit=()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r||!nodes.length){setZoom(.9);setPan({x:160,y:100});markDirty();return;}const minX=Math.min(...nodes.map(n=>n.x)),minY=Math.min(...nodes.map(n=>n.y)),maxX=Math.max(...nodes.map(n=>n.x+spaceNodeWidth(n))),maxY=Math.max(...nodes.map(n=>n.y+(nodeHeights[n.node_id]||SPACE_BASE_NODE_H)));const z=Math.max(.35,Math.min(1.15,Math.min((r.width-180)/(maxX-minX),(r.height-180)/(maxY-minY))));setZoom(z);setPan({x:(r.width-(minX+maxX)*z)/2,y:(r.height-(minY+maxY)*z)/2});markDirty();};
 const onWheel=(e:React.WheelEvent)=>{e.preventDefault();const next=Math.max(.35,Math.min(1.65,zoom*(e.deltaY>0?.9:1.1)));const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const mx=e.clientX-r.left,my=e.clientY-r.top,wx=(mx-pan.x)/zoom,wy=(my-pan.y)/zoom;setPan({x:mx-wx*next,y:my-wy*next});setZoom(next);markDirty();};
 const onCanvasDown=(e:React.PointerEvent)=>{if(e.button!==0||e.target!==e.currentTarget)return;setSelectedId(null);setQuick(null);panRef.current={x:e.clientX,y:e.clientY,ox:pan.x,oy:pan.y};e.currentTarget.setPointerCapture(e.pointerId);};
 const onCanvasMove=(e:React.PointerEvent)=>{if(linking){setLinking(v=>v?{...v,clientX:e.clientX,clientY:e.clientY}:v);return;}if(dragRef.current){const p=canvasPoint(e.clientX,e.clientY);setNodes(rows=>rows.map(n=>n.node_id===dragRef.current?.id?{...n,x:Math.max(0,Math.min(SPACE_WORLD_W-spaceNodeWidth(n),p.x-dragRef.current!.dx)),y:Math.max(0,Math.min(SPACE_WORLD_H-SPACE_BASE_NODE_H,p.y-dragRef.current!.dy))}:n));setSaved(false);return;}if(panRef.current)setPan({x:panRef.current.ox+e.clientX-panRef.current.x,y:panRef.current.oy+e.clientY-panRef.current.y});};
 const onCanvasUp=(e:React.PointerEvent)=>{if(linking){const r=canvasRef.current?.getBoundingClientRect();const p=canvasPoint(e.clientX,e.clientY);if(r){setInspectorOpen(false);setQuick({x:e.clientX-r.left,y:e.clientY-r.top,worldX:p.x,worldY:p.y,fromId:linking.fromId});setQuickQuery('');}setLinking(null);}if(dragRef.current){dragRef.current=null;markDirty();}if(panRef.current)markDirty();panRef.current=null;};
 const openAddMenu=()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const p=canvasPoint(r.left+r.width*.5,r.top+r.height*.45);setInspectorOpen(false);setLinking(null);setQuick({x:Math.min(r.width-310,Math.max(20,r.width*.5-150)),y:86,worldX:p.x,worldY:p.y,fromId:null});setQuickQuery('');};
 const onCanvasContext=(e:React.MouseEvent)=>{e.preventDefault();const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const p=canvasPoint(e.clientX,e.clientY);setSelectedId(null);setInspectorOpen(false);setLinking(null);setQuick({x:e.clientX-r.left,y:e.clientY-r.top,worldX:p.x,worldY:p.y,fromId:null});setQuickQuery('');};

 useEffect(()=>{if(!quick)return;const onPointerDown=(event:PointerEvent)=>{const target=event.target as HTMLElement|null;if(target?.closest('[data-space-popover="quick-menu"],[data-space-popover-trigger="add"]'))return;setQuick(null);setQuickQuery('');};document.addEventListener('pointerdown',onPointerDown,true);return()=>document.removeEventListener('pointerdown',onPointerDown,true);},[quick]);

 useEffect(()=>{const onKeyDown=(event:KeyboardEvent)=>{const target=event.target as HTMLElement|null,isTyping=Boolean(target?.closest('input,textarea,select,[contenteditable="true"]'));if(event.key==='Escape'){setQuick(null);setQuickQuery('');setLinking(null);setInspectorOpen(false);return;}if(isTyping)return;if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='d'&&selected){event.preventDefault();duplicateNode(selected);return;}if((event.key==='Delete'||event.key==='Backspace')&&selected){event.preventDefault();removeNode(selected.node_id);return;}if(event.key.toLowerCase()==='f'){event.preventDefault();fit();return;}if(event.key==='/'){event.preventDefault();openAddMenu();}};window.addEventListener('keydown',onKeyDown);return()=>window.removeEventListener('keydown',onKeyDown);},[selected,nodes,edges,pan,zoom]);

 const sourceForQuick=quick?.fromId?nodes.find(n=>n.node_id===quick.fromId):null;
 const sourceQuickTypes=sourceForQuick?spaceNodeOutputTypes(models,sourceForQuick):[];
 const rootQuickActions=useMemo(()=>[
  {id:'text-to-image',label:'Gerar imagem',capability:'text-to-image',icon:ImageIcon,description:'Comece com um prompt de imagem.'},
  {id:'text-to-video',label:'Gerar vídeo',capability:'text-to-video',icon:Video,description:'Comece com um prompt de vídeo.'},
  {id:'image-edit',label:'Editar imagem',capability:'image-edit',icon:WandSparkles,description:'Crie o node e conecte uma imagem depois.',group:'TRANSFORMAR'},
  {id:'video-edit',label:'Editar vídeo',capability:'video-edit',icon:WandSparkles,description:'Crie o node e conecte um vídeo depois.',group:'VÍDEO'},
  {id:'video-extend',label:'Estender vídeo',capability:'video-extend',icon:Video,description:'Crie o node e conecte um vídeo depois.',group:'VÍDEO'},
 ] as QuickAction[],[]);
 const quickActions=useMemo(()=>sourceForQuick?quickFor(spaceNodeOutputTypes(models,sourceForQuick)):rootQuickActions,[sourceForQuick,models,rootQuickActions]);
 const emptyPoint=()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r)return{x:760,y:420};const p=canvasPoint(r.left+r.width*.5,r.top+r.height*.48);return{x:p.x-SPACE_NODE_W/2,y:p.y-SPACE_BASE_NODE_H/2};};
 const addEmptyTool=(action:QuickAction)=>{const p=emptyPoint();addTool(action.capability,p.x,p.y,null);};
 const addEmptyAsset=(type:'IMAGE'|'VIDEO')=>{const p=emptyPoint(),asset=assets.find(a=>a.type===type);if(asset)addAssetNode(asset,p.x,p.y);else setError(type==='IMAGE'?'Sua Biblioteca ainda não possui imagens.':'Sua Biblioteca ainda não possui vídeos.');};
 const visibleQuick=quickActions.filter(a=>a.label.toLowerCase().includes(quickQuery.toLowerCase()));

 const preview=(node:FlowNode)=>{const history=nodeHistoryMap.get(node.node_id)||[];if(history.length){const index=historyIndexByNode[node.node_id]||0;return <NodeResultPreview items={history} index={index} onIndexChange={next=>setHistoryIndexByNode(current=>({...current,[node.node_id]:next}))}/>;}const asset=node.asset_id?assetMap.get(node.asset_id):null;if(!asset)return null;const url=asset.preview_url||asset.public_url;if(!url)return null;if(asset.type==='IMAGE')return <img src={url} alt="" draggable={false} className="h-full w-full bg-black/30 object-cover"/>;if(asset.type==='VIDEO')return <video src={asset.public_url||url} muted preload="metadata" playsInline controls className="h-full w-full bg-black object-cover"/>;return null;};

 const renderNode=(node:FlowNode)=>{const selectedNow=selectedId===node.node_id,cap=spaceNodeCapability(models,node),manualModels=models.filter(m=>m.model_id!=='AUTO'&&m.capabilities.some(c=>c.id===node.capability_id)),nr=nodeRunMap.get(node.node_id),out=spaceNodeOutputTypes(models,node),isAsset=node.kind==='ASSET',mediaPreview=preview(node),history=nodeHistoryMap.get(node.node_id)||[],historyIndex=historyIndexByNode[node.node_id]||0,isImageGenerator=node.kind==='TOOL'&&['text-to-image','image-to-image'].includes(node.capability_id||''),isVideoGenerator=node.kind==='TOOL'&&['text-to-video','image-to-video'].includes(node.capability_id||'');return <SpaceNodeShell key={node.node_id} node={node} selected={selectedNow} nodeRun={nr} outputTypes={out} subtitle={isAsset?'Asset da Biblioteca':capabilityLabels[node.capability_id||'']||node.capability_id||''} onPointerDown={e=>{if((e.target as HTMLElement).closest('button,input,textarea,select'))return;e.stopPropagation();setSelectedId(node.node_id);const p=canvasPoint(e.clientX,e.clientY);dragRef.current={id:node.node_id,dx:p.x-node.x,dy:p.y-node.y};}} onInputPointerUp={e=>{if(linking){e.stopPropagation();connectExisting(linking.fromId,node.node_id);setLinking(null);}}} onOutputPointerDown={e=>{e.stopPropagation();setLinking({fromId:node.node_id,clientX:e.clientX,clientY:e.clientY});}} onLabelChange={value=>patchNode(node.node_id,{label:value})} onDuplicate={()=>duplicateNode(node)} onDelete={()=>removeNode(node.node_id)} onRunFromHere={node.kind==='TOOL'&&run?.status!=='RUNNING'?()=>void startRun('DOWNSTREAM',node.node_id):undefined} onInspect={node.kind==='TOOL'?()=>{setQuick(null);setQuickQuery('');setLinking(null);setSelectedId(node.node_id);setInspectorOpen(true);}:undefined}>
   {isImageGenerator?<ImageGeneratorNode node={node} capability={cap} models={models} nodeRun={nr} history={history} historyIndex={historyIndex} busy={busy==='run'||run?.status==='RUNNING'} onHistoryIndexChange={next=>setHistoryIndexByNode(current=>({...current,[node.node_id]:next}))} onPatch={patch=>patchNode(node.node_id,patch)} onGenerate={()=>{setSelectedId(node.node_id);void startRun('NODE',node.node_id);}}/>:isVideoGenerator?<VideoGeneratorNode node={node} capability={cap} models={models} nodeRun={nr} history={history} historyIndex={historyIndex} busy={busy==='run'||run?.status==='RUNNING'} onHistoryIndexChange={next=>setHistoryIndexByNode(current=>({...current,[node.node_id]:next}))} onPatch={patch=>patchNode(node.node_id,patch)} onGenerate={()=>{setSelectedId(node.node_id);void startRun('NODE',node.node_id);}}/>:isAsset?<div className="h-[210px] overflow-hidden bg-[#071018]">{mediaPreview||<div className="grid h-full place-items-center text-[8px] text-zinc-600">Asset indisponível</div>}</div>:<div className="space-y-2 px-2.5 pb-2.5">
    {mediaPreview||<textarea rows={2} value={node.prompt||''} onChange={e=>patchNode(node.node_id,{prompt:e.target.value})} placeholder="Digite o prompt…" className="w-full resize-none rounded-lg bg-black/20 p-2 text-[8px] leading-relaxed text-zinc-300 outline-none placeholder:text-zinc-700 focus:ring-1 focus:ring-cyan-400/15"/>}
    {node.kind==='TOOL'&&<div className="flex items-center gap-1.5"><select value={node.model_id||'AUTO'} onChange={e=>patchNode(node.node_id,{model_id:e.target.value})} className="min-w-0 flex-1 rounded-lg bg-black/25 px-2 py-1.5 text-[8px] text-zinc-400 outline-none"><option value="AUTO">Auto</option>{manualModels.map(m=><option key={m.model_id} value={m.model_id}>{m.name}</option>)}</select><button onClick={()=>{setSelectedId(node.node_id);void startRun('NODE',node.node_id);}} disabled={Boolean(busy)||run?.status==='RUNNING'||!cap} className="inline-flex h-7 items-center gap-1 rounded-lg bg-cyan-300 px-2 text-[8px] font-black text-[#041019] disabled:opacity-40"><Play className="h-3 w-3"/>Gerar</button></div>}
   </div>}
  </SpaceNodeShell>;};

 return <div className="flex h-full min-h-0 flex-col bg-[#050a10] text-zinc-100">
  <SpaceToolbar name={name} onNameChange={value=>{setName(value);markDirty();}} onBack={()=>{void (async()=>{if(dirty)await save(true);onBack();})();}} saving={saving} saved={saved} running={busy==='run'||run?.status==='RUNNING'} addOpen={Boolean(quick&&!quick.fromId)} zoom={zoom} onZoomOut={()=>{setZoom(z=>Math.max(.35,z/1.15));markDirty();}} onZoomIn={()=>{setZoom(z=>Math.min(1.65,z*1.15));markDirty();}} onFit={fit} onAdd={openAddMenu} onRunAll={()=>void startRun('FULL')}/>
  {(error||catalogError||assetsError)&&<div role="alert" aria-live="assertive" className="flex shrink-0 items-center gap-3 border-b border-rose-400/10 bg-rose-500/[0.06] px-4 py-2 text-[9px] text-rose-300"><span className="min-w-0 flex-1 truncate">{error||catalogError||assetsError}</span><button onClick={()=>{setError('');void loadCatalog();void loadAssets();}} className="inline-flex items-center gap-1 font-bold"><RefreshCw className="h-3 w-3"/>Recarregar</button></div>}
  <div className="relative min-h-0 flex-1 overflow-hidden">
   <div ref={canvasRef} role="application" aria-label="Canvas do Space" tabIndex={0} onDragOver={e=>e.preventDefault()} onDrop={onDrop} onWheel={onWheel} onContextMenu={onCanvasContext} onPointerDown={onCanvasDown} onPointerMove={onCanvasMove} onPointerUp={onCanvasUp} onPointerCancel={onCanvasUp} className="relative h-full w-full touch-none overflow-hidden bg-[#050a10]" style={{backgroundImage:'radial-gradient(rgba(125,211,252,.13) 1px, transparent 1px)',backgroundSize:`${24*zoom}px ${24*zoom}px`,backgroundPosition:`${pan.x}px ${pan.y}px`}}>
    {!nodes.length&&<SpaceEmptyState actions={rootQuickActions} isReady={capability=>Boolean(modelFor(capability))} onAction={addEmptyTool} onAddImageAsset={()=>addEmptyAsset('IMAGE')} onAddVideoAsset={()=>addEmptyAsset('VIDEO')}/>}
    <div className="absolute origin-top-left" style={{width:SPACE_WORLD_W,height:SPACE_WORLD_H,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
     <SpaceConnectionLayer nodes={nodes} edges={edges} nodeHeights={nodeHeights}/>
     {nodes.map(renderNode)}
    </div>
    {linking&&(()=>{const r=canvasRef.current?.getBoundingClientRect(),source=nodes.find(n=>n.node_id===linking.fromId);if(!r||!source)return null;const x1=pan.x+(source.x+spaceNodeWidth(source))*zoom,y1=pan.y+(source.y+(nodeHeights[source.node_id]||SPACE_BASE_NODE_H)/2)*zoom,x2=linking.clientX-r.left,y2=linking.clientY-r.top,c=Math.max(80,Math.abs(x2-x1)*.4);return <svg className="pointer-events-none absolute inset-0 h-full w-full"><path d={`M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`} fill="none" stroke="rgba(34,211,238,.8)" strokeWidth="2" strokeDasharray="6 5"/></svg>;})()}
    {quick&&<SpaceQuickMenu x={quick.x} y={quick.y} canvasWidth={canvasRef.current?.clientWidth||900} canvasHeight={canvasRef.current?.clientHeight||700} fromSource={Boolean(sourceForQuick)} sourceTypeLabel={sourceQuickTypes.includes('IMAGE')?'imagem':sourceQuickTypes.includes('VIDEO')?'vídeo':null} query={quickQuery} actions={visibleQuick} onQueryChange={setQuickQuery} isReady={capability=>Boolean(modelFor(capability))} onAction={action=>addTool(action.capability,quick.worldX,quick.worldY,quick.fromId)} onAddImageAsset={()=>{const img=assets.find(a=>a.type==='IMAGE');if(img)addAssetNode(img,quick.worldX,quick.worldY);else setError('Sua Biblioteca ainda não possui imagens.');setQuick(null);}} onAddVideoAsset={()=>{const vid=assets.find(a=>a.type==='VIDEO');if(vid)addAssetNode(vid,quick.worldX,quick.worldY);else setError('Sua Biblioteca ainda não possui vídeos.');setQuick(null);}}/>}
    {inspectorOpen&&selected?.kind==='TOOL'&&<SpaceAdvancedInspector node={selected} capability={spaceNodeCapability(models,selected)} models={models} nodeRun={nodeRunMap.get(selected.node_id)} onPatch={patch=>patchNode(selected.node_id,patch)} onClose={()=>setInspectorOpen(false)}/>}
    {busy==='upload'&&<div role="status" aria-live="polite" className="absolute bottom-5 right-5 z-40 inline-flex items-center gap-2 rounded-xl border border-white/[0.07] bg-[#08131e]/95 px-3 py-2 text-[9px] text-zinc-300 shadow-xl"><LoaderCircle className="h-3.5 w-3.5 animate-spin text-cyan-300"/>Enviando asset…</div>}
   </div>
  </div>
 </div>;
};

export default SpaceWorkspace;
