import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{ArrowLeft,Check,ChevronDown,Copy,Image as ImageIcon,LoaderCircle,Maximize2,Minus,MousePointer2,Play,Plus,RefreshCw,Save,Search,Trash2,Video,WandSparkles,ZoomIn,ZoomOut}from'lucide-react';
import type{BetaCapability,BetaCapabilityMediaType,BetaCapabilityModel}from'../../beta/capabilityClient.js';
import type{FlowEdge,FlowNode,FlowRecord}from'../../beta/flowClient.js';
import type{FlowRunView}from'../../beta/flowRuntimeClient.js';
import{assetService}from'../../services/assetService.js';
import{ApiError}from'../../services/apiClient.js';
import{spacesClient,SpaceAsset}from'../../services/spacesClient.js';

const WORLD_W=8000,WORLD_H=5000,NODE_W=260,NODE_H=170;
type QuickAction={id:string;label:string;capability:string;icon:React.ComponentType<{className?:string}>;description:string};
const errorText=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir a operação.';
const uid=(prefix:string)=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
const capabilityLabels:Record<string,string>={
 'text-to-image':'Gerar imagem','image-to-image':'Gerar imagem','image-edit':'Editar imagem','video-edit':'Editar vídeo','video-extend':'Estender vídeo','text-to-video':'Gerar vídeo','image-to-video':'Gerar vídeo',
};
const capabilityForOutput=(models:BetaCapabilityModel[],node:FlowNode)=>{if(node.kind==='ASSET'||node.kind==='INPUT')return node.media_type?[node.media_type]:[];if(node.kind==='TOOL'&&node.capability_id){for(const model of models){const cap=model.capabilities.find(c=>c.id===node.capability_id);if(cap)return cap.outputs;}}return[] as BetaCapabilityMediaType[];};
const capabilityForInput=(models:BetaCapabilityModel[],node:FlowNode)=>{if(node.kind==='TOOL'&&node.capability_id){for(const model of models){const cap=model.capabilities.find(c=>c.id===node.capability_id);if(cap)return cap.inputs;}}return[] as BetaCapabilityMediaType[];};
const capabilityView=(models:BetaCapabilityModel[],node:FlowNode):BetaCapability|null=>{if(node.kind!=='TOOL'||!node.capability_id)return null;const preferred=models.find(m=>m.model_id===node.model_id)?.capabilities.find(c=>c.id===node.capability_id);if(preferred)return preferred;return models.flatMap(m=>m.capabilities).find(c=>c.id===node.capability_id)||null;};
const pathFor=(a:FlowNode,b:FlowNode)=>{const x1=a.x+NODE_W,y1=a.y+NODE_H/2,x2=b.x,y2=b.y+NODE_H/2,c=Math.max(80,Math.abs(x2-x1)*.45);return`M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`;};

const quickFor=(types:BetaCapabilityMediaType[]):QuickAction[]=>{
 const rows:QuickAction[]=[];
 if(types.includes('IMAGE'))rows.push(
  {id:'image-to-image',label:'Gerar imagem',capability:'image-to-image',icon:ImageIcon,description:'Use esta imagem como referência.'},
  {id:'image-edit',label:'Editar imagem',capability:'image-edit',icon:WandSparkles,description:'Transforme mantendo a imagem como origem.'},
  {id:'image-to-video',label:'Gerar vídeo',capability:'image-to-video',icon:Video,description:'Anime esta imagem em vídeo.'},
 );
 if(types.includes('VIDEO'))rows.push(
  {id:'video-edit',label:'Editar vídeo',capability:'video-edit',icon:WandSparkles,description:'Transforme este vídeo com IA.'},
  {id:'video-extend',label:'Estender vídeo',capability:'video-extend',icon:Video,description:'Continue o vídeo preservando a sequência.'},
 );
 return rows;
};

interface Props{flow:FlowRecord;onBack:()=>void;onUpdated:(flow:FlowRecord)=>void;}

export const SpaceWorkspace:React.FC<Props>=({flow,onBack,onUpdated})=>{
 const[name,setName]=useState(flow.name||'Space sem título'),[nodes,setNodes]=useState<FlowNode[]>(flow.graph?.nodes||[]),[edges,setEdges]=useState<FlowEdge[]>(flow.graph?.edges||[]);
 const[models,setModels]=useState<BetaCapabilityModel[]>([]),[assets,setAssets]=useState<SpaceAsset[]>([]);
 const[selectedId,setSelectedId]=useState<string|null>(null),[dirty,setDirty]=useState(false),[saving,setSaving]=useState(false),[saved,setSaved]=useState(true);
 const[busy,setBusy]=useState(''),[error,setError]=useState(''),[catalogError,setCatalogError]=useState(''),[assetsError,setAssetsError]=useState('');
 const[run,setRun]=useState<FlowRunView|null>(null),[zoom,setZoom]=useState(.9),[pan,setPan]=useState({x:160,y:100});
 const[quick,setQuick]=useState<{x:number;y:number;worldX:number;worldY:number;fromId?:string|null}|null>(null),[quickQuery,setQuickQuery]=useState('');
 const[linking,setLinking]=useState<{fromId:string;clientX:number;clientY:number}|null>(null);
 const canvasRef=useRef<HTMLDivElement|null>(null),dragRef=useRef<{id:string;dx:number;dy:number}|null>(null),panRef=useRef<{x:number;y:number;ox:number;oy:number}|null>(null),saveTimer=useRef<number|null>(null),revisionRef=useRef(flow.revision);
 const selected=nodes.find(n=>n.node_id===selectedId)||null;
 const assetMap=useMemo(()=>new Map(assets.map(a=>[a.asset_id,a])),[assets]);
 const nodeRunMap=useMemo(()=>new Map((run?.node_runs||[]).map(n=>[n.node_id,n])),[run]);

 const loadCatalog=useCallback(async()=>{setCatalogError('');try{const result=await spacesClient.catalog();setModels(result.models||[]);}catch(e){setCatalogError(errorText(e));}},[]);
 const loadAssets=useCallback(async()=>{setAssetsError('');try{setAssets(await spacesClient.assets());}catch(e){setAssetsError(errorText(e));}},[]);
 useEffect(()=>{void loadCatalog();void loadAssets();},[loadCatalog,loadAssets]);
 useEffect(()=>{const refresh=()=>void loadAssets();window.addEventListener('creations:updated',refresh);window.addEventListener('ia:asset-upload-complete',refresh);return()=>{window.removeEventListener('creations:updated',refresh);window.removeEventListener('ia:asset-upload-complete',refresh);};},[loadAssets]);

 const markDirty=()=>{setDirty(true);setSaved(false);};
 const save=useCallback(async(silent=false)=>{if(!dirty&&!silent)return flow;setSaving(true);try{const updated=await spacesClient.save(flow.flow_id,{name:name.trim()||'Space sem título',description:flow.description||'',project_id:flow.project_id||null,graph:{nodes,edges},expected_revision:revisionRef.current});revisionRef.current=updated.revision;setDirty(false);setSaved(true);onUpdated(updated);return updated;}catch(e){setError(errorText(e));return null;}finally{setSaving(false);}},[dirty,edges,flow.description,flow.flow_id,flow.project_id,name,nodes,onUpdated]);
 useEffect(()=>{if(!dirty)return;if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(()=>void save(),650);return()=>{if(saveTimer.current)window.clearTimeout(saveTimer.current);};},[dirty,nodes,edges,name,save]);
 useEffect(()=>{if(!run||run.status!=='RUNNING')return;const timer=window.setTimeout(async()=>{try{const next=await spacesClient.advance(run.run_id);setRun(next);if(next.status==='SUCCEEDED'){await loadAssets();window.dispatchEvent(new CustomEvent('creations:updated'));}}catch(e){setError(errorText(e));}},1800);return()=>window.clearTimeout(timer);},[run,loadAssets]);

 const canvasPoint=(clientX:number,clientY:number)=>{const r=canvasRef.current?.getBoundingClientRect();return r?{x:(clientX-r.left-pan.x)/zoom,y:(clientY-r.top-pan.y)/zoom}:{x:400,y:240};};
 const addNode=(base:Omit<FlowNode,'node_id'|'x'|'y'>,x:number,y:number)=>{const node:FlowNode={...base,node_id:uid('node'),x:Math.max(0,Math.min(WORLD_W-NODE_W,x)),y:Math.max(0,Math.min(WORLD_H-NODE_H,y))};setNodes(rows=>[...rows,node]);setSelectedId(node.node_id);markDirty();return node;};
 const modelFor=(capability:string)=>{const eligible=models.filter(m=>m.capabilities.some(c=>c.id===capability));return eligible.find(m=>m.model_id==='AUTO')||eligible[0]||null;};
 const addTool=(capability:string,x:number,y:number,fromId?:string|null)=>{const model=modelFor(capability);if(!model){setError('Nenhum modelo elegível está disponível para esta ação.');return;}const next=addNode({kind:'TOOL',label:capabilityLabels[capability]||capability,capability_id:capability,model_id:model.model_id,prompt:'',controls:{}},x,y);if(fromId){const source=nodes.find(n=>n.node_id===fromId);if(source){const out=capabilityForOutput(models,source),input=capabilityForInput(models,next),media=out.find(t=>input.includes(t));if(media)setEdges(rows=>[...rows,{edge_id:uid('edge'),from_node_id:fromId,to_node_id:next.node_id,media_type:media}]);}}setQuick(null);setQuickQuery('');};
 const addAssetNode=(asset:SpaceAsset,x:number,y:number)=>addNode({kind:'ASSET',label:asset.name||'Asset',media_type:asset.type as BetaCapabilityMediaType,asset_id:asset.asset_id},x,y);
 const patchNode=(id:string,patch:Partial<FlowNode>)=>{setNodes(rows=>rows.map(n=>n.node_id===id?{...n,...patch}:n));markDirty();};
 const removeNode=(id:string)=>{setNodes(rows=>rows.filter(n=>n.node_id!==id));setEdges(rows=>rows.filter(e=>e.from_node_id!==id&&e.to_node_id!==id));if(selectedId===id)setSelectedId(null);markDirty();};
 const duplicateNode=(node:FlowNode)=>{const{node_id:_,...base}=node;addNode(base,node.x+40,node.y+40);};

 const connectExisting=(fromId:string,toId:string)=>{if(fromId===toId)return;const a=nodes.find(n=>n.node_id===fromId),b=nodes.find(n=>n.node_id===toId);if(!a||!b)return;const media=capabilityForOutput(models,a).find(t=>capabilityForInput(models,b).includes(t));if(!media){setError('Esses nodes não possuem mídia compatível.');return;}if(!edges.some(e=>e.from_node_id===fromId&&e.to_node_id===toId&&e.media_type===media)){setEdges(rows=>[...rows,{edge_id:uid('edge'),from_node_id:fromId,to_node_id:toId,media_type:media}]);markDirty();}};

 const uploadAt=async(file:File,x:number,y:number)=>{if(!file.type.startsWith('image/')&&!file.type.startsWith('video/'))return;setBusy('upload');setError('');try{const uploaded=await assetService.uploadAsset({file,name:file.name});await loadAssets();const asset:SpaceAsset={asset_id:uploaded.asset_id,type:uploaded.type,category:uploaded.category,name:uploaded.name,alias:uploaded.alias,status:uploaded.status,origin:String(uploaded.origin||'UPLOAD'),public_url:uploaded.public_url||null,preview_url:uploaded.preview_url||uploaded.thumbnail_url||uploaded.public_url||null,preview_mime_type:uploaded.preview_mime_type||null,mime_type:uploaded.mime_type,size_bytes:uploaded.size_bytes,width:uploaded.width??null,height:uploaded.height??null,duration_seconds:uploaded.duration_seconds??null,source_generation_id:uploaded.source_generation_id??null,source_job_id:uploaded.source_job_id??null,derived_from_asset_id:uploaded.derived_from_asset_id??null,source_output_index:uploaded.source_output_index??null,source_model_id:uploaded.source_model_id??null,media_metadata:uploaded.media_metadata||{},created_at:uploaded.created_at,updated_at:uploaded.updated_at};setAssets(rows=>[asset,...rows.filter(a=>a.asset_id!==asset.asset_id)]);addAssetNode(asset,x,y);}catch(e){setError(errorText(e));}finally{setBusy('');}};
 useEffect(()=>{const onPaste=(event:ClipboardEvent)=>{const file=Array.from(event.clipboardData?.files||[]).find(f=>f.type.startsWith('image/')||f.type.startsWith('video/'));if(!file)return;event.preventDefault();const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const p=canvasPoint(r.left+r.width*.5,r.top+r.height*.45);void uploadAt(file,p.x-NODE_W/2,p.y-NODE_H/2);};window.addEventListener('paste',onPaste);return()=>window.removeEventListener('paste',onPaste);},[pan,zoom,loadAssets]);
 const onDrop=(e:React.DragEvent)=>{e.preventDefault();const file=Array.from(e.dataTransfer.files||[]).find(f=>f.type.startsWith('image/')||f.type.startsWith('video/'));if(!file)return;const p=canvasPoint(e.clientX,e.clientY);void uploadAt(file,p.x-NODE_W/2,p.y-NODE_H/2);};

 const startRun=async()=>{setBusy('run');setError('');try{const persisted=dirty?await save():flow;if(!persisted)return;setRun(await spacesClient.start(flow.flow_id,{}));}catch(e){setError(errorText(e));}finally{setBusy('');}};
 const fit=()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r||!nodes.length){setZoom(.9);setPan({x:160,y:100});return;}const minX=Math.min(...nodes.map(n=>n.x)),minY=Math.min(...nodes.map(n=>n.y)),maxX=Math.max(...nodes.map(n=>n.x+NODE_W)),maxY=Math.max(...nodes.map(n=>n.y+NODE_H));const z=Math.max(.35,Math.min(1.15,Math.min((r.width-180)/(maxX-minX),(r.height-180)/(maxY-minY))));setZoom(z);setPan({x:(r.width-(minX+maxX)*z)/2,y:(r.height-(minY+maxY)*z)/2});};
 const onWheel=(e:React.WheelEvent)=>{e.preventDefault();const next=Math.max(.35,Math.min(1.65,zoom*(e.deltaY>0?.9:1.1)));const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const mx=e.clientX-r.left,my=e.clientY-r.top,wx=(mx-pan.x)/zoom,wy=(my-pan.y)/zoom;setPan({x:mx-wx*next,y:my-wy*next});setZoom(next);};
 const onCanvasDown=(e:React.PointerEvent)=>{if(e.button!==0||e.target!==e.currentTarget)return;setSelectedId(null);setQuick(null);panRef.current={x:e.clientX,y:e.clientY,ox:pan.x,oy:pan.y};e.currentTarget.setPointerCapture(e.pointerId);};
 const onCanvasMove=(e:React.PointerEvent)=>{if(linking){setLinking(v=>v?{...v,clientX:e.clientX,clientY:e.clientY}:v);return;}if(dragRef.current){const p=canvasPoint(e.clientX,e.clientY);setNodes(rows=>rows.map(n=>n.node_id===dragRef.current?.id?{...n,x:Math.max(0,Math.min(WORLD_W-NODE_W,p.x-dragRef.current!.dx)),y:Math.max(0,Math.min(WORLD_H-NODE_H,p.y-dragRef.current!.dy))}:n));setSaved(false);return;}if(panRef.current)setPan({x:panRef.current.ox+e.clientX-panRef.current.x,y:panRef.current.oy+e.clientY-panRef.current.y});};
 const onCanvasUp=(e:React.PointerEvent)=>{if(linking){const r=canvasRef.current?.getBoundingClientRect();const p=canvasPoint(e.clientX,e.clientY);if(r)setQuick({x:e.clientX-r.left,y:e.clientY-r.top,worldX:p.x,worldY:p.y,fromId:linking.fromId});setLinking(null);}if(dragRef.current){dragRef.current=null;markDirty();}panRef.current=null;};
 const openAddMenu=()=>{const r=canvasRef.current?.getBoundingClientRect();if(!r)return;const p=canvasPoint(r.left+r.width*.5,r.top+r.height*.45);setQuick({x:Math.min(r.width-310,Math.max(20,r.width*.5-150)),y:86,worldX:p.x,worldY:p.y,fromId:null});setQuickQuery('');};

 const sourceForQuick=quick?.fromId?nodes.find(n=>n.node_id===quick.fromId):null;
 const quickActions=useMemo(()=>{if(sourceForQuick)return quickFor(capabilityForOutput(models,sourceForQuick));return[
  {id:'text-to-image',label:'Gerar imagem',capability:'text-to-image',icon:ImageIcon,description:'Comece com um prompt de imagem.'},
  {id:'text-to-video',label:'Gerar vídeo',capability:'text-to-video',icon:Video,description:'Comece com um prompt de vídeo.'},
 ] as QuickAction[];},[sourceForQuick,models]);
 const visibleQuick=quickActions.filter(a=>a.label.toLowerCase().includes(quickQuery.toLowerCase()));

 const preview=(node:FlowNode)=>{const nr=nodeRunMap.get(node.node_id),resultId=nr?.output_asset_ids?.[0],asset=resultId?assetMap.get(resultId):node.asset_id?assetMap.get(node.asset_id):null;if(!asset)return null;const url=asset.preview_url||asset.public_url;if(!url)return null;if(asset.type==='IMAGE')return <img src={url} alt="" className="h-[92px] w-full rounded-xl object-cover"/>;if(asset.type==='VIDEO')return <video src={asset.public_url||url} muted preload="metadata" playsInline className="h-[92px] w-full rounded-xl object-cover"/>;return null;};

 const renderNode=(node:FlowNode)=>{const selectedNow=selectedId===node.node_id,cap=capabilityView(models,node),manualModels=models.filter(m=>m.model_id!=='AUTO'&&m.capabilities.some(c=>c.id===node.capability_id)),nr=nodeRunMap.get(node.node_id),out=capabilityForOutput(models,node),isAsset=node.kind==='ASSET';return <div key={node.node_id} className={`absolute rounded-2xl border bg-[#0a141e]/97 shadow-[0_20px_70px_rgba(0,0,0,.35)] ${selectedNow?'border-cyan-300/55 ring-1 ring-cyan-300/15':'border-white/[0.08]'}`} style={{left:node.x,top:node.y,width:NODE_W,minHeight:NODE_H}} onPointerDown={e=>{if((e.target as HTMLElement).closest('button,input,textarea,select'))return;e.stopPropagation();setSelectedId(node.node_id);const p=canvasPoint(e.clientX,e.clientY);dragRef.current={id:node.node_id,dx:p.x-node.x,dy:p.y-node.y};}}>
   {node.kind==='TOOL'&&<button onPointerUp={e=>{if(linking){e.stopPropagation();connectExisting(linking.fromId,node.node_id);setLinking(null);}}} className="absolute -left-2 top-1/2 z-20 h-4 w-4 -translate-y-1/2 rounded-full border-2 border-[#061019] bg-zinc-500" title="Entrada"/>}
   <button onPointerDown={e=>{e.stopPropagation();setLinking({fromId:node.node_id,clientX:e.clientX,clientY:e.clientY});}} className="absolute -right-2 top-1/2 z-20 h-4 w-4 -translate-y-1/2 rounded-full border-2 border-[#061019] bg-cyan-400 shadow-[0_0_10px_rgba(34,211,238,.35)]" title="Arraste para conectar"/>
   <div className="flex items-start gap-2 border-b border-white/[0.06] p-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-xl border border-cyan-400/10 bg-cyan-400/[0.05] text-cyan-300">{out.includes('VIDEO')?<Video className="h-4 w-4"/>:<ImageIcon className="h-4 w-4"/>}</span><div className="min-w-0 flex-1"><input value={node.label} onChange={e=>patchNode(node.node_id,{label:e.target.value})} className="w-full truncate bg-transparent text-[10px] font-bold text-white outline-none"/><span className="mt-0.5 block truncate text-[7px] uppercase tracking-[.12em] text-zinc-600">{isAsset?'Asset da Biblioteca':capabilityLabels[node.capability_id||'']||node.capability_id}</span></div>{nr&&<span className={`mt-1.5 h-2 w-2 rounded-full ${nr.status==='SUCCEEDED'?'bg-emerald-400':nr.status==='FAILED'?'bg-rose-400':nr.status==='RUNNING'?'animate-pulse bg-cyan-300':'bg-zinc-600'}`}/>}</div>
   <div className="space-y-2 p-2.5">
    {preview(node)||isAsset?<>{preview(node)||<div className="grid h-[92px] place-items-center rounded-xl bg-white/[0.02] text-[8px] text-zinc-600">Asset indisponível</div>}</>:<textarea rows={2} value={node.prompt||''} onChange={e=>patchNode(node.node_id,{prompt:e.target.value})} placeholder="Digite o prompt…" className="w-full resize-none rounded-xl border border-white/[0.06] bg-black/20 p-2 text-[9px] leading-relaxed text-zinc-300 outline-none placeholder:text-zinc-700 focus:border-cyan-400/20"/>}
    {node.kind==='TOOL'&&<div className="flex items-center gap-2"><select value={node.model_id||'AUTO'} onChange={e=>patchNode(node.node_id,{model_id:e.target.value})} className="min-w-0 flex-1 rounded-lg border border-white/[0.06] bg-[#071018] px-2 py-1.5 text-[8px] text-zinc-400 outline-none"><option value="AUTO">Auto</option>{manualModels.map(m=><option key={m.model_id} value={m.model_id}>{m.name}</option>)}</select><button onClick={()=>{setSelectedId(node.node_id);void startRun();}} disabled={Boolean(busy)||!cap} className="inline-flex h-7 items-center gap-1 rounded-lg bg-cyan-400 px-2 text-[8px] font-black text-[#041019] disabled:opacity-40"><Play className="h-3 w-3"/>Gerar</button></div>}
   </div>
   <div className="flex items-center justify-between border-t border-white/[0.05] px-2.5 py-1.5"><span className="text-[7px] text-zinc-700">{node.kind==='TOOL'?'Saída: '+out.join(', '):node.media_type}</span><div className="flex"><button onClick={()=>duplicateNode(node)} className="grid h-6 w-6 place-items-center rounded text-zinc-600 hover:bg-white/[0.04] hover:text-zinc-300"><Copy className="h-3 w-3"/></button><button onClick={()=>removeNode(node.node_id)} className="grid h-6 w-6 place-items-center rounded text-zinc-600 hover:bg-rose-400/[0.08] hover:text-rose-300"><Trash2 className="h-3 w-3"/></button></div></div>
  </div>;};

 return <div className="flex h-full min-h-0 flex-col bg-[#050a10] text-zinc-100">
  <header className="flex h-14 shrink-0 items-center gap-2 border-b border-white/[0.06] bg-[#071019]/95 px-3 sm:px-4 backdrop-blur-xl">
   <button onClick={onBack} className="grid h-8 w-8 place-items-center rounded-xl border border-white/[0.07] text-zinc-500 hover:text-white"><ArrowLeft className="h-4 w-4"/></button>
   <input value={name} onChange={e=>{setName(e.target.value);markDirty();}} className="min-w-0 max-w-[320px] flex-1 bg-transparent px-1 text-[12px] font-bold text-white outline-none" aria-label="Nome do Space"/>
   <span className="hidden items-center gap-1 text-[8px] text-zinc-600 sm:flex">{saving?<><LoaderCircle className="h-3 w-3 animate-spin"/>Salvando…</>:saved?<><Check className="h-3 w-3 text-emerald-400"/>Salvo</>:<><Save className="h-3 w-3"/>Alterações</>}</span>
   <div className="ml-auto flex items-center gap-1 rounded-xl border border-white/[0.06] bg-black/20 p-1"><button onClick={()=>setZoom(z=>Math.max(.35,z/1.15))} className="grid h-7 w-7 place-items-center rounded-lg text-zinc-500 hover:text-white"><ZoomOut className="h-3.5 w-3.5"/></button><span className="w-10 text-center text-[8px] text-zinc-600">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(1.65,z*1.15))} className="grid h-7 w-7 place-items-center rounded-lg text-zinc-500 hover:text-white"><ZoomIn className="h-3.5 w-3.5"/></button><button onClick={fit} className="grid h-7 w-7 place-items-center rounded-lg text-zinc-500 hover:text-white"><Maximize2 className="h-3.5 w-3.5"/></button></div>
   <button onClick={openAddMenu} className="inline-flex h-9 items-center gap-1.5 rounded-xl border border-white/[0.08] bg-white/[0.025] px-3 text-[9px] font-semibold text-zinc-300 hover:border-cyan-400/20 hover:text-cyan-200"><Plus className="h-3.5 w-3.5"/>Adicionar</button>
  </header>
  {(error||catalogError||assetsError)&&<div className="flex shrink-0 items-center gap-3 border-b border-rose-400/10 bg-rose-500/[0.06] px-4 py-2 text-[9px] text-rose-300"><span className="min-w-0 flex-1 truncate">{error||catalogError||assetsError}</span><button onClick={()=>{setError('');void loadCatalog();void loadAssets();}} className="inline-flex items-center gap-1 font-bold"><RefreshCw className="h-3 w-3"/>Recarregar</button></div>}
  <div className="relative min-h-0 flex-1 overflow-hidden">
   <div ref={canvasRef} onDragOver={e=>e.preventDefault()} onDrop={onDrop} onWheel={onWheel} onPointerDown={onCanvasDown} onPointerMove={onCanvasMove} onPointerUp={onCanvasUp} onPointerCancel={onCanvasUp} className="relative h-full w-full touch-none overflow-hidden bg-[#050a10]" style={{backgroundImage:'radial-gradient(rgba(125,211,252,.13) 1px, transparent 1px)',backgroundSize:`${24*zoom}px ${24*zoom}px`,backgroundPosition:`${pan.x}px ${pan.y}px`}}>
    {!nodes.length&&<div className="pointer-events-none absolute inset-0 z-0 grid place-items-center"><div className="max-w-md text-center"><MousePointer2 className="mx-auto h-7 w-7 text-zinc-750"/><strong className="mt-3 block text-[13px] text-zinc-400">Comece instantaneamente</strong><p className="mt-1 text-[9px] leading-relaxed text-zinc-650">Cole uma imagem com Ctrl+V, arraste um arquivo para cá ou clique em Adicionar.</p></div></div>}
    <div className="absolute origin-top-left" style={{width:WORLD_W,height:WORLD_H,transform:`translate(${pan.x}px,${pan.y}px) scale(${zoom})`}}>
     <svg className="pointer-events-none absolute inset-0 overflow-visible" width={WORLD_W} height={WORLD_H}>{edges.map(edge=>{const a=nodes.find(n=>n.node_id===edge.from_node_id),b=nodes.find(n=>n.node_id===edge.to_node_id);if(!a||!b)return null;return <path key={edge.edge_id} d={pathFor(a,b)} fill="none" stroke="rgba(34,211,238,.48)" strokeWidth={2}/>})}</svg>
     {nodes.map(renderNode)}
    </div>
    {linking&&(()=>{const r=canvasRef.current?.getBoundingClientRect(),source=nodes.find(n=>n.node_id===linking.fromId);if(!r||!source)return null;const x1=pan.x+(source.x+NODE_W)*zoom,y1=pan.y+(source.y+NODE_H/2)*zoom,x2=linking.clientX-r.left,y2=linking.clientY-r.top,c=Math.max(80,Math.abs(x2-x1)*.4);return <svg className="pointer-events-none absolute inset-0 h-full w-full"><path d={`M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`} fill="none" stroke="rgba(34,211,238,.8)" strokeWidth="2" strokeDasharray="6 5"/></svg>;})()}
    {quick&&<div className="absolute z-40 w-[300px] overflow-hidden rounded-2xl border border-white/[0.08] bg-[#0a141e]/98 shadow-2xl backdrop-blur-xl" style={{left:Math.max(12,Math.min((canvasRef.current?.clientWidth||900)-312,quick.x)),top:Math.max(12,Math.min((canvasRef.current?.clientHeight||700)-360,quick.y))}}>
      <div className="border-b border-white/[0.06] p-3"><strong className="text-[10px] text-white">{sourceForQuick?'O que deseja fazer com esta saída?':'Adicionar ao Space'}</strong><label className="mt-2 flex h-8 items-center gap-2 rounded-lg border border-white/[0.06] bg-black/20 px-2.5"><Search className="h-3 w-3 text-zinc-700"/><input autoFocus value={quickQuery} onChange={e=>setQuickQuery(e.target.value)} placeholder="Buscar ação…" className="min-w-0 flex-1 bg-transparent text-[9px] text-zinc-300 outline-none"/></label></div>
      <div className="max-h-[280px] overflow-y-auto p-1.5">{visibleQuick.map(action=>{const Icon=action.icon;const enabled=Boolean(modelFor(action.capability));return <button key={action.id} disabled={!enabled} onClick={()=>addTool(action.capability,quick.worldX,quick.worldY,quick.fromId)} className="flex w-full items-start gap-2.5 rounded-xl p-2.5 text-left hover:bg-white/[0.04] disabled:opacity-35"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-cyan-400/[0.06] text-cyan-300"><Icon className="h-4 w-4"/></span><span className="min-w-0"><strong className="block text-[9px] text-zinc-200">{action.label}</strong><small className="mt-0.5 block text-[8px] leading-relaxed text-zinc-600">{enabled?action.description:'Nenhum modelo elegível disponível.'}</small></span></button>})}
       {!sourceForQuick&&<><div className="my-1 h-px bg-white/[0.05]"/><button onClick={()=>{const img=assets.find(a=>a.type==='IMAGE');if(img)addAssetNode(img,quick.worldX,quick.worldY);else setError('Sua Biblioteca ainda não possui imagens.');setQuick(null);}} className="flex w-full items-center gap-2.5 rounded-xl p-2.5 text-left hover:bg-white/[0.04]"><ImageIcon className="h-4 w-4 text-zinc-500"/><span className="text-[9px] text-zinc-300">Imagem da Biblioteca</span></button><button onClick={()=>{const vid=assets.find(a=>a.type==='VIDEO');if(vid)addAssetNode(vid,quick.worldX,quick.worldY);else setError('Sua Biblioteca ainda não possui vídeos.');setQuick(null);}} className="flex w-full items-center gap-2.5 rounded-xl p-2.5 text-left hover:bg-white/[0.04]"><Video className="h-4 w-4 text-zinc-500"/><span className="text-[9px] text-zinc-300">Vídeo da Biblioteca</span></button></>}
      </div>
     </div>}
    {busy==='upload'&&<div className="absolute bottom-5 right-5 z-40 inline-flex items-center gap-2 rounded-xl border border-white/[0.07] bg-[#08131e]/95 px-3 py-2 text-[9px] text-zinc-300 shadow-xl"><LoaderCircle className="h-3.5 w-3.5 animate-spin text-cyan-300"/>Enviando asset…</div>}
   </div>
  </div>
 </div>;
};

export default SpaceWorkspace;
