import crypto from 'crypto';
import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';
import { walletRepository } from '../repositories/walletRepository.js';

export type CreditLotSource='PURCHASE'|'PROMOTION'|'COMPENSATION'|'CREATOR_REWARD'|'MIGRATION';
export type CreditTransactionType='PURCHASE_ISSUE'|'PROMO_ISSUE'|'ADMIN_CREDIT'|'ADMIN_DEBIT'|'GENERATION_RESERVE'|'GENERATION_CAPTURE'|'GENERATION_RELEASE'|'PAYMENT_REVERSAL'|'EXPIRE'|'CREATOR_REWARD'|'MIGRATION_ISSUE';
export interface CreditAccount{
 user_id:string;available_credits:number;reserved_credits:number;total_credits:number;total_purchased_credits:number;total_promotional_credits:number;total_used_credits:number;total_expired_credits:number;total_revoked_credits:number;updated_at:string;
 // Temporary compatibility aliases for the existing frontend while the UI migrates terminology.
 available_balance_cents:number;reserved_balance_cents:number;total_balance_cents:number;
}
export interface CreditLot{
 credit_lot_id:string;user_id:string;source:CreditLotSource;original_credits:number;available_credits:number;reserved_credits:number;consumed_credits:number;revoked_credits:number;expired_credits:number;expires_at:string|null;
 payment_id?:string;promotion_id?:string;reference_id?:string;pack_id?:string;pack_version?:number;promotion_version?:number;net_cash_backing_micros:number;net_cash_value_per_credit_micros:number;subsidy_budget_id?:string|null;created_at:string;metadata?:Record<string,any>;
}
export interface CreditLotAllocation{credit_lot_id:string;credits:number;net_cash_value_per_credit_micros:number;source:CreditLotSource;expires_at:string|null;}
export interface CreditReservation{reservation_id:string;generation_id:string;user_id:string;credits:number;status:'RESERVED'|'CAPTURED'|'RELEASED';allocations:CreditLotAllocation[];authorized_net_backing_micros:number;created_at:string;updated_at:string;}
export interface CreditTransaction{transaction_id:string;user_id:string;type:CreditTransactionType;amount_credits:number;status:'COMPLETED';reference_type:string;reference_id:string;idempotency_key:string;lot_allocations:CreditLotAllocation[];balance_after_credits:number;created_at:string;metadata?:Record<string,any>;}

const ACCOUNT='credit_accounts',LOTS='credit_lots',TX='credit_transactions',IDEM='credit_idempotency',RES='credit_reservations';
function idemId(key:string){return crypto.createHash('sha256').update(key).digest('hex');}
function id(prefix:string){return `${prefix}_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`;}
function empty(userId:string):CreditAccount{return{user_id:userId,available_credits:0,reserved_credits:0,total_credits:0,total_purchased_credits:0,total_promotional_credits:0,total_used_credits:0,total_expired_credits:0,total_revoked_credits:0,updated_at:new Date().toISOString(),available_balance_cents:0,reserved_balance_cents:0,total_balance_cents:0};}
function aliases(a:CreditAccount){a.available_balance_cents=a.available_credits;a.reserved_balance_cents=a.reserved_credits;a.total_balance_cents=a.total_credits;return a;}
function isExpired(l:CreditLot,now=Date.now()){return Boolean(l.expires_at&&new Date(l.expires_at).getTime()<=now);}
function orderLots(a:CreditLot,b:CreditLot){const ap=a.source==='PROMOTION',bp=b.source==='PROMOTION';if(ap!==bp)return ap?-1:1;const ae=a.expires_at?new Date(a.expires_at).getTime():Infinity,be=b.expires_at?new Date(b.expires_at).getTime():Infinity;if(ae!==be)return ae-be;return new Date(a.created_at).getTime()-new Date(b.created_at).getTime();}
async function listLots(userId:string){const rows=await firestoreAdminRest.runQuery({from:[{collectionId:LOTS}],where:{fieldFilter:{field:{fieldPath:'user_id'},op:'EQUAL',value:{stringValue:userId}}}});return rows.map((r:any)=>({...r.data,__updateTime:r.updateTime}) as CreditLot&{__updateTime:string}).sort(orderLots);}
async function getIdempotent(key:string){return firestoreAdminRest.get(`${IDEM}/${idemId(key)}`);}

export const creditWalletService={
 async getAccount(userId:string):Promise<CreditAccount>{
  const p=`${ACCOUNT}/${encodeURIComponent(userId)}`;const d=await firestoreAdminRest.get(p);if(d.exists)return aliases(d.data as CreditAccount);
  // One-time safe migration: only legacy AVAILABLE BRL balance becomes credits at the base 1 cent = 1 credit ratio.
  const legacy=await walletRepository.getAccount(userId);const credits=Math.max(0,Number(legacy.available_balance_cents||0));
  if(credits>0){await this.issue({userId,credits,source:'MIGRATION',idempotencyKey:`credit-migration:${userId}`,referenceId:userId,netCashBackingMicros:credits*10000,metadata:{legacy_available_balance_cents:credits}});const reread=await firestoreAdminRest.get(p);if(reread.exists)return aliases(reread.data as CreditAccount);}
  const a=empty(userId);try{await firestoreAdminRest.commit([{update:{name:firestoreAdminRest.docName(p),fields:firestoreAdminRest.fields(a)},currentDocument:{exists:false}}]);}catch{}
  const final=await firestoreAdminRest.get(p);return aliases(final.exists?final.data as CreditAccount:a);
 },
 async listTransactions(userId:string,limit=50){const rows=await firestoreAdminRest.runQuery({from:[{collectionId:TX}],where:{fieldFilter:{field:{fieldPath:'user_id'},op:'EQUAL',value:{stringValue:userId}}},limit:Math.min(100,limit)});return rows.map((r:any)=>r.data as CreditTransaction).sort((a,b)=>new Date(b.created_at).getTime()-new Date(a.created_at).getTime());},
 async issue(p:{userId:string;credits:number;source:CreditLotSource;idempotencyKey:string;referenceId:string;netCashBackingMicros:number;paymentId?:string;promotionId?:string;packId?:string;packVersion?:number;expiresAt?:string|null;metadata?:Record<string,any>}){
  if(!Number.isInteger(p.credits)||p.credits<=0)throw new Error('Quantidade de créditos inválida.');const idemPath=`${IDEM}/${idemId(p.idempotencyKey)}`;const existing=await getIdempotent(p.idempotencyKey);if(existing.exists)return this.getAccount(p.userId);
  for(let attempt=0;attempt<4;attempt++){
   const accountPath=`${ACCOUNT}/${encodeURIComponent(p.userId)}`;const ad=await firestoreAdminRest.get(accountPath);const current=aliases(ad.exists?ad.data as CreditAccount:empty(p.userId));const now=new Date().toISOString();
   const lotId=id('clot'),txId=id('ctx');const per=Math.max(0,Math.floor(Number(p.netCashBackingMicros||0)/p.credits));const lot:CreditLot={credit_lot_id:lotId,user_id:p.userId,source:p.source,original_credits:p.credits,available_credits:p.credits,reserved_credits:0,consumed_credits:0,revoked_credits:0,expired_credits:0,expires_at:p.expiresAt||null,payment_id:p.paymentId,promotion_id:p.promotionId,reference_id:p.referenceId,pack_id:p.packId,pack_version:p.packVersion,net_cash_backing_micros:Math.max(0,Math.floor(p.netCashBackingMicros||0)),net_cash_value_per_credit_micros:per,subsidy_budget_id:null,created_at:now,metadata:p.metadata};
   const promo=p.source==='PROMOTION';const purchased=p.source==='PURCHASE'||p.source==='MIGRATION';const next=aliases({...current,available_credits:current.available_credits+p.credits,total_credits:current.total_credits+p.credits,total_purchased_credits:current.total_purchased_credits+(purchased?p.credits:0),total_promotional_credits:current.total_promotional_credits+(promo?p.credits:0),updated_at:now});
   const tx:CreditTransaction={transaction_id:txId,user_id:p.userId,type:p.source==='PROMOTION'?'PROMO_ISSUE':p.source==='MIGRATION'?'MIGRATION_ISSUE':p.source==='CREATOR_REWARD'?'CREATOR_REWARD':'PURCHASE_ISSUE',amount_credits:p.credits,status:'COMPLETED',reference_type:p.source,reference_id:p.referenceId,idempotency_key:p.idempotencyKey,lot_allocations:[{credit_lot_id:lotId,credits:p.credits,net_cash_value_per_credit_micros:per,source:p.source,expires_at:lot.expires_at}],balance_after_credits:next.available_credits,created_at:now,metadata:p.metadata};
   const writes:any[]=[{update:{name:firestoreAdminRest.docName(accountPath),fields:firestoreAdminRest.fields(next)},currentDocument:ad.exists?{updateTime:ad.updateTime}:{exists:false}},{update:{name:firestoreAdminRest.docName(`${LOTS}/${lotId}`),fields:firestoreAdminRest.fields(lot)},currentDocument:{exists:false}},{update:{name:firestoreAdminRest.docName(`${TX}/${txId}`),fields:firestoreAdminRest.fields(tx)},currentDocument:{exists:false}},{update:{name:firestoreAdminRest.docName(idemPath),fields:firestoreAdminRest.fields({transaction_id:txId,user_id:p.userId,created_at:now})},currentDocument:{exists:false}}];
   try{await firestoreAdminRest.commit(writes);return next;}catch(e){const idem=await getIdempotent(p.idempotencyKey);if(idem.exists)return this.getAccount(p.userId);if(attempt===3)throw e;}
  }throw new Error('Falha ao emitir créditos.');
 },
 async simulateReserve(userId:string,credits:number){await this.getAccount(userId);const lots=(await listLots(userId)).filter(l=>l.available_credits>0&&!isExpired(l));let left=credits,backing=0;const allocations:CreditLotAllocation[]=[];for(const l of lots){if(left<=0)break;const take=Math.min(left,l.available_credits);allocations.push({credit_lot_id:l.credit_lot_id,credits:take,net_cash_value_per_credit_micros:l.net_cash_value_per_credit_micros,source:l.source,expires_at:l.expires_at});backing+=take*l.net_cash_value_per_credit_micros;left-=take;}return{has_sufficient_credits:left===0,missing_credits:left,allocations,authorized_net_backing_micros:backing};},
 async reserveForGeneration(p:{userId:string;credits:number;generationId:string;idempotencyKey:string}){
  const prior=await getIdempotent(p.idempotencyKey);if(prior.exists){const r=await firestoreAdminRest.get(`${RES}/${encodeURIComponent(p.generationId)}`);if(r.exists)return r.data as CreditReservation;}
  for(let attempt=0;attempt<5;attempt++){
   const accountPath=`${ACCOUNT}/${encodeURIComponent(p.userId)}`;const ad=await firestoreAdminRest.get(accountPath);const current=aliases(ad.exists?ad.data as CreditAccount:await this.getAccount(p.userId));if(current.available_credits<p.credits)throw Object.assign(new Error('Créditos insuficientes.'),{code:'CREDIT_INSUFFICIENT_FUNDS',missing_credits:p.credits-current.available_credits});
   const lots=await listLots(p.userId),usable=lots.filter(l=>l.available_credits>0&&!isExpired(l));let left=p.credits,backing=0;const alloc:CreditLotAllocation[]=[];const changed:any[]=[];
   for(const l of usable){if(left<=0)break;const take=Math.min(left,l.available_credits);if(!take)continue;alloc.push({credit_lot_id:l.credit_lot_id,credits:take,net_cash_value_per_credit_micros:l.net_cash_value_per_credit_micros,source:l.source,expires_at:l.expires_at});backing+=take*l.net_cash_value_per_credit_micros;left-=take;changed.push({lot:l,next:{...l,available_credits:l.available_credits-take,reserved_credits:l.reserved_credits+take,__updateTime:undefined}});}
   if(left>0)throw Object.assign(new Error('Créditos disponíveis não podem ser alocados.'),{code:'CREDIT_ALLOCATION_FAILED'});
   const now=new Date().toISOString(),txId=id('ctx');const next=aliases({...current,available_credits:current.available_credits-p.credits,reserved_credits:current.reserved_credits+p.credits,updated_at:now});const reservation:CreditReservation={reservation_id:p.generationId,generation_id:p.generationId,user_id:p.userId,credits:p.credits,status:'RESERVED',allocations:alloc,authorized_net_backing_micros:backing,created_at:now,updated_at:now};const tx:CreditTransaction={transaction_id:txId,user_id:p.userId,type:'GENERATION_RESERVE',amount_credits:p.credits,status:'COMPLETED',reference_type:'GENERATION',reference_id:p.generationId,idempotency_key:p.idempotencyKey,lot_allocations:alloc,balance_after_credits:next.available_credits,created_at:now};
   const writes:any[]=[{update:{name:firestoreAdminRest.docName(accountPath),fields:firestoreAdminRest.fields(next)},currentDocument:ad.exists?{updateTime:ad.updateTime}:{exists:false}},...changed.map(x=>({update:{name:firestoreAdminRest.docName(`${LOTS}/${x.lot.credit_lot_id}`),fields:firestoreAdminRest.fields(x.next)},currentDocument:{updateTime:x.lot.__updateTime}})),{update:{name:firestoreAdminRest.docName(`${RES}/${p.generationId}`),fields:firestoreAdminRest.fields(reservation)},currentDocument:{exists:false}},{update:{name:firestoreAdminRest.docName(`${TX}/${txId}`),fields:firestoreAdminRest.fields(tx)},currentDocument:{exists:false}},{update:{name:firestoreAdminRest.docName(`${IDEM}/${idemId(p.idempotencyKey)}`),fields:firestoreAdminRest.fields({transaction_id:txId,user_id:p.userId,created_at:now})},currentDocument:{exists:false}}];
   try{await firestoreAdminRest.commit(writes);return reservation;}catch(e){const idem=await getIdempotent(p.idempotencyKey);if(idem.exists){const r=await firestoreAdminRest.get(`${RES}/${p.generationId}`);if(r.exists)return r.data as CreditReservation;}if(attempt===4)throw e;}
  }throw new Error('Falha ao reservar créditos.');
 },
 async settleGeneration(p:{userId:string;generationId:string;mode:'CAPTURE'|'RELEASE';idempotencyKey:string}){
  const prior=await getIdempotent(p.idempotencyKey);if(prior.exists)return this.getAccount(p.userId);const rd=await firestoreAdminRest.get(`${RES}/${encodeURIComponent(p.generationId)}`);if(!rd.exists)throw new Error('Reserva de créditos não encontrada.');const reservation=rd.data as CreditReservation;if(reservation.status!=='RESERVED')return this.getAccount(p.userId);
  for(let attempt=0;attempt<5;attempt++){
   const accountPath=`${ACCOUNT}/${encodeURIComponent(p.userId)}`;const ad=await firestoreAdminRest.get(accountPath);const current=aliases(ad.exists?ad.data as CreditAccount:empty(p.userId));const lots=await listLots(p.userId);const byId=new Map(lots.map(l=>[l.credit_lot_id,l]));let releaseAvailable=0,expire=0;const changed:any[]=[];
   for(const a of reservation.allocations){const l=byId.get(a.credit_lot_id);if(!l||l.reserved_credits<a.credits)throw Object.assign(new Error('Reserva de lote inconsistente.'),{code:'CREDIT_RESERVE_INVALID'});const next:any={...l,__updateTime:undefined,reserved_credits:l.reserved_credits-a.credits};if(p.mode==='CAPTURE')next.consumed_credits=l.consumed_credits+a.credits;else if(isExpired(l)){next.expired_credits=l.expired_credits+a.credits;expire+=a.credits;}else{next.available_credits=l.available_credits+a.credits;releaseAvailable+=a.credits;}changed.push({lot:l,next});}
   const now=new Date().toISOString();let next:CreditAccount;if(p.mode==='CAPTURE')next=aliases({...current,reserved_credits:current.reserved_credits-reservation.credits,total_credits:current.total_credits-reservation.credits,total_used_credits:current.total_used_credits+reservation.credits,updated_at:now});else next=aliases({...current,available_credits:current.available_credits+releaseAvailable,reserved_credits:current.reserved_credits-reservation.credits,total_credits:current.total_credits-expire,total_expired_credits:current.total_expired_credits+expire,updated_at:now});
   if(next.reserved_credits<0||next.available_credits<0||next.total_credits<0)throw Object.assign(new Error('Ledger de créditos inconsistente.'),{code:'CREDIT_LEDGER_INVALID'});const txId=id('ctx');const tx:CreditTransaction={transaction_id:txId,user_id:p.userId,type:p.mode==='CAPTURE'?'GENERATION_CAPTURE':'GENERATION_RELEASE',amount_credits:reservation.credits,status:'COMPLETED',reference_type:'GENERATION',reference_id:p.generationId,idempotency_key:p.idempotencyKey,lot_allocations:reservation.allocations,balance_after_credits:next.available_credits,created_at:now,metadata:p.mode==='RELEASE'?{expired_on_release:expire}:undefined};const nextRes={...reservation,status:p.mode==='CAPTURE'?'CAPTURED':'RELEASED',updated_at:now};
   const writes:any[]=[{update:{name:firestoreAdminRest.docName(accountPath),fields:firestoreAdminRest.fields(next)},currentDocument:{updateTime:ad.updateTime}},...changed.map(x=>({update:{name:firestoreAdminRest.docName(`${LOTS}/${x.lot.credit_lot_id}`),fields:firestoreAdminRest.fields(x.next)},currentDocument:{updateTime:x.lot.__updateTime}})),{update:{name:firestoreAdminRest.docName(`${RES}/${p.generationId}`),fields:firestoreAdminRest.fields(nextRes)},currentDocument:{updateTime:rd.updateTime}},{update:{name:firestoreAdminRest.docName(`${TX}/${txId}`),fields:firestoreAdminRest.fields(tx)},currentDocument:{exists:false}},{update:{name:firestoreAdminRest.docName(`${IDEM}/${idemId(p.idempotencyKey)}`),fields:firestoreAdminRest.fields({transaction_id:txId,user_id:p.userId,created_at:now})},currentDocument:{exists:false}}];
   try{await firestoreAdminRest.commit(writes);return next;}catch(e){const idem=await getIdempotent(p.idempotencyKey);if(idem.exists)return this.getAccount(p.userId);if(attempt===4)throw e;}
  }throw new Error('Falha ao liquidar reserva de créditos.');
 },
 async captureForGeneration(userId:string,generationId:string){return this.settleGeneration({userId,generationId,mode:'CAPTURE',idempotencyKey:`credit-capture:${generationId}`});},
 async releaseForGeneration(userId:string,generationId:string){return this.settleGeneration({userId,generationId,mode:'RELEASE',idempotencyKey:`credit-release:${generationId}`});},
 async revokePayment(userId:string,paymentId:string){
  const lots=(await listLots(userId)).filter(l=>l.payment_id===paymentId);let revoked=0;for(const l of lots)revoked+=Math.max(0,l.available_credits);if(!revoked)return this.getAccount(userId);
  const key=`credit-payment-reversal:${paymentId}`;if((await getIdempotent(key)).exists)return this.getAccount(userId);const accountPath=`${ACCOUNT}/${encodeURIComponent(userId)}`;const ad=await firestoreAdminRest.get(accountPath);const current=aliases(ad.exists?ad.data as CreditAccount:empty(userId));const now=new Date().toISOString(),txId=id('ctx');const changed=lots.filter(l=>l.available_credits>0).map(l=>({lot:l,next:{...l,revoked_credits:l.revoked_credits+l.available_credits,available_credits:0,__updateTime:undefined}}));const next=aliases({...current,available_credits:current.available_credits-revoked,total_credits:current.total_credits-revoked,total_revoked_credits:current.total_revoked_credits+revoked,updated_at:now});const allocations=changed.map(x=>({credit_lot_id:x.lot.credit_lot_id,credits:x.lot.available_credits,net_cash_value_per_credit_micros:x.lot.net_cash_value_per_credit_micros,source:x.lot.source,expires_at:x.lot.expires_at}));const tx:CreditTransaction={transaction_id:txId,user_id:userId,type:'PAYMENT_REVERSAL',amount_credits:revoked,status:'COMPLETED',reference_type:'PAYMENT',reference_id:paymentId,idempotency_key:key,lot_allocations:allocations,balance_after_credits:next.available_credits,created_at:now};await firestoreAdminRest.commit([{update:{name:firestoreAdminRest.docName(accountPath),fields:firestoreAdminRest.fields(next)},currentDocument:{updateTime:ad.updateTime}},...changed.map(x=>({update:{name:firestoreAdminRest.docName(`${LOTS}/${x.lot.credit_lot_id}`),fields:firestoreAdminRest.fields(x.next)},currentDocument:{updateTime:x.lot.__updateTime}})),{update:{name:firestoreAdminRest.docName(`${TX}/${txId}`),fields:firestoreAdminRest.fields(tx)},currentDocument:{exists:false}},{update:{name:firestoreAdminRest.docName(`${IDEM}/${idemId(key)}`),fields:firestoreAdminRest.fields({transaction_id:txId,user_id:userId,created_at:now})},currentDocument:{exists:false}}]);return next;
 }
};
