import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';

type RangeKey='24h'|'7d'|'30d'|'90d'|'all';
const ranges:Record<RangeKey,number>={"24h":86400000,"7d":7*86400000,"30d":30*86400000,"90d":90*86400000,all:0};
const n=(v:any)=>Number(v||0),iso=(v:any)=>new Date(String(v||0)).getTime();
function inRange(v:any,range:RangeKey){return range==='all'||iso(v)>=Date.now()-ranges[range];}
async function all(collectionId:string,limit=5000){return(await firestoreAdminRest.runQuery({from:[{collectionId}],limit})).map((r:any)=>r.data||{});}
function sourceLabel(l:any){if(l.source==='PURCHASE')return'PURCHASE';if(l.source==='PROMOTION')return l.metadata?.campaign_id||l.promotion_id||l.metadata?.coupon_code||'PROMOTION';return l.metadata?.campaign_id||l.source||'UNKNOWN';}
function originRow(map:Map<string,any>,lot:any){const key=sourceLabel(lot),row=map.get(key)||{key,source:lot.source||'UNKNOWN',credits_issued:0,credits_consumed:0,credits_available:0,credits_reserved:0,credits_expired:0,credits_revoked:0,backing_micros:0,cogs_cents:0};map.set(key,row);return row;}
export const economicsAnalyticsService={
 async overview(rangeInput:string='30d'){
  const range=(['24h','7d','30d','90d','all'].includes(rangeInput)?rangeInput:'30d')as RangeKey;
  const[cash,lots,txs,generations,economics,couponRedemptions]=await Promise.all([all('cash_ledger'),all('credit_lots'),all('credit_transactions'),all('generations'),all('generation_economics'),all('coupon_redemptions')]);
  const cashRows=cash.filter(x=>inRange(x.created_at,range)),lotRows=lots.filter(x=>inRange(x.created_at,range)),txRows=txs.filter(x=>inRange(x.created_at,range));
  const cashReceived=cashRows.filter(x=>x.type==='CASH_RECEIVED').reduce((s,x)=>s+n(x.amount_cents),0),cashReversal=cashRows.filter(x=>x.type==='CASH_REVERSAL').reduce((s,x)=>s+n(x.amount_cents),0),purchaseLots=lotRows.filter(x=>x.source==='PURCHASE'),promoLots=lotRows.filter(x=>x.source==='PROMOTION'),packBonusIssued=purchaseLots.reduce((s,x)=>s+n(x.metadata?.bonus_credits),0),purchaseBaseIssued=purchaseLots.reduce((s,x)=>s+n(x.metadata?.base_credits||Math.max(0,n(x.original_credits)-n(x.metadata?.bonus_credits))),0);
  const credits={issued:lotRows.reduce((s,x)=>s+n(x.original_credits),0),purchased:purchaseLots.reduce((s,x)=>s+n(x.original_credits),0),purchased_base:purchaseBaseIssued,pack_bonus:packBonusIssued,promotional:promoLots.reduce((s,x)=>s+n(x.original_credits),0),compensation:lotRows.filter(x=>x.source==='COMPENSATION').reduce((s,x)=>s+n(x.original_credits),0),creator:lotRows.filter(x=>x.source==='CREATOR_REWARD').reduce((s,x)=>s+n(x.original_credits),0),migration:lotRows.filter(x=>x.source==='MIGRATION').reduce((s,x)=>s+n(x.original_credits),0),gifted:lotRows.filter(x=>['PROMOTION','COMPENSATION','CREATOR_REWARD'].includes(String(x.source))).reduce((s,x)=>s+n(x.original_credits),0),available:lots.reduce((s,x)=>s+n(x.available_credits),0),reserved:lots.reduce((s,x)=>s+n(x.reserved_credits),0),consumed:lots.reduce((s,x)=>s+n(x.consumed_credits),0),expired:lots.reduce((s,x)=>s+n(x.expired_credits),0),revoked:lots.reduce((s,x)=>s+n(x.revoked_credits),0),in_circulation:lots.reduce((s,x)=>s+n(x.available_credits)+n(x.reserved_credits),0)};
  const econByGen=new Map(economics.map((x:any)=>[String(x.generation_id),x])),genById=new Map(generations.map((x:any)=>[String(x.generation_id),x])),lotById=new Map(lots.map((x:any)=>[String(x.credit_lot_id),x]));
  let backingMicros=0,cogsCents=0,capturedCredits=0,promotionalConsumed=0,promotionalCogs=0;const byModel=new Map<string,any>(),byProvider=new Map<string,any>(),byOrigin=new Map<string,any>();
  for(const lot of lots){const row=originRow(byOrigin,lot);row.credits_available+=n(lot.available_credits);row.credits_reserved+=n(lot.reserved_credits);row.credits_expired+=n(lot.expired_credits);row.credits_revoked+=n(lot.revoked_credits);if(inRange(lot.created_at,range))row.credits_issued+=n(lot.original_credits);}
  for(const tx of txRows.filter(x=>x.type==='GENERATION_CAPTURE')){const gid=String(tx.reference_id||''),econ:any=econByGen.get(gid)||{},gen:any=genById.get(gid)||{},allocs=Array.isArray(tx.lot_allocations)?tx.lot_allocations:[],creditsForGen=allocs.reduce((s:any,a:any)=>s+n(a.credits),0),finalCogs=n(econ.final_cogs_cents||gen.final_cogs_cents||0);let genBacking=0;for(const a of allocs){const lot:any=lotById.get(String(a.credit_lot_id))||{},cr=n(a.credits),value=n(a.net_cash_value_per_credit_micros||lot.net_cash_value_per_credit_micros),allocatedCogs=creditsForGen>0?finalCogs*(cr/creditsForGen):0;genBacking+=cr*value;const row=originRow(byOrigin,lot);row.credits_consumed+=cr;row.backing_micros+=cr*value;row.cogs_cents+=allocatedCogs;if(lot.source==='PROMOTION'){promotionalConsumed+=cr;promotionalCogs+=allocatedCogs;}}backingMicros+=genBacking;cogsCents+=finalCogs;capturedCredits+=creditsForGen;const model=String(gen.model_id||'UNKNOWN'),provider=String(gen.provider_id||'UNKNOWN');for(const[map,key]of[[byModel,model],[byProvider,provider]]as any){const row=map.get(key)||{key,generations:0,credits:0,backing_micros:0,cogs_cents:0};row.generations+=1;row.credits+=creditsForGen;row.backing_micros+=genBacking;row.cogs_cents+=finalCogs;map.set(key,row);}}
  const normalize=(row:any)=>{const backingCents=row.backing_micros/10000,contribution=backingCents-row.cogs_cents,margin=backingCents>0?100*(contribution/backingCents):null;return{...row,backing_cents:Math.round(backingCents),cogs_cents:Math.round(row.cogs_cents),contribution_cents:Math.round(contribution),margin_percent:margin,credits_in_circulation:n(row.credits_available)+n(row.credits_reserved)};},backingCents=backingMicros/10000,contribution=backingCents-cogsCents,margin=backingCents>0?100*contribution/backingCents:null,couponDirect=couponRedemptions.filter((x:any)=>inRange(x.created_at,range)&&x.redemption_mode==='DIRECT_CREDIT'&&x.status!=='REVERSED');
  return{range,generated_at:new Date().toISOString(),cash:{received_cents:cashReceived,reversal_cents:cashReversal,net_cents:cashReceived-cashReversal},credits,consumption:{captured_credits:capturedCredits,backing_cents:Math.round(backingCents),cogs_cents:Math.round(cogsCents),contribution_cents:Math.round(contribution),margin_percent:margin,contribution_per_1000_credits_cents:capturedCredits>0?Math.round(contribution*1000/capturedCredits):0,cogs_per_1000_credits_cents:capturedCredits>0?Math.round(cogsCents*1000/capturedCredits):0},subsidy:{direct_coupon_redemptions:couponDirect.length,direct_coupon_credits:couponDirect.reduce((s:any,x:any)=>s+n(x.credits),0),promotional_credits_consumed:promotionalConsumed,promotional_cogs_cents:Math.round(promotionalCogs),promotional_credits_in_circulation:lots.filter(x=>x.source==='PROMOTION').reduce((s,x)=>s+n(x.available_credits)+n(x.reserved_credits),0)},by_origin:Array.from(byOrigin.values()).map(normalize).sort((a,b)=>Math.max(b.credits_issued,b.credits_consumed)-Math.max(a.credits_issued,a.credits_consumed)),by_model:Array.from(byModel.values()).map(normalize).sort((a,b)=>b.cogs_cents-a.cogs_cents),by_provider:Array.from(byProvider.values()).map(normalize).sort((a,b)=>b.cogs_cents-a.cogs_cents)};
 },
 async generations(rangeInput='30d',limit=100){const data=await this.overview(rangeInput);const[gens,econs,txs,lots]=await Promise.all([all('generations'),all('generation_economics'),all('credit_transactions'),all('credit_lots')]),econMap=new Map(econs.map((x:any)=>[String(x.generation_id),x])),lotMap=new Map(lots.map((x:any)=>[String(x.credit_lot_id),x])),range=data.range as RangeKey;return gens.filter((g:any)=>inRange(g.created_at,range)&&g.status==='SUCCEEDED').sort((a:any,b:any)=>iso(b.created_at)-iso(a.created_at)).slice(0,Math.min(250,limit)).map((g:any)=>{const econ:any=econMap.get(String(g.generation_id))||{},capture:any=txs.find((t:any)=>t.type==='GENERATION_CAPTURE'&&String(t.reference_id)===String(g.generation_id)),allocs=Array.isArray(capture?.lot_allocations)?capture.lot_allocations:[],backingMicros=allocs.reduce((s:any,a:any)=>s+n(a.credits)*n(a.net_cash_value_per_credit_micros||(lotMap.get(String(a.credit_lot_id))as any)?.net_cash_value_per_credit_micros),0),backingCents=backingMicros/10000,cogs=n(econ.final_cogs_cents||g.final_cogs_cents),margin=backingCents>0?100*(1-cogs/backingCents):null;return{generation_id:g.generation_id,user_mask:`${String(g.user_id||'').slice(0,4)}••${String(g.user_id||'').slice(-3)}`,model_id:g.model_id,provider_id:g.provider_id,mode:g.mode,created_at:g.created_at,credits:capture?.amount_credits||g.final_credit_cost||0,backing_cents:Math.round(backingCents),cogs_cents:cogs,contribution_cents:Math.round(backingCents-cogs),margin_percent:margin,attempt_count:g.attempt_count||0};});}
};
