import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';

export type EconomicCampaignType='BETA'|'FOUNDERS'|'COUPON'|'WELCOME'|'CREATOR'|'SUPPORT'|'OTHER';
export interface EconomicCampaign{campaign_id:string;name:string;type:EconomicCampaignType;active:boolean;budget_credits:number|null;starts_at:string|null;ends_at:string|null;notes:string;created_at:string;created_by:string;updated_at:string;updated_by:string;}
const COLLECTION='economic_campaigns';
function id(v:string){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9_-]/g,'_').replace(/_+/g,'_').replace(/^_|_$/g,'');}
function normalize(input:any,adminId:string,existing?:EconomicCampaign):EconomicCampaign{const now=new Date().toISOString(),campaignId=id(input.campaign_id||existing?.campaign_id||'');if(campaignId.length<3)throw Object.assign(new Error('Identificador da campanha deve ter ao menos 3 caracteres.'),{code:'CAMPAIGN_ID_INVALID'});const type=String(input.type||existing?.type||'OTHER').toUpperCase() as EconomicCampaignType;if(!['BETA','FOUNDERS','COUPON','WELCOME','CREATOR','SUPPORT','OTHER'].includes(type))throw new Error('Tipo de campanha inválido.');const starts=input.starts_at===undefined?existing?.starts_at:input.starts_at?new Date(input.starts_at).toISOString():null,ends=input.ends_at===undefined?existing?.ends_at:input.ends_at?new Date(input.ends_at).toISOString():null;if(starts&&ends&&new Date(ends).getTime()<=new Date(starts).getTime())throw new Error('O fim da campanha deve ser posterior ao início.');const budget=input.budget_credits===undefined?existing?.budget_credits:input.budget_credits===''||input.budget_credits==null?null:Math.floor(Number(input.budget_credits));if(budget!=null&&(!Number.isFinite(budget)||budget<=0))throw new Error('Budget de créditos inválido.');return{campaign_id:campaignId,name:String(input.name??existing?.name??campaignId).trim(),type,active:input.active===undefined?(existing?.active??true):Boolean(input.active),budget_credits:budget??null,starts_at:starts||null,ends_at:ends||null,notes:String(input.notes??existing?.notes??''),created_at:existing?.created_at||now,created_by:existing?.created_by||adminId,updated_at:now,updated_by:adminId};}
export const economicCampaignService={
 async list(){const rows=await firestoreAdminRest.runQuery({from:[{collectionId:COLLECTION}],limit:250});return rows.map((r:any)=>r.data as EconomicCampaign).sort((a,b)=>a.name.localeCompare(b.name));},
 async get(campaignId:string){const d=await firestoreAdminRest.get(`${COLLECTION}/${encodeURIComponent(id(campaignId))}`);return d.exists?d.data as EconomicCampaign:null;},
 async save(input:any,adminId:string){const campaignId=id(input.campaign_id),path=`${COLLECTION}/${encodeURIComponent(campaignId)}`,d=await firestoreAdminRest.get(path),existing=d.exists?d.data as EconomicCampaign:undefined,campaign=normalize({...input,campaign_id:campaignId},adminId,existing);await firestoreAdminRest.set(path,campaign);return campaign;}
};
