import crypto from 'crypto';
import { Generation, GenerationMode, GenerationAttemptLog, AssetType } from '../../src/types/index.js';
import { generationRepository } from '../repositories/generationRepository.js';
import { smartRouterService } from './smartRouterService.js';
import { walletService } from './walletService.js';
import { creditWalletService } from './creditWalletService.js';
import { creditPricingService } from './creditPricingService.js';
import { assetReferenceResolver } from './assetReferenceResolver.js';
import { providerRegistry } from '../adapters/providerRegistry.js';
import { assetRepository } from '../repositories/assetRepository.js';
import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';

interface GenerationReferenceInput{asset_id:string;slot_type?:'INITIAL'|'END'|'GENERAL';alias?:string;}
interface StartParams{userId:string;model_id:string;mode?:GenerationMode;prompt:string;negative_prompt?:string;duration_seconds:number;resolution:string;aspect_ratio:string;number_of_outputs:number;seed?:number|null;motion_strength?:number|null;references?:GenerationReferenceInput[];requested_provider_id?:string;client_request_id?:string;maximum_authorized_cost_cents?:number;authorized_credit_price?:number;retail_pricing_id?:string;pricing_signature_hash?:string;reqHost?:string;idToken?:string;}
const IMAGE_MODEL_IDS=new Set(['nano-banana-pro-image','nano-banana-2-image','nano-banana-2-lite','seedream-5-pro-image','gpt-image-2']);
function isImageMode(mode?:GenerationMode){return mode==='TEXT_TO_IMAGE'||mode==='IMAGE_TO_IMAGE';}
function inferMode(refs:GenerationReferenceInput[],requested:GenerationMode|undefined,modelId:string):GenerationMode{if(requested)return requested;if(IMAGE_MODEL_IDS.has(modelId))return refs.length?'IMAGE_TO_IMAGE':'TEXT_TO_IMAGE';if(!refs.length)return'TEXT_TO_VIDEO';if(refs.some(r=>r.slot_type==='INITIAL'))return'IMAGE_TO_VIDEO';return'REFERENCE_TO_VIDEO';}
function terminal(status:string){return['SUCCEEDED','FAILED','CANCELLED','REFUNDED'].includes(status);}
function creditBilling(g:Generation){return (g as any).billing_scheme==='CREDITS_V2';}
const ECONOMICS_IMMUTABLE_FIELDS=['generation_id','retail_pricing_id','retail_pricing_version','pricing_signature_hash','authorized_credit_price','credit_lot_allocations','authorized_net_backing_micros','max_allowed_cogs_cents','quoted_at','started_at'] as const;
async function saveEconomics(generationId:string,data:any){
 const path=`generation_economics/${encodeURIComponent(generationId)}`;
 try{
  const existing=await firestoreAdminRest.get(path);
  const previous=existing.exists?(existing.data as Record<string,any>):{};
  const next={...previous,...data,generation_id:generationId};
  if(existing.exists){for(const key of ECONOMICS_IMMUTABLE_FIELDS){if(previous[key]!==undefined)next[key]=previous[key];}}
  next.updated_at=new Date().toISOString();
  await firestoreAdminRest.set(path,next);
 }catch(err:any){console.warn('[EconomicsSnapshot]',err?.message||err);}
}
async function registerGeneratedAssets(generation:Generation,urls:string[]){const mediaType:AssetType=isImageMode(generation.mode)?'IMAGE':'VIDEO';const created=[];for(let i=0;i<urls.length;i++){const url=urls[i];if(!url)continue;try{created.push(await assetRepository.createAsset({owner_user_id:generation.user_id,type:mediaType,category:'GENERIC',name:mediaType==='IMAGE'?`Imagem gerada ${generation.generation_id.slice(-6)}${urls.length>1?` ${i+1}`:''}`:`Vídeo gerado ${generation.generation_id.slice(-6)}${urls.length>1?` ${i+1}`:''}`,alias:`${mediaType==='IMAGE'?'generated_image':'generated_video'}_${generation.generation_id.slice(-6)}${urls.length>1?`_${i+1}`:''}`,storage_path:`provider://${generation.provider_id}/${generation.provider_job_id||generation.generation_id}/${i+1}`,public_url:url,thumbnail_url:mediaType==='IMAGE'?url:generation.thumbnail_url||'',mime_type:mediaType==='IMAGE'?'image/jpeg':'video/mp4',size_bytes:0,status:'READY',origin:'GENERATED',source_generation_id:generation.generation_id,source_model_id:generation.model_id,source_provider_id:generation.provider_id}));}catch(err:any){console.warn('[GeneratedAssetRegister]',generation.generation_id,err?.message||err);}}return created;}

export const generationService={
 async createAndStartGeneration(params:StartParams):Promise<Generation>{
  if(!params.model_id||!params.prompt?.trim())throw Object.assign(new Error('Modelo e prompt são obrigatórios.'),{code:'VALIDATION_ERROR'});const refs=params.references||[],mode=inferMode(refs,params.mode,params.model_id),imageJob=isImageMode(mode),billDuration=imageJob?1:params.duration_seconds;if(!imageJob&&(!Number.isInteger(params.duration_seconds)||params.duration_seconds<=0))throw Object.assign(new Error('Duração inválida.'),{code:'VALIDATION_ERROR'});if(!Number.isInteger(params.number_of_outputs)||params.number_of_outputs<1||params.number_of_outputs>4)throw Object.assign(new Error('Quantidade de saídas inválida.'),{code:'VALIDATION_ERROR'});if(mode==='IMAGE_TO_IMAGE'&&!refs.length)throw Object.assign(new Error('Adicione pelo menos uma imagem de referência para editar.'),{code:'REFERENCE_REQUIRED'});
  const clientId=params.client_request_id||crypto.randomUUID(),existing=await generationRepository.findByClientRequest(params.userId,clientId);if(existing)return existing;const generationId=`gen_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`;
  const preview=await creditPricingService.preview({userId:params.userId,model_id:params.model_id,mode,prompt:params.prompt.trim(),negative_prompt:params.negative_prompt,duration_seconds:billDuration,resolution:params.resolution,aspect_ratio:params.aspect_ratio,number_of_outputs:params.number_of_outputs,seed:params.seed,motion_strength:params.motion_strength,references:refs,force_live_quote:true});const price=preview.retail.retail_credit_price;const authorized=Number(params.authorized_credit_price??params.maximum_authorized_cost_cents);if(Number.isFinite(authorized)&&authorized>0&&authorized!==price)throw Object.assign(new Error('O preço em créditos mudou desde a autorização. Atualize a prévia antes de gerar; nenhum crédito foi reservado.'),{code:'PRICE_CHANGED_REQUOTE_REQUIRED',quoted_credit_price:authorized,current_credit_price:price});
  const now=new Date().toISOString();let generation:any={generation_id:generationId,user_id:params.userId,status:'QUEUED',billing_scheme:'CREDITS_V2',model_id:params.model_id,provider_id:preview.decision.selected.provider_id,mode,original_prompt:params.prompt.trim(),compiled_prompt:params.prompt.trim(),prompt_compiler_version:'credits-v2',negative_prompt:params.negative_prompt||'',duration_seconds:imageJob?undefined:params.duration_seconds,resolution:params.resolution,aspect_ratio:params.aspect_ratio,number_of_outputs:params.number_of_outputs,seed:params.seed??null,motion_strength:params.motion_strength??null,references:refs.map(r=>({asset_id:r.asset_id,slot_type:r.slot_type||'GENERAL',alias:r.alias})),retail_credit_price:price,authorized_credit_price:price,final_credit_cost:0,retail_pricing_id:preview.retail.retail_pricing_id,retail_pricing_version:preview.retail.version,pricing_signature_hash:preview.signature.hash,max_allowed_cogs_cents:0,incurred_cogs_cents:0,estimated_cost_cents:price,maximum_authorized_cost_cents:price,final_cost_cents:0,currency:'BRL',client_request_id:clientId,progress_percent:0,result_asset_id:null,result_url:null,thumbnail_url:null,error_code:null,error_message:null,attempt_count:0,references_count:refs.length,created_at:now,submitted_at:null,completed_at:null,failed_at:null};
  await generationRepository.saveGeneration(generation);generation.status='RESERVING_FUNDS';await generationRepository.saveGeneration(generation);
  let reservation;try{reservation=await creditWalletService.reserveForGeneration({userId:params.userId,credits:price,generationId,idempotencyKey:`credit-reserve:${generationId}`});}catch(err){generation.status='FAILED';generation.error_code=(err as any)?.code||'CREDIT_RESERVE_FAILED';generation.error_message=(err as any)?.message||'Falha ao reservar créditos';generation.failed_at=new Date().toISOString();await generationRepository.saveGeneration(generation);throw err;}
  const backingCents=Math.floor(reservation.authorized_net_backing_micros/10000),floor=preview.retail.normal_floor_margin_percent/100,maxAllowed=Math.max(0,Math.floor(backingCents*(1-floor)));generation.max_allowed_cogs_cents=maxAllowed;generation.authorized_net_backing_micros=reservation.authorized_net_backing_micros;generation.credit_reservation_id=generationId;await generationRepository.saveGeneration(generation);
  await saveEconomics(generationId,{generation_id:generationId,retail_pricing_id:preview.retail.retail_pricing_id,retail_pricing_version:preview.retail.version,pricing_signature_hash:preview.signature.hash,authorized_credit_price:price,credit_lot_allocations:reservation.allocations,authorized_net_backing_micros:reservation.authorized_net_backing_micros,max_allowed_cogs_cents:maxAllowed,incurred_cogs_cents:0,remaining_cogs_budget_cents:maxAllowed,expected_margin_percent:null,provider_attempts:[],quoted_at:preview.decision.selected.quoted_at,started_at:now,delivered_at:null});
  try{
   const decision=await smartRouterService.selectProvider({userId:params.userId,model_id:params.model_id,mode,prompt:params.prompt.trim(),negative_prompt:params.negative_prompt,duration_seconds:billDuration,resolution:params.resolution,aspect_ratio:params.aspect_ratio,number_of_outputs:params.number_of_outputs,seed:params.seed,motion_strength:params.motion_strength,generation_id:generationId,max_allowed_cogs_cents:maxAllowed,incurred_cogs_cents:0,force_live_quote:true});const resolved=await assetReferenceResolver.resolveReferenceAssetUrls(params.userId,refs.map(r=>r.asset_id),params.reqHost,params.idToken);const enriched=resolved.map(asset=>{const source=refs.find(ref=>ref.asset_id===asset.asset_id);return{...asset,slot_type:(source?.slot_type||'GENERAL') as 'INITIAL'|'END'|'GENERAL',prompt_alias:source?.alias||asset.alias};});let incurred=0,lastError:any=null;
   for(let i=0;i<decision.candidates.length;i++){
    const candidate=decision.candidates[i];if(candidate.fully_loaded_safe_cogs_cents>Math.max(0,maxAllowed-incurred))continue;const adapter=providerRegistry.getAdapter(candidate.provider_id);if(!adapter||!adapter.isConfigured())continue;const attempt:GenerationAttemptLog={attempt_id:`att_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,generation_id:generationId,attempt_number:i+1,provider_id:candidate.provider_id,status:'SUBMITTED',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};
    try{generation.provider_id=candidate.provider_id;generation.attempt_count=i+1;generation.incurred_cogs_cents=incurred;await generationRepository.saveGeneration(generation);const job=await adapter.submitGeneration({generation_id:generationId,user_id:params.userId,model_id:params.model_id,mode,prompt:params.prompt.trim(),negative_prompt:params.negative_prompt,duration_seconds:billDuration,resolution:params.resolution,aspect_ratio:params.aspect_ratio,number_of_outputs:params.number_of_outputs,seed:params.seed,motion_strength:params.motion_strength,references:enriched});attempt.provider_job_id=job.provider_job_id;attempt.updated_at=new Date().toISOString();await generationRepository.recordAttemptLog(attempt);generation.provider_job_id=job.provider_job_id;generation.status='SUBMITTED';generation.submitted_at=new Date().toISOString();generation.authorized_provider_safe_cogs_cents=candidate.fully_loaded_safe_cogs_cents;await generationRepository.saveGeneration(generation);return generation as Generation;}
    catch(err:any){lastError=err;attempt.status='FAILED';attempt.error_message=err?.message||'Falha ao enviar';attempt.updated_at=new Date().toISOString();await generationRepository.recordAttemptLog(attempt);if(candidate.billing_policy!=='CHARGE_ON_SUCCESS')incurred+=candidate.fully_loaded_safe_cogs_cents;generation.incurred_cogs_cents=incurred;await generationRepository.saveGeneration(generation);await saveEconomics(generationId,{incurred_cogs_cents:incurred,remaining_cogs_budget_cents:Math.max(0,maxAllowed-incurred)});}
   }
   throw lastError||Object.assign(new Error('Nenhum fallback permaneceu dentro do orçamento econômico da geração.'),{code:'PROVIDER_SUBMISSION_FAILED'});
  }catch(err:any){await creditWalletService.releaseForGeneration(params.userId,generationId).catch(()=>{});generation.status='FAILED';generation.error_code=err?.code||'GENERATION_SUBMIT_FAILED';generation.error_message=err?.message||'Falha ao iniciar geração';generation.failed_at=new Date().toISOString();await generationRepository.saveGeneration(generation);await saveEconomics(generationId,{failed_at:generation.failed_at,error_code:generation.error_code,error_message:generation.error_message});throw err;}
 },
 async refreshGenerationState(generation:Generation):Promise<Generation>{
  if(terminal(generation.status)||!generation.provider_job_id)return generation;const adapter=providerRegistry.getAdapter(generation.provider_id);if(!adapter||!adapter.isConfigured())return generation;let status;try{status=await adapter.checkStatus(generation.provider_job_id);}catch(err:any){console.warn('[GenerationPoll]',generation.generation_id,err?.message);return generation;}if(status.status==='QUEUED'||status.status==='PROCESSING'){generation.status=status.status;generation.progress_percent=status.progress_percent??generation.progress_percent;return generationRepository.saveGeneration(generation);}if(status.status==='FAILED'){if(creditBilling(generation))await creditWalletService.releaseForGeneration(generation.user_id,generation.generation_id).catch(()=>{});else{const reserved=generation.maximum_authorized_cost_cents||generation.estimated_cost_cents||0;if(reserved>0)await walletService.releaseForGeneration({userId:generation.user_id,amount_cents:reserved,generation_id:generation.generation_id,idempotency_key:`release:${generation.generation_id}:provider-failure`,reason:'Provider finalizou com falha'}).catch(()=>{});}generation.status='FAILED';generation.progress_percent=0;generation.error_code=status.error_code||'PROVIDER_GENERATION_FAILED';generation.error_message=status.error_message||'A geração falhou no provider.';generation.failed_at=new Date().toISOString();await saveEconomics(generation.generation_id,{failed_at:generation.failed_at,error_code:generation.error_code,error_message:generation.error_message});return generationRepository.saveGeneration(generation);}
  const outputs=(status.result_urls||status.result_image_urls||[status.result_video_url]).filter(Boolean) as string[];if(!outputs.length){if(creditBilling(generation))await creditWalletService.releaseForGeneration(generation.user_id,generation.generation_id).catch(()=>{});generation.status='FAILED';generation.error_code='DELIVERY_FAILED';generation.error_message='O provider concluiu, mas nenhum arquivo recuperável foi entregue.';generation.failed_at=new Date().toISOString();await saveEconomics(generation.generation_id,{failed_at:generation.failed_at,error_code:generation.error_code,error_message:generation.error_message});return generationRepository.saveGeneration(generation);}generation.result_url=outputs[0];generation.thumbnail_url=isImageMode(generation.mode)?outputs[0]:status.thumbnail_url||null;generation.result_urls=outputs;const assets=await registerGeneratedAssets(generation,outputs);if(assets[0])generation.result_asset_id=assets[0].asset_id;generation.result_asset_ids=assets.map(a=>a.asset_id);
  if(creditBilling(generation)){await creditWalletService.captureForGeneration(generation.user_id,generation.generation_id);(generation as any).final_credit_cost=(generation as any).retail_credit_price||generation.estimated_cost_cents||0;generation.final_cost_cents=(generation as any).final_credit_cost;}else{const finalCost=generation.estimated_cost_cents||0;if(finalCost>0)await walletService.captureForGeneration({userId:generation.user_id,amount_cents:finalCost,generation_id:generation.generation_id,idempotency_key:`capture:${generation.generation_id}`});generation.final_cost_cents=finalCost;}
  generation.status='SUCCEEDED';generation.progress_percent=100;generation.completed_at=new Date().toISOString();await saveEconomics(generation.generation_id,{generation_id:generation.generation_id,retail_pricing_id:(generation as any).retail_pricing_id,retail_pricing_version:(generation as any).retail_pricing_version,pricing_signature_hash:(generation as any).pricing_signature_hash,authorized_credit_price:(generation as any).retail_credit_price,authorized_net_backing_micros:(generation as any).authorized_net_backing_micros,max_allowed_cogs_cents:(generation as any).max_allowed_cogs_cents,incurred_cogs_cents:(generation as any).incurred_cogs_cents||0,remaining_cogs_budget_cents:Math.max(0,Number((generation as any).max_allowed_cogs_cents||0)-Number((generation as any).incurred_cogs_cents||0)),final_provider_cost_if_known:(generation as any).authorized_provider_safe_cogs_cents,delivered_at:generation.completed_at});return generationRepository.saveGeneration(generation);
 },
 async getGeneration(id:string,userId:string){const g=await generationRepository.getGeneration(id);if(!g||g.user_id!==userId)return null;return this.refreshGenerationState(g);},
 async listUserGenerations(userId:string,limit=50){const list=await generationRepository.listUserGenerations(userId,limit);return Promise.all(list.map(g=>terminal(g.status)?g:this.refreshGenerationState(g)));},
 async cancelGeneration(id:string,userId:string){const g=await generationRepository.getGeneration(id);if(!g||g.user_id!==userId)throw new Error('Geração não encontrada.');if(terminal(g.status))return g;if(g.provider_job_id){const adapter=providerRegistry.getAdapter(g.provider_id);const cancelled=adapter?.cancelJob?await adapter.cancelJob(g.provider_job_id):false;if(!cancelled)throw new Error('Este provider não permite cancelar depois que o job foi enviado.');}if(creditBilling(g))await creditWalletService.releaseForGeneration(userId,id).catch(()=>{});else{const reserved=g.maximum_authorized_cost_cents||g.estimated_cost_cents||0;if(reserved>0)await walletService.releaseForGeneration({userId,amount_cents:reserved,generation_id:id,idempotency_key:`release:${id}:cancel`,reason:'Cancelamento do usuário'});}g.status='CANCELLED';g.failed_at=new Date().toISOString();await saveEconomics(g.generation_id,{cancelled_at:g.failed_at});return generationRepository.saveGeneration(g);}
};