import { STUDIO_FALLBACK_MODELS } from '../../src/config/studioCatalog.js';
import { providerRegistry } from '../adapters/providerRegistry.js';
import { quoteCacheService } from './quoteCacheService.js';
import { providerFinanceService } from './providerFinanceService.js';
import { fxRateService } from './fxRateService.js';
import { pricingSettingsService } from './pricingSettingsService.js';
import { retailPricingService } from './retailPricingService.js';
import { GenerationMode } from '../../src/types/index.js';
import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';
import { PricingSignature } from './pricingSignatureService.js';

export interface PricingHealthRow {key:string;provider_id:string;provider_name:string;model_id:string;mode:GenerationMode;duration_seconds:number;resolution:string;provider_cost_usd:number|null;provider_cost_brl_cents:number|null;safe_cost_brl_cents:number|null;fully_loaded_safe_cogs_cents?:number|null;retail_credit_price?:number|null;retail_pricing_version?:number|null;margin_percent:number|null;status:'OK'|'FAILED';checked_at:string;error?:string;pricing_signature_hash?:string;health?:'GREEN'|'YELLOW'|'RED'|'PROBE';}
export interface PricingHealthSnapshot {snapshot_id?:string;checked_at:string|null;checked:number;healthy:number;failed:number;fx_rate:number|null;fx_source:string|null;cache_ttl_minutes:number;provider_finance:any[];rows:PricingHealthRow[];signatures_checked?:number;normal_floor_margin_percent?:number;emergency_floor_margin_percent?:number;conservative_credit_value_micros?:number;}
const LATEST_DOC='app_config/pricing_health_latest',HISTORY_COLLECTION='pricing_health_snapshots';let latestSnapshot:PricingHealthSnapshot={checked_at:null,checked:0,healthy:0,failed:0,fx_rate:null,fx_source:null,cache_ttl_minutes:30,provider_finance:[],rows:[]};
function baselineSignature(model:(typeof STUDIO_FALLBACK_MODELS)[number]):PricingSignature{const mode=(model.category==='IMAGE'?'TEXT_TO_IMAGE':model.supported_modes.includes('TEXT_TO_VIDEO')?'TEXT_TO_VIDEO':model.supported_modes[0]) as GenerationMode,duration=model.category==='IMAGE'?1:(model.supported_durations[Math.floor(model.supported_durations.length/2)]||5),resolution=(model.category==='IMAGE'?['2K','1K','4K']:['720p','768p','540p','480p','1080p']).find(r=>model.supported_resolutions.includes(r))||model.supported_resolutions[0];return{model_id:model.model_id,mode,resolution,duration_seconds:duration,aspect_ratio:model.recommended_aspect_ratio||'16:9',number_of_outputs:1,audio_enabled:false,reference_mode:'none',reference_count:0,reference_count_band:'0',model_variant:'default',pricing_options:{},normalized:'baseline',hash:`baseline:${model.model_id}`};}
async function activeRetail(){await retailPricingService.migrateAllLegacy().catch(()=>({migrated:0}));const pointers=await firestoreAdminRest.runQuery({from:[{collectionId:'retail_pricing_active'}]}).catch(()=>[]);const out:Array<{signature:PricingSignature;price:number;version:number}>=[];for(const p of pointers){const hash=String(p.data?.pricing_signature_hash||''),version=Number(p.data?.version||0);if(!hash||!version)continue;const d=await firestoreAdminRest.get(`retail_pricing_versions/${encodeURIComponent(hash)}_v${version}`).catch(()=>({exists:false}as any));if(d.exists&&d.data?.signature)out.push({signature:d.data.signature as PricingSignature,price:Number(d.data.retail_credit_price||0),version});}return out;}
async function mapWithConcurrency<T,R>(items:T[],limit:number,fn:(item:T)=>Promise<R>):Promise<R[]>{const out=new Array<R>(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await fn(items[i]);}}await Promise.all(Array.from({length:Math.min(limit,items.length||1)},()=>worker()));return out;}
async function persistSnapshot(snapshot:PricingHealthSnapshot){const snapshotId=`phs_${String(snapshot.checked_at||new Date().toISOString()).replace(/[^0-9]/g,'')}`,stored={...snapshot,snapshot_id:snapshotId};await Promise.all([firestoreAdminRest.set(LATEST_DOC,stored),firestoreAdminRest.set(`${HISTORY_COLLECTION}/${snapshotId}`,stored)]);return stored;}
export const pricingSyncService={
 async getLatestSnapshot(){if(latestSnapshot.rows.length)return latestSnapshot;try{const doc=await firestoreAdminRest.get(LATEST_DOC);if(doc.exists&&Array.isArray((doc.data as any)?.rows))latestSnapshot=doc.data as PricingHealthSnapshot;}catch(err:any){console.warn('[PricingHealthLoad]',err?.message||err);}return latestSnapshot;},
 async runHourlySync(){const checkedAt=new Date().toISOString();const[fx,providerFinance,active,settings]=await Promise.all([fxRateService.get(true),providerFinanceService.getAll(true).catch(()=>[]),activeRetail(),pricingSettingsService.get(true)]);quoteCacheService.invalidateAll();const signatures=new Map<string,{signature:PricingSignature;price:number|null;version:number|null}>();for(const r of active)signatures.set(r.signature.hash,{signature:r.signature,price:r.price,version:r.version});for(const model of STUDIO_FALLBACK_MODELS.filter(m=>m.status==='ACTIVE'))if(![...signatures.values()].some(x=>x.signature.model_id===model.model_id)){const s=baselineSignature(model);signatures.set(s.hash,{signature:s,price:null,version:null});}
 const jobs:Array<{adapter:any;signature:PricingSignature;price:number|null;version:number|null}>=[];for(const item of signatures.values())for(const adapter of providerRegistry.listAdapters())if(adapter.isConfigured()&&adapter.quoteCostUsd&&adapter.supports(item.signature.model_id,item.signature.mode))jobs.push({adapter,signature:item.signature,price:item.price,version:item.version});
 const rows=await mapWithConcurrency(jobs,4,async(job):Promise<PricingHealthRow>=>{const{adapter,signature:s,price,version}=job,key=`${adapter.providerId}:${s.hash}`;try{const quote=await quoteCacheService.getOrQuote(adapter,{userId:'pricing-health',model_id:s.model_id,mode:s.mode,duration_seconds:s.duration_seconds,resolution:s.resolution,aspect_ratio:s.aspect_ratio,number_of_outputs:s.number_of_outputs},true);const backingCents=price?Math.floor(price*settings.conservative_credit_value_micros/10000):0,margin=backingCents>0?100*(1-quote.fully_loaded_safe_cogs_cents/backingCents):null,health=margin==null?'PROBE':margin>=settings.normal_floor_margin_percent?'GREEN':margin>=settings.emergency_floor_margin_percent?'YELLOW':'RED';return{key,provider_id:adapter.providerId,provider_name:adapter.name,model_id:s.model_id,mode:s.mode,duration_seconds:s.duration_seconds,resolution:s.resolution,provider_cost_usd:quote.provider_cost_usd,provider_cost_brl_cents:quote.provider_cost_brl_cents,safe_cost_brl_cents:quote.safe_cost_brl_cents,fully_loaded_safe_cogs_cents:quote.fully_loaded_safe_cogs_cents,retail_credit_price:price,retail_pricing_version:version,margin_percent:margin,status:'OK',health,checked_at:checkedAt,pricing_signature_hash:s.hash};}catch(err:any){return{key,provider_id:adapter.providerId,provider_name:adapter.name,model_id:s.model_id,mode:s.mode,duration_seconds:s.duration_seconds,resolution:s.resolution,provider_cost_usd:null,provider_cost_brl_cents:null,safe_cost_brl_cents:null,fully_loaded_safe_cogs_cents:null,retail_credit_price:price,retail_pricing_version:version,margin_percent:null,status:'FAILED',health:'RED',checked_at:checkedAt,error:err?.message||'Provider não retornou cotação válida.',pricing_signature_hash:s.hash};}});
 latestSnapshot={checked_at:checkedAt,checked:rows.length,healthy:rows.filter(r=>r.status==='OK'&&r.health!=='RED').length,failed:rows.filter(r=>r.status==='FAILED'||r.health==='RED').length,fx_rate:fx.rate,fx_source:fx.source,cache_ttl_minutes:Math.round(quoteCacheService.ttl_ms()/60000),provider_finance:providerFinance,rows,signatures_checked:signatures.size,normal_floor_margin_percent:settings.normal_floor_margin_percent,emergency_floor_margin_percent:settings.emergency_floor_margin_percent,conservative_credit_value_micros:settings.conservative_credit_value_micros};try{latestSnapshot=await persistSnapshot(latestSnapshot);}catch(err:any){console.error('[PricingHealthPersist]',err?.message||err);}return latestSnapshot;}
};
