import crypto from 'crypto';
import { catalogRepository } from '../repositories/catalogRepository.js';
import { providerRegistry } from '../adapters/providerRegistry.js';
import { firestoreAdminRest } from '../repositories/firestoreAdminRest.js';
import { providerFinanceService, ProviderFinanceSnapshot } from './providerFinanceService.js';
import { quoteCacheService } from './quoteCacheService.js';
import { GenerationMode, ProviderStatus, ProviderModelMapping } from '../../src/types/index.js';

export interface RoutingCandidate{provider_id:string;provider_name:string;provider_cost_cents:number;safe_cost_cents:number;fully_loaded_safe_cogs_cents:number;customer_price_cents:number;provider_cost_usd:number;margin_percent:number;quoted_at:string;quote_estimated:boolean;priority:number;status:ProviderStatus;is_healthy:boolean;balance_brl_cents?:number|null;low_balance?:boolean;billing_policy:'CHARGE_ON_SUCCESS'|'CHARGE_ON_SUBMISSION'|'CHARGE_ON_PROCESSING'|'UNKNOWN';}
export interface RoutingDecision{selected:RoutingCandidate;candidates:RoutingCandidate[];reason:string;strategy:'CHEAPEST_RELIABLE';remaining_cogs_budget_cents:number|null;}
const nowIso='2026-09-09T00:00:00.000Z';
const seedance20WaveMapping:ProviderModelMapping={mapping_id:'map-seed20-wave-runtime',model_id:'seedance-2-0',provider_id:'provider-wavespeed',provider_model_identifier:'bytedance/seedance-2.0',status:'ACTIVE',updated_at:nowIso};

export const smartRouterService={
 async selectProvider(params:{userId:string;model_id:string;mode:GenerationMode;duration_seconds:number;resolution:string;number_of_outputs:number;aspect_ratio?:string;prompt?:string;negative_prompt?:string;seed?:number|null;motion_strength?:number|null;generation_id?:string;force_live_quote?:boolean;max_allowed_cogs_cents?:number;incurred_cogs_cents?:number;}):Promise<RoutingDecision>{
  const[providers,baseMappings,financeRows]=await Promise.all([catalogRepository.listProviders(),catalogRepository.listMappings(),providerFinanceService.getAll(false).catch(()=>[] as ProviderFinanceSnapshot[])]);const financeById=new Map(financeRows.map(r=>[r.provider_id,r]));const mappings=[...baseMappings];if(!mappings.some(m=>m.model_id==='seedance-2-0'&&m.provider_id==='provider-wavespeed'))mappings.push(seedance20WaveMapping);const mapProviders=new Set(mappings.filter(m=>m.model_id===params.model_id&&m.status==='ACTIVE').map(m=>m.provider_id));
  const max=Number.isFinite(Number(params.max_allowed_cogs_cents))?Math.max(0,Number(params.max_allowed_cogs_cents)):null;const incurred=Math.max(0,Number(params.incurred_cogs_cents||0));const remaining=max==null?null:Math.max(0,max-incurred);
  const attempts=await Promise.all(providers.map(async p=>{if(p.status==='INACTIVE'||!mapProviders.has(p.provider_id))return null;const adapter=providerRegistry.getAdapter(p.provider_id);if(!adapter||!adapter.isConfigured()||!adapter.supports(params.model_id,params.mode)||!adapter.quoteCostUsd)return null;try{const q=await quoteCacheService.getOrQuote(adapter,{userId:params.userId,model_id:params.model_id,mode:params.mode,prompt:params.prompt,negative_prompt:params.negative_prompt,duration_seconds:params.duration_seconds,resolution:params.resolution,aspect_ratio:params.aspect_ratio||'16:9',number_of_outputs:params.number_of_outputs,seed:params.seed,motion_strength:params.motion_strength},Boolean(params.force_live_quote));const finance=financeById.get(p.provider_id);if(finance?.balance_brl_cents!=null&&finance.balance_brl_cents<q.provider_cost_brl_cents)return null;const loaded=Number((q as any).fully_loaded_safe_cogs_cents||q.safe_cost_brl_cents);if(remaining!=null&&loaded>remaining)return null;const low=Boolean(finance?.low_balance);return{provider_id:p.provider_id,provider_name:p.name,provider_cost_cents:q.provider_cost_brl_cents,safe_cost_cents:q.safe_cost_brl_cents,fully_loaded_safe_cogs_cents:loaded,customer_price_cents:q.customer_price_cents,provider_cost_usd:q.provider_cost_usd,margin_percent:q.effective_margin*100,quoted_at:q.quoted_at,quote_estimated:q.estimated,priority:p.priority,status:p.status,is_healthy:p.status==='ACTIVE'&&!low,balance_brl_cents:finance?.balance_brl_cents,low_balance:low,billing_policy:(q as any).billing_policy||'UNKNOWN'} as RoutingCandidate;}catch(err:any){console.warn('[SmartRouterQuote]',p.provider_id,params.model_id,err?.code||err?.message||err);return null;}}));
  const candidates=attempts.filter((x):x is RoutingCandidate=>Boolean(x));if(!candidates.length){const e:any=new Error(remaining!=null?'Nenhum provider consegue executar esta configuração dentro do orçamento econômico seguro.':'Nenhum provider retornou uma cotação segura, possui saldo suficiente e suporta esta configuração.');e.code='NO_SAFE_PROVIDER_AVAILABLE';e.remaining_cogs_budget_cents=remaining;throw e;}candidates.sort((a,b)=>(a.is_healthy===b.is_healthy?a.fully_loaded_safe_cogs_cents-b.fully_loaded_safe_cogs_cents:a.is_healthy?-1:1)||b.priority-a.priority);const selected=candidates[0];const reason=`${selected.provider_name} selecionado por custo seguro, disponibilidade e orçamento de COGS.`;
  const log={log_id:`route_${Date.now()}_${crypto.randomBytes(4).toString('hex')}`,generation_id:params.generation_id,user_id:params.userId,model_id:params.model_id,selected_provider_id:selected.provider_id,strategy:'CHEAPEST_RELIABLE',candidate_providers:candidates.map(c=>({provider_id:c.provider_id,provider_cost_cents:c.provider_cost_cents,safe_cost_cents:c.safe_cost_cents,fully_loaded_safe_cogs_cents:c.fully_loaded_safe_cogs_cents,status:c.status,priority:c.priority,is_healthy:c.is_healthy})),reason,max_allowed_cogs_cents:max,incurred_cogs_cents:incurred,remaining_cogs_budget_cents:remaining,created_at:new Date().toISOString()};await firestoreAdminRest.set(`routing_logs/${encodeURIComponent(log.log_id)}`,log).catch(()=>{});return{selected,candidates,reason,strategy:'CHEAPEST_RELIABLE',remaining_cogs_budget_cents:remaining};
 },
 async listRoutingLogs(limit=50){const rows=await firestoreAdminRest.runQuery({from:[{collectionId:'routing_logs'}],orderBy:[{field:{fieldPath:'created_at'},direction:'DESCENDING'}],limit}).catch(()=>[] as any[]);return rows.map((r:any)=>r.data);}
};