import { httpServerHandler } from 'cloudflare:node';
import express from 'express';
import { apiRouter } from '../server/routes/apiRoutes.js';
import { runtimeRouter } from '../server/routes/runtimeRoutes.js';
import { generationRuntimeRouter } from '../server/routes/generationRuntimeRoutes.js';
import { providerFinanceRouter } from '../server/routes/providerFinanceRoutes.js';
import { pricingRuntimeRouter } from '../server/routes/pricingRuntimeRoutes.js';
import { adminPricingRuntimeRouter } from '../server/routes/adminPricingRuntimeRoutes.js';
import { communityRouter } from '../server/routes/communityRoutes.js';
import { creditRuntimeRouter } from '../server/routes/creditRuntimeRoutes.js';
import { adminEconomicsRouter } from '../server/routes/adminEconomicsRoutes.js';
import { pricingSyncService } from '../server/services/pricingSyncService.js';

const app=express();
app.use('/api',runtimeRouter);
app.use(express.json({limit:'4mb'}));
app.use('/api',creditRuntimeRouter);
app.use('/api',adminEconomicsRouter);
app.use('/api',providerFinanceRouter);
app.use('/api',adminPricingRuntimeRouter);
app.use('/api',pricingRuntimeRouter);
app.use('/api',communityRouter);
app.use('/api',generationRuntimeRouter);
app.use('/api',apiRouter);
app.get('/health',(_req,res)=>res.json({status:'ok',service:'ia-conect',runtime:'cloudflare-workers',stage:'credits-v2'}));
app.listen(3000);
const httpHandler=httpServerHandler({port:3000}) as any;
export default{fetch:httpHandler.fetch.bind(httpHandler),async scheduled(_controller:any,_env:unknown,ctx:any){ctx.waitUntil(pricingSyncService.runHourlySync().then(result=>console.log('[PricingSync]',JSON.stringify({checked_at:result.checked_at,checked:result.checked,healthy:result.healthy,failed:result.failed,fx_rate:result.fx_rate}))));}};
