import React,{useEffect,useMemo,useState}from'react';
import{Copy,FilePlus2,Layers3,LoaderCircle,RefreshCw,Tag,Trash2}from'lucide-react';
import{ApiError}from'../../services/apiClient.js';
import{betaFlowClient,FlowRecord}from'../flowClient.js';
import{betaTemplateClient,TemplateCategory,TemplateView}from'../templateClient.js';

const CATEGORIES:TemplateCategory[]=['GENERIC','IMAGE','VIDEO','AUDIO','THREE_D','MULTIMODAL'];
const labels:Record<TemplateCategory,string>={GENERIC:'Geral',IMAGE:'Imagem',VIDEO:'Vídeo',AUDIO:'Áudio',THREE_D:'3D',MULTIMODAL:'Multimodal'};
const message=(error:any)=>error instanceof ApiError?error.message:error?.message||'Não foi possível concluir a operação.';
export const BetaTemplatesView:React.FC<{onOpenFlow?:(flowId:string)=>void}>=({onOpenFlow})=>{
 const[templates,setTemplates]=useState<TemplateView[]>([]),[flows,setFlows]=useState<FlowRecord[]>([]),[flowId,setFlowId]=useState(''),[name,setName]=useState(''),[category,setCategory]=useState<TemplateCategory>('GENERIC'),[tags,setTags]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[filter,setFilter]=useState<'ALL'|TemplateCategory>('ALL');
 const load=async()=>{setBusy('load');setError('');try{const[t,f]=await Promise.all([betaTemplateClient.list(),betaFlowClient.list()]);setTemplates(t);setFlows(f);if(!flowId&&f[0])setFlowId(f[0].flow_id);}catch(e){setError(message(e));}finally{setBusy('');}};
 useEffect(()=>{void load()},[]);
 const visible=useMemo(()=>filter==='ALL'?templates:templates.filter(t=>t.category===filter),[templates,filter]);
 const create=async()=>{if(!flowId)return;setBusy('create');setError('');try{const created=await betaTemplateClient.create({flow_id:flowId,name:name.trim()||undefined,category,tags:tags.split(',').map(v=>v.trim()).filter(Boolean)});setTemplates(rows=>[created,...rows]);setName('');setTags('');}catch(e){setError(message(e));}finally{setBusy('');}};
 const useTemplate=async(template:TemplateView)=>{setBusy(template.template_id);setError('');try{const flow=await betaTemplateClient.instantiate(template.template_id);setTemplates(rows=>rows.map(item=>item.template_id===template.template_id?{...item,use_count:item.use_count+1}:item));onOpenFlow?.(flow.flow_id);}catch(e){setError(message(e));}finally{setBusy('');}};
 const remove=async(templateId:string)=>{setBusy('delete:'+templateId);try{await betaTemplateClient.remove(templateId);setTemplates(rows=>rows.filter(item=>item.template_id!==templateId));}catch(e){setError(message(e));}finally{setBusy('');}};
 return <main className="ia-beta-templates"><header className="ia-beta-templates-head"><div><span><Layers3/> Templates V1</span><h1>Transforme seus Flows em atalhos reutilizáveis.</h1><p>Templates preservam a lógica do grafo e convertem assets privados em inputs, para reutilização segura.</p></div><button onClick={()=>void load()}><RefreshCw/>{busy==='load'?'Atualizando…':'Atualizar'}</button></header>{error&&<div className="ia-beta-template-error">{error}</div>}<section className="ia-beta-template-create"><div><h2>Criar a partir de um Flow</h2><p>Use a revisão atual de um Flow salvo como base.</p></div><select value={flowId} onChange={e=>setFlowId(e.target.value)}><option value="">Selecione um Flow</option>{flows.map(flow=><option key={flow.flow_id} value={flow.flow_id}>{flow.name} · r{flow.revision}</option>)}</select><input value={name} onChange={e=>setName(e.target.value)} placeholder="Nome opcional do template"/><select value={category} onChange={e=>setCategory(e.target.value as TemplateCategory)}>{CATEGORIES.map(c=><option key={c} value={c}>{labels[c]}</option>)}</select><input value={tags} onChange={e=>setTags(e.target.value)} placeholder="tags, separadas, por vírgula"/><button className="is-primary" disabled={!flowId||Boolean(busy)} onClick={()=>void create()}>{busy==='create'?<LoaderCircle className="is-spin"/>:<FilePlus2/>}Criar template</button></section><div className="ia-beta-template-filters"><button className={filter==='ALL'?'is-selected':''} onClick={()=>setFilter('ALL')}>Todos</button>{CATEGORIES.map(c=><button key={c} className={filter===c?'is-selected':''} onClick={()=>setFilter(c)}>{labels[c]}</button>)}</div><section className="ia-beta-template-grid">{visible.map(template=><article key={template.template_id}><div className="ia-beta-template-card-top"><span>{labels[template.category]}</span><small>{template.graph.nodes.length} nós · {template.graph.edges.length} conexões</small></div><h3>{template.name}</h3><p>{template.description||'Template reutilizável de Flow.'}</p><div className="ia-beta-template-tags">{template.tags.map(tag=><span key={tag}><Tag/>{tag}</span>)}</div><div className="ia-beta-template-card-meta">Origem r{template.source_flow_revision} · usado {template.use_count}x</div><div className="ia-beta-template-card-actions"><button className="is-primary" onClick={()=>void useTemplate(template)} disabled={Boolean(busy)}>{busy===template.template_id?<LoaderCircle className="is-spin"/>:<Copy/>}Usar template</button><button onClick={()=>void remove(template.template_id)} disabled={Boolean(busy)}><Trash2/></button></div></article>)}{!visible.length&&<div className="ia-beta-template-empty"><Layers3/><strong>Nenhum template ainda</strong><span>Salve um Flow e transforme-o em template acima.</span></div>}</section></main>;
};
