import React,{useEffect,useMemo,useState} from 'react';
import {Play,Plus,RefreshCw,Save,Trash2,UploadCloud} from 'lucide-react';
import {betaFlowClient,FlowRecord} from '../flowClient.js';
import {betaTemplateClient,TemplateView} from '../templateClient.js';
import {workflowAppClient,WorkflowAppView} from '../workflowAppClient.js';

const valueFor=(field:any,value:string)=>field.media_type==='STRUCTURED_DATA'?(()=>{try{return JSON.parse(value);}catch{return value;}})():value;
export const BetaWorkflowAppsView:React.FC=()=>{
 const [apps,setApps]=useState<WorkflowAppView[]>([]),[flows,setFlows]=useState<FlowRecord[]>([]),[templates,setTemplates]=useState<TemplateView[]>([]),[selected,setSelected]=useState<WorkflowAppView|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[runResult,setRunResult]=useState<any>(null),[values,setValues]=useState<Record<string,string>>({}),[sourceType,setSourceType]=useState<'FLOW'|'TEMPLATE'>('FLOW'),[sourceId,setSourceId]=useState('');
 const load=async()=>{const [a,f,t]=await Promise.all([workflowAppClient.list(),betaFlowClient.list(),betaTemplateClient.list()]);setApps(a);setFlows(f);setTemplates(t);if(selected){const fresh=a.find(x=>x.app_id===selected.app_id)||null;setSelected(fresh);}};
 useEffect(()=>{void load().catch(e=>setError(String(e?.message||e)));},[]);
 const sources=sourceType==='FLOW'?flows.map(x=>({id:x.flow_id,name:x.name})):templates.map(x=>({id:x.template_id,name:x.name}));
 const current=selected;
 const updateLocal=(patch:Partial<WorkflowAppView>)=>current&&setSelected({...current,...patch});
 const orderedInputs=useMemo(()=>[...(current?.input_schema||[])].sort((a,b)=>a.order-b.order),[current]);
 const act=async(fn:()=>Promise<any>)=>{setBusy(true);setError('');try{const result=await fn();await load();return result;}catch(e:any){setError(String(e?.message||e));}finally{setBusy(false);}};
 return <main className="ia-beta-page ia-flow-apps"><section className="ia-beta-page-head"><div><p className="ia-beta-kicker">Workflow Apps</p><h1>Transforme Flows em experiências simples</h1><p>Escolha o que o usuário vê. O grafo, providers, Jobs e créditos continuam por trás.</p></div></section>{error&&<div className="ia-beta-error">{error}</div>}
 <div className="ia-apps-layout"><aside className="ia-apps-sidebar"><div className="ia-apps-create"><select value={sourceType} onChange={e=>{setSourceType(e.target.value as any);setSourceId('');}}><option value="FLOW">Flow</option><option value="TEMPLATE">Template</option></select><select value={sourceId} onChange={e=>setSourceId(e.target.value)}><option value="">Selecione…</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><button disabled={!sourceId||busy} onClick={()=>void act(async()=>{const app=await workflowAppClient.create({source_type:sourceType,source_id:sourceId});setSelected(app);return app;})}><Plus/>Criar App</button></div><div className="ia-apps-list">{apps.map(app=><button key={app.app_id} className={current?.app_id===app.app_id?'is-selected':''} onClick={()=>{setSelected(app);setRunResult(null);setValues({});}}><strong>{app.name}</strong><span>{app.status==='PUBLISHED'?'Publicado':'Rascunho'} · rev. {app.revision}</span></button>)}</div></aside>
 <section className="ia-apps-main">{!current?<div className="ia-beta-empty"><h2>Meus Apps</h2><p>Crie um App a partir de um Flow ou Template existente.</p></div>:<><div className="ia-apps-toolbar"><div><input value={current.name} onChange={e=>updateLocal({name:e.target.value})}/><textarea value={current.description} onChange={e=>updateLocal({description:e.target.value})}/><small>Fonte fixa: {current.source_type} · revisão {current.flow_revision}</small></div><div className="ia-apps-actions"><button disabled={busy} onClick={()=>void act(()=>workflowAppClient.update(current.app_id,{name:current.name,description:current.description,input_schema:current.input_schema,output_schema:current.output_schema}))}><Save/>Salvar</button><button disabled={busy} onClick={()=>void act(()=>workflowAppClient.refreshRevision(current.app_id))}><RefreshCw/>Atualizar revisão</button>{current.status==='DRAFT'&&<button disabled={busy} onClick={()=>void act(()=>workflowAppClient.publish(current.app_id))}><UploadCloud/>Publicar</button>}<button disabled={busy} onClick={()=>void act(async()=>{await workflowAppClient.remove(current.app_id);setSelected(null);})}><Trash2/></button></div></div>
 <div className="ia-apps-builder"><h2>Campos públicos</h2>{orderedInputs.map((field,index)=><div className="ia-app-field" key={field.node_id}><div><strong>{field.media_type}</strong><input value={field.label} onChange={e=>updateLocal({input_schema:current.input_schema.map(x=>x.node_id===field.node_id?{...x,label:e.target.value}:x)})}/></div><input placeholder="Placeholder" value={field.placeholder} onChange={e=>updateLocal({input_schema:current.input_schema.map(x=>x.node_id===field.node_id?{...x,placeholder:e.target.value}:x)})}/><label><input type="checkbox" checked={field.required} onChange={e=>updateLocal({input_schema:current.input_schema.map(x=>x.node_id===field.node_id?{...x,required:e.target.checked}:x)})}/>Obrigatório</label><span>#{index+1}</span></div>)}<h2>Resultados públicos</h2>{current.output_schema.map(field=><div className="ia-app-field" key={field.node_id}><strong>{field.media_type}</strong><input value={field.label} onChange={e=>updateLocal({output_schema:current.output_schema.map(x=>x.node_id===field.node_id?{...x,label:e.target.value}:x)})}/></div>)}</div>
 <div className="ia-app-runtime"><h2>Executar App</h2>{orderedInputs.map(field=><label key={field.node_id}><span>{field.label}{field.required?' *':''}</span>{field.media_type==='STRUCTURED_DATA'?<textarea value={values[field.node_id]||''} placeholder={field.placeholder||'{ }'} onChange={e=>setValues({...values,[field.node_id]:e.target.value})}/>:<input value={values[field.node_id]||''} placeholder={field.placeholder} onChange={e=>setValues({...values,[field.node_id]:e.target.value})}/>}</label>)}<button disabled={busy||current.status!=='PUBLISHED'} onClick={()=>void act(async()=>{const inputs=Object.fromEntries(orderedInputs.map(f=>[f.node_id,valueFor(f,values[f.node_id]||'')]));const result=await workflowAppClient.run(current.app_id,inputs);setRunResult(result);return result;})}><Play/>Executar</button>{current.status!=='PUBLISHED'&&<small>Publique o App para habilitar novas execuções.</small>}{runResult&&<pre>{JSON.stringify(runResult.outputs||runResult.flow_run?.outputs||{},null,2)}</pre>}</div></>}</section></div></main>;
};
export default BetaWorkflowAppsView;
